### ISSUE TITLE
Some thoughts on part matching

### ISSUE THREAD

**Issue by HendriXML** [partkeepr/PartKeepr#1005]

**Comment by HendriXML** [comment]
After some more thinking, I posted a followup suggestion:

[#54](https://github.com/partkeepr/PartKeepr/issues/54#issuecomment-437588810)

**Comment by baradhili** [comment]
@HendriXML trying to cleanup the issues in Partkeepr.. your ticket here doesn't quite let me know what the direction of teh ticket was.. is this just FYI? or are you suggesting it could be added to code?

**Comment by HendriXML** [comment]
@baradhili From a developers perspective: you could add it to a "redesign suggestion" category... But you could also flag it as "not going to happen", close it and make it disappear from the open issue list.

**Comment by baradhili** [comment]
thanks!
