### ISSUE TITLE
add parts to project with storege location

### ISSUE THREAD

**Issue by datamaskinen** [partkeepr/PartKeepr#1022]
Hi there,
Great software but i have some feature requests that could be useful and as i do not know how to tag this issue as an feature request i hope that someone of the admins can do that.

So I was thinking that it would be useful if we could in the 'Part manager' when we choose a part... add a button that can add that part to a project in the 'Projects' .... 

The parts that we add to the projects in that way should then have another column that tells us where that item is located as in 'storage location'.... in that way it is so much easier to export the projects parts list and go out and find the right parts for that project.

**Comment by HendriXML** [comment]
Hi,

If you create a project report the location amongst other things is showed.
Steps:
So create a project. Goto project report. Add quantity > 1. Create report.

**Comment by datamaskinen** [comment]
haha sorry ... it was just not being to quick ... i found now how to add collumns
