### ISSUE TITLE
LDAP Library not found!

### ISSUE THREAD

**Issue by jylescoad-ward** [partkeepr/PartKeepr#1024]
Hi everyone,

I'm trying to install PartKeepr on Windows Server 2012 R2 with PHP 7.2 and it says that the LDAP library is not found but its listed in the extensions on the php.ini file.

But the installer says that the library is not found?

I have restarted my server twice and it still does not work. Any help?
[http://jyles.pw/partkeeprerror.png](url) <<error screenshot<<
```
[ExtensionList]
extension=php_mysqli.dll
extension=php_mbstring.dll
extension=php_gd2.dll
extension=php_gettext.dll
extension=php_curl.dll
extension=php_exif.dll
extension=php_xmlrpc.dll
extension=php_openssl.dll
extension=php_soap.dll
extension=php_pdo_mysql.dll
extension=php_pdo_sqlite.dll
extension=php_imap.dll
extension=php_tidy.dll
extention=php_ldap.dll```

**Comment by Drachenkaetzchen** [comment]
Please note that the GitHub issue tracker is reserved for bug reports and feature requests. It is not a support forum - for community support, please refer to https://partkeepr.com/support/
