### ISSUE TITLE
Synology Installation problem

### ISSUE THREAD

**Issue by MauroApollo** [partkeepr/PartKeepr#1026]
if I install partkeepr in my synology ds212 in setup 2/2 I have an error like "WARMING UP THE CACHE invalid Response from server", how can I fix it?

Synology ds212j
PHP 7.0 or 5.6
Apache 2.2 or nginx

**Comment by crazyduck** [comment]
Got it working on DS918+:

Created a virtual Host
MariaDB10
Apache 2.4
php 7.0
-> PHP-Cache enabled
-> packages activated: curl, gd, iconv, intl, ldap, mysqli, pdo_mysql, pdo_sqlite, posix, 
advanced settings:
default_socket_timeout: 600
max_execution_time: 600

also this nginx reverse proxy changing:
https://www.bluescreengenerator.de/blog/synology-webstation-timeout-problem-beheben
-> /var/packages/WebStation/target/misc/VirtualHost-nginx.mustache

`{{#apache22}}
    include     proxy.conf;
    proxy_read_timeout 600s;
    location / {
        proxy_pass  http://{{listen}};
    }
{{/apache22}}
{{#apache24}}
    include     proxy.conf;
    proxy_read_timeout 600s;
    location / {
        proxy_pass  http://{{listen}};
    }
{{/apache24}}`

sudo synoservicectl --restart nginx

Afterwards I could pass "Warming up the cache"

**Comment by christianlupus** [comment]
@MauroApollo could you please verify that your issue is solved in the meantime or not and if this issue is still relevant for you? I added the *Will be closed soon!* tag to enable the stale bot.
