### ISSUE TITLE
Error while searching for Internal ID

### ISSUE THREAD

**Issue by cloakingdevice** [partkeepr/PartKeepr#1027]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version: 1.4.0
* Reproducible on the demo system: Yes

![partkeepr system information](https://user-images.githubusercontent.com/25953786/55154084-41874e80-5154-11e9-9cd4-a04556d8762f.png)
* 1.1.0 overwritten with 1.4.0, setup completed OK

# How to reproduce

After checking @id under System Preferences / Full text search and then searching for internal ID, it throws an error. I've tried choosing "Use entered text as-is" and "Separate search terms" Under System Preferences / Full text search to no avail.

# Full error report

An error occurred

* Details
==================================
[Syntax Error] line 0, col 171: Error: Expected =, <, <=, <>, >, >=, !=, got 'id'

* Request
==================================
GET http://partkeepr/api/parts?_dc=1553770205987

* Response Status Code
==================================
500

* Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"[Syntax Error] line 0, col 171: Error: Expected =, \u003C, \u003C=, \u003C\u003E, \u003E, \u003E=, !=, got \u0027id\u0027"}

* Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.15-1~dotdeb+8.1
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: false
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: false
defaultGridPresets: []

**Comment by christianlupus** [comment]
This is a duplicate of #992, I think.

**Comment by cloakingdevice** [comment]
> This is a duplicate of #992, I think.

Yep, might just be, will check tomorrow.

**Comment by cloakingdevice** [comment]
> This is a duplicate of #992, I think.

Solution in #992 solved the problem!
