### ISSUE TITLE
Octopart search not working after migration

### ISSUE THREAD

**Issue by Matjaz-LPVO** [partkeepr/PartKeepr#1032]
# System Information

* PartKeepr Version: 1.4.0
* Reproducible on the demo system: No.

# How to reproduce

So, I had Partkeepr working perfectly on my home server. Because my server was slow and consumed to much power, I decided to move partkeepr to VPS. So I just copied files from my server to a new VPS (database also), ran a setup again and got things working, Only thing that isn't working is Octopart search. It always returns blank window.

p.s. I also tried deleting cache and rerunning setup like described here (https://github.com/partkeepr/PartKeepr/issues/818), but nothing changed.

Could it be, that API key is locked to IP?

**Comment by willbicks** [comment]
Are you paying for an API from octopart? If so, it sounds like you might want to contact them and see if they have locked your API key for some reason.

If you haven't been paying, then I'm guessing your API key just got deactivated as they eliminate their free API users, and that timing happened to correspond to with you moving your installation. See issue #1030

**Comment by Matjaz-LPVO** [comment]
Thank you for the answer willbicks.
Didn't know about new Octopart policy about API keys. It's a real shame, because I liked that feature of PartKeepr, but now it looks like I will have to enter everithing manualy, as 25$ per month is just to much to enter a part here and there :(
