### ISSUE TITLE
Cannot install 1.4.0 from tarball

### ISSUE THREAD

**Issue by fuzxxl** [partkeepr/PartKeepr#1033]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version: 1.4.0
* operating system: FreeBSD 12.0
* Reproducible on the demo system: No.

Fill in any steps to reproduce the issue. A good description of an issue would be:

I tried to install Partkeepr 1.4.0 by downloading the [tarball](https://github.com/partkeepr/PartKeepr/archive/1.4.0.tar.gz) from github and then pointing my browser to `web/setup`.  The “Testing for correct PHP settings” check fails with “Invalid Response from server.”  Apparently, this is because the `vendor` directory with all the dependencies is missing.  `httpd_errors.log` says:

    require_once(): Failed opening required '/var/www/partkeepr/web/setup/tests/../../../app/SymfonyRequirements.php' (include_path='.:/php/includes') in /var/www/partkeepr/web/setup/tests/check.php on line 3, referer: http://some_host/partkeepr/web/setup/

Please either fix the tarball such that the old instructions apply once again or update the installation instructions to indicate how to install PartKeepr 1.4.0.

**Comment by Drachenkaetzchen** [comment]
The tarball you downloaded is the source tarball, which is the same as cloning the repository and checking out the 1.4.0 tag. As such, you need to follow the [Runninng from GIT](https://wiki.partkeepr.org/wiki/Running_PartKeepr_from_GIT) instructions or download the release from https://partkeepr.com/download/

**Comment by fuzxxl** [comment]
That explains it.  It might be a good idea to upload the release tarball to github, too, or at least link to the aforementioned website from the release tag.

Thank you for your time.
