### ISSUE TITLE
Raspbian error during setup

### ISSUE THREAD

**Issue by QvixoteRoux** [partkeepr/PartKeepr#1038]
Hello, I had the weird idea of putting partKeepr in a Raspberry 3, I remember setting it in windows some years ago and everything went fine but now I am struggling

I am using the master branch of partKeepr with Raspbian 10, PHP is 7.3

I am now to the point when I can run the setup screen but there is an error in step 

Invalid Response from server

Warning: require_once(/var/www/html/almacen1/web/setup/tests/../../../app/SymfonyRequirements.php): failed to open stream: No such file or directory in /var/www/html/almacen1/web/setup/tests/check.php on line 3

Fatal error: require_once(): Failed opening required '/var/www/html/almacen1/web/setup/tests/../../../app/SymfonyRequirements.php' (include_path='.:/usr/share/php') in /var/www/html/almacen1/web/setup/tests/check.php on line 3

I am assuming this problem is because symfony is not installed, after researching I found I have to use composer, so I configure everything (maybe) and I have all the packages but I encounter this error, nicely marked in red background:

[Symfony\Component\Debug\Exception\ContextErrorException]                                        
  Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
                                                                                                   

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets handling the post-install-cmd event terminated with an exception

                                                                               
  [RuntimeException]                                                          
  An error occurred when executing the "'assets:install --symlink '\''web'\''  
  '" command:                                                                                                   
                                                                       
    [Symfony\Component\Debug\Exception\ContextErrorException]          
                                                                       
    Warning: "continue" targeting switch is equivalent to "break". Di  
  d you mean to use "continue 2"?                                      
                             

I am completly stuck in this part

**Comment by christianlupus** [comment]
Maybe you want to look at #1033. I think this might be related.

**Comment by QvixoteRoux** [comment]
Thanks for your answer Cristian, it seems related but it does not gives me a solution

Solution 1 was to download directly from [](url)http://www.partkeepr.org but the site is blank


Solution 2 is to follow the guide using composer to install from a git clone, that is what I was trying to do until I get the second error mentioned in my post

**Comment by Drachenkaetzchen** [comment]
You can download it from https://downloads.partkeepr.org/

Will fix the main site problem now.

**Comment by Drachenkaetzchen** [comment]
Main site is up and running again

**Comment by QvixoteRoux** [comment]
thanks Drachen, I was able to download zip from main site

I am now stuck with a new error in the same step 3 of setup

Will make some research before deciding if is worth a new issue or still related

**Comment by QvixoteRoux** [comment]
new issue solved with solution found in issue #980, error message was not displayed correctly

encountered error with writeable permission, Solved!

there are a few things to implement now but I am not sure how GITs work

Correct the problem found in issue 980, the solution is indeed there

Review libraries/versions when installing from GIT with PHP 7.3 and using composer to install all the vendor components

By now I am on the step when the setup ask me for the "auth key" so I am closing this issue

Thanks guys
