### ISSUE TITLE
Error during new database setup

### ISSUE THREAD

**Issue by QvixoteRoux** [partkeepr/PartKeepr#1039]
Following the installation of my previous issue I had another error while the setup was trying to configure/populate the database for the first time

# System Information
Raspberry 3 with raspbian 10, using PHP 7.3, mysql 15.1 dist 10.3.15-mariaDB

* PartKeepr Version: 1.4.0
* Reproducible on the demo system: Not sure.

the error log is as follow

`<Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/almacen/vendor/zendframework/zend-stdlib/src/ArrayObject.php on line 426

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/almacen/vendor/zendframework/zend-code/src/Reflection/MethodReflection.php on line 272

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/almacen/vendor/zendframework/zend-code/src/Reflection/MethodReflection.php on line 275

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/almacen/vendor/zendframework/zend-code/src/Reflection/MethodReflection.php on line 281

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/almacen/vendor/zendframework/zend-code/src/Reflection/MethodReflection.php on line 287

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/almacen/vendor/zendframework/zend-code/src/Reflection/MethodReflection.php on line 296

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/almacen/vendor/zendframework/zend-code/src/Reflection/MethodReflection.php on line 314

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/almacen/vendor/zendframework/zend-code/src/Reflection/MethodReflection.php on line 319

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/almacen/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2636

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/almacen/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2665
{"success":true,"errors":[],"message":"Connection successful"}
OK>`

I am researching this new issue, I dont find any related issues yet with these files "MethodReflection.php" and UnitOfWork.php"

Could this be PHP 7.3 is not fully supported? I will make a clean installation with a lower version of php (7.0 maybe) and check if this happens again

**Comment by aarontc** [comment]
I ran into this as well and then discovered somewhere in the documentation that PHP 7.0 is the latest supported version.

**Comment by QvixoteRoux** [comment]
yes, recently I went back to check this, made a new installation using PHP 7.0 and it worked
