### ISSUE TITLE
Is this project even alive?

### ISSUE THREAD

**Issue by imranparuk** [partkeepr/PartKeepr#1042]

**Comment by imranparuk** [comment]
This project looks amazing. 
One of a kind.

If it is to move forward. I will definitely donate to keep it alive.

**Comment by phil31** [comment]
i really expect that Partkeepr continue to live !
hope someone can do the job and thanksfull the original creator

**Comment by Drachenkaetzchen** [comment]
I have added information to https://github.com/partkeepr/PartKeepr/issues/1059 and made it pinned, so I'll close this one.
