### ISSUE TITLE
Efficient order picking

### ISSUE THREAD

**Issue by HendriXML** [partkeepr/PartKeepr#1045]
I store my components in flat boxes that are stacked on each other. I keep them in a fixed order 1,2,3 etc. This saves a lot of space and is relatively inexpensive, but used to be time consuming when a lot of components had to be picked.

So I added an extra report to my tool [KiCad-BOM-reporter](https://github.com/HendriXML/KiCad-BOM-reporter) that shows what should be taken out of what box in the right order. And also what components that are needed but aren't on stock.

Because this can be run from KiCad in an instance, this can give some nice info, such as the production remarks, comments, status.

Another feature is an extra field Functions on a new component class IntegratedCircuit. This allows you to register the functions an IC contains and how many. Functions that are defined are: OpAmp, Comparator, SchmittTrigger, Optocoupler, Timer, AndGate, OrGate, XorGate, XnorGate, NandGate, NorGate, NotGate, VRef, TempSens
This info is used when generating descriptions and can even be used during the matching of schema components. For example: create a dummy IC symbol and use it's Functions field to do a "query". This is an easy way to find out which digital gate IC's could be used. Or which quad op amps are on stock: Functions=4*OpAmp.

![Material locations](https://user-images.githubusercontent.com/40315442/64391868-a7a0c780-d04a-11e9-94d5-c9fbdcfe4e84.png)

**Comment by christianlupus** [comment]
This seems to be a quite personal setup you are referring to. Also, you did not provide the intention of your post here. I will close this issue for now. Please comment again to clarify, then I might reopen the issue.
