### ISSUE TITLE
Matching KiCad footprints

### ISSUE THREAD

**Issue by HendriXML** [partkeepr/PartKeepr#1051]

**Comment by baradhili** [comment]
just nitpicking, but maybe some of these types of tickets should be closed? 300_ issues is not good on a repo..

**Comment by christianlupus** [comment]
@HendriXML, I am sorry but I do not get your point here. Do you want PartKeepr to support your tool? Do you need a feature to make it run smoothly? Do you just want to promote your tool?

Please explain your intention. I will have to close this issue otherwise soon, sorry.

**Comment by baradhili** [comment]
since @HendriXML  has gone into a huff.. we might as well close the tickets
