### ISSUE TITLE
Your database schema is not up-to-date! Please re-run setup immediately!

### ISSUE THREAD

**Issue by phil31** [partkeepr/PartKeepr#1055]
Dear all

i was using v1.09 since long time.
now i try to use a fressh new install of the 1.40 version.

setup :
NAS SYNOLOGY DS918+ / MariaDB 10.3.11 / Apache 2.4.39

the install was succesful, but i get this warning when i'm login to partkeepr.
i try all solutions provided in this issue list, but nothing working for me. if i right understand, this isse come from the mariaDB version.

1/ what is the risk if i stay like this ? 
2/ if there is a problem with this wraning, is there any plan to fix it ? (seem complicated if i right understand the others threads)

thanks, best regards
Phil

**Comment by christianlupus** [comment]
This seems to be a duplicate from #1063 with less information. I will close this now. Please write a comment if this is independent (and clarify why), then I will reopen the issue.

**Comment by phil31** [comment]
hi, 
no this is not the same as #1063
this thread is about the problem "Your database schema is not up-to-date! Please re-run setup immediately!". i had thie message since the begining of the new fresh install of 1.40. independatly than the import components from 1.09 !

the #1063 is about the import components from 1.09

**Comment by christianlupus** [comment]
Duplicate of #1050

**Comment by christianlupus** [comment]
Yes, you are right, this is a different issue then but was reported anyways recently in #1050.

Regarding your questions:

> 1/ what is the risk if i stay like this ?

This depends if your NAS is reachable from the internet or not. If it is publicly reachable, you should think twice about it. If it is only reachable locally and your LAN can be assumed *safe*, the security risk is comparably low. PartKeepr will not update itself at the moment and you might need to keep an eye on your NAS.

Nevertheless, any risk analysis must be done with your setup in mind. As I do not know all the boundary constraints, I cannot give you a full answer here.

> 2/ if there is a problem with this wraning, is there any plan to fix it ? (seem complicated if i right understand the others threads)

Of course there is a plan to fix it. Simply put, your MariaDB is too new. There is an incompatibility in a library used by PartKeepr that causes the problem. There are (#1050) intentions to move to a newer version of this library but this needs some code changes on the side of PartKeepr.

I hope this answered your questions.
