### ISSUE TITLE
import from 1.09 version to 1.4

### ISSUE THREAD

**Issue by phil31** [partkeepr/PartKeepr#1056]
Hi all

my previous install is 1.09. since longtime, i was happy with this.
but now, i would like to import all my base to my new fresh install 1.40

what is the best way to do this ? 
i try quickly to use the export csv from 1.09 then import csv files to 1.40.
but it seem not easy ! the fields from the export files are not reconized byt the import function of the 1.40 ..

is there any tutorial available ?

thanks for any help
best regards

**Comment by phil31** [comment]
please anybody have the same requirement ?
too bad to understand that Partkeepr is dead :(

kinds regards

**Comment by christianlupus** [comment]
See [here](https://github.com/partkeepr/PartKeepr/issues/1042#issuecomment-525517320). Unfortunately, you will have to wit until things get sorted out.

**Comment by Drachenkaetzchen** [comment]
See https://wiki.partkeepr.org/wiki/How_to_update
