### ISSUE TITLE
Search Function Not Work

### ISSUE THREAD

**Issue by Teknisyen** [partkeepr/PartKeepr#1057]
The following error occurs when I try to use the search feature at the top right. 
*PartKeepr version 1.4.0
*Your demo page not working
---------------------------------------------------
An error occurred

Details
==================================
[Syntax Error] line 0, col 115: Error: Expected =, <, <=, <>, >, >=, !=, got 'id'

Request
==================================
GET https://partkeepr.asartech.com.tr/api/parts?_dc=1575027543940

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"[Syntax Error] line 0, col 115: Error: Expected =, \u003C, \u003C=, \u003C\u003E, \u003E, \u003E=, !=, got \u0027id\u0027"}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.1.24
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]
defaultGridPresets: []
---------------------------------------------------------------------------------

[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version:
* Reproducible on the demo system: Yes/No.
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): 

Please attach files, for example, screenshots to describe your issue. If you can, create a screenshot ob View->System Information.

# How to reproduce

Fill in any steps to reproduce the issue. A good description of an issue would be:

* When I click the button "Add Part" in the "Parts List", then I expect the "Add Part" window to be opened. Instead, I receive an error on the JavaScript console.

A bad description would be:
* Adding parts do not work

**Comment by Drachenkaetzchen** [comment]
Demo page is now fixed

**Comment by Teknisyen** [comment]
![Screenshot](https://user-images.githubusercontent.com/17426019/71308238-011adf80-240b-11ea-83d7-49af78c7465d.png)

**Comment by Teknisyen** [comment]
If i want use search function, Partkepr returned this fault. How the solve this problem?

**Comment by Drachenkaetzchen** [comment]
Looks like https://github.com/partkeepr/PartKeepr/issues/1027
