### ISSUE TITLE
Make Travis build without error

### ISSUE THREAD

**Issue by christianlupus** [partkeepr/PartKeepr#1070]
The travis system does not build successful at the moment. This should be corrected to allow automated testing or travis should be removed altogether.

**Comment by christianlupus** [comment]
I would be willing to look into this if I can make it running but I am unsure if I will get it there. So, please be kind :smile:.

**Comment by dromer** [comment]
This is just a single test that fails at the moment (see https://github.com/partkeepr/PartKeepr/pull/1061 )

**Comment by christianlupus** [comment]
@dromer I just opened #1082 to remove the failing test temporarily. It should work out (needs 15 more minutes, I go to bed now), will check next days.

Is there a reason why #1061 was not yet merged? I do not see any obvious show-stoppers. This would allow testing all the dangling PRs if they were rebased/check-merged to the master branch afterward.

**Comment by dromer** [comment]
Thnx, for now we can at least use travis again. Of course this tests should get fixed at some point ;)
