### ISSUE TITLE
issue in webcam js support in Chrome

### ISSUE THREAD

**Issue by allali** [partkeepr/PartKeepr#1090]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version:
1.4.0
* Google Chome version (ubuntu client):
Version 80.0.3987.106 (Official Build) (64-bit)
* Reproducible on the demo system: Yes/No.
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): 

Please attach files, for example, screenshots to describe your issue. If you can, create a screenshot ob View->System Information.

# How to reproduce

There is an issue in file /web/js/compiled/main2.js at line 19474: 

this.video.src = window.URL.createObjectURL(stream);

is not supported by Chrome anymore, should be replace by:

this.video.srcObject = stream;

**Comment by christianlupus** [comment]
This is already known in #1002 (Firefox) and a PR #1076 is also present.

**Comment by baradhili** [comment]
duplicate #1002
