### ISSUE TITLE
Trying to access array offset on value of type null 

### ISSUE THREAD

**Issue by sandlin6** [partkeepr/PartKeepr#1102]
When trying to install in the testing web server setting I get the error below. Im not the best at this type of stuff, just trying to improve efficiency at work. Any help is appreciated. Sorry if you need more info. Let me know what you need. 

Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\dashboard\ent\PartKeepr\src\PartKeepr\SetupBundle/Controller/ExistingUserSetupController.php (which is being imported from "C:\xampp\htdocs\dashboard\ent\PartKeepr\src\PartKeepr\SetupBundle/Resources/config/routing.yml").

**Comment by christianlupus** [comment]
OK, I first ask a few questions, maybe we get there.

- You seem to run apache, right? Which version (not so critical)?
- What is your PHP version?
- What DB system are you using? MariaDB or MySQL? Version?
- The error happens during the setup routine, right? It did never run before, am I correct?
- Which version of PartKeepr are you trying to install? Release or source code checked out from github?

I hope this is it for now.

**Comment by sandlin6** [comment]
Apache: 2.4.41
PHP: 7.4.1
MySQL
I have never been able to get past the first page in the setup. Always has some error.
I have tried to install 1.4.0 from the website and the latest from github.

**Comment by christianlupus** [comment]
You might be hit by the outdated symfony dependency. See #905. Can you downgrade to PHP 7.1 or earlier?

**Comment by sandlin6** [comment]
Sadly I need to be on at least 7.3 for another part of the site.
