### ISSUE TITLE
Webserver Rewrite

### ISSUE THREAD

**Issue by CurtisFeatures** [partkeepr/PartKeepr#1103]
I know that PartKeepr isn't supported on Windows but I wonder if anyone has successfully got this going in IIS - It pains me to setup a linux server to run this when I already have a web server running loads more PHP webs.

Im getting a error on the checks for Webserver Rewrite.

![Screenshot 2020-03-09 at 16 28 06](https://user-images.githubusercontent.com/34516049/76235540-24dc0d80-6223-11ea-8708-85558edb0349.png)
![Screenshot 2020-03-09 at 16 28 02](https://user-images.githubusercontent.com/34516049/76235547-2574a400-6223-11ea-9447-e6b06b1d3d31.png)

**Comment by christianlupus** [comment]
I think I have seen people using Windows yet. I do not know which web server, could be only Apache. 

I keep it open for discussion here but I don't think it will get much traction to be honest. 

In Apache you need rewriting rules on place to make it work. Did you cover these rules in htaccess to the corresponding ones for IIS?

**Comment by JustinEldracher** [comment]
I got it to work on Apache on Windows 10, went pretty smoothly once I got the right versions of all the dependencies installed.  No idea about IIS though.

**Comment by christianlupus** [comment]
There was not much traction on the topic the last few months. So I marked for closing soon.
