### ISSUE TITLE
Authentication Key is wrong ?

### ISSUE THREAD

**Issue by yukihaihai** [partkeepr/PartKeepr#1104]
Every Configuration is right and i cant find anything, either in logs or in the webconsole WHY it wouldnt work. Every time when I retrieve the key it just say that the Key is invalid..

Any thoughts why ? Or maybe a Solution?

PHP7.4 => Everything installed besides php-dom

Apache2 => followed the configuration again as on the wiki

Using Debian 10 Buster

**Comment by christianlupus** [comment]
A side remark: You will run into issues with PHP > 7.1. There is a dependency not yet updated (see #905).

Just to make things clear: You open the setup page, proceed to the point where the key is requested, then you download/look at the key file in the server and use the string provided there as a key, right? No other order of actions.

**Comment by yukihaihai** [comment]
Yes thats right.

**Comment by yukihaihai** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/59184951/76414452-9f2d9e80-6397-11ea-8d5e-7d6bbfc0e1cc.png)
![Screenshot_2](https://user-images.githubusercontent.com/59184951/76414454-9fc63500-6397-11ea-9ac2-c5dbbd19252e.png)

So as you can see, everything is right but only the key is wrong even though it just generated

**Comment by christianlupus** [comment]
Your PHP version *will* cause problems later. It is simply not checked/reported. There is a PR #1099.

Are you running in Windows or Linux? In the latter case, you might want to look at docker as this allows to simply switch the various versions of software involved. Sorry, I cannot help you more for now.
I could install a development container with PHP7.4 but this will fail at another stage later. So it is useless at the moment.

**Comment by yukihaihai** [comment]
Im using linux => Debian 10 "Buster". So probably the easiest way would be to kick 7.4 and use 5.0 ?

**Comment by christianlupus** [comment]
If this is an option, it would be worth a try.

**Comment by yukihaihai** [comment]
So i rerun the steps with php5.6 installed, and it worked out of the box apparently..

Well, thanks for your help

**Comment by christianlupus** [comment]
OK, good to hear. I will close here thus.
