### ISSUE TITLE
Update of the demo system is required soon

### ISSUE THREAD

**Issue by christianlupus** [partkeepr/PartKeepr#1122]
As soon as progress is made in the codebase, the demo system needs to be updated.

Here the question at @Drachenkaetzchen is on which server(s) the demo page is located and if that will be kept as it is now or if the financial situation of the project is too weak.
As soon as this is clear, we can decide on further steps.

If the system is to be kept as it is, the next question is: Is it a root server or only a webspace with FTP/SCP/SFTP/... access?

**Comment by Drachenkaetzchen** [comment]
The demo site is on a root server. The demo site should update itself once every hour from git.

**Comment by christianlupus** [comment]
That is good to know. Thanks for the quick response.
