### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by pggood** [partkeepr/PartKeepr#1124]
installed on php 7 and cant get the setup to run in the error log it has 
PHP Fatal error:  require_once(): Failed opening required '/var/www/partkeeper/web/../app/bootstrap.php.cache' (include_path='.:/usr/share/php') in /var/www/partkeeper/web/app.php on line 6, referer: http://192.168.20.7:90/setup/
it appears there is no app/bootstrap.php.cache in the distibution

**Comment by christianlupus** [comment]
Are you running from git or which version are you running from?
