### ISSUE TITLE
E-Bay Integration

### ISSUE THREAD

**Issue by OfficialPax** [partkeepr/PartKeepr#1130]
Hi, Maybe this was already requested in a sense here: [#692](https://github.com/partkeepr/PartKeepr/issues/692), but I thought, I might bring that up again. I know you all are really busy and I really appreciate your work. I really love this project so far. The only thing I'm missing is an E-bay integration. It's really a ton of work to inventories in the Partkeepr interface and then switch to e-bay to put it in there. Also, when somebody takes an object from the Inventory at my company but it doesn't get updated in the E-bay stuff that's a massive issue. Unfortunately this occurred three times already. That's why I decided to shut down the E-bay shop until I found a solution. Unfortunately I'm not a software dev, so I can't solve it myself. However, I'm quite sure, that I'm not the only one looking for a software capable of doing that.

To get concrete I'd imagine it working with a Checkbox similar to the NEEDS REVIEW checkbox, because often enough there's stuff in my company inventory, that isn't for sale. An automatically adjusting Stock count would be useful, however this actually only has to go one-way, because when a colleague takes something out of the Inventory and that doesn't get registered although he puts it into Partkeepr that's a big Issue! However, it's not that big of an issue when e-bay doesn't automatically cont -1 when an Order occurs, because when preparing the order, it's not that big of a deal to have to log it. of course it would be great to still have that implemented.

Thanks to everyone contributing to this Project! I really respect all the Hard work everyone is putting into the Project! That's why I'd like to offer my Professional video skills to promote this awesome Software! Let me know, when you're interested!

Best Regards!
Emil

**Comment by christianlupus** [comment]
I'd say integration with eBay is a quite high and tough business. Most probably, this would be best suited for a plugin that can be managed outside the core of PartKeepr. See #531.

Anyway, there is a clear specification needed what you need and what the system should do for you.

I want to be honest with you. I doubt that the project will gain that much traction to make such a feature request feasible in the next few months or even years. We have quite more pressing issues with outdated dependencies. So, please be warned that the chance you get this soon is quite low unless you can provide us with the required manpower....

**Comment by Gasman2014** [comment]
Partkeepr is primarily a front end to an SQL database. You can query the database directly using standard SQL queries - I have done this myself. I have not investigated extensively but I would be very surprised if there wasn’t a programatic solution to directly add parts from a SQL database into an eBay shop. I suspect that you might need to add some extra fields or abuse some of the notes but I suspect this would be a more fruitful line to pursue. I think integrating PartKeepr directly into eBay is pretty niche.

**Comment by OfficialPax** [comment]
Ok, so i might have found a way to import the SQL DB to E-bay https://developer.ebay.com/api-docs/sell/inventory/resources/inventory_item/methods/bulkCreateOrReplaceInventoryItem
However, since i'm not a dev i have no idea how exactly to implement this. I've talked to the company i'm working together for this Project. We have a Budget of a few hundred euros. Would somebody be able to do that job from the Partkeepr Team, or should i organize someone from Outside. When i get somebody outside the Partkeepr project, would you be able to support the dev when there are any major issues? i wouldn't want to demand to mutch from you guys!

**Comment by dromer** [comment]
This would have extremely low priority. Think: `first we need to do all the other things in the backlog' before even considering something like this.

Your use-case is extremely specific and considering the state of the project you should not expect any such functionality within any reasonable term.

And no, there is currently no possibility of support for fringe features like this.
