### ISSUE TITLE
one more issue on partkeepr:cron:run:synctips

### ISSUE THREAD

**Issue by ginocic** [partkeepr/PartKeepr#1135]
I can not get rid of it...
I've read [#850](https://github.com/partkeepr/PartKeepr/issues/850), [#858](https://github.com/partkeepr/PartKeepr/issues/858) and [#862](https://github.com/partkeepr/PartKeepr/issues/862). 

Trying to follow those directions, I called:
sudo -u www-data /usr/bin/php /var/www/partkeepr-1.4.0/app/console partkeepr:cron:synctips --verbose

and I get this error:

` 
  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

Exception trace:
 () at /var/www/partkeepr-1.4.0/vendor/zendframework/zend-stdlib/src/ArrayObject.php:426
 Symfony\Component\Debug\ErrorHandler->handleError() at /var/www/partkeepr-1.4.0/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php:169
 require() at /var/www/partkeepr-1.4.0/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php:169
 Symfony\Component\Debug\DebugClassLoader->loadClass() at n/a:n/a
 spl_autoload_call() at /var/www/partkeepr-1.4.0/vendor/zendframework/zend-code/src/Generator/ValueGenerator.php:89
 Zend\Code\Generator\ValueGenerator->__construct() at /var/www/partkeepr-1.4.0/vendor/zendframework/zend-code/src/Generator/PropertyGenerator.php:174
 Zend\Code\Generator\PropertyGenerator->setDefaultValue() at /var/www/partkeepr-1.4.0/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/PropertyGenerator/PublicPropertiesMap.php:50
 ProxyManager\ProxyGenerator\PropertyGenerator\PublicPropertiesMap->__construct() at /var/www/partkeepr-1.4.0/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolderGenerator.php:65
 ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator->generate() at /var/www/partkeepr-1.4.0/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/LazyLoadingValueHolderGenerator.php:27
 Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator->generate() at /var/www/partkeepr-1.4.0/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php:122
 Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper->generateProxyClass() at /var/www/partkeepr-1.4.0/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php:68
 Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper->getProxyFactoryCode() at /var/www/partkeepr-1.4.0/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:616
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->addService() at /var/www/partkeepr-1.4.0/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:666
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->addServices() at /var/www/partkeepr-1.4.0/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:145
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->dump() at /var/www/partkeepr-1.4.0/app/bootstrap.php.cache:2855
 Symfony\Component\HttpKernel\Kernel->dumpContainer() at /var/www/partkeepr-1.4.0/app/bootstrap.php.cache:2768
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /var/www/partkeepr-1.4.0/app/bootstrap.php.cache:2542
 Symfony\Component\HttpKernel\Kernel->boot() at /var/www/partkeepr-1.4.0/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:62
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/partkeepr-1.4.0/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /var/www/partkeepr-1.4.0/app/console:27
`
![error](https://user-images.githubusercontent.com/64708315/85944504-7fff5080-b937-11ea-880e-e34508352515.png)
![system](https://user-images.githubusercontent.com/64708315/85944506-8261aa80-b937-11ea-906e-b5070349d988.png)

**Comment by christianlupus** [comment]
Hello @ginocic, what PHP version are you using? Could it be you are using PHP 7.2 or later? The message 
```
[Symfony\Component\Debug\Exception\ContextErrorException]
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
```
reminds me of another issue related with either the PHP or the database version. I suspect the PHP version. But let's see.

**Comment by christianlupus** [comment]
Just one more point for you: The synctips are not working at the moment from the server side. So you will not get new tips of the days (but the cron service should run anyways....).

**Comment by ginocic** [comment]
First of all, thanks for your support.

Then, php version is 7.3. So, maybe could it be that the reason why I get the "error"? May I ask where I can get more info about it?

Then, if it doesn't work from the server side, I will disable the notification and I will check it later when it will work for sure from the server side.

Thank you again for the support. And keep up the great work!

**Comment by christianlupus** [comment]
Yes, that seems to be the culprit. Due to used libraries (read: the Symfony framework) we are at the moment restricted to PHP <= 7.1. I am surprised that the rest and especially the setup was running. Typically the setup fails in case PHP > 7.1. Was the installation maybe done before the update to the current PHP version and just now it was revived?

In general, I am unsure what other side effects there are with an unsupported PHP version. There might easily be cases where the software does not behave as it should... We are trying to get things to a more recent Symfony framework but we are all working on this in our leisure time so please be kind to us.

Do you see a chance in using an older PHP version?
Are there any data in the PK installation already?

The tip of the day is currently not maintained as other things are hugely more pressing... Therefore, there are no real tips at the moment. I op[ened an issue #1136 to keep this for later reference in the issues.

**Comment by ginocic** [comment]
>
> I am surprised that the rest and especially the setup was running.
>> Typically the setup fails in case PHP > 7.1. Was the installation maybe
>> done before the update to the current PHP version and just now it was
>> revived?
>
> I've installed a VM just last week following the tutorial on PartKeepr on
Debian "Stretch"
<https://wiki.partkeepr.org/wiki/PartKeepr_on_Debian_%22Stretch%22>  . I've
just used Debian 10 "Buster". The setup went all right. No errors.

Do you see a chance in using an older PHP version?
>
I will try it.

Are there any data in the PK installation already?
>
 Yes, There a looooooot a data... But I will setup a new VM so that's not a
problem


Il giorno mar 30 giu 2020 alle ore 08:46 Christian <notifications@github.com>
ha scritto:

**Comment by ginocic** [comment]
> 
> 
> Yes, that seems to be the culprit. Due to used libraries (read: the Symfony framework) we are at the moment restricted to PHP <= 7.1. I am surprised that the rest and especially the setup was running. Typically the setup fails in case PHP > 7.1. Was the installation maybe done before the update to the current PHP version and just now it was revived?
> 

Ok, I've put together a new VM with Debian 10 following again from [here](https://wiki.partkeepr.org/wiki/PartKeepr_on_Debian_%22Stretch%22) but with php 7.1 (source: [here](https://www.itzgeek.com/how-tos/linux/debian/how-to-install-php-7-3-7-2-7-1-on-debian-10-debian-9-debian-8.html) ) and, as you thought, that was the problem.
Now, I get no error or warning.. I'm super happy

> In general, I am unsure what other side effects there are with an unsupported PHP version. There might easily be cases where the software does not behave as it should... We are trying to get things to a more recent Symfony framework but we are all working on this in our leisure time so please be kind to us.
> 
> Do you see a chance in using an older PHP version?

Made it and it works!!!!!!

> Are there any data in the PK installation already?

'm exporting/importing all the data from the old to the new one. But I would like to know how it works with php 7.3 so I'll keep working on both of them. Am I stupid? Maybe, but I've the chance to learn something more and maybe new...

**Comment by christianlupus** [comment]
> Now, I get no error or warning.. I'm super happy
> [...]
> Made it and it works!!!!!!

That is good to hear.

> 'm exporting/importing all the data from the old to the new one. But I would like to know how it works with php 7.3 so I'll keep working on both of them. Am I stupid? Maybe, but I've the chance to learn something more and maybe new...

Here I am a bit lost, to be honest, what is your goal? Having a PK installation on PHP 7.3 might cause trouble because the Symfony framework in version 2 is incompatible with PHP > 7.1. As soon as we manage to get a new Symfony framework to run, the restriction about the PHP version will vanish. I cannot give any sort of estimate on the time schedule, as the main developer has left us and we are very short in manpower.

Maybe I did not get your point in your statement, so could you please rephrase and make your point a bit clearer?

**Comment by mhtvsSFrpHdE** [comment]
I use PHP 7.0 but also get such hint.  
Since I install PartKeepr first time, I haven't rebooted my Linux host.  
Today after a apt upgrade and reboot, every time I log in to PartKeepr, this dialog will show.

![image](https://user-images.githubusercontent.com/10773245/181872670-4b6d2534-be54-4aa1-bcca-a06cee98a3b2.png)
