### ISSUE TITLE
Share folder structure creation script

### ISSUE THREAD

**Issue by morphal** [partkeepr/PartKeepr#1140]
Hi!

Can you please share a db script to create similar folder structure that can be seen at demo url?

**Comment by christianlupus** [comment]
I have a DB dump of the demo page. I might be able to extract the relevant part. However, this might overwrite your existing structure (or better most of your DB). So if you have already some data in your database, I'd not recommend that.

Please tell me if I should extract the relevant data from the dump.

**Comment by morphal** [comment]
I've just started and have no valuable data yet. Please do the extraction. Thank you

**Comment by christianlupus** [comment]
OK, I just extracted the categories table from the demo page. Nothing else.This might throw your existing pats in various categories. So be warned. You might eventually need to truncate the table if there is data colliding.

[pk-cat.sql.gz](https://github.com/partkeepr/PartKeepr/files/4932466/pk-cat.sql.gz)

**Comment by morphal** [comment]
thanks a lot!
