### ISSUE TITLE
Blank setup page

### ISSUE THREAD

**Issue by Pararera** [partkeepr/PartKeepr#1141]
Hi,
I'm trying to install PartKeepr on my localhost(XAMMP, PHP 7.1.33).
PartKeepr version is "main", from master branch.
For some reason, setup page(http://localhost/partkeepr/web/setup/) is blank/white.
Console says 

Uncaught SyntaxError: Unexpected token '<'

BreadCrumbWizard.js:19 Uncaught ReferenceError: Ext is not defined  ext-all-debug.js:1
    at BreadCrumbWizard.js:19

And a lot of errors with "Ext"
I'm using Edge(Chromium).

**Comment by christianlupus** [comment]
Did you run [the steps required to run a git repository](https://wiki.partkeepr.org/wiki/Running_PartKeepr_from_GIT)?

**Comment by Pararera** [comment]
No, I did not. Only downloaded via download button. Last time it worked.
Also, latest release is v1.4.0 which I can run on PHP 7.4(as check says), master branch requires PHP 7.1

**Comment by christianlupus** [comment]
No, the check was recently added to the master branch as a relatively large number of issues arose regarding the incompatibility with PHP >= 7.2 and MariaDB >= 10.2. I know that such old installations of PHP are nowadays no longer suggested and we are trying to change that. The thing is that Symfony 2 (we are heavily relying on it) is only supporting up to PHP 7.1. Earlier, the test was just not present as no one thought that this issue might arise. We should have learned it but now, the 7.4 is definitively not possible. You will need to go with 7.1.

**Comment by christianlupus** [comment]
I assume the problem is the PHP version you are using. Unfortunately, you did no more answer if the problem still persists.

You might want to look into the development tools of your browser and check if any requests any sort of unreachable pages. In this case, you could check if the pages exist in the file system on the server.

**Comment by JoarGjersund** [comment]
You should also remember to set the correct permissions as explained in the [Install Guidelines](https://wiki.partkeepr.org/wiki/Main_Page)
```
$ sudo chown -R $(whoami):www-data /var/www/partkeepr-1.4.0
$ sudo find /var/www/partkeepr-1.4.0 -type d -exec chmod 770 {} +
$ sudo find /var/www/partkeepr-1.4.0 -type f -exec chmod 660 {} +
```

**Comment by tylerazfab** [comment]
> No, I did not. Only downloaded via download button. Last time it worked.
> Also, latest release is v1.4.0 which I can run on PHP 7.4(as check says), master branch requires PHP 7.1

Download from the website and not GitHub

**Comment by christianlupus** [comment]
> Download from the website and not GitHub

This will not necessarily help. The (outdated) version on the partkeepr.org website misses the test for a compatible PHP version. As a result, you might run into another issue that was documented here. So be careful here.
So, if you get any strange error messages, you might want to check your PHP and database versions!
