### ISSUE TITLE
Deployment to AWS

### ISSUE THREAD

**Issue by RobertMouncer** [partkeepr/PartKeepr#1154]
I've been trying to deploy Partkeepr to AWS eleastic beanstalk, but with no luck.

Are there any guides or is someone able to help me deploy to elastic beanstalk?

**Comment by christianlupus** [comment]
I will add the *Will be closed soon!* tag as this will enable the stale bot on the issue. If no answers are coming and you forget about the issue, you will get a reminder about it.
