### ISSUE TITLE
Project Run Delete Option

### ISSUE THREAD

**Issue by KHufman35** [partkeepr/PartKeepr#1159]
Requested to implement a Project Run Delete function.

Upon generating a **Project Report**, if the option is executed to **Remove Stock From Inventory**; the resulting action creates a project run report (under Project Run tab).  There is currently no method to delete the project run.  

Once a project run is created, the project nor any associated components can be removed from the PartKeepr database.  Either implement a delete function for the Project Run tab or decouple the output of the Project Run from the project and parts to permit removal of these items as needed.

**Comment by christianlupus** [comment]
Just to clarify: When a project run is to be removed, what should happen exactly?
Should only the project run be no longer listed in the list of runs or should the whole project run be reversed (aka the parts stock level refilled)?

**Comment by KHufman35** [comment]
My expectation is the project run would be removed from the list; stock inventory would not be revised.  

My specific scenario is:  
1)  I create a Project and run the Project Report / Remove Inventory.  This creates the Project Run Report and updates my inventory levels to reflect parts consumed in the build.
2)  The project becomes obsolete and is dropped from my project list.  The parts used in prior builds is still accurate (stock history), but I need to remove the project runs in order to remove the project from my PartKeepr project list
3)  Alternately, a part in my project becomes obsolete and I wish to delete the part from my inventory.  Retaining prior history is useful; but I do want the ability to delete the part from my inventory.

Hopefully this clarifies my issue.  Thank you for your prompt response.

**Comment by christianlupus** [comment]
Yes, that clarifies the issue but opens the question for me if it is better to drop the connection or marking the complete project as archived. The same could be done for removal of parts completely. This would as well reduce the amount a user has to do in order to gain the desired effect.

**Comment by KHufman35** [comment]
I am setting up a PartKeepr instance for a small PCB assembly shop in my area.  I assumed they would want the ability to delete old projects, but perhaps not.  Since this feature request was specifically for this application, I'd like to solicit their feedback before proceeding.  Perhaps it is best for the assembly shop to work with ParKeepr for a few weeks then revisit this issue.

Thank you for your suggestion.  I will post again in a few weeks.

**Comment by christianlupus** [comment]
I added the will-be-closed-soon tag as this activates the stale bot. It will send a comment in a few weeks. Just issue a comment to restart the time.

**Comment by KHufman35** [comment]
As the original requester for this item, I no longer am requesting this as a feature improvement.  The end user I assisted has not expressed a need in this feature, after working with the product for a few weeks.

Regards,
Kevin
