### ISSUE TITLE
Setup will not run

### ISSUE THREAD

**Issue by myval** [partkeepr/PartKeepr#1164]
I have tried installing and running PartKeepr in all sorts of ways and they all seem to be failing now.
I have installed and run the PartKeepr in Docker about a week ago and it worked fine of course I made a mess in the database so I decided to reinstall it.
Docker install went through fine, PartKeepr setup started (first window) and when I click next the next button gray out and that is it.
I thought it was Docker issue so got rid of docker Installed apache 2.4.46 and PHP 7.0.33 on my Windows 10. Downloaded partkeepr zip and end up with the same result setup starts first window, click next and that is all.
It freezes right there.

**Comment by ericmoon** [comment]
Docker is working fairly well, using the "unofficial" mhubig (https://hub.docker.com/r/mhubig/partkeepr/).  Is that the image you were using?  Can you provide either the docker command or compose file you used?

Getting it to run from source right now (either a git clone or the release), is a bit of a challenge due to older dependencies.

**Comment by myval** [comment]
I just made a discovery that the issue is with Google Chrome actually. Tried it in Internet explorer and it seems to work fine. So my guess is that it is something google done to Chrome in last week or two. Tried reseting chrome (oh what a stupid idea just made a mess big times) and it did not make any difference. So Docker and Mhubig's image seems to be ok. 
What Iam trying now is to get the setup done through Explorer and then try to run in chrome will see what happens.
But since this project seems dead I am not sure if I should not stick to alternative anyway Which would be a shame I dont think there is anything even close to Partkeepr. Everything I tried so far was rubbish.

**Comment by ericmoon** [comment]
It's not exactly dead.  It's definitely not flourishing, but there are sparks of life.  There is now a functional development docker image  (merged in the last few weeks) that should help move things along.  

The major issue is that it is currently in "old dependency hell."  That clean up is a major effort that will take some time and effort.

**Comment by myval** [comment]
Ok, well I might stick to it since I have not found anything else which is usefull anyway yet. Partkeepr seems perfect for the job.

**Comment by myval** [comment]
You seem to know a bit about this PartKeepr world can you tell me where and how to get Octopart working in Partkeepr?
on mhubig's git it  is
running the following commands:

export PARTKEEPR_OCTOPART_APIKEY=0123456 # optional, get one here https://octopart.com

but I am probably to dumb to work out how and where to run it. Doing docker compose install from mhubig's git.

**Comment by myval** [comment]
Definitelly Google does not like the next button in PartKeepr. I have installed it again and run setup in explorer no problem all went well.
now I can login to it from chrome no drama.

**Comment by ericmoon** [comment]
Interesting about chrome not liking the next button.  What version/build of chrome are you using and do you have any extensions installed?

As for the Octopart API.  I haven't used octopart recently.  Theoretically,  you should be able to add the API key to the mkparameters file (which is then copied into parameters.php in the container).  But I haven't tried that, so not sure if it is working in the current state.

**Comment by myval** [comment]
yeah and more interesting is that it worked few weeks ago. I have few extensions installed but I got rid of them all I reset chrome to factory settings and still no go.
Version 87.0.4280.88 (Official Build) (64-bit)
ok I will try to add my api key there but should not expect any mirrracles, got it.
Thanks anyway

**Comment by myval** [comment]
is this how the Api token is supposed to be done? in mkparameters
'PARTKEEPR_OCTOPART_APIKEY' => getenv('PARTKEEPR_OCTOPART_APIKEY') ?: '0xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx1',

run compose up but it still comes up with message that it is not configured. I have checked it with Vi and it was not coppied to parameters.php. So while I was tehre I manualy add the token but still does not work.

I think I am too dumb for this

**Comment by ericmoon** [comment]
Just to make sure we're on the same page, you added the key to mkparamters like this:
` 'PARTKEEPR_OCTOPART_APIKEY' => getenv('PARTKEEPR_OCTOPART_APIKEY') ?: 'axxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxd',`
Then you did a `docker-compose up -d` , 
then `docker exec -it <container_name> bash`
and checked the values in `/var/www/html/app/config/parameters.php`
and it wasn't set?
can you do an `echo $PARTKEEPR_OCTOPART_APIKEY` inside the container and see if it's set?

**Comment by myval** [comment]
all the steps like you said except -d in compose not sure what that does?
`echo $PARTKEEPR_OCTOPART_APIKEY` returns nothing

**Comment by myval** [comment]
this: `docker-compose exec partkeepr cat /var/www/html/app/config/parameters.php`
gives me: `$container->setParameter('partkeepr.octopart.apikey', '');`

**Comment by ericmoon** [comment]
the -d just runs it as a daemon .. not important.

try one more thing.   I may have also set the the API key as an env. variable outside of the container.  so, you can set it before running docker-compose up, or add it to the actual docker-compose.yml file.

**Comment by myval** [comment]
ok but you have to give me some pointers I am not really up to scratch with all this. if I look in compose.yml I have  this in it:  - PARTKEEPR_OCTOPART_APIKEY
it is in
```
  partkeepr:
    environment:
```

**Comment by ericmoon** [comment]
yeah, you can just add it the the 
`      - PARTKEEPR_OCTOPART_APIKEY`
line, as seen in the reference: 
https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers

You could also create a .env file for that variable, but putting it directly in the compose file is top precedence.  Take a look at that link and see which works best for you.

**Comment by myval** [comment]
there is bit of a mess in footprints right from the start. I can not add image here but it is one footprint per category so there is a lot of BGA categories and lot of DIP categories with one footprint in each.

-DIP
    |-  CERDIP
-DIP
    |-  CERDIP
-DIP
    |-  CERDIP
-DIP
    |-  CERDIP

and so on

**Comment by myval** [comment]
👍  I shoved it into yml file and it works fine, well fine as far as fine can go. it does not throw error anymore. but I dont get any returns from Octopart. At least I know how to set it up now so when it gets sorted I am set.
Thank you

**Comment by ericmoon** [comment]
See  #1150  for current status.. the docker image most likely doesn't have this PR in it.  I'll try it later on a dev image.  In the meantime, I think this one can be closed?

**Comment by myval** [comment]
roger that it can be closed. I will do bit of reading on it tomorrow. Thanks again
