### ISSUE TITLE
javascript error if octopart request fails

### ISSUE THREAD

**Issue by absorb-it** [partkeepr/PartKeepr#1173]
# Bug description

If parts not existent at octopart, search will fail and never end (javascript error)

## Steps to reproduce

Add new part like "test0815" and search octopart for it. Rotating waiting indicator will never go away. Check javascript- console:

Uncaught TypeError: Cannot read property 'length' of null
    at F.checkForErrors (main2.js:30353)

## Expected behavior

search ends without result or with some error message

## Observed behavior

waiting indicator will never go away.

## JavaScript errors

Uncaught TypeError: Cannot read property 'length' of null
    at F.checkForErrors (main2.js:30353)

**Comment by absorb-it** [comment]
# working patch
<pre>
diff --git a/src/PartKeepr/FrontendBundle/Resources/public/js/Components/OctoPart/SearchPanel.js b/src/PartKeepr/FrontendBundle/Resources/public/js/Components/OctoPart/SearchPanel.js
index 1f146f57..f62671cf 100644
--- a/src/PartKeepr/FrontendBundle/Resources/public/js/Components/OctoPart/SearchPanel.js
+++ b/src/PartKeepr/FrontendBundle/Resources/public/js/Components/OctoPart/SearchPanel.js
@@ -206,7 +206,7 @@ Ext.define("PartKeepr.Components.OctoPart.SearchPanel", {
     },
     checkForErrors: function (data)
     {
-        if (data.results.length == 0 && data.errors.length > 0) {
+        if (data.results.length == 0 && data.errors && data.errors.length > 0) {
             Ext.Msg.alert(i18n("Octopart Error"), data.errors.map(e => e.message).join());
         }
</pre>

**Comment by christianlupus** [comment]
@absorb-it Thank you for the patch. Are you able to open a PR or should we just use that patch on the codebase?

**Comment by absorb-it** [comment]
If you can, than please add it to the codebase. From my side this will be fine, I don't have the code forked on github.
