### ISSUE TITLE
Blank Setup Page

### ISSUE THREAD

**Issue by Chriz02** [partkeepr/PartKeepr#1179]
Hello,

I'm trying to install partkeepr from github on my websever (Hetzner Level 4 hosting). 
The cloned github repo was uploaded to my webspace and a subdomain was added. If I try to open /web/setup/index.htmlI see only a blank page. and the tab of firefox is named "PartKeeper Setup". But nothing more.

I asked support of my space and they told me 

> AllowOverride ist im Normalfall im Apache VHost konfiguriert.

> Dies kann man bei Webhostingpaketen nicht beeinflussen, ist aber für das genannte Vorhaben in der Regel passend gesetzt.

That means AllowOverrite is activated. And PHP Version was setup by myself to Vers. 7.1.

And hint how to get partkeepr running?

Thanks!

Regards
Chris

**Comment by Chriz02** [comment]
I added 
AcceptPathInfo on
RewriteEngine on

on the start of .htacess but still the same. A blank page :-/

**Comment by christianlupus** [comment]
Hello. Did you [build the app](https://wiki.partkeepr.org/wiki/Running_PartKeepr_from_GIT) before running setup? When running from GIT, you need to perform some basic steps in order to build the JS part of the page and import some PHP libraries.
