### ISSUE TITLE
Web server misconfiguration

### ISSUE THREAD

**Issue by ruslanbathenway** [partkeepr/PartKeepr#1183]
Hello, I'm trying to install partkeepr on Ubuntu 20.04 and keep getting "Web server misconfiguration" error. I already tried: 

* This guide: https://wiki.partkeepr.org/wiki/PartKeepr_on_Debian_%22Jessie%22
* And this one: https://wiki.partkeepr.org/wiki/KB00005:Web_Server_Configuration

But I'm still keeping getting the same error. 
![image](https://user-images.githubusercontent.com/29664294/105931269-a4382280-6029-11eb-92a9-fdeb7ac7107b.png)

Thank you for any suggestion in advance

**Comment by ruslanbathenway** [comment]
So, I reviewed the log files. You can see how the last POST fails (500 response)

![image](https://user-images.githubusercontent.com/29664294/105931905-cf6f4180-602a-11eb-90e4-b8589bc02b3b.png)

No I'm wondering why it's being sent to `/setup.php/setup/webserverTest HTTP/1.1` ? That doesn't sounds right to me, kind of invalid path. I guess it should be `/setup/webserverTest/setup.php HTTP/1.1"` ?

Any idea?

**Comment by ruslanbathenway** [comment]
Ok, so here is the full error message I get 
http://partkeepr.henwaytools.com/setup.php/setup/webserverTest

**Comment by christianlupus** [comment]
I assume you are not running in docker but in the php version of ubuntu directly, right? The thing is Ubuntu 20.04 has PHP 7.4 as far as I think from the repository. Please check your PHP version. PartKeepr only supports PHP 7.0 and 7.1 currently, sorry.

**Comment by ghost-from-the-past** [comment]
Dera ruslanbathenway here you have all the steps to install partkeepr in Ubuntu 20.10 that are the same for your Ubuntu 20.04
https://readthedocs.web.cern.ch/display/PARTK/Install+PartKeepr+on+Ubuntu+20.10
Regards
