### ISSUE TITLE
PartKeepr Implementation on RedHat 8 Linux

### ISSUE THREAD

**Issue by KHufman35** [partkeepr/PartKeepr#1188]
Is it possible to install PartKeepr on RedHat Linux version 8?  The versions of PHP and Symphony currently running with PartKeepr are not supported on RedHat Version 8.

**Comment by christianlupus** [comment]
I am sorry, the PHP version is a requirement of Symfony and the update takes time (and a skillful developer). I see only the chance to run the correct PHP version in a (docker) container. Apart from that we cannot do much in this direction.

**Comment by KHufman35** [comment]
Thank you for the quick response.  Is upgrading / replacing Symfony a long term project goal?  Assuming I can successfully resolve the near term need, I will need to plan for longer term needs and knowing your plans with SYmfony would be very helpful.

**Comment by christianlupus** [comment]
Yes, #1083 is the next high prio task. But this is a task that might take quite some time as we are lacking a bit of manpower. The update of Symfony is required for the project to continue to exist as the current version of PHP required can be considered a security risk.

**Comment by KHufman35** [comment]
Understood.  Your reply is extremely helpful as we can plan accordingly
with both a short term and longer term action plan.
