### ISSUE TITLE
CSV stock level import problem

### ISSUE THREAD

**Issue by BoraDikmen** [partkeepr/PartKeepr#1189]
Hi,

This was an old issue (from 2017) but it seems that it is still unsolved;

https://github.com/partkeepr/PartKeepr/issues/918

At your demo sites;

https://demo.partkeepr.org/
https://demo-git.partkeepr.org/

I can import almost all fields but not the Stock Levet and it is extremely important filed. 

How it can be imported?

**Comment by christianlupus** [comment]
As #918 is still open, I will have to close this as a duplicate.

Currently, a bit of work is done to push the dependencies to newer versions. This should simplify development and attract potentially new contributors. Until then this issue might have to wait a bit.
