### ISSUE TITLE
"Prerequisites" setup step fails with uncaught error while checking for Symfony requirements

### ISSUE THREAD

**Issue by jomag** [partkeepr/PartKeepr#1192]
# Bug description

When installing, the second step  (prerequisites) fails with an uncaught error as in this screenshot:

![image](https://user-images.githubusercontent.com/430635/108602618-2efb0b80-73a3-11eb-9585-0cd2deb9327c.png)

I realize that this is likely an issue with my setup, since it is a blocker that would render the software useless for everyone if not.

Probably unrelated, I also have a problem with getting a "forbidden" response if I go to `http://myserver/setup`. `http://myserver/setup/index.html` works though. I'm quite sure this has something to do with my docker setup though (see below), but maybe it gives you a hint...

## Steps to reproduce

Luckily, I'm trying to setup PartKeepr with Docker, so the single step is to build and run this `Dockerfile`:

```Dockerfile
FROM php:8.0-apache
WORKDIR /partkeepr

ENV PARTKEEPR_VERSION 1.4.0

ENV APACHE_DOCUMENT_ROOT /partkeepr/partkeepr-${PARTKEEPR_VERSION}/web
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN curl -sL https://downloads.partkeepr.org/partkeepr-${PARTKEEPR_VERSION}.tbz2 | tar jx-
RUN chown -R www-data:www-data /partkeepr/partkeepr-${PARTKEEPR_VERSION}/web
```

## System Information

* PartKeepr Version: 1.4.0
* Operating System: Debian 10 (Buster)
* Web Server: apache
* PHP Version: 8.0.2

**Comment by jomag** [comment]
Ok, so after reading #1110 I tested an older PHP version (7.4) and it seems to work. Maybe the documentation should be more clear about the PHP version requirements?

**Comment by ghost-from-the-past** [comment]
Hi, I try to put several installation examples here to help the community
https://readthedocs.web.cern.ch/display/PARTK/Install+PartKeepr+on
and I mentioned that the actual PartKeepr version is supported only by PHP 7.1
(I don't have access to the official wiki to change there)
