### ISSUE TITLE
Moving partkeepr from one system to another

### ISSUE THREAD

**Issue by bprosman** [partkeepr/PartKeepr#1205]
Moving partkeepr data from one system to another.

Currently I have 2 running partkeepr systems, one hosted online, one hosted myself.
I have tried to move (copy) the data from an online system to a local system, all works except the part attachments.

What i did is:
Source system -> Backup (Export) SQL database
ZIP /data/files/PartAttachment directory

On the destination system <- Import SQL database
Unzip /data/files/PartAttachment directory
Set the correct owner / attributes for the files.

When I open a part in the destination system I do see that there are attachments though:
1. The icon is wrong
2. When I try to open an attachment it tries to open on this URL : http://192.168.10.46/api/part_attachments/482/getFile
and it gives me an error 401.
I did doublecheck and files are there in the PartAttachment directory

For the rest all works, all parts, categories, storage locations etc are there.

Hope someone can help.

**Comment by bprosman** [comment]
Please ignore my message. Got it fixed  , cleared the /var/www/partkeepr-1.4.0/app/cache/prod/sessions folder. That fixed it.

**Comment by ghost-from-the-past** [comment]
Dear bprosman
if you have any suggestion on this manipulation I'll be happy to add it into the manual
https://readthedocs.web.cern.ch/display/PARTK/11+-+Backup+Import+Export+MySQL+tables

Regards

**Comment by stegl** [comment]
hello

well i upgraded from 0.1.9 to 1.4.0. I fully installed new system. Everything works as it shuld. Then i wanted to inport items i hava on old version. I tryed to do it like it says on https://wiki.partkeepr.org/wiki/How_to_update but it just ignores everything. So i gave it up on this way. 

now im trying to inport parts trought .csv inport function and i cant get it work/insert everything. biggest problem is price. 
i have MinStockLevel but no StockLevel? :O 
![why](https://user-images.githubusercontent.com/65857447/114280153-4c119980-9a38-11eb-818b-d7258d5d34ba.png)

is it a bug? is it just me? why? how do i input i have alot of items....

Thanks in advance for answer. Have a nice day.

**Comment by christianlupus** [comment]
I will close the issue here.

@bprosman you can still comment here, if you have a suggestion for @ghost-from-the-past.
