### ISSUE TITLE
Import Menu Breaks after creating part

### ISSUE THREAD

**Issue by arneman44** [partkeepr/PartKeepr#1209]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

- Docker built From the Current master c6323d57ddc8e7a13d29d2a7a111d7ac2b1dfa40
- Reproducible on the demo system: Yes on Release and Git

# Bug Info
If you use the Import menu there are 2 ways it can appear 

**Normal**
![image](https://user-images.githubusercontent.com/31143396/113621448-ebf7ad80-965b-11eb-937f-5feb5579f4bc.png)
**Broken**
![image](https://user-images.githubusercontent.com/31143396/113621341-cec2df00-965b-11eb-994c-8348180c8d05.png)
 
The broken version appears if you have used the create part function before it in your session.
If you refresh it works again like normal.

**Comment by ghost-from-the-past** [comment]
Dear arneman44
I see in the second screen capture more "folders" (more relation to tables) than in the first screenshot, after the "folder" StorageLocation.
Is this what you refer to ? 
Regards

**Comment by arneman44** [comment]
Yes and some of the names change

**Comment by stegl** [comment]
hello

well i upgraded from 0.1.9 to 1.4.0. I fully installed new system. Everything works as it shuld. Then i wanted to inport items i hava on old version. I tryed to do it like it says on https://wiki.partkeepr.org/wiki/How_to_update and https://readthedocs.web.cern.ch/display/PARTK/11+-+Backup+Import+Export+MySQL+tables but it just ignores everything. So i gave it up on this way. 

now im trying to inport parts trought .csv inport function and i cant get it work/insert everything. biggest problem is price. 
i have MinStockLevel but no StockLevel? :O 
![why](https://user-images.githubusercontent.com/65857447/114280153-4c119980-9a38-11eb-818b-d7258d5d34ba.png)

is it a bug? is it just me? why? how do i input i have alot of items....

Thanks in advance for answer. Have a nice day.

**Comment by arneman44** [comment]
I have tried myself and couldn't get stock to import so I stopped using partkeepr. in my eyes as long as there is no new main developer there is no future in partkeepr.

**Comment by stegl** [comment]
> I have tried myself and couldn't get stock to import so I stopped using partkeepr. in my eyes as long as there is no new main developer there is no future in partkeepr.

this thing could be really good.. Did you fund any good alternative? im looking for free opensource.... aaand it must have "item location"? 
thx in advance.

**Comment by arneman44** [comment]
I personally Changed to parts-DB. I really like it and am exited for the V1 version. but here Is a list of all the inventory systems i found.

* Partsbox
* Bomist
* Partkeepr
* Partsbolt
* Mouser inventory mangement
* Part DB
* InvenTree
* Binner
* Partsinplace
* PIA ( Parts Inventory Assistant ) ( evolved )

**Comment by ghost-from-the-past** [comment]
> hello
> 
> well i upgraded from 0.1.9 to 1.4.0. I fully installed new system. Everything works as it shuld. Then i wanted to inport items i hava on old version. I tryed to do it like it says on https://wiki.partkeepr.org/wiki/How_to_update and https://readthedocs.web.cern.ch/display/PARTK/11+-+Backup+Import+Export+MySQL+tables but it just ignores everything. So i gave it up on this way.
> 
> now im trying to inport parts trought .csv inport function and i cant get it work/insert everything. biggest problem is price.
> i have MinStockLevel but no StockLevel? :O
> ![why](https://user-images.githubusercontent.com/65857447/114280153-4c119980-9a38-11eb-818b-d7258d5d34ba.png)
> 
> is it a bug? is it just me? why? how do i input i have alot of items....
> 
> Thanks in advance for answer. Have a nice day.

Dear Stegl, could you move your comments to a new issue ? and delete from here.
This create a bit of confusion because two different problems (the one form arneman44 and your are mixed in the same place) and makes difficult to answer to one or the other.

**Comment by ghost-from-the-past** [comment]
Dear Stegl,
if you exported the information from your MySQL database for partkeepr version 0.1.9 and imported that contents in partkeepr version 1.4.0 you should run http://parkeerpxxxxxxxx/setup again to reconfigure the database structure that is different.

**Comment by ghost-from-the-past** [comment]
Dear arnemann44 you are right there is no import of the stock, only the import of the transactions
https://readthedocs.web.cern.ch/display/PARTK/Stock+History+Import
and is missing to update the totals in the Part table. (to be improved in future versions)
I was confronted to the same problem and it required basic skills in programming, If you wish to go this way I could assist you with some help.

**Comment by ghost-from-the-past** [comment]
Dear arnemann44,
I am glad you fund a software that fits your needs!

I took some elements your list and completed the one prepared here
https://readthedocs.web.cern.ch/display/PARTK/Alternatives
to help others.
Regards

**Comment by ghost-from-the-past** [comment]
Dear Christianlupus
What does WIP stand for ?
You can close this issue, there is nothing to fix and is a mix of two persons facing different problems.
The only thing to retain is the improvement needed in the import in the stock qtys, but this is well known.
Regards

**Comment by christianlupus** [comment]
@ghost-from-the-past  WIP means *work in progress*. I will close anyways.
