### ISSUE TITLE
Problem with Installation 

### ISSUE THREAD

**Issue by mbalarr** [partkeepr/PartKeepr#1211]
Hay 
I have problem with installation of partkeepr.org LDAP Libery
![unnamed (5)](https://user-images.githubusercontent.com/82933902/115516499-752af900-a286-11eb-9254-84053371b206.png)
 not found

**Comment by stegl** [comment]
the best possible tutorial to go step by step you will find here: https://readthedocs.web.cern.ch/display/PARTK/Install+PartKeepr+on 

sorry but i cant help you with.. hopefully you find solution.

**Comment by arretx** [comment]
`apt install php7.x-ldap`

Solved the problem on my config.

**Comment by christianlupus** [comment]
I will close here as there seems to be a solution. Reopening is always possible.
