### ISSUE TITLE
Setting up the database schema - Invalid Response from the server Error

### ISSUE THREAD

**Issue by VasilyRakche** [partkeepr/PartKeepr#1213]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# Bug description
While trying to setup partkeepr as explained [PartKeepr 1.4.0 installation on a Raspberry Pi](https://wiki.partkeepr.org/wiki/PartKeepr_1.4.0_installation_on_a_Raspberry_Pi) I got an error:
![image](https://user-images.githubusercontent.com/30003101/118010569-77491a80-b34f-11eb-8504-0374795c1b58.png)

## Steps to reproduce

1. Installation as explained [here](https://wiki.partkeepr.org/wiki/PartKeepr_1.4.0_installation_on_a_Raspberry_Pi)

## System Information

* PartKeepr Version: 1.4.0
* Operating System: [2019-04-08-raspbian-stretch-lite](https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-04-09/2019-04-08-raspbian-stretch-lite.zip)
* Web Server: apache
* PHP Version: PHP 7.0.33-0+deb9u10 (cli) (built: Oct  6 2020 17:08:28) ( NTS )
* Database and version: mysql  Ver 15.1 Distrib 10.0.28-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2

**Comment by Masterwolf2050** [comment]
If you click show error and then post what that says

**Comment by VasilyRakche** [comment]
No more details compared to what is initially shown near the red cross, the same message : **_"Invalid Response from the server"_**

**Comment by christianlupus** [comment]
Then you should open the browser console and have a look at the console output as well as the communication between server and browser.

**Comment by VasilyRakche** [comment]
Hey, so for some reason it worked when I tried today - I wanted to dump the data for you, the only thing different that I did was that I ssh to the server and I didnt quit from MySQL after `sudo mysql -u root -p`. Maybe that helped.

I will mark this question solved, can you please just let me know before that how I can **open the browser console and have a look at the console output as well as the communication between server and browser.** so I know it for the future? - it will be useful if I have any problems in the future.

**Comment by christianlupus** [comment]
> I will mark this question solved, can you please just let me know before that how I can _**"open the browser console and have a look at the console output as well as the communication between server and browser."**_ so I know it for the future? - it will be useful if I have any problems in the future.

You did not specify the browser you are using. I think most browsers (Firefox and Chrome as far as I know at least) use the `F12` key. Depending on your browser, OS and personal settings you get a window or a dock like the one below (sorry this one is in German but you get the idea).
![grafik](https://user-images.githubusercontent.com/8202922/120466230-1b4a4280-c39f-11eb-9c3e-52dacffa6fcd.png)
There is a tab network analysis or network traffic. There you can see all the request/response pairs of the current window. You can look what data are sent and are received etc. (Only connections after opening the dev tools are logged). Here is an example of uploading the image above to github:
![grafik](https://user-images.githubusercontent.com/8202922/120466601-8b58c880-c39f-11eb-9588-6e79e6f2b12b.png)
