### ISSUE TITLE
Installing 1.4.0 on Debian 10 (PHP 7.3)

### ISSUE THREAD

**Issue by 71GA** [partkeepr/PartKeepr#1227]
I am trying to install Partkeepr 1.4.0 on Debian 10 (with PHP 7.3). But got stuck. This is my procedure:

#### INSTALLATION

> **Note:**
> SELinux is not disabled.

I installed prerequisites:

```
┌─[root@eu]─[~]
└──> apt install curl ntp wget

┌─[root@eu]─[~]
└──> apt install php7.3 php-apcu php-apcu-bc php7.3-bcmath php7.3-curl php7.3-gd php7.3-intl php7.3-ldap php7.3-my
sql php7.3-xml
```

> **Note:**
> PHP 7.0 is not an option on Debian 11.

I downloaded Partkeepr 1.4.0 *(the last release version)*:

```
┌─[root@eu]─[~]
└──> wget https://downloads.partkeepr.org/partkeepr-1.4.0.zip
```

I extracted the compressed `.zip` file:

```
┌─[root@eu]─[~]
└──> unzip partkeepr-1.4.0.zip
```

I moved the extracted folder `partkeepr-1.4.0` as the `/var/www/partkeepr`:

```
┌─[root@eu]─[~]
└──> mv partkeepr-1.4.0 /var/www/partkeepr
```

I set our Partkeepr installation's ownership and  permissions so that its files and directories are owned by our `www-data`  user and the `www-data` group *(on our server we configure everything like this)*. I set the files readable and writable by the owner and group, but inaccessible to everyone else.

```
┌─[root@eu]─[~]
└──> chown -R www-data:www-data /var/www/partkeepr

┌─[root@eu]─[~]
└──> find /var/www/partkeepr -type d -exec chmod 770 {} +

┌─[root@eu]─[~]
└──> find /var/www/partkeepr -type f -exec chmod 660 {} +
```

#### APACHE SETTINGS

I configured the `apache` HTTP server. First I enabled the `apache` modules `userdir` and `rewrite`:

```
┌─[root@eu]─[~]
└──> a2enmod userdir rewrite
```

I opened the file `/etc/apache/sites-available/000-default.conf` file:

```
┌─[root@eu]─[~]
└──> nvim /etc/apache2/sites-available/000-default.conf 
```

And I added this section inside the `<VirtualHost *:80>` tags: 

```
        ########################## PARTKEEPR ############################

        Alias /partkeepr /var/www/partkeepr/web

        #################################################################
```

and this section at the bottom:

```
########################## PARTKEEPR FOLDERS ###########################

<Directory /var/www/partkeepr>
        Require all granted
        AllowOverride All
        AcceptPathInfo On
</Directory>

########################################################################
```

#### PHP SETTINGS

I opened the `apache2` PHP configuration:

```
┌─[root@eu]─[~]
└──> nvim /etc/php/7.3/apache2/php.ini
```

And set some lines as follows _(I need higher values as recommended as Nextcloud is also running on this machine)_:

```
max_execution_time = 300
```

```
upload_max_filesize = 500M
```

```
date.timezone = Europe/Ljubljana
```

I saved the changes and restarted `apache2` daemon:

```
┌─[root@eu]─[~]
└──> systemctl restart apache2.service
```

When I visit `http://<server's IP>/partkeepr/setup/index.html` to verify if my current settings work, setup page shows up, but after I click <kbd>Next</kbd>, I end up in the tab _"Prerequisites"_ and I get an error:

![20211008_22h10m44s_grim](https://user-images.githubusercontent.com/8915807/136620968-86c98a57-31e2-4b51-b14f-c08c1ecff7f7.png)

Is this due to incompatibilities with PHP version 7.3? Is there any other possible suspect? Could this be fixed?

**Comment by dromer** [comment]
PHP higher than 7.1 is indeed currently not supported and clearly documented.

**Comment by miiichael** [comment]
I think you mean "Clearly documented in a location that people downloading the tarball from the website and following the instructions on the wiki won't know to check" :stuck_out_tongue:  Neither the [download page](https://www.partkeepr.org/download/) (which says "PHP5.6 or higher"), nor the linked [installation guide](https://wiki.partkeepr.org/wiki/Installer) (which says "PHP is at least version 5.3.0"), nor the README.md in the downloaded tarball (which says "PHP 5.6 and up") mention the PHP 7.1 limit...

Though I now see README.md has changed since the last release...
