### ISSUE TITLE
Testing for correct PHP settings FAIL

### ISSUE THREAD

**Issue by Satnet** [partkeepr/PartKeepr#1268]
I've tried different PHP versions (7.0, 7.1, 8.2) and I'm currently on 7.1. No idea what's wrong here.
![image](https://github.com/partkeepr/PartKeepr/assets/3933296/7529124d-7bfe-4bed-aa58-e97a22c0e9fc)

**Comment by christianlupus** [comment]
No, you are not on 7.1. The logs state in the first row that you are on 8. This is not working with PartKeepr.

**Comment by Satnet** [comment]
Yes I know PartKeepr says 8.1.21 but if I run "php -v" in my terminal It says 7.1.33.

**Comment by christianlupus** [comment]
Then your CLI PHP is not the same as the one running with the web server. Are you using Apache? Is there maybe some containers involved?

**Comment by Satnet** [comment]
This has been resolved. Reinstalled the entire server.

Thanks :)


ons 4 okt. 2023 kl. 22:51 skrev Christian Wolf ***@***.***>:
