### ISSUE TITLE
SSRF vulnerability in PartKeeper

### ISSUE THREAD

**Issue by asesidaa** [partkeepr/PartKeepr#1269]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# Bug description

[comment]: # (A clear and concise description of what the bug is.)
Since there is no security policy and I cannot find contact information to the developers, I have to use issue to report this.

There is an SSRF vulnerability in PartKeeper. The add attatchment through URL function does not have any restriction on the URL. 

[comment]: # (A good description of an issue would be: When I click the button "Add Part" in the "Parts List", then I expect the "Add Part" window to be opened. Instead, I receive an error on the JavaScript console.)

[comment]: # (A bad description would be: Adding parts do not work)

## Steps to reproduce

1. Go to Edit part->attatchments
2. Add attatchments through URL
3. Use file:///etc/passwd as URL
4. Observe local file on server being loaded
5. If on demo site, use http://169.254.169.254 as URL
6. Observe the matadata being retrieved

## Suggestion
Check this [link](https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/) for more information on SSRF
Check this [link](https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html) for more information on how to fix this. Basically you would need to make sure only http and https URLs are accepted, and requests to non public ip addresses are blocked.

## System Information

* PartKeepr Version: Latest commit

**Comment by matmair** [comment]
Considering https://github.com/partkeepr/PartKeepr/issues/1059 you will probably not get a response or official recognition.

**Comment by Core2DuoKing** [comment]
> Considering #1059 you will probably not get a response or official recognition.

Which is terrible. The PartKeepr demo online looks like it was incredibly well thought out and works nicely, I guess just keeping it air-gapped and using it as-is might be sufficient for some. But dang, for a free self-hosted open source inventory management software, it's surprisingly good.
