### ISSUE TITLE
Integrate octopart.com

### ISSUE THREAD

**Issue by felicitus** [partkeepr/PartKeepr#145]
Looks as this might come in very handy.
##

**Comment by tinix84** [comment]
really intersting feature!

**Comment by Forceu** [comment]
Any updates on this issue? I just had a look at the API and it seems quite straight-forward.

**Comment by felicitus** [comment]
Yes, hopefully this will come very soon-ish, but I can't give an exact ETA yet.

**Comment by felicitus** [comment]
The OctoPart integration is now basically implemented and can be tested on the demo system. There are a few issues to solve before this issue can be completed:

#773
#772 
#771 
#770

**Comment by felicitus** [comment]
Only #771 is not fixed so far. As such, I'll close the main issue for 1.2 and fix #771 at a later point in time.
