### ISSUE TITLE
Text based parameters for parts

### ISSUE THREAD

**Issue by pfranquesa** [partkeepr/PartKeepr#155]
Capacitor dielectric specs are normally entered through EIA three-character codes, for instance:

X7R -> -55ºC to 125ºC +-15% capacitance change permitted

So it would be good to be able to enter alphanumeric codes or have some sort of pre-defined enumerated parameters.

This can be useful also to set other attributes as internal part#, etc.
##

**Comment by felicitus** [comment]
Advanced Part Parameters are now implemented, which support test-based parameters.
