### ISSUE TITLE
Feature Request: Remove from Stock for Project

### ISSUE THREAD

**Issue by elsni** [partkeepr/PartKeepr#232]
I'd like to remove parts from stock for project prototyping. When prototyping finished, I'd like to put parts back to stock. It would be nice if I could remove parts from stock and associate them with a project in one step, without losing the storage location reference, so that they can be put back to stock from the project editor in one click.
##

**Comment by baradhili** [comment]
Closing this:
1. #22 covers it mostly
2. the chances of anyone putting things back in the location they got them from... yeah
