### ISSUE TITLE
Do not require PATH_INFO to work

### ISSUE THREAD

**Issue by prauscher** [partkeepr/PartKeepr#245]
Currently, Login and many features only work when PATH_INFO is working. This is the case in Apache, but in most nginx-installations this will not work and has to be fixed by hand.

**Comment by felicitus** [comment]
Reminder to me to test PartKeepr on nginx.

**Comment by felicitus** [comment]
There's no sensible way around PATH_INFO, but setup now checks for proper setup and alerts the user with a link to the [PartKeepr knowledge base article](https://wiki.partkeepr.org/wiki/KB00005:Web_Server_Configuration)
