### ISSUE TITLE
New structure for Parts -> Footprints -> Manufacturer

### ISSUE THREAD

**Issue by Boldie** [partkeepr/PartKeepr#257]
I have some different "implementations" of a part, which has different types of footprints or different attributes like PbFree. 

Use cases:
I have a specific part (identical part id) of transistor, from which I have one with SOT-4 and TO-92. I also want to assign different locations.

I want to attach information about PbFree or not to my parts, but also on the per implementation level.

For myself, I have identified the following things, which are of interest to save on such a base:
- Footprint
- PbFree
- Manufacturer
- Manufacturer part number
- Storage Location

Maybe one can extend the manufacturer pane by these details.
##

**Comment by baradhili** [comment]
Hmm thats not a correct way to use an inventory.. same device ID with different footprints or attributes should be different stock items - otherwise you would never know which one were being drawn.
