### ISSUE TITLE
Unable to load demo data to partkeepr database (UBUNTU-INSTALL)

### ISSUE THREAD

**Issue by Boldie** [partkeepr/PartKeepr#260]
I have tried to install a development version of partkeeper, following the UBUNTU-INSTALL instructions. I stuck on the following command while trying to set up a database from sample data:

php SetupDatabase.php --yes --migrate
PartKeepr Setup
Use SetupDatabase.php --help for help

Performing actions...
- Database Schema created/updated
- Admin User created
- Added default part unit
- Imported 36 footprints, skipped 0 because they already existed
- Imported 21 Si Prefixes, skipped 0
- Imported 28 Units, skipped 0 because they already exist
- Imported 285 Manufacturers, skipped 0 because they already exist
- Migrated 7 distributors, skipped 0 because they already exist
- Migrated 43 footprints, skipped 0 because they already exist
- Migrated 448 storage locations, skipped 0 because they already exist
  PHP Warning:  require(/var/www/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/Setup.php): failed to open stream: No such file or directory in /usr/share/php/Doctrine/Common/ClassLoader.php on line 164
  PHP Fatal error:  require(): Failed opening required '/var/www/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/Setup.php' (include_path='.:/usr/share/php:/usr/share/pear') in /usr/share/php/Doctrine/Common/ClassLoader.php on line 164
##

**Comment by baradhili** [comment]
Very old - need to check if migration from PartDB is still around, but suspect not
