### ISSUE TITLE
Not using pre-existing location

### ISSUE THREAD

**Issue by chuck99z28** [partkeepr/PartKeepr#270]
The applications allows you to enter any data into Location field, but then wont save the record unless the location already exists in the database.

This makes it appear as if the application is broken and causes users to complain the records won't save.  It needs a warning or other instruction for clueless users.
##

**Comment by felicitus** [comment]
The field is now highlighted when an invalid category is selected.

**Comment by baradhili** [comment]
tested in 1.4.0 and this stays highlighted if you try and select an invalid location
