### ISSUE TITLE
Exporting to Excel 2007/2010

### ISSUE THREAD

**Issue by HIEHldg** [partkeepr/PartKeepr#271]
when i try export to xlsx, i get an error, "Excel cannot open the file 'filenme.xlxs' because the file format or file extension is not valid..." I have tried 2 computers with same results.. running office 2010.

Open Office 3.4.1 works fine

**Comment by felicitus** [comment]
The xls exporter is working again with the new release, see #435 .

**Comment by datumv** [comment]
Confirming that the xls exporter is not working. #435

**Comment by felicitus** [comment]
datumv: Please open a new issue and more details.

**Comment by felicitus** [comment]
@datumv: Please open a new issue an include details on how to reproduce. Make sure you read [CONTRIBUTING.md](https://github.com/partkeepr/PartKeepr/blob/master/CONTRIBUTING.md) for which information is mandatory in bug reports.
