### ISSUE TITLE
Suggestions on User privileges 

### ISSUE THREAD

**Issue by hebere** [partkeepr/PartKeepr#281]
There may be different level of user privileges.

Admin can do anything. Define categories, components, users, projects vs. 

Normal user can search the components, create own project and just see and manage own project, can not define or modify components.

Admin user can reserve components for normal users, but normal users can not reserve for themselves. Normal users will see which component is reserved for whom.

**Comment by mctomaszek** [comment]
hello

Is it any chance to limit privileges only to add and remove stock for normal users. I don't want to give them permission to change something else than stock only

**Comment by felicitus** [comment]
Currently there's no way to limit user privileges. This is planned for the next release.
