### ISSUE TITLE
Cannot add comments during remove stock

### ISSUE THREAD

**Issue by jeffromanski** [partkeepr/PartKeepr#282]
Feature request - can we get a comments during remove stock?

**Comment by isd0** [comment]
Please add comments to "remove stock"

**Comment by andreir1** [comment]
Hi, 

Please add a comments field to "remove stock". 

Can you tell us what files should we modify to enable the comment field when removing from stock ?

@Boldie: did cloneapoc provided the PartService.php and partkeepr.js files  ?

Thank you

**Comment by felicitus** [comment]
This is added, thus closing.
