### ISSUE TITLE
Storage location browsing

### ISSUE THREAD

**Issue by elsni** [partkeepr/PartKeepr#286]
It would be great for inventory control if parts can be browsed not only by categories but also by storage locations in the part manager. Hierarchical storage locations (#225) would become very useful in this context.

**Comment by felicitus** [comment]
The implementation for the next release is to provide an own category tree for storage locations: 
![slcat](https://cloud.githubusercontent.com/assets/162974/10539646/5a3993a4-7401-11e5-8123-c0a03fed8f64.png)

Would that for for you?

**Comment by felicitus** [comment]
No feedback given, thus closing.
