### ISSUE TITLE
Duplicate File Warning on Windows

### ISSUE THREAD

**Issue by Avotronics** [partkeepr/PartKeepr#310]
Extracting contents of partkeepr archive results in the following error on Windows system.

![extract-error](https://f.cloud.github.com/assets/4352762/467329/94fc93ce-b676-11e2-8b0f-0d32b140e8a8.jpg)
##

**Comment by felicitus** [comment]
Reminder for me to test the 1.0 release on windows platforms (e.g. WAMP Stack)

**Comment by baradhili** [comment]
no response - since things have moved on a fair bit.. closing this
