### ISSUE TITLE
stock level does not increase when adding stock

### ISSUE THREAD

**Issue by bandrack** [partkeepr/PartKeepr#317]
The stock level does not increase when adding stock. What am I doing wrong? See attachements...

![zwischenablage01](https://f.cloud.github.com/assets/4696937/653610/615ba0a4-d4db-11e2-9494-1be523ece64b.png)
![zwischenablage02](https://f.cloud.github.com/assets/4696937/653611/691faa4c-d4db-11e2-9e09-089373978b0b.png)

**Comment by evoltek** [comment]
Yes, there's a refresh problem where you end up adding stock to a different part than the intended one.

**Comment by felicitus** [comment]
Stock levels should now immediately change.
