### ISSUE TITLE
Project Parts Add Creates Unintended Part Associations Visible in Project Reports

### ISSUE THREAD

**Issue by slylandro** [partkeepr/PartKeepr#329]
After adding several new parts to a project and running a Project Report it appears completely different parts are being grouped together on one row.  This makes the report feature completely unusable.  I observed that when adding parts to a project, little red triangles appear in some of the cells' upper left corner of the parts I've added and in cells of other earlier added parts for some reason I can't understand.  It appears in these indicate some kind of link as it's these parts that are combined in the report.  These parts are in no way related categorically.

In the following pic, I simply added remarks to parts added several days ago during the same session as adding the new parts.

![image](https://f.cloud.github.com/assets/5251306/981425/ff73e088-0764-11e3-9c56-3186c002d7a1.png)

Then these parts were added and the project SAVED:

![image](https://f.cloud.github.com/assets/5251306/981426/111cc3ae-0765-11e3-94c4-443742efbe78.png)

And here's the result in the project report:

![image](https://f.cloud.github.com/assets/5251306/981429/3a8f3e4c-0765-11e3-83fe-b703226eb19d.png)

As can be seen, it appears it combined the parts whose remarks were edited and the parts just added.  The quantity count (13) appears to be the summation of the LEDs (3) and the plug pins (10) corroborated by the Remarks field.  This correlates with the red triangles in the Quantity field and Remark fields of the Project Parts.  And the LEDs are not on the Project Report.

I don't know what is creating the red triangles and I don't know what they mean.

Please advise.

PS: Upon further investigation, it appears the red triangles are simply an indicator that the field has changed?  Correct me if I'm wrong please.  However, if this is the case, why are there red triangles in the LED Part fields as I didn't change that info, I simply added remarks (colors) to the rows.  After getting out and back in and looking at the Project Parts list, the LED Part info now had the pins part info in them, hence the reason why they were combined in the Project Report.  I can't think of a reason for the LEDs part being changed to the pins I just added.  I'm confused.  Also, correct me if I'm wrong, but it might be a good idea to do a SAVE after every add, change, delete of a part in the Project page?  Also, during correcting the LED part numbers, changing them back to what they were, two of the parts ended up with the same part number.  Again, I was very careful to make sure the part numbers where correct and therefore unique, so this shouldn't have happened.  And if I simply select the Part field to see what it is, and click out of it by just clicking in the attachment area, a red triangle appears in the part field.  I also did this in a remark field for the pin part and a red triangle appeared in one of the LED Part fields, which wasn't there earlier.  Flakey.

**Comment by felicitus** [comment]
Any news on this?

**Comment by slylandro** [comment]
As far as?

**Comment by felicitus** [comment]
My last comment wasa that I did not receive a dump and asked you to send it to info[at]partkeepr.org

**Comment by slylandro** [comment]
Ah.  I'll resend what I thought I sent.

**Comment by felicitus** [comment]
I guess you probably replied to the github mail, which of course doesn't add attachments to the issue ;)

**Comment by slylandro** [comment]
Attached.

**Comment by felicitus** [comment]
There's still no attachment when you reply to GitHub messages. **Please send it to info[at]partkeepr.org**

**Comment by slylandro** [comment]
Sorry.  Will do.  Glad to see PK being worked on again.

**Comment by felicitus** [comment]
DB dump received with MessageID CA+K=TkD3BM4FDHG-N1LCapN_xip4aUBFYfhqw8sXMhc2M2yGpg@mail.gmail.com

**Comment by felicitus** [comment]
I have just tested this using the most recent GIT version and your database dump. I now get 10 JST Terminals and all 3 LEDs individually in the project report. Is this the expected result?

**Comment by felicitus** [comment]
No feedback given for an extended period of time, closing. Please re-open if you have additional information.
