### ISSUE TITLE
After Project SAVE tab still says New Project.

### ISSUE THREAD

**Issue by slylandro** [partkeepr/PartKeepr#338]
After saving a new project the tab still says New Project.  This doesn't seem to happen all the time.  But this time I can't seem to get it to say anything else.  I hit refresh on the Projects panel, resave and click on other projects and come back to the newly added project and tab still remains New Project.  I have four parts in project.

I have nightly build 20130902.

![image](https://f.cloud.github.com/assets/5251306/1090657/a2ec214a-165a-11e3-87f5-0b40764fcf65.png)

PS - a work around seems to be to close Project's tab and reEdit Projects.

**Comment by felicitus** [comment]
This should now be fixed.
