### ISSUE TITLE
Quantity automatically resets to -n after removing stock.

### ISSUE THREAD

**Issue by ryanpiccirillo** [partkeepr/PartKeepr#340]
Almost always, when I or one of my users removes stock of an item, the stock resets to negative whatever number was taken. IE if I have 9 of an item, and remove 2, the stock sets itself to -2, not 7. This does not always happen.

**Comment by felicitus** [comment]
Any news on this?

**Comment by ryanpiccirillo** [comment]
Basically there was an issue in our database and the tables got screwed up.
I think there was a mismatch between stock entry and part. So no issue with
pk, just a db issue on our end

**Comment by felicitus** [comment]
Thank you for the feedback, I'll close the issue now.
