### ISSUE TITLE
Feature Request: new default units (Bytes, Bits per second and Bits) and 1024-based prefixes

### ISSUE THREAD

**Issue by matthijskooijman** [partkeepr/PartKeepr#356]
For some parts, I guess it makes sense to have "Bytes" (symbol B) and "Bits per seconds" (Symbol bps) units. Perhaps also "Bits" (Symbol b?), for things like bus width?

For properly supporting bytes, the 1024-based prefixes should also be added (e.g., Ki, Mi, Gi, etc.).

**Comment by felicitus** [comment]
1024-based prefixes are now added to the system: https://github.com/partkeepr/PartKeepr/blob/sf2migration/src/PartKeepr/SetupBundle/Resources/setup-data/siprefixes.yml
