### ISSUE TITLE
Unable to attach an image to a storage place

### ISSUE THREAD

**Issue by SweBarre** [partkeepr/PartKeepr#357]
When I try to upload an image to a storage place partkeepr fails to complete the command. 
The image is uploaded to the server and lands in the data/images/temp folder converted to png-format but it never shows up in the web interface.
I've tried to attach images to components and that works just fine.
I'm running 0.1.9 on debian 6.0.8 + apache with MySQL 5.5.33-0+wheezy1 on a second host.

I've reproduced this behavior at http://demo.partkeepr.org/ by trying to attach an image to a storage place.

Cheers

**Comment by felicitus** [comment]
This is now fixed.
