### ISSUE TITLE
Export Stock History Does Nothing

### ISSUE THREAD

**Issue by glowplug** [partkeepr/PartKeepr#359]
Expected:

View => Stock History => *Right Click* => "Export as CSV (.csv)"

Prompts user to download .csv file with contents of Stock History tables.

Current:

View => Stock History => *Right Click* => "Export as CSV (.csv)"

There is no prompt.

***************

This bug affects my system which is an OHV appliance installed into a Ganeti cluster running KVM.  It also affects demo.partkeepr.org so I do not believe the bug is directly related to my configuration.

**Comment by felicitus** [comment]
This should be fixed with the next release, see #435
