### ISSUE TITLE
Uploading attachments litters /tmp with temporary files

### ISSUE THREAD

**Issue by matthijskooijman** [partkeepr/PartKeepr#360]
It seems that when uploading an attachment, it gets saved to /tmp during the process, but the file is then not removed from there. After uploading a bunch of attachments, my /tmp filled up with files named like "PARTKEEPR1mtqFj".

Are those supposed to be cleaned (in which case I should look more closely at my system's setup), or is this an oversight in the code?
##

**Comment by felicitus** [comment]
It seems that the issue is solved as Symfony2 seems to take care of removing temporary files. At least I can't reproduce it anymore - closing.
