### ISSUE TITLE
Issue with setupdatabase script when using postgres

### ISSUE THREAD

**Issue by zarya** [partkeepr/PartKeepr#369]
root@parts:/var/www/tmp/PartKeepr/testing# php SetupDatabase.php --yes --migrate
PartKeepr Setup
Use SetupDatabase.php --help for help

Performing actions...
- Database Schema created/updated
- Admin User created
- Added default part unit
- Imported 36 footprints, skipped 0 because they already existed
- Imported 21 Si Prefixes, skipped 0
- Imported 28 Units, skipped 0 because they already exist
- Imported 285 Manufacturers, skipped 0 because they already exist
  PHP Warning:  mysql_connect(): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in /var/www/tmp/PartKeepr/testing/SetupDatabase.php on line 85
  PHP Warning:  mysql_query(): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in /var/www/tmp/PartKeepr/testing/SetupDatabase.php on line 86
  PHP Warning:  mysql_query(): A link to the server could not be established in /var/www/tmp/PartKeepr/testing/SetupDatabase.php on line 86
  PHP Warning:  mysql_query(): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in /var/www/tmp/PartKeepr/testing/SetupDatabase.php on line 87
  PHP Warning:  mysql_query(): A link to the server could not be established in /var/www/tmp/PartKeepr/testing/SetupDatabase.php on line 87
  PHP Warning:  mysql_select_db(): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in /var/www/tmp/PartKeepr/testing/SetupDatabase.php on line 88
  PHP Warning:  mysql_select_db(): A link to the server could not be established in /var/www/tmp/PartKeepr/testing/SetupDatabase.php on line 88
  PHP Warning:  mysql_query(): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/DistributorMigration.php on line 16
  PHP Warning:  mysql_query(): A link to the server could not be established in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/DistributorMigration.php on line 16
  PHP Warning:  mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/DistributorMigration.php on line 17
- Migrated 0 distributors, skipped 0 because they already exist
  PHP Warning:  mysql_query(): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/FootprintMigration.php on line 21
  PHP Warning:  mysql_query(): A link to the server could not be established in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/FootprintMigration.php on line 21
  PHP Warning:  mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/FootprintMigration.php on line 23
- Migrated 0 footprints, skipped 0 because they already exist
  PHP Warning:  mysql_query(): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/PartCategoryMigration.php on line 33
  PHP Warning:  mysql_query(): A link to the server could not be established in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/PartCategoryMigration.php on line 33
  PHP Warning:  mysql_fetch_array() expects parameter 1 to be resource, boolean given in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/PartCategoryMigration.php on line 35
  PHP Warning:  mysql_query(): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/StorageLocationMigration.php on line 23
  PHP Warning:  mysql_query(): A link to the server could not be established in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/StorageLocationMigration.php on line 23
  PHP Warning:  mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/StorageLocationMigration.php on line 25
- Migrated 0 storage locations, skipped 0 because they already exist
  PHP Warning:  mysql_query(): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/PartMigration.php on line 26
  PHP Warning:  mysql_query(): A link to the server could not be established in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/PartMigration.php on line 26
  PHP Warning:  mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /var/www/tmp/PartKeepr/src/backend/PartKeepr/Setup/Migration/PartDB/PartMigration.php on line 28
- Migrated 0 parts, skipped 0 because they already exist
  All done.

Use the user 'admin' with password 'admin' to login. Access the frontend using the `frontend` directory.
##

**Comment by felicitus** [comment]
Leaving this open to provide a sample database of any kind.

**Comment by baradhili** [comment]
closing this
