### ISSUE TITLE
Fatal error on SetupDatabase.php

### ISSUE THREAD

**Issue by jbirdkerr** [partkeepr/PartKeepr#375]
Good morning,

I'm attempting to set up a dev instance of Partkeepr so I can hack together some barcode scanner functionality. While preparing the installation, I keep running into an error message when I execute the SetupDatabase.php file. Any insight on what might be going wrong? Any help would be greatly appreciated.

ERROR:
Class 'PartKeepr\Util\Configuration' not found in /var/www/PartKeepr/config.php on line 9

Thanks,
Justin

(accidentally closed my initial issue)

**Comment by felicitus** [comment]
I'm sorry for the late reply, the issue must have been slipped through my fingers. Could you solve it or do you need assistance?

**Comment by felicitus** [comment]
No feedback given, please re-open if required.
