### ISSUE TITLE
UpdatePartCacheData.php running, but not updating cronlogger

### ISSUE THREAD

**Issue by staze** [partkeepr/PartKeepr#376]
For some reason, UpdatePartCacheData.php runs, but doesn't update CronLogger field. Debugging shows that for some reason, the __DIR__ and __FILE__ magic constants are not being defined in this script (shown with an echo __FILE__), so it can't update the cronlogger since it doesn't know what script it is. 

Anyone else seeing this issue?

**Comment by felicitus** [comment]
Does the issue occur with more recent PartKeepr versions?

**Comment by staze** [comment]
oh, far as I know, this issue is resolved. UpdatePartCacheData is no longer a cron task, and cron runs successfully with the current version.
