### ISSUE TITLE
New Parameter:Insert exception.

### ISSUE THREAD

**Issue by nobicycle** [partkeepr/PartKeepr#378]
Hi,
When I Add a Parameter

Parameter:Weight 
Value:Gg 
Unit:Gram 
Description:Item Weight

I get this error:

An exception occurred while executing 'INSERT INTO PartParameter (name, description, value, rawValue, part_id, unit_id, siPrefix_id) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["Weight", "Item weight", null, 0, 1, 2, 6]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'value' cannot be null

Versions
partkeepr-0.1.9
mysql  Ver 15.1 Distrib 5.5.37-MariaDB, for Linux (armv7l) using readline 5.1
apache 2.4.9-1 
PHP 5.5.13 (cli) (built: May 29 2014 06:30:19)
##

**Comment by EmanueleDelzeri** [comment]
Hi,
I have the same issue using PartKeepr 0.1.9 Virtual Machine (ova, 2013-10-11)

**Comment by felicitus** [comment]
The issue should now be fixed with the new part parameters, closing.
