### ISSUE TITLE
PHP 5.6

### ISSUE THREAD

**Issue by stazeii** [partkeepr/PartKeepr#383]
Realize Partkeepr isn't actively developed anymore, but curious if anyone has any input on getting it running under PHP 5.6. Seems like the issue is Doctrine, but I'm running into a wall getting things working. 

The error I'm seeing, when trying to login, is:

Class "PartKeepr\User\User" sub class of "PartKeepr\Util\BaseEntity" is not a valid entity or mapped super class.

I previously had this running with 5.3.x, but once I upgraded to 5.6, the login page would load, but on login, I'd get the above warning. 

Any info would be great. I'd really like to get my install back up and running. =)

Thanks!

**Comment by felicitus** [comment]
PartKeepr will be maintained soon again, so good news on that :)

It's hard to tell where the error comes from, I need to reproduce it myself on PHP 5.6, but this could take a couple of weeks. Which exact PartKeepr verson are you running?

**Comment by stazeii** [comment]
=D Hooray! 

Partkeepr version, I'm not sure (I believe it's 0.1.9, judging by the modification dates on the files being 2013/5/3). I'm unable to find that in any of the files (or see where it's reported on the error). 

The "Full Report" is here: 

Class "PartKeepr\User\User" sub class of "PartKeepr\Util\BaseEntity" is not a valid entity or mapped super class.

Exception
==================================
Doctrine\ORM\Mapping\MappingException

Backtrace
==================================
Doctrine\ORM\Mapping\MappingException

Request
==================================
{"url":"rest.php/Auth/login","success":null,"failure":null,"method":"POST","params":"{\"username\":\"username\",\"password\":\"ec84855d96xxxxxxxxxx8015dea550bb\"}","headers":{"call":"login","lang":"en_US"}}

Response
==================================
{"status":"systemerror","success":false,"exception":{"message":"Class \"PartKeepr\\User\\User\" sub class of \"PartKeepr\\Util\\BaseEntity\" is not a valid entity or mapped super class.","exception":"Doctrine\\ORM\\Mapping\\MappingException","backtrace":"#0 \/usr\/local\/php5-5.6.4-20141224-112105\/lib\/php\/Doctrine\/ORM\/Mapping\/Driver\/AnnotationDriver.php(87): Doctrine\\ORM\\Mapping\\MappingException::classIsNotAValidEntityOrMappedSuperClass('PartKeepr\\\\User\\\\...')\n#1 \/usr\/local\/php5-5.6.4-20141224-112105\/lib\/php\/Doctrine\/ORM\/Mapping\/ClassMetadataFactory.php(113): Doctrine\\ORM\\Mapping\\Driver\\AnnotationDriver->loadMetadataForClass('PartKeepr\\\\User\\\\...', Object(Doctrine\\ORM\\Mapping\\ClassMetadata))\n#2 \/usr\/local\/php5-5.6.4-20141224-112105\/lib\/php\/Doctrine\/Common\/Persistence\/Mapping\/AbstractClassMetadataFactory.php(302): Doctrine\\ORM\\Mapping\\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\\ORM\\Mapping\\ClassMetadata), NULL, false, Array)\n#3 \/usr\/local\/php5-5.6.4-20141224-112105\/lib\/php\/Doctrine\/Common\/Persistence\/Mapping\/AbstractClassMetadataFactory.php(205): Doctrine\\Common\\Persistence\\Mapping\\AbstractClassMetadataFactory->loadMetadata('PartKeepr\\\\User\\\\...')\n#4 \/usr\/local\/php5-5.6.4-20141224-112105\/lib\/php\/Doctrine\/ORM\/EntityManager.php(268): Doctrine\\Common\\Persistence\\Mapping\\AbstractClassMetadataFactory->getMetadataFor('PartKeepr\\\\User\\\\...')\n#5 \/usr\/local\/php5-5.6.4-20141224-112105\/lib\/php\/Doctrine\/ORM\/EntityManager.php(682): Doctrine\\ORM\\EntityManager->getClassMetadata('PartKeepr\\\\User\\\\...')\n#6 \/var\/www\/html\/partkeepr\/src\/backend\/PartKeepr\/User\/UserManager.php(89): Doctrine\\ORM\\EntityManager->getRepository('PartKeepr\\\\User\\\\...')\n#7 \/var\/www\/html\/partkeepr\/src\/backend\/PartKeepr\/Auth\/AuthService.php(73): PartKeepr\\User\\UserManager->authenticate(Object(PartKeepr\\User\\User))\n#8 \/var\/www\/html\/partkeepr\/src\/backend\/PartKeepr\/Service\/ServiceManager.php(131): PartKeepr\\Auth\\AuthService->login()\n#9 \/var\/www\/html\/partkeepr\/frontend\/rest.php(56): PartKeepr\\Service\\ServiceManager->call()\n#10 {main}"},"timing":0.0031380653381348}

Server Configuration
==================================
doctrine_orm_version: 2.3.3
doctrine_dbal_version: 2.3.4
doctrine_common_version: 2.3.0
php_version: 5.6.4
maxUploadSize: 2097152
availableImageFormats: 3FR,A,AI,ART,ARW,AVI,AVS,B,BGR,BMP,BMP2,BMP3,BRF,BRG,C,CAL,CALS,CAPTION,CIN,CIP,CLIP,CMYK,CMYKA,CR2,CRW,CUR,CUT,DCM,DCR,DCX,DDS,DFONT,DNG,DOT,DPX,EPDF,EPI,EPS,EPS2,EPS3,EPSF,EPSI,EPT,EPT2,EPT3,ERF,FAX,FITS,FRACTAL,FTS,G,G3,GBR,GIF,GIF87,GRADIENT,GRAY,GRB,GROUP4,HALD,HISTOGRAM,HRZ,HTM,HTML,ICB,ICO,ICON,INFO,INLINE,IPL,ISOBRL,JPEG,JPG,K,K25,KDC,LABEL,M,M2V,M4V,MAP,MAT,MATTE,MIFF,MONO,MOV,MP4,MPC,MPEG,MPG,MRW,MSL,MSVG,MTV,MVG,NEF,NULL,O,ORF,OTB,OTF,PAL,PALM,PAM,PATTERN,PBM,PCD,PCDS,PCL,PCT,PCX,PDB,PDF,PDFA,PEF,PFA,PFB,PFM,PGM,PICON,PICT,PIX,PJPEG,PLASMA,PNM,PPM,PREVIEW,PS,PS2,PS3,PSD,PTIF,PWP,R,RADIAL-GRADIENT,RAF,RAS,RBG,RGB,RGBA,RGBO,RLA,RLE,SCR,SCT,SFW,SGI,SHTML,SR2,SRF,STEGANO,SUN,SVG,SVGZ,TEXT,TGA,THUMBNAIL,TIFF,TIFF64,TILE,TIM,TTC,TTF,TXT,UBRL,UIL,UYVY,VDA,VICAR,VID,VIFF,VST,WBMP,WMF,WMV,WMZ,WPG,X,X3F,XBM,XC,XCF,XPM,XPS,XV,XWD,Y,YCbCr,YCbCrA,YUV

**Comment by stazeii** [comment]
I've also made sure, just in case, to disable opcache for this vhost just incase it was causing an issue. No change.

**Comment by felicitus** [comment]
The PartKeepr version can be found at View->System Information. If you need to have the system back up running, I suggest you roll back to PHP 5.3 or PHP 5.4 until I can verify the issue.

**Comment by stazeii** [comment]
I can't get to view unless logged in, which is where this error comes up. 

It's not a huge deal it's not running... would just love to get it back up and running, so I'm quite happy it'll be maintained again soon. I had hopes since I saw there was a github change a couple weeks ago. =)

**Comment by felicitus** [comment]
Whoops, my fault /o\

The file which contains the version is src/backend/PartKeepr/PartKeeprVersion.php

**Comment by stazeii** [comment]
const PARTKEEPR_VERSION = '0.1.9';

=)

**Comment by stazeii** [comment]
Judging by some googling, it SEEMS like it's a relatively known issue that Doctrine 2.3.x (and later versions) have issues with PHP 5.6. So may be there's just some update to doctrine that needs to happen, but when I tried going down that hole, things just broke worse. =/ Doesn't help that Doctrine no longer supports pear installs, you have to use Composer. =/

**Comment by stazeii** [comment]
Also, here's Apache error log (sanitized):

[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP Warning:  require(Doctrine/Common/Cache/ArrayCache.php): failed to open stream: No such file or directory in /usr/local/php5-5.6.4-20141224-112105/lib/php/Doctrine/Common/ClassLoader.php on line 182
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP Stack trace:
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP   1. {main}() /var/www/html/partkeepr/frontend/index.php:0
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP   2. PartKeepr\\PartKeepr::initialize() /var/www/html/partkeepr/frontend/index.php:13
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP   3. PartKeepr\\PartKeepr::initializeDoctrine() /var/www/html/partkeepr/src/backend/PartKeepr/PartKeepr.php:34
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP   4. Doctrine\\ORM\\Configuration->newDefaultAnnotationDriver() /var/www/html/partkeepr/src/backend/PartKeepr/PartKeepr.php:168
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP   5. spl_autoload_call() /var/www/html/partkeepr/src/backend/PartKeepr/PartKeepr.php:158
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP   6. Doctrine\\Common\\ClassLoader->loadClass() /var/www/html/partkeepr/src/backend/PartKeepr/PartKeepr.php:0
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP Fatal error:  require(): Failed opening required 'Doctrine/Common/Cache/ArrayCache.php' (include_path='.:/usr/local/php5/lib/php') in /usr/local/php5-5.6.4-20141224-112105/lib/php/Doctrine/Common/ClassLoader.php on line 182
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP Stack trace:
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP   1. {main}() /var/www/html/partkeepr/frontend/index.php:0
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP   2. PartKeepr\\PartKeepr::initialize() /var/www/html/partkeepr/frontend/index.php:13
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP   3. PartKeepr\\PartKeepr::initializeDoctrine() /var/www/html/partkeepr/src/backend/PartKeepr/PartKeepr.php:34
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP   4. Doctrine\\ORM\\Configuration->newDefaultAnnotationDriver() /var/www/html/partkeepr/src/backend/PartKeepr/PartKeepr.php:168
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP   5. spl_autoload_call() /var/www/html/partkeepr/src/backend/PartKeepr/PartKeepr.php:158
[Thu Jan 08 16:31:38 2015] [error] [client 123.123.123.123] PHP   6. Doctrine\\Common\\ClassLoader->loadClass() /var/www/html/partkeepr/src/backend/PartKeepr/PartKeepr.php:0

**Comment by stazeii** [comment]
Sorry, that Apache log in just posted (and deleted) was old when I was trying to upgrade Doctrine. I have no current errors being logged by Apache.

**Comment by stazeii** [comment]
This http://www.doctrine-project.org/jira/browse/DDC-3120 may or may not be relevant. There seem to be no shortage of google results for "Doctrine php 5.6" with or without specifying Doctrine 2.3. =(

**Comment by stazeii** [comment]
felicitus,

Did you manage to reproduce? Any luck with workarounds or anything?

**Comment by felicitus** [comment]
Sorry I completely forgot about this. Just tried PartKeepr 0.1.9 on my development machine, and it seems to work fine here.

I haven't got an idea yet why you're getting that error.
![untitled](https://cloud.githubusercontent.com/assets/162974/6079503/74818c38-ae06-11e4-81fc-996d827f99ea.png)

A (very quick) research yields a hint where opcache might be an issue. Can you post your phpinfo() status page? A description on how to create one is described here: http://kb.mediatemple.net/questions/764/How+can+I+create+a+phpinfo.php+page%3F#gs

If you don't want to post it here, you can also send it via email to me.

**Comment by stazeii** [comment]
I do have a phpinfo page. Where should I email it to? 

Interesting you're using the same doctrine version... I have tried turning off opcache and it didn't seem to help.

**Comment by stazeii** [comment]
Damn it, you're right. I just found a second place it was enabled, disabled it, and partkeepr runs. Crap. 

Now I just need to figure out why I can't disable it on a vhost basis....

**Comment by stazeii** [comment]
Okay, fixed. That link you pointed me to just said you need to set (in php.ini): 

opcache.save_comments=1
opcache.load_comments=1

And indeed, that fixes it. Awesome, thanks!

**Comment by stazeii** [comment]
Figures, here's the php.net documentation on opcache.save_comments. 

opcache.save_comments boolean
If disabled, all documentation comments will be discarded from the opcode cache to reduce the size of the optimised code. Disabling this configuration directive may break applications and frameworks that rely on comment parsing for annotations, including Doctrine, Zend Framework 2 and PHPUnit.

I would have never thought comments would be used for actual necessary code... that just seems wrong.

**Comment by felicitus** [comment]
Yes, it seems odd at first that comments influence code, but it's heavily used in modern frameworks (including Symfony2) to boost performance by parsing meta-data which otherwise would not be possible with PHP.

Metadata could be stored in other formats, like XML or YAML, but the common way is to use annotations because it is directly visible in the code directly without having to maintain separate files. Here's a pretty critical POV about using annotations: https://r.je/php-annotations-are-an-abomination.html

I really hope that PHP will get real annotations at some point in the future like in JAVA ( http://en.wikipedia.org/wiki/Java_annotation ) but right now it's the only convinient method for me to develop things (and it is the standard for Symfony2 and Doctrine2).

I will leave this issue open so that I implement a check wether opcache.save_comments is disabled and to spit out a runtime error when it is.

**Comment by stazeii** [comment]
Awesome, thanks! May want to check for opcache.load_comments as well, but I haven't checked if that actually matters. 

Other option would just be to add those php directives a .htaccess, or to the config file for partkeepr. 

Thanks for the assist with finding that... must have been searching for something else since I never saw any indication of that being the issue. =/

**Comment by felicitus** [comment]
Well it took me quite some thinking about the correct search terms, because the error was very odd, indicating that some mapping has gone wrong. I'm glad you got it working!

**Comment by stazeii** [comment]
oh, good. =) Now I won't doubt my google-fu... I don't use doctrine at all, so I had no place to start. =)

Thanks again, and good luck with version 1.0!

**Comment by DarkGigaByte** [comment]
Created new Issue for better Overview. This one will be closed soon.
