### ISSUE TITLE
DropDownLists show only one Item

### ISSUE THREAD

**Issue by HKay** [partkeepr/PartKeepr#387]
The drop-down list (e.g. footprint) in the "edit part"-dialog only shows one random item. This will not go away by closing the floating window and reopening it. It affects all parts. Closing the browser tab however works. To my knowledge this bug only appears after extended use(6+ hours) of the same browser tab.
This bug is more prominent in the "Manufacturers" tab. After adding a new element it only shows a single manufacturer.
Steps to reproduce:
1. reset all filters
2. search a part by internal partnumber
3. open filter and enter a valid foodprint to filter by
3. do _not_ press apply button
4. double click part to open detailed view
5. bug: you cannot select footprints other than the one you entered in the filter

**Comment by angelusbritos** [comment]
I have seen it here many times.
Just logout -> login or reload the tab and everything come back. (reload
means that I have to login again)



Regards,
Angelo Silva Brito.
Graduate in Engenharia da Computação - UFPE
*http://about.me/angelobrito <http://about.me/angelobrito>*
*_________________________________________________*

**Comment by felicitus** [comment]
This should now be fixed. Every dropdown uses their own store with own filtering, so filters added to one dropdown won't affect the others.
