### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'stockLevel' cannot be null' 

### ISSUE THREAD

**Issue by stazeii** [partkeepr/PartKeepr#392]
Seeing an error when UpdatePartCacheData.php runs where it's claiming there is a stockLevel that's null. From looking through the DB, I don't see what it's talking about. =/ 

Any thoughts on where I could look to figure out what it's talking about?

The full error message is: 

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'stockLevel' cannot be null' in /usr/local/php5-5.6.6-20150220-223817/lib/php/Doctrine/DBAL/Connection.php:784
Stack trace:
#0 /usr/local/php5-5.6.6-20150220-223817/lib/php/Doctrine/DBAL/Connection.php(784): PDOStatement->execute()
#1 /usr/local/php5-5.6.6-20150220-223817/lib/php/Doctrine/ORM/Persisters/BasicEntityPersister.php(447): Doctrine\DBAL\Connection->executeUpdate('UPDATE Part SET...', Array, Array)
#2 /usr/local/php5-5.6.6-20150220-223817/lib/php/Doctrine/ORM/Persisters/BasicEntityPersister.php(357): Doctrine\ORM\Persisters\BasicEntityPersister->_updateTable(Object(PartKeepr\Part\Part), 'Part', Array, NULL)
#3 /usr/local/php5-5.6.6-20150220-223817/lib/php/Doctrine/ORM/UnitOfWork.php(984): Doctrine\ORM\Persisters\BasicEntityPersister->update(Object(PartKeepr\Part\Part))
#4 /usr/local/php5-5.6.6-20150220-223817/lib/php/Doctrine/ORM/UnitOfWork.php(317): Doctrine\ORM\UnitOfWork->executeUpdates(Ob in /usr/local/php5-5.6.6-20150220-223817/lib/php/Doctrine/DBAL/DBALException.php on line 47

**Comment by hardwic** [comment]
This happens if you add a part but don't enter a value or forget to tick the per item box.
Just find the parts with no stock history and add 1 comp with a value and then remove it.

**Comment by stazeii** [comment]
Okay, I just finished doing this. Interestingly, for those parts, "add stock" treated things like having null stock to start with (so a part that showed as having 10 pieces, adding 2 resulted in 2 total). We'll see if the error re-occurs next Cron run. 

Thanks!

**Comment by stazeii** [comment]
That seems to have worked. I thought it didn't, but then managed to find one item I missed adding stock to. 

Cool, thanks!

**Comment by felicitus** [comment]
I'm reopening this as it's a bug which should be fixed.

**Comment by felicitus** [comment]
The cronjob is not necessary anymore, thus closing.
