### ISSUE TITLE
Feature request: Datasheet PDF Button

### ISSUE THREAD

**Issue by kitusmark** [partkeepr/PartKeepr#394]
I wish there was a button right in the part details window to show up the datasheet.

Now I have to enter edit mode and fo to the attachment label.

**Comment by DIYsciBorg** [comment]
Second this one.
Seems like the simplest "just for now" options is to make the paperclip icon functional.
Click it, it immediately opens the part data view popup set to the Attachments tab. From there you can view the datasheet.

**Comment by felicitus** [comment]
Attachments are now directly accessible in the details panel.

![attachments](https://cloud.githubusercontent.com/assets/162974/9027173/d047947a-394a-11e5-8422-fc9281bd0480.png)

Let me know if this works for you.

**Comment by felicitus** [comment]
@DIYsciBorg @kitusmark ping, can you give feedback if directly accessible attachments as shown above will work for you?

**Comment by felicitus** [comment]
No feedback given, so I believe this issue is fixed.
