### ISSUE TITLE
SF2Migration developer install

### ISSUE THREAD

**Issue by troy-jacobson** [partkeepr/PartKeepr#395]
Hi,
I'm running into some problems with the developer install of the SF2Migration branch.  Some I've been able to fix, but there are a couple I need help with.  This is a fresh install of partkeepr on a clean Ubuntu 15.4 VM. 

- Early in the INSTALL-UBUNTU directions is the "composer.phar install" command.  However, the composer.json and composer.lock files don't exist until the repo is checked out.  It ran successfully once the repo exists.  Should the directions be updated to reflect this?
- I ran across some packages that I needed to install, like php5-imagick and php5-gd, plus some pear packages that aren't explicitly listed in the directions.  Should they be added to the directions?
- GIT was complaining about extras/library/extjs5.  I added a new entry in .gitmodules for that library.
- In response to another issue, you suggested opening the PartKeepr/setup page in the browser.  That helped resolve some issues.  Should that be added to the directions as well? 

The unresolved issues:
- When running SetupDatabase.php
       PHP Fatal error:  Class 'PartKeepr\Util\Configuration' not found in /home/osboxes/PartKeepr/config.php on line 9
- When running php partkeepr.php migrations:migrate
        PHP Fatal error:  Call to undefined method PartKeepr\PartKeepr::initializeClassLoaders() in /home/osboxes/PartKeepr/partkeepr.hp on line 16
- the same initializeClassLoaders() error occurs when runing phing build
- This log message at the Checking Database Connectivity stop of setup:
        PHP Fatal error:  Call to undefined method PartKeepr\\PartKeepr::initialiizeClassLoaders() in /home/osboxes/PartKeepr/setup/tests/check-database-connectivity.php on line 12, referer: http://localhost/PartKeepr/setup/

**Comment by felicitus** [comment]
The installation instructions are completely invalid for this branch. If you are interested in helping with development, please step by in IRC and we can go through the setup together. However, be aware that the frontend doesn't work at all and my focus is currently on moving all PartKeepr modules into separate bundles.

**Comment by felicitus** [comment]
Keeping this issue open to remind me to update documentation for the sf2 branch.

**Comment by felicitus** [comment]
The installation instructions are now in place, refer to README.md
