### ISSUE TITLE
Can PartKeepr be installed on HostGator?

### ISSUE THREAD

**Issue by greenrider** [partkeepr/PartKeepr#403]
Hi,
I really like this project, and I want to try it for my home electronics inventory and maybe later install it at our local hackerspace.
But I have no idea how to install it because I can't find the Setup folder.
The latest release is from 2013 and it has a Setup folder but I am not sure how to update it later to the newest verion.

Can you please make a new release?
Also can PartKeepr be installed as a website on HostGator (this will make it easier to access from anywhere)?

Thank you very much for your help.

**Comment by felicitus** [comment]
i have no idea if PartKeepr can be installed at that particular provider.

PartKeepr 0.1.9 is the latest version and there's no release since then, you should stick with that version until a new one is released.

**Comment by greenrider** [comment]
Thank you.
I will try it.
