### ISSUE TITLE
Distributor Order Change

### ISSUE THREAD

**Issue by lookme2** [partkeepr/PartKeepr#423]
Have the ability to change the order of the listed distributor per part.

**Comment by felicitus** [comment]
Where exactly do you want to change the order?

**Comment by lookme2** [comment]
Under the Edit Part window.  There is a tab for Distributors.  That is where I would like to change the order.  I have found that if I do a Project Report and have multiple distributors that the first distributor is the only one to show up.

**Comment by felicitus** [comment]
If you refer to the auto-fill function: The order of the distributors doesn't matter. It should pick the cheapest distributor for a specific part.

**Comment by lookme2** [comment]
OK thanks.

**Comment by felicitus** [comment]
Can this issue be closed?

**Comment by lookme2** [comment]
Yes this can be closed.
