### ISSUE TITLE
Print or export stock level 

### ISSUE THREAD

**Issue by diodenschein** [partkeepr/PartKeepr#424]
it would be nice to have a printable list view of parts, 
either by direct print or export to csv.

**Comment by felicitus** [comment]
What you already can do is to right-click on any grid and export it as CSV, if that helps.

**Comment by diodenschein** [comment]
\o/ Works for me. I didn't search for it there. Thanks

**Comment by felicitus** [comment]
The only problem with that approach is that it only exports the visible view. I'll reopen this to implement export over all records, not only the visible ones.

**Comment by lookme2** [comment]
We have figured out how the printing works.   You need to add json_decode  expressions into the "Additional Configuration" field.

Here is  an Example

{
"barcodeEnable":true,
"text": "<span style='font-size: 11pt;'><b>!!name!!</b>
</span><br><span style='font-size: 8pt;'>!!description!!</span><br>
<span>Storage Location = !!storageLocationName!!</span>"
}

**Comment by felicitus** [comment]
The new exporter is in place, which allows to export all pages.
