### ISSUE TITLE
Unable to setup Partkeepr

### ISSUE THREAD

**Issue by sukhbirkaur** [partkeepr/PartKeepr#427]
I'm trying to set up 'PartKeepr', but keep getting the error at the prerequisites:

Doctrine needs to be installed and in the PHP include_path.

Doctrine\Common\ClassLoader was not found

I have installed Doctrine through Composer in C drive
![capture3](https://cloud.githubusercontent.com/assets/13806148/9808438/946f4bb8-587c-11e5-9118-45881a30b8a7.PNG)

I did include_path in php.ini file but didn't work. What path i have to include and how to resolve the issue? Please help

**Comment by felicitus** [comment]
PartKeepr 0.1.9 does not run on Windows. Please use the virtual machine which you can download at https://www.partkeepr.org/download/

**Comment by sukhbirkaur** [comment]
Ok. Thanks for help.
