### ISSUE TITLE
Help for Immigration from virtual machine to Ubuntu step by step (nothing happens)

### ISSUE THREAD

**Issue by Greatal** [partkeepr/PartKeepr#432]
Hi I recently have problem with my original virtual machine image so I decide to move from it to new Ubuntu Linux I use this topic (https://forum.partkeepr.org/viewtopic.php?f=2&t=1655) as guide to install my new partkeepr installation and it was almost successful at least setup goes with no errors
Step 1:
Using su to login as root user then 
apt-get install php5
apt-get install apache2
apt-get install apache2-utils
apt-get install libmagickwand5
apt-get install imagemagick
apt-get install php5-curl
apt-get install php-pear
apt-get install mysql-server-5.5
apt-get install php5-dev
apt-get install curl
apt-get install php5-json
apt-get install php5-imagick
apt-get install php5-gd
apt-get install php5-mysql

Then use this command
chmod 777 /etc/php5/apache2/php.ini
nano /etc/php5/apache2/php.ini
find “date.timezone” using CTL+W
to change 
date.timezone = Europe/Tallinn
Actually uncomment it then change it 
And then CRTL+x to exit and save using y and confirm file path by just enter after file path displayed
Then 
pear channel-discover pear.symfony.com
pear channel-discover pear.doctrine-project.org
pear install pear.doctrine-project.org/DoctrineORM
pear install pear.doctrine-project.org/DoctrineSymfonyYaml
pear install pear.doctrine-project.org/DoctrineSymfonyConsole
pear channel-discover pear.twig-project.org
pear install twig/Twig
Then
Using this command download last partkeepr
wget -O /tmp/ partkeepr-0.1.9.tbz2 http://partkeepr.org/downloads/partkeepr-0.1.9.tbz2
then unpack it
using
tar -xvf /tmp/ partkeepr-0.1.9.tbz2
then move it using 
sudo mv /tmp/partkeepr-0.1.9 /var/www/html/partkeepr-0.1.9
then give it full permission using this command
sudo chmod -R 777 /var/www/partkeepr-0.1.9
then login to mysql using this command
mysql --user=root –pMyPassword
Then create database using 
CREATE DATABASE partkeepr
And exit it using /q
Then restore my data base using this command
mysql partkeepr < partkeepr.sql –u root –pMyPassword
then copy old parkeepr files from my old virtual machine over network
re run setup
and then nothing happens it simply show me nothing
can any one help me how I can fix my problem

**Comment by Greatal** [comment]
I use have to use this path for setup 
http://127.0.0.1/partkeepr-0.1.9/setup/
But in old system partkeepr folder was not required

**Comment by Greatal** [comment]
it almost work using this url http://127.0.0.1/partkeepr-0.1.9/frontend/

**Comment by felicitus** [comment]
Is the problem solved?
