### ISSUE TITLE
Symfony2 memory issue

### ISSUE THREAD

**Issue by Drachenkaetzchen** [partkeepr/PartKeepr#438]
When running the kernel in the production environment with debugging turned off, the initial container building process eats lots of memory (>128M on my machine).

The main reason for that is that Symfony attempts to build the container cache and stripping all comments. This happens within bootstrap.php.cache in stripComments.

I'm having a hard time lifting the minimum required memory limit to 256M, so for now, the app kernel runs in debug mode which doesn't strip the comments.

We should check if we can refactor stripComments to work on individual files or if we can disable stripping if low memory is detected.

**Comment by JarrettR** [comment]
Running PHP 7 significantly improves (but does not fix) this issue

**Comment by felicitus** [comment]
@JarrettR as there was already a commit to reduce memory usage, what exact problem do you encounter?

**Comment by JarrettR** [comment]
Sorry, should clarify that I'm just adding more information for people that are troubleshooting memory issues with PK. No action needed! I'm an edge case trying to run it on a tiny tiny VM.
