### ISSUE TITLE
After git clone, get error executing composer install

### ISSUE THREAD

**Issue by damoclark** [partkeepr/PartKeepr#442]
Using commit: 2dc6fd724395ab910966af23243206ce24cebba9

When executing 'composer install', I get the following error:

...
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
                                
  [Symfony\Component\Config\Exception\FileLoaderLoadException]                                                                                                                                                                 
  The file "parameters.php" does not exist (in: /opt/rh/httpd24/root/var/www/html/PartKeepr/app/config) in parameters.php (which is being imported from "/opt/rh/httpd24/root/var/www/html/PartKeepr/app/config/config.yml").  
                                                                                                          
  [InvalidArgumentException]                                                                              
  The file "parameters.php" does not exist (in: /opt/rh/httpd24/root/var/www/html/PartKeepr/app/config).  

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets handling the post-install-cmd event terminated with an exception

  [RuntimeException]                                                           
  An error occurred when executing the "'assets:install '\''web'\'''" command  
  .                                                                            
                                                                               
I am using apache 2.4, php 5.6 and postgresql 9.4 from softwarecollections.org on Centos 7.1

**Comment by damoclark** [comment]
Further information.  I rolled back to the previous commit on the sf2migration branch (e775641e442836e779d08f3d68898adffa310f6d) and the error does not occur.  The regression is introduced in the latest commit on the sf2migration branch. 

Hope this helps.

**Comment by felicitus** [comment]
Yes, because `incenteev/composer-parameter-handler` could auto-create the parameters.yml file, but doesn't know about parameters.php file.

Just copy the parameters.php.dist file in app/config to parameters.php. After that, run web/setup/index.html to start the setup.

**Comment by damoclark** [comment]
Thanks.  Didn't notice the 'dist' file there.

**Comment by felicitus** [comment]
The remark is now added to the README file.
