### ISSUE TITLE
ImageMagick not installed

### ISSUE THREAD

**Issue by damoclark** [partkeepr/PartKeepr#445]
Hi Timo,
I hope these bug reports are helping.  

Related to the missing index page for the web/ directory, if I point my browser directly at the app.php script (not sure if that should be done):
http://site/app.php

then get the following error in browser page.
![screen shot 2015-10-18 at 8 54 53 pm](https://cloud.githubusercontent.com/assets/275110/10563779/5dfda792-75db-11e5-8051-003f1e4e238a.png)

After installing the ImageMagick libraries for php and graceful apache, this error disappears.  Might want to add to your dependencies list.

**Comment by felicitus** [comment]
Yes, they are helping :+1: 

In fact this is a bogus message from the old PartKeepr versions - I need to remove the check within the IndexController.

**Comment by felicitus** [comment]
The check for Imagick is now gone. Leaving this issue open to implement a generic wrapper for GD and Imagick, because Imagick supports more formats, but is not widely available.

**Comment by baradhili** [comment]
I think this is gone now
