### ISSUE TITLE
After logging in, UI does not work and not connected

### ISSUE THREAD

**Issue by damoclark** [partkeepr/PartKeepr#446]
Hi Timo,
Not sure if this is where you are up to with your dev.  I get a login page by pointing at app.php after installing imagemagick, but after logging in with admin account, the UI does not update to reflect login status.  I have checked my browser console log using firebug, and there are no errors reported.
Here is what the UI looks like - hopefully it might help.  

![screen shot 2015-10-18 at 8 44 26 pm](https://cloud.githubusercontent.com/assets/275110/10563796/2b181a96-75dc-11e5-851c-79f3d854086f.png)
![screen shot 2015-10-18 at 8 44 37 pm](https://cloud.githubusercontent.com/assets/275110/10563797/2b1aaaa4-75dc-11e5-9825-ad5c121bcb83.png)
![screen shot 2015-10-18 at 8 45 07 pm](https://cloud.githubusercontent.com/assets/275110/10563798/2b21f318-75dc-11e5-8b65-76ae952f398c.png)
![screen shot 2015-10-18 at 8 45 17 pm](https://cloud.githubusercontent.com/assets/275110/10563800/2b2e1a4e-75dc-11e5-8526-4c0d27432c5c.png)
![screen shot 2015-10-18 at 8 45 26 pm](https://cloud.githubusercontent.com/assets/275110/10563799/2b2771ee-75dc-11e5-86d4-b86c0323e444.png)

Again, hope this helps.
Damien.

**Comment by felicitus** [comment]
Given the previous bug, I assume that your apache server can't parse the `.htaccess` files.

**Comment by felicitus** [comment]
There have been a few major changes, can you try again with the latest GIT version?

**Comment by damoclark** [comment]
Hey sorry for the delay in responding.  Busy period at work.  

I'll take a look this weekend.

**Comment by felicitus** [comment]
No feedback was given for an extended period of time, thus closing the issue as I believe it is fixed.
