### ISSUE TITLE
Rename or delete old config.php after successful setup

### ISSUE THREAD

**Issue by felicitus** [partkeepr/PartKeepr#460]

**Comment by felicitus** [comment]
This should be solved as we are parsing the legacy config.php file only if no parameters.php file exists.

**Comment by diodenschein** [comment]
This did't work fr my last pull. Old config.php was read.

**Comment by felicitus** [comment]
You need a very fresh pull, this was fixed with https://github.com/partkeepr/PartKeepr/issues/461

**Comment by diodenschein** [comment]
Race condition ;-)
