### ISSUE TITLE
Unable to add Distributor to Part 

### ISSUE THREAD

**Issue by diodenschein** [partkeepr/PartKeepr#471]
Open Part Details -> Distributors -> Add -> select a distributor from dropdown -> save 

Javascript console: 

>  InvalidCharacterError: DOM Exception 5: An invalid or illegal character was specified, such as in an XML name. setAttributemain.js:47064

**Comment by felicitus** [comment]
I tried to reproduce this, but it works fine on my machine. Does this happen for all distributors on your installation, or just a specific one?

**Comment by diodenschein** [comment]
Even if I might start looking like I'm making up bugs. 
It happened. Can't reproduce anymore.

**Comment by felicitus** [comment]
No worries. Can I close it until you can reproduce it again?
