### ISSUE TITLE
problem with deleting users 

### ISSUE THREAD

**Issue by mctomaszek** [partkeepr/PartKeepr#478]
An exception occurred while executing 'DELETE FROM PartKeeprUser WHERE id = ?' with params [2]: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`partkeepr`.`Session`, CONSTRAINT `FK_1FF9EC48A76ED395` FOREIGN KEY (`user_id`) REFERENCES `PartKeeprUser` (`id`))

any idea what is wrong?

**Comment by felicitus** [comment]
Yes, there's an active session in the database. You can delete the session from the database session table, but if the user has added parts, changed stock etc it's currently not possible to delete the user due to a similar issue.

This exact issue will be fixed with the next release, because no sessions are stored in the database anymore.

**Comment by felicitus** [comment]
Were you able to delete the user?

**Comment by felicitus** [comment]
This issue is related to #417

**Comment by punkkeks** [comment]
I have a similar issue, but not with the session, but because the users has preferences (hmm... not too unusual). Maybe add a foreign `ON DELETE CASCADE` ?! (It is a legecay user, that I tried to get rid off, maybe that's important?)


````
An error occurred

Details
==================================
An exception occurred while executing 'DELETE FROM PartKeeprUser WHERE id = ?' with params [18]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`partkeepr`.`UserPreference`, CONSTRAINT `FK_922CE7A2A76ED395` FOREIGN KEY (`user_id`) REFERENCES `PartKeeprUser` (`id`))

Request
==================================
DELETE /api/users/18?_dc=1452883707666

[object Object]

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"An exception occurred while executing \u0027DELETE FROM PartKeeprUser WHERE id = ?\u0027 with params [18]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`partkeepr`.`UserPreference`, CONSTRAINT `FK_922CE7A2A76ED395` FOREIGN KEY (`user_id`) REFERENCES `PartKeeprUser` (`id`))"}

Server Configuration
==================================
doctrine_orm_version: 2.5.1
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.17-1~dotdeb+7.1
auto_start_session: true
maxUploadSize: 8388608
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
```

**Comment by felicitus** [comment]
Good find. Would it be able to open a separate issue? UserPreferences should be deleted when the user is deleted and can be fixed separately.

**Comment by baradhili** [comment]
closing this
