### ISSUE TITLE
Setup Compete tab Submit button returns to Welcome

### ISSUE THREAD

**Issue by nobicycle** [partkeepr/PartKeepr#480]
When clicking submit on the Setup Compete tab of the installer, it does not forward to Partkeepr app, but returns to the installer Welcome screen. No errors displayed. No errors in Nginx log.

Perhaps the nginx rewrite rules need adjusting . What is the url that Submit should forward to?
(Github install)

**Comment by felicitus** [comment]
Which URI did you use to run the setup? Was it /setup/index.html or just /setup/?

What I'm basically doing in the setup is to strip /setup/index.html from the path. I guess it should also remove /setup/ in case the user didn't use the index.html file.

**Comment by felicitus** [comment]
I changed the redirect, can you check if this problem is solved when you run setup next time?

**Comment by nobicycle** [comment]
Just did a fresh github refreshed install. "Symphony2 Requirements " stage passed OK.
But next the "Webserver misconfiguration" error returned
Exactly the same configuration for nginx as in https://github.com/partkeepr/PartKeepr/issues/479 (where install finished OK) was in use.

*location ~ ^/partkeepr/(web|app)/.php(/|$) {
fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
fastcgi_split_path_info ^(.+.php)(/.)$;
include /etc/nginx/fastcgi.conf;
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
fastcgi_param DOCUMENT_ROOT $realpath_root;
}*

The nginx error :
*2015/11/17 17:53:56 [error] 517#0: *104 open() "/srv/http/partkeepr/web/setup.php/setup/webserverTest" failed (20: Not a directory), client: 127.0.0.1, server: localhost, request: "POST /partkeepr/web/setup.php/setup/webserverTest HTTP/1.1", host: "localhost", referrer: "http://localhost/partkeepr/web/setup/"*

Regards

**Comment by felicitus** [comment]
From your config it seems that it is missing setup. You only got (web|app), but I think it should be (web|app|setup).

**Comment by felicitus** [comment]
The knowledge base article regarding web server setup is now updated [PartKeepr knowledge base article](https://wiki.partkeepr.org/wiki/KB00005:Web_Server_Configuration)

**Comment by felicitus** [comment]
I believe this issue was solved by providing proper nginx configuration in the PartKeepr wiki. If you feel otherwise, please leave a comment.
