### ISSUE TITLE
Setup blank page

### ISSUE THREAD

**Issue by RichardNeilson** [partkeepr/PartKeepr#484]
Hi, I have been trying again to install PartKeepr using the upto date Zip file from GitHub. Maybe it's something i'm doing wrong but when trying to run setup all I see is a blank screen. Viewing the debugger window it seems to be an issue with the breadcrumbwizard, an error or line 19 saying EXT isn't defined. Is this something still being worked on or is it just me being dumb and missing something. Many thanks, Richard

**Comment by felicitus** [comment]
You can't use the ZIP file from github unless you follow the steps listed in https://github.com/partkeepr/PartKeepr/blob/sf2migration/documentation/Installation.md

If you wish to use the 0.75 release which came out yesterday you can download it from https://www.partkeepr.org/downloads

**Comment by RichardNeilson** [comment]
Thanks for your quick reply again. I had read you're installation instructions but had assumed the zip file was from the GitHub zip download, I didn't realise that there was a downloads page as well as a download page with a new version just released. As usual I'm being a bit of a div. From following your advise I uploaded the correct files to my website and after upgrading PHP from 5.5 to 5.6 to clear the first error during setup I now have an error when testing for PHP setting - "Invalid Response from server" Is there something else I need to be checking for? I have the option to upgrade to PHP 7.0 as well if needed but I'm not sure I can go back to PHP 5.6 afterwards if needed. Thanks again!

**Comment by felicitus** [comment]
What response is it? You can view it by clicking the "Details" button

**Comment by RichardNeilson** [comment]
Clicking details shows the same message "Invalid Response from server"

**Comment by felicitus** [comment]
It's odd that there's no text. I assume that you are getting the invalid response due to an internal server error, so you should have a look at your web server's error log.

**Comment by RichardNeilson** [comment]
I think the issue was with missing files. I uploaded and over wrote the existing files again and it worked ok. I do however still have a problem with login. After the setup clicking submit tried to restart the setup. I instead went directly to the app to start out but it doesn't recognise the username/password I created. Setup won't let me redo this as it detects an existing user. Is there somewhere I can retrieve or reset the user details? Thanks again.

**Comment by felicitus** [comment]
You can remove the app/config/parameters.php file, then it should allow you to re-create an admin user.

**Comment by RichardNeilson** [comment]
Thank you yet again for your support, I'll try that later when I'm back at home. Cheers

**Comment by felicitus** [comment]
On second thought, I believe the user is only created if it doesn't exist. So you would need to specify a different username for the admin. I also created an issue to reset the password on setup #485

**Comment by felicitus** [comment]
May I close the issue?

**Comment by RichardNeilson** [comment]
Yes if you want to. I still can't login after the setup. I've tried removing the parameters file and re-running setup (it completes fine now although doesn't launch to app at the end) and tried using different usernames, passwords and emails etc but it still returns username or password invalid. I guess this is a different issue to the title one anyway re closing it. I'm going to try deleting everything, files and database and try again. Thanks

**Comment by RichardNeilson** [comment]
Setup up resolved, looks like a couple of files didn't upload to the server correctly. Login problem started as a new issue #491 Thanks for your help.
