### ISSUE TITLE
internal partnumber as a unique value

### ISSUE THREAD

**Issue by databeest** [partkeepr/PartKeepr#486]
Please consider the possibility of making the Internal Part number Unique.
This would help in not getting doubles.

marc (databeest)

**Comment by felicitus** [comment]
It's a good idea. If I develop that feature, I need to make sure that the user receives a proper error message on setup if duplicate internal part numbers are detected.

Another way would be to make this configurable. That would avoid duplicate part number problems on upgrade, however, it is increased effort to check on each part save.

**Comment by databeest** [comment]
Maybe make it a fork? Either someone uses uniqueness or not.
