### ISSUE TITLE
Right  Click  menu is not  working

### ISSUE THREAD

**Issue by lookme2** [partkeepr/PartKeepr#487]
I have installed  .75.  When I do a right click via FireFox  42.0 running Ubuntu I get the browsers menu and not the menu for partkeepr

**Comment by felicitus** [comment]
There's no right-click menu anymore. The trees have now buttons in their toolbar and the grids have their own export button.

**Comment by lookme2** [comment]
Ok thanks

**Comment by lookme2** [comment]
So  it  looks like in the Categories window I have two buttons with out icons and one down at the bottom of the Parts List window.  
![screenshot from 2015-11-18 13 24 48](https://cloud.githubusercontent.com/assets/11365211/11251704/21f68f40-8df8-11e5-8126-d22b7e77e00c.png)
![screenshot from 2015-11-18 13 25 10](https://cloud.githubusercontent.com/assets/11365211/11251703/21f4414a-8df8-11e5-9bb5-d2ef5a6a9728.png)

**Comment by felicitus** [comment]
Yes, it's a firefox bug: #481

**Comment by iankellogg** [comment]
This is still a bug as far as I am concerned. The code still is there to open menus but it doesn't function. This leaves me with no way to export projects to excel/csv.

**Comment by felicitus** [comment]
Right click menu is disabled for recent PartKeepr versions. Each grid has an export button now, see the lower toolbar.

**Comment by iankellogg** [comment]
I do not see any export option for a project's BoM. When in the project page, the only export option is the grid export.

**Comment by felicitus** [comment]
Can you give details? Where exactly is a project's BoM?

Previosly the right click menu contained the grid export, now there's a dedicated button.

**Comment by iankellogg** [comment]
![inventory](https://cloud.githubusercontent.com/assets/19454690/15503895/4975e356-218a-11e6-928e-024248a389d9.png)

I see the export option for the list of projects but not for the BoM itself. Previously I could right click in the listing of parts to export.

**Comment by felicitus** [comment]
I just fixed the issue, it will be merged in about one hour.

Please open a separate issue next time including all details (a screenshot is worth every time ;)), it makes bugfixing on our side much easier. Thank you :)
