### ISSUE TITLE
Unable to logon - Username or password invalid

### ISSUE THREAD

**Issue by RichardNeilson** [partkeepr/PartKeepr#491]
Hi Timo, I have deleted both the database and all files from my server, reloaded and carried out setup again. It setups up fine but still won't login.

**Comment by felicitus** [comment]
First you should check if the proper user exists in the FOSUser table. If it is there, please check if the configured time on the server and your machine matches.

If nothing helps please try to change the parameter:

`$container->setParameter('authentication_provider', 'PartKeepr.Auth.WSSEAuthenticationProvider');` to `$container->setParameter('authentication_provider', 'PartKeepr.Auth.HTTPBasicAuthenticationProvider');` in your parameters.php file

Also you can have a look in the app/logs directory if there are any errors logged.

**Comment by RichardNeilson** [comment]
Thanks yet again for your assistance. The FOS table does show my username and the time/date at the bottom of your app matches my local machine. I have tried changing the parameter file to use HTTPBasic but still no change. There are 3 log files although I must be honest, the contents don't make much sense to a layman like me.

**Comment by felicitus** [comment]
Please send the log files to felicitus (at) felicitus.org and I will have a look

**Comment by felicitus** [comment]
Unfortunately there's no log for the production environment.

Can you try to use web/app_dev.php to log in and send the dev log file to me afterwards? The dev log file should be named like your database.

**Comment by RichardNeilson** [comment]
if I try to load the app_dev.php file I get a 403 error returned. Should there be another log file added to the log folder afterwards?

**Comment by felicitus** [comment]
Yes, there should be a new log file. Are you running PartKeepr on a different machine than your desktop? If so, please check that the _server_ time is actually the same time than on your machine. The time display within PartKeepr is your local time and not the server time.

If these are different machines, please remove the first few lines of app_dev.php which prevent you from accessing app_dev.php remotely:

```
if (isset($_SERVER['HTTP_CLIENT_IP'])
    || isset($_SERVER['HTTP_X_FORWARDED_FOR'])
    || !in_array(@$_SERVER['REMOTE_ADDR'], array('127.0.0.1', 'fe80::1', '::1'))
) {
    header('HTTP/1.0 403 Forbidden');
    exit('You are not allowed to access this file. Check '.basename(__FILE__).' for more information.');
}
```

**Comment by RichardNeilson** [comment]
Yes, I am trying to run partkeepr from the same server I host my website on. It's a managed server from a hosting plan company. I created a php file that returns the time and date an this matches my local time/date. I can now login with the above line commented out in the app_dev.php file. Where would the new log file be as I still only have 3 in the app/log folder although dev.log looks to have been updated?!

**Comment by felicitus** [comment]
You say you can now login - so is the problem resolved when you use the app_dev.php file?

If no, please send the updated dev.log file _after_ you tried to login, so I have the logging for what went wrong during login.

**Comment by RichardNeilson** [comment]
I can log in using app_dev.php but not with app.php, or should I be logging in with app_dev anyway? I will email you the latest dev.log anyway. Cheers

**Comment by felicitus** [comment]
Please try re-running setup (leaving all values as-is), maybe the cache wasn't cleared properly after you changed the Authentication Provider. I believe there's a time issue with your client and server in some form (different time zones maybe?) so the default WSSE authentication provider wouldn't work.

**Comment by RichardNeilson** [comment]
I've just had to go out, I have redone the setup a couple of times but not since changing the WSSE auth I don't think. The times seem to match but maybe different time zones but also different summer time settings so the times match? ! I'll let you know when I get back. Thanks for all your support.

**Comment by RichardNeilson** [comment]
Hi, I have re run setup again, first time since changing the auth to HTTP and it now lets me log in. Thanks SO much for everything. Now for a few hours/days entering all my details!

**Comment by briangordon** [comment]
@Drachenkaetzchen I'm having the same issue, and changing from WSSE to HTTP basic auth by re-running setup doesn't help. Interestingly, the bottom of the page says:

```<script type="text/javascript">
    window.parameters = {"doctrine_orm_version":"2.5.4","doctrine_dbal_version":"2.5.2","doctrine_common_version":"2.6.0-DEV","php_version":"7.0.33-0+deb9u1","auto_start_session":true,"maxUploadSize":2097152,"isOctoPartAvailable":false,"availableImageFormats":["JPG","GIF","PNG"],"autoLoginUsername":"admin","autoLoginPassword":"admin","max_users":"unlimited","authentication_provider":"PartKeepr.Auth.HTTPBasicAuthenticationProvider","tip_of_the_day_uri":"https:\/\/partkeepr.org\/tips\/%s","password_change":true,"patreonStatus":{"goal":500000},"defaultGridPresets":"[]"};
</script>```

But the response headers from the `login` endpoint contain:

```WWW-Authenticate: WSSE realm="Secured with WSSE", profile="UsernameToken"```

This is kind of weird too:

```
/home/brian # curl -vvv --basic -u brian:pass http://192.168.1.100/pk/web/api/users/login | jq .
*   Trying 192.168.1.100...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 192.168.1.100 (192.168.1.100) port 80 (#0)
* Server auth using Basic with user 'brian'
> GET /pk/web/api/users/login HTTP/1.1
> Host: 192.168.1.100
> Authorization: Basic YnJpYW46cGFzcw==
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Date: Mon, 18 Feb 2019 21:05:47 GMT
< Server: Apache/2.4.25 (Debian)
< Vary: Authorization
< Set-Cookie: PHPSESSID=u867cbknh060pk5itei9gkj1m7; path=/; HttpOnly
< Cache-Control: no-cache
< Link: <http://192.168.1.100/pk/web/api/apidoc>; rel="http://www.w3.org/ns/hydra/core#apiDocumentation"
< Content-Length: 614
< Connection: close
< Content-Type: application/ld+json
<
{ [614 bytes data]
* Curl_http_done: called premature == 0
100   614  100   614    0     0  27201      0 --:--:-- --:--:-- --:--:-- 27909
* Closing connection 0
{
  "@context": "/pk/web/api/contexts/Error",
  "@type": "Error",
  "hydra:title": "An error occurred",
  "hydra:description": "An exception occurred while executing 'SELECT p0_.id AS id_0, p0_.username AS username_1, p0_.password AS password_2, p0_.email AS email_3, p0_.admin AS admin_4, p0_.legacy AS legacy_5, p0_.lastSeen AS lastseen_6, p0_.active AS active_7, p0_.protected AS protected_8, p0_.provider_id AS provider_id_9 FROM PartKeeprUser p0_ WHERE p0_.id = ?' with params [\"login\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"login\""
}
```

**Comment by briangordon** [comment]
OK, I tried running setup several times and nothing was improving. I noticed that `partkeepr.frontend.auto_login.enabled` was `true` in parameters.php with the wrong credentials so I turned that off, but that didn't help. 

Then I accessed app_dev.php and ran setup again and everything works fine! My guess is that app_dev.php clears some cache that setup does not. 🤷‍♂️
