### ISSUE TITLE
"Warming up the cache" takes too long

### ISSUE THREAD

**Issue by matthijskooijman** [partkeepr/PartKeepr#496]
I'm running PHP with the (I think) default 30-second execution limit, and during the setup the "Warming up the cache" fails with execution time exceeded.

Increasing the time limit helps, but I wonder if this can be somehow be fixed differently? Perhaps the script itself could call [`set_time_limit`](http://php.net/manual/en/function.set-time-limit.php) every now and then?

**Comment by matthijskooijman** [comment]
This is probably related to the hardware that this runs on, I'm using a fairly slow atom machine as my server.

**Comment by felicitus** [comment]
Setup will now display a warning if the max_execution_time is below 30 seconds, but allows the user to continue anyways.
