### ISSUE TITLE
Setup does not warn about missing .htaccess support

### ISSUE THREAD

**Issue by matthijskooijman** [partkeepr/PartKeepr#497]
I'm running nginx and PHP inside uwsgi, so I do not have any support for .htaccess files. On IRC I suggested that a heads up that a .htaccess file is used in the installation docs would be nice, but @felicitus said that the setup procedure should show a notice in this case. However, my setup didn't show any warning, so apparently that is broken (either in general, or in my setup specifically).

**Comment by felicitus** [comment]
Setup will in fact check for an invalid configuration. However, one thing setup can't test is if the nginx index directive is correctly set. I have added an [index.html](https://github.com/partkeepr/PartKeepr/commit/71dd507118c8e558e2ca7be3a7aeb10e253d32d3) page with a link to [KB00005](https://wiki.partkeepr.org/wiki/KB00005:Web_Server_Configuration) for proper configuration.

![image](https://cloud.githubusercontent.com/assets/162974/11452505/2ac37170-95ea-11e5-919a-c2ec499cd24e.png)

**Comment by matthijskooijman** [comment]
Sounds like a good solution, thanks!
