### ISSUE TITLE
When an attachment file is missing from the server, no error is shown

### ISSUE THREAD

**Issue by matthijskooijman** [partkeepr/PartKeepr#503]
When an attachment file is missing from the server (in my case due to #502), a 500 internal server error is returned, but without any meaningful error message. The PHP error log and partkeepr.log don't mention this error at all either.

**Comment by felicitus** [comment]
Further investigation required if exceptions are serialized properly.

**Comment by felicitus** [comment]
I just double-checked, the response is indeed a JSON-LD string when any other exception occurs.
