### ISSUE TITLE
When I get on "setting up the database schema" I got an "database setup error".

### ISSUE THREAD

**Issue by agardim** [partkeepr/PartKeepr#506]
I'm updating an already existing database from previous version and got the following detailed error:

An exception occurred while executing 'ALTER TABLE part ADD removals TINYINT(1) NOT NULL, ADD lowStock TINYINT(1) NOT NULL, CHANGE averagePrice averagePrice NUMERIC(13, 4) NOT NULL': SQLSTATE[22004]: Null value not allowed: 1138 Invalid use of NULL value

**Comment by felicitus** [comment]
Can you try to execute the following command in your database prior updating:

`UPDATE Part SET averagePrice = 0 WHERE averagePrice IS NULL`

Then re-run setup. Please leave feedback, so I can write a fix.

**Comment by agardim** [comment]
I execute the command and get: 29 lines where affected.
Then I run Partkeepr setup again and it finished without errors.
It runs slowly than the previous version but works and have a better
interface.
New problem: I cannot open any of my attached PDFs anymore. When I click on
it, it shows this error:

{"@context":"\/componentes\/web\/api\/contexts\/Error","@type":"Error","hydra:title":"An
error occurred","hydra:description":"The file
\u0022eccb6a14-eaad-4c50-a871-db2cc913c8eb.pdf\u0022 was not found."}



2015-11-27 11:42 GMT-02:00 Timo A. Hummel <notifications@github.com>:

**Comment by felicitus** [comment]
This is probably related to #502. You can move the directories manually, I'm currently working on a fix for that issue.

Performance will be improved soon :)

**Comment by agardim** [comment]
Solved!
Regards!


2015-11-27 14:23 GMT-02:00 Timo A. Hummel <notifications@github.com>:

**Comment by felicitus** [comment]
@agardim If you wish to try out the performance improvement, install the PHP5 APCu cache (the package is usually called `php5-apcu` on debian systems), replace the contents of your `app/config/config_dunglas.yml` file with the contents of https://github.com/partkeepr/PartKeepr/blob/master/app/config/config_dunglas.yml, then re-run setup. Let me know if this improves performance.
