### ISSUE TITLE
Image preview in part list

### ISSUE THREAD

**Issue by MrExplore** [partkeepr/PartKeepr#509]
I might be nice to have an image preview in the part list, images say more then a thousand words when searching :)

Something like this:

![request_imagepreview](https://cloud.githubusercontent.com/assets/16072118/11459680/7736d11c-96dc-11e5-95ee-dcc16a007d52.jpg)

**Comment by felicitus** [comment]
Sounds useful. The user should be able to configure the displayed image height as well as marking a specific image as primary image.
