### ISSUE TITLE
Preview Image of Footprint does not work

### ISSUE THREAD

**Issue by maugsburger** [partkeepr/PartKeepr#518]
When showing a footprint, the attachement images/datasheet/whatever work fine. But in the box on the right side, I just get an 500 Server Error, path is like:
https://partkeepr-installation/api/footprint_images/1/getImage?maxWidth=undefined&maxHeight=undefined&ts=1449170985243

When changing maxWidth and maxHeight to real numbers, it just works fine. Probably some Frontend JS Problem? (Using Chrome Version 46.0.2490.86 (64-bit) on Debian)

I just checked it on https://demo.partkeepr.org/, same behaviour there.

**Comment by timofonic** [comment]
Why is this closed?

**Comment by felicitus** [comment]
Because it was fixed.

**Comment by felicitus** [comment]
Hint: Click on the ID after "closed via" to see the commit log entry.
