### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by PePaPossum** [partkeepr/PartKeepr#522]
Hi there,
I have tried installation multiple times, but it does not let me log in - Gives me a "Username or password invalid" error.

My PartKeepr Installation (0.76) is on Debian Jessie (a VM) and I am accessing it from my Windows 7 PC.
I have tried using WSSE and basic http authentication but neither make a difference.
I have set the Debian Jessie VM and my Windows 7 to both use the Windows ntp server as per Issue #513 
I have also commented out the beginning lines in the app_dev.php file as per issue #491 but I still cannot login when accessing app_dev.php
I have looked for the FOSUser table and all I can find is FOSUser.php (is that the right file?) but there  do not appear to be any entries for my username.
When I re run the setup, on the Setup (1/2) page it says No existing users next to Checking for existing users.
I did find this entry in the log file:
[2015-12-05 20:04:56] request.INFO: Matched route "partkeepr_setup_adminusersetup_intcreateuser". {"route_parameters":{"_controller":"PartKeepr\\SetupBundle\\Controller\\AdminUserSetupController::intCreateUserAction","_route":"partkeepr_setup_adminusersetup_intcreateuser"},"request_uri":"http://localhost/setup/_int_create_user?email=my_email&password=my_pw&username=my_name"} []

Are you able to offer any suggestion?
Thanks,
Possum

**Comment by felicitus** [comment]
Have you looked in your database if an entry in the table FOSUser exists?

Also the Basic auth/WSSE selection in the setup is broken with 0.76 and will be fixed with the next release. To switch authentication providers manually, please set the authentication provider in your parameters.php:

```
$container->setParameter('authentication_provider', 'PartKeepr.Auth.HTTPBasicAuthenticationProvider');
```

Then re-run setup.

**Comment by PePaPossum** [comment]
I looked in the Partkeepr database and found an entry under username for my name.

I also changed to basic auth as you described, and it still will not let me login.

This was the guide I followed to set up the server:
http://technologyrealm.blogspot.co.nz/2014/03/partkeepr-installation-on-ubuntu-or.html
Have I missed something out in my install?

**Comment by felicitus** [comment]
Have you re-ran setup after you changed it to basic auth?

**Comment by PePaPossum** [comment]
I did; made no difference

**Comment by felicitus** [comment]
Navigate to the login page with your browser and view the source code. At the very bottom you'll find something like this:

```
window.parameters = {"doctrine_orm_version":"2.5.1","doctrine_dbal_version":"2.5.2"
```

Within that string there should be `authentication_provider` Tell me what the `authentication_provider` is set to.

**Comment by PePaPossum** [comment]
HTTP Basic:

window.parameters = {"doctrine_orm_version":"2.5.1","doctrine_dbal_version":"2.5.2","doctrine_common_version":"2.6.0-DEV","php_version":"5.6.14-0+deb8u1","auto_start_session":true,"maxUploadSize":2097152,"availableImageFormats":["JPG","GIF","PNG"],"max_users":"unlimited","authentication_provider":"PartKeepr.Auth.HTTPBasicAuthenticationProvider","tip_of_the_day_uri":"http:\/\/partkeepr.org\/tips\/%s","password_change":true};

**Comment by felicitus** [comment]
Hmm, it's hard to tell what's wrong. Can you try to create another user using the setup?

**Comment by PePaPossum** [comment]
I made another user (bob) and it let me in with that user. 
I will try to see if I can recreate the issue I was having tomorrow with a new setup and another VM.

Thanks for your help!

**Comment by felicitus** [comment]
I'm glad it works! I'll close the issue.

**Comment by progman32** [comment]
Ran into this because I'd inadvertently placed the entire partkeepr installation behind auth at the apache level (`RequireUser`, etc). This is incompatible with how partkeepr wants to handle its auth. I'm now letting partkeepr manage its own auth and everything's fine.
