### ISSUE TITLE
Attachments and take image

### ISSUE THREAD

**Issue by RichardNeilson** [partkeepr/PartKeepr#523]
Hi, when trying to add an attachment, ie a pdf datasheet from my local pc, I get the following path after selecting the file "C:\fakepath\<filename>.pdf and then the following error as well as trying to save a json file. This also happens if I try to upload a PNG file as per the available image formats:
Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================

Response
==================================

Server Configuration
==================================
doctrine_orm_version: 2.5.1
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.16
auto_start_session: true
maxUploadSize: 134217728
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: http://partkeepr.org/tips/%s
password_change: true

Also if I try to take an image via a webcam a popup window open but with no image, it will save a file but with no filesize  (n/a) My webcam does work on your old demo site although I realise that is using the older flash method.

Many thanks,

Richard

**Comment by felicitus** [comment]
Can you test the file upload on the demo site? 

For webcam your browser needs to support it. If using a recent browser, it will prompt you with "This site wants to have access to your webcam". The demo site is not using the flash method.

**Comment by RichardNeilson** [comment]
Hi Timo,
Ok, it appears an issue with my default browser IE11, I've tried it with Edge and it works ok. Thanks for you patience again.
Richard

**Comment by felicitus** [comment]
Good to know that IE11 makes trouble. I will test PartKeepr using IE11.

**Comment by RichardNeilson** [comment]
I guess if there was only one browser to cause an issue it would be IE !
