### ISSUE TITLE
yaml parse method depricated

### ISSUE THREAD

**Issue by miststlkr** [partkeepr/PartKeepr#529]
I tried to install from http://partkeepr.org/downloads/partkeepr-0.1.9.zip and got up to the Setup screen and I get the following error:

>An unexpected error occured during installation. The error message was:
>The ability to pass file names to the Symfony\Component\Yaml\Yaml::parse method is deprecated since version 2.2 and will be removed in 3.0. Pass the YAML contents of the file instead. and happened in /usr/share/php/Symfony/Component/Yaml/Yaml.php:59

I'm not really sure where to go with this.

**Comment by felicitus** [comment]
Any particular reason why you are using partkeepr 0.1.9?

**Comment by miststlkr** [comment]
I am running it in a VM and that was the version on the download page ...
which I just realized... that link is for a full VM image using 1.9, not
saying that 1,9 is the latest that will run in a VM... because that
wouldn't make any sense.   This is what I get for trying this before
coffee.  I'll try again from a git clone

**Comment by felicitus** [comment]
You can also use the 0.76 zip version, which is linked on the PartKeepr website. If you are using the git version, please make sure you read [the guide on running PartKeepr from GIT](https://wiki.partkeepr.org/wiki/Running_PartKeepr_from_GIT)

**Comment by miststlkr** [comment]
I have the git version installing through composer right now.  I'll go brew
a pot and let that do its thing.   Sorry.  PEBKAC

**Comment by felicitus** [comment]
No problem :) I'll close the issue.
