### ISSUE TITLE
Installing partkeeper

### ISSUE THREAD

**Issue by kisame0020** [partkeepr/PartKeepr#541]
Im trying to install partkeeper on my synology ds415+ I have dsm beta 6 which support php 5.6 i installed myphpadmin with mariadb to support the mysql database. Here are some screen shots, but i keep getting the access denied error. I can see it trying ot make the connection but it dose not work. I gave the user account both full access on phpmyadmin and the synology.
http://imgur.com/WHvE793

http://imgur.com/wG1CCBN

http://imgur.com/qq1uwOS

http://imgur.com/317NmaY

**Comment by felicitus** [comment]
Try using localhost instead of DiskStation, or the actual IP address.

**Comment by kisame0020** [comment]
Still getting the same error using localhost

**Comment by felicitus** [comment]
Well the error message is what the MySQL driver returns, so it seems that the user doesn't have full access. You should be able to verify the behavior by using the exact same credentials you entered in PartKeepr for the MySQL client - you will get the exact same error message.

**Comment by felicitus** [comment]
To assist further please give a screenshot of the user in phpmyadmin.

**Comment by felicitus** [comment]
Actually it would help if you use the PartKeepr support mailing list or IRC, as this is not a PartKeepr bug. I'm closing the issue due to that.
