### ISSUE TITLE
More verbose LDAP logging

### ISSUE THREAD

**Issue by agamez** [partkeepr/PartKeepr#542]
Adding the following to config_dev.yml doesn't result on ldap.log file being written, so something else must be needed.

        ldap:
            type:   stream
            path:   "%kernel.logs_dir%/ldap.log"
            level:  debug
            channels: ldap_driver

**Comment by felicitus** [comment]
Logging actually occurs, but it isn't logged if LDAP is disabled. The debug log should also contain whether ldap is enabled or not.
