### ISSUE TITLE
Update from v0.76 to 0.77 fails with  InvalidFieldNameException

### ISSUE THREAD

**Issue by momu** [partkeepr/PartKeepr#550]
Rerunning Partkeepr Setup gives the error when migrating an empty (no parts yet) database:

Invalid Response from server
Symfony
Search on Symfony website
Exception detected!
An exception occurred while executing 'UPDATE PartKeeprUser SET active = 1':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'active' in 'field list'
500 Internal Server Error - InvalidFieldNameException
2 linked Exceptions:

    PDOException »
    PDOException »

[3/3] InvalidFieldNameException: An exception occurred while executing 'UPDATE PartKeeprUser SET active = 1':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'active' in 'field list'  +
[2/3] PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'active' in 'field list'  +
[1/3] PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'active' in 'field list'  +
Logs  -

Stack Trace (Plain Text)  +

**Comment by felicitus** [comment]
What does the table `PartKeeprUser` looks like in your installation?

**Comment by momu** [comment]
Like this
![selection_2016010512 29 18](https://cloud.githubusercontent.com/assets/1451642/12114173/016a91e2-b3a8-11e5-98fc-47bdb55c5e2d.png)

**Comment by felicitus** [comment]
I will have a look, but this will take a few days. Another serious issue has occurred with 0.77, you should downgrade to 0.76 as soon as possible.

**Comment by momu** [comment]
Ok thanks, will do.

**Comment by felicitus** [comment]
I just tried to reproduce the issue, but couldn't. Steps performed:

- Downloaded [PartKeepr 0.76](https://downloads.partkeepr.org/partkeepr-0.76.tbz2)
- Setup into a blank database
- Downloaded [PartKeepr 0.77](https://downloads.partkeepr.org/partkeepr-0.77.tbz2)
- Re-ran setup, no errors occured

How did you upgrade your PartKeepr files? Did you extract the archive in-place?

To me it looks like some files weren't upgraded.

**Comment by momu** [comment]
I did it like this:
* Downloaded Partkeepr 0.76
* Setup blank database
* Ran setup
* Downloaded Partkeepr 0.77 into new directory
* Copied 'data/' and 'app/config/parameters.php' to new directory (According to https://wiki.partkeepr.org/wiki/How_to_update)
* Re-ran setup in new directory

**Comment by felicitus** [comment]
I just released 0.78. Can you check if the issue still exists for you?

**Comment by momu** [comment]
Thanks, with update from version 0.76 to 0.78 it worked and there were no issues.
