### ISSUE TITLE
Column selection and width not saved/remembered (+ sorting columns)

### ISSUE THREAD

**Issue by MrTinkerman** [partkeepr/PartKeepr#555]
Hi, 

A bug / feature request from MrExplore here, posting on another account.

Selecting columns and setting the width is a nice feature of partkeepr.
The selection and width are however not remembered when disconnecting.

I tested with firefox, chrome and IE.

It would be nice if column setting would be remembered.

Thanks.

**Comment by felicitus** [comment]
Duplicate of #373
