### ISSUE TITLE
Doesn't appear the footprint image 

### ISSUE THREAD

**Issue by glaukos78** [partkeepr/PartKeepr#566]
When I click on footprint doesn't appear the image and appear error 404 not found
version 0.78

**Comment by felicitus** [comment]
I just tried to reproduce the issue on https://demo.partkeepr.org - I uploaded a footprint image, saved the footprint and opened it again, the footprint loads fine.

Can you provide details on how to reproduce the issue?

**Comment by glaukos78** [comment]
Updated from 0.76 to 0.78 version.
In the 0.76 doesn't appear footprints and i have has solve in 0.78

**Comment by glaukos78** [comment]
Updated from 0.76 to 0.78 version.
In the 0.76 doesn't appear footprints and i have read in the list has solve this problem in the 0.78

**Comment by felicitus** [comment]
What happens if you upload a new footprint image using PartKeepr 0.78? Does it work?

**Comment by glaukos78** [comment]
I have try upload image in the current version and work.
Thanks for your help.

**Comment by felicitus** [comment]
You're welcome. I guess that the file upload was broken previously, and thus you were not able to view the files.

**Comment by glaukos78** [comment]
Maybe the link must was broken.
Thanks a lot of
