### ISSUE TITLE
Installer says it checks for GD, instead checks for CURL

### ISSUE THREAD

**Issue by neaai** [partkeepr/PartKeepr#567]
Hello,
During installation, there are several requirements that are checked by the installer, in order for the installation to complete.
Two of these checks are to see whether gd library and curl library for php5 are installed. In debian, these are provided by php5-gd and php5-curl.

But for both of these checks, the installer says it is checking for GD. When it does not find curl, it will report that it didn't find GD.

It seems this is an easy fix.
 In file "app/PartKeeprRequirements.php"  at lines 18 and 23.
 At line 23, it looks for curl, and when it does not find it, it reports that it does not find GD. It is the message text which needs to be modified.

**Comment by felicitus** [comment]
This is now fixed.
