### ISSUE TITLE
webserver-test was not found

### ISSUE THREAD

**Issue by lookme2** [partkeepr/PartKeepr#570]
I am trying to upgrade to 
![screenshot from 2016-01-14 13 10 43](https://cloud.githubusercontent.com/assets/11365211/12363205/2a38ddbc-bb8d-11e5-89bf-1dfa78f76b08.png)
.78.   I will not pass the setup with the following error.

**Comment by tarioch** [comment]
Same issue. What I could see as important is that I'm using a subdirectory (i.e. http://mydomain.com/partkeepr)

**Comment by kenzertech** [comment]
i had the same issue come up, but it was fixed by following the link in the error box and setting up apache2 server per instructions.  you also have to be careful about doc root as well.  mine is now up and running...  try the link

**Comment by tarioch** [comment]
Do you use a subpath in your domain? As far as I was ableto tell from the htaccess the test did not work for subpaths. I commented the check and the app works fine

**Comment by kenzertech** [comment]
http://10.0.1.206/partkeepr-0.78/web/

Not sure why the difference.  After fighting with it for so long, I'm going to try to build a new vm and set up
something more robust just to see how well it works with multiple sites.  But for now, this seems to work
fine.  If commenting the check works, probably wasn't all that necessary anyway it seems.  If I have 
good luck with the new vm install the next couple of days, I'll try to record the steps and post.  There seems to be a real need for a step by step for those of us who are not that literate on the depths of 
mysql, php, and apache2.  :)  Glad you got it running....

**Comment by dpenezic** [comment]
And solution was ?

**Comment by dpenezic** [comment]
O.k. ... I found reason ... please be aware that your apache server config look like :

        Alias "/partkeepr" "/var/www/partkeepr-1.3.0/web"

        <Directory "/var/www/partkeepr-1.3.0/web">
                **AcceptPathInfo on
                Require all granted
                AllowOverride All**
        </Directory>

I think bold part is important

**Comment by vasc0x** [comment]
I found the issue. Apache's mod_rewrite should be enabled for the provided .htaccess file perform the redirection from setup/webserverTest to setup.php/setup/webserverTest.
Run this command as super user: `a2enmod rewrite` and restart apache.
