### ISSUE TITLE
Partkeepr 0.78 installation routine does not import previous parameters.php database settings

### ISSUE THREAD

**Issue by trial-n-error** [partkeepr/PartKeepr#573]
Hi,

found a minor issue when using the web-based installation routine. After copying a previous parameters.php, the tab in the browser informs that "Existing configuration imported successfully.", but on the following database settings dialog the information is missing and needs user input.

Environment:
- php-5.6.11
- nginx-1.8.0
- postgresql-9.4.4
- https://downloads.partkeepr.org/partkeepr-0.78.tbz2

Workaround:
Re-enter database configuration.

**Comment by felicitus** [comment]
It's hard to tell what's wrong at this point, I think there should be way for the end-user to view which previous data has been imported to make debugging easier.

**Comment by felicitus** [comment]
The problem with this issue is that I can't reproduce it. Can you give more details on how to reproduce, like where exactly you have put the `parameters.php` file and it's contents (with anonymized database usernames/passwords of course)?

**Comment by felicitus** [comment]
Can you reproduce the issue with the latest version?

**Comment by madcad** [comment]
Hi, I tested this currently with 1.2.0 and it seems that the setup takes all settings from the parameters.php file.

**Comment by baradhili** [comment]
This is no longer an issue with 1.4.0

**Comment by trial-n-error** [comment]
Hi,
I created the bug ticket initially and stumbled over notification on it just now. I actually tried it again and I did not got the problem with the latest software. Thank you for the great software, and sorry that I not saw the question on feedback back in 2017.
