### ISSUE TITLE
Partkeepr 0.78 / PostgreSQL: Add storage location

### ISSUE THREAD

**Issue by trial-n-error** [partkeepr/PartKeepr#576]
Hi,

an exception is thrown when form is loaded to create a new storage location. If exception window is closed, a new entry can be created and edited.

Not sure yet how to debug/solve. It seems when preparing the form for user entry of a new storage location, a DB query is executed to search for all associated parts (shall be none on a new one). Might be that the to be created storage location is not instantiated and the ORM fails on the join.

Keep looking on how to fix it.

```
An error occurred

Details
==================================
An exception occurred while executing 'SELECT count(DISTINCT p0_.id) AS sclr_0 FROM Part p0_ WHERE p0_.storageLocation_id = ?' with params ["PartKeepr.StorageLocationBundle.Entity.StorageLocation-5"]:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "PartKeepr.StorageLocationBundle.Entity.StorageLocation-5"

Request
==================================
GET http://parts.trial-n-error.net/api/parts?_dc=1453124413262

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"An exception occurred while executing \u0027SELECT count(DISTINCT p0_.id) AS sclr_0 FROM Part p0_ WHERE p0_.storageLocation_id = ?\u0027 with params [\u0022PartKeepr.StorageLocationBundle.Entity.StorageLocation-5\u0022]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \u0022PartKeepr.StorageLocationBundle.Entity.StorageLocation-5\u0022"}

Server Configuration
==================================
doctrine_orm_version: 2.5.1
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.11
auto_start_session: true
maxUploadSize: 104857600
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.WSSEAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
```

**Comment by felicitus** [comment]
The cause is probably that it tries to cast "PartKeeprStorageLocationBundleEntityStorageLocation-5" to an integer which fails on PostgreSQL. I think it's easy to fix, the storage location contents grid should not be loaded if it's a new record.

I believe you can simply ignore the error until I fix the issue.

**Comment by trial-n-error** [comment]
OK, the way you describe the issue makes sense. As you said its not a blocker as the the dialog can be ignored and the final operation is functional.

**Comment by felicitus** [comment]
The issue should now be solved
