### ISSUE TITLE
Can't login after fresh installation

### ISSUE THREAD

**Issue by tarioch** [partkeepr/PartKeepr#580]
Hi,

I did a fresh installation and provided a username. But now I can't login using the specified credentials.
The logfile just shows:

[2016-01-28 09:38:52] app.WARNING: Bad credentials. [] []

**Comment by tarioch** [comment]
Using firebug I see first a successful call for getting the salt and then a call for

https://mydomain.com/partkeepr/api/users/login

which fails with a 401 but seems to have a x-wsse header

**Comment by felicitus** [comment]
Please try the HTTP Basic authentication: https://wiki.partkeepr.org/wiki/KB00006:Authentication_Provider

**Comment by tarioch** [comment]
Basic auth works

**Comment by felicitus** [comment]
Nice! May I close the issue?

**Comment by tarioch** [comment]
fine for me, but maybe someone else will run into the same issue, especially as wsse is the recommended one by the setup.

**Comment by felicitus** [comment]
Yes, however the "Help me choose" link contains a link to the Knowledge Base Article with further information.

**Comment by tarioch** [comment]
I actually read that one and it made me choose the default, which then did not work in the end, so that's a bit confusing.

**Comment by felicitus** [comment]
Well, on https://wiki.partkeepr.org/wiki/KB00006:Authentication_Provider it says:

When to choose HTTP Basic: If WSSE doesn't work.

I'm not sure on how to implement this better.

**Comment by tarioch** [comment]
You're right, my mistake

**Comment by felicitus** [comment]
No it's alright :) I appreciate if you have any ideas on how to make this more clear

**Comment by TheKentishMan** [comment]
Hi Both

Want to say thanks for posting this as I've just run into this issue during a fresh install ...

@felicitus Have you though about adding as an option during set up? Specifically when you set up the admin account, also this will help when re-run the setup a second. Option could be change admin pass word / yes/no then change authentication method yes/no

**Comment by felicitus** [comment]
@TheKentishMan the option to change the authentication provider is already implemented. Also you can add additional users. Note that you do not need to create a new user account when you change the authentication provider.
![untitled](https://cloud.githubusercontent.com/assets/162974/12654994/015675d4-c5f7-11e5-91fd-c334d088fcdc.png)

**Comment by TheKentishMan** [comment]
@felicitus Sorry I must of missed that... I was running an install on 0.75 via zip rather than the git. Feel a bit silly now

**Comment by felicitus** [comment]
0.75 didn't have it, but 0.78 has it

**Comment by TheKentishMan** [comment]
Cheer, I'll do a fresh install with 0.78 later tonight...
