### ISSUE TITLE
Unable to save parameter values and custom units.

### ISSUE THREAD

**Issue by vmw** [partkeepr/PartKeepr#581]
PROBLEM: Unable to save parameters with custom units.

REPRODUCTION (on demo.partskeepr.org)

1) Create a new unit. (Edit -> Units -> Add Unit. Unit name is "Weeks", Symbol is "wk", Allowed SI units is "-". Save unit.

2) Open existing part properties, and attempt to add a new parameter (Open part properties -> Parameter tab -> Add Parameter. Parameter Name is "LeadTime", Value is "1". Unit is "Weeks".

EXPECTED:

That the new value and unit are correctly saved and displayed.

ACTUAL:

Though the name of the parameter is (sometimes) displayed, the value of the parameter, or its units, are neither saved or displayed.

**Comment by felicitus** [comment]
This is most likely related to #512

**Comment by felicitus** [comment]
The parameters are very buggy and are removed for now. I will re-introduce them at a later point in time.

**Comment by felicitus** [comment]
Advanced Part Parameters are now implemented, can you check if they work for you?

**Comment by felicitus** [comment]
No feedback given for an extended period of time, closing the issue.

Feel free to re-open if you have additional information.
