### ISSUE TITLE
Duplicate part with all data deletes distributor information on originating part

### ISSUE THREAD

**Issue by momu** [partkeepr/PartKeepr#582]
Problem: When duplicating a part with all data and the part has distributor entries the distributor entries are removed in the originating part (but copied to the duplicated part).

Steps to reproduce (on demo.partkeepr.org):
* Create a part _testpart_ with distributor entry ([selection_003](https://cloud.githubusercontent.com/assets/1451642/12689188/75a2a306-c6db-11e5-8f9b-c0004a740bf4.png))
* Select testpart and _duplicate with all data_
* Change the name of the new part to _testpart_new_ and save changes
* _testpart_ will now have no distributor entry anymore
* _testpart_new_ has the distributor entry in the distributors list
* Does not matter if _testpart_new_ distributor entry is changed before saving 

Tested with demo.partkeepr.org and also with partkeepr version 0.78

**Comment by felicitus** [comment]
I haven't reproduced this issue yet, but it's most likely that the associated data gets copied over without removing the primary key. As a result, `DunglasApiBundle` assumes the associated data was moved from one part to another.

This most likely only occurs on `isMany` associations. Within `setAssociationData` the foreign PK should be removed.

**Comment by felicitus** [comment]
I believe I have a bugfix for the issue. Can you try it out?

It should be enough to replace the contents of HydraModel.js and re-run setup so that all caches are cleared and the JS files are rebuilt.

**Comment by felicitus** [comment]
Have you had a chance to test the bugfix?

**Comment by momu** [comment]
Sorry for the late reply.
Replacing Hydramodel.js with commit f3ade0a24ac9e4d7b768ac2b7debf5b415cb35c and rerunning setup did not solve it.

**Comment by felicitus** [comment]
That's strange, I just re-tested it according to the steps to reproduce the issue. After the bugfix, I'm not able to reproduce the problem anymore.

I'll create a PR. Can you check in a few hours if you can still reproduce the issue on https://demo.partkeepr.org

**Comment by momu** [comment]
That is indeed strange. I tested it on https://demo.partkeepr.org and on my local installation an now it worked. Since my last comment I did not change anything here, so problably some kind of cache issue.
Sorry for the confusion, I think it's solved now.
