### ISSUE TITLE
Hangs at app/logs access check [0.78]

### ISSUE THREAD

**Issue by adis1987** [partkeepr/PartKeepr#584]
No clue why. To be on the safe side, whole partkeepr folder on webserver has -R 777 permission

**Comment by felicitus** [comment]
Can you check if there are any error messages on the JavaScript console? See https://wiki.partkeepr.org/wiki/How_to_Debug#Frontend_Debugging on how to open the console.

Also please give details about your webserver, operating system etc.

**Comment by adis1987** [comment]
Solved; I set the /web/ folder as root for the web server That did not work.
The solution was to set the parent folter of the /web/ folder as the root of web server.

**Comment by felicitus** [comment]
I have just created a bugfix, the issue should not re-occur with the next release.
