### ISSUE TITLE
Manufacturer data losed

### ISSUE THREAD

**Issue by leafARC** [partkeepr/PartKeepr#586]
Hello, I've filled the components with the manufacturers and part number and now the information of all manufacturer / part number is gone.

The only problem I've seen is this error:

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET http://10.0.0.9/partkeepr-0.76/web/api/part_categories/getExtJSRootNode?_dc=1454417869467

Response
==================================

Server Configuration
==================================
doctrine_orm_version: 2.5.1
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.17-1+deb.sury.org~trusty+2
auto_start_session: true
maxUploadSize: 2097152
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.WSSEAuthenticationProvider
tip_of_the_day_uri: http://partkeepr.org/tips/%s
password_change: true
-- 
-------------------------------------------------------

**Comment by felicitus** [comment]
Did you use the duplicate parts function?

**Comment by leafARC** [comment]
Hello Timo. No I've not used duplicate parts function in the same node.
But, maybe in different nodes I was using the same part, e.g. I have the
same value for a resistor but one in the node 0805 and the other in 0603.

------> Resistor
                |-------> 0805 Case
                                       1K  1%
                |-------> 0603 Case
                                       1K 1%
But I think both component differs in the power average (1/8 and 1/10)...
so, maybe I wasn't using the same part....



*Once we start to add components, the message  "**The server returned a
response which we were not able to interpret." appears, and then more
frequently and finally we can save more parts and all the work done y
losed.*

Thanks

\\\\\\\\\\\\\\\\\\\\\\\\\\\

Alejandro Clerici

**Comment by felicitus** [comment]
Can you reproduce the problem somehow on demo.partkeepr.org ?

**Comment by leafARC** [comment]
Timo, I've only opened the page and the message "*Critical Error *The
server returned a response which we were not able to interpret.
​a​
ppears
​, I've change anything.

​
​


\\\\\\\\\\\\\\\\\\\\\\\\\\\

Alejandro Clerici

**Comment by leafARC** [comment]
[image: Inline image 1]

\\\\\\\\\\\\\\\\\\\\\\\\\\\

Alejandro Clerici

**Comment by felicitus** [comment]
I noticed that you are still using PartKeepr 0.76 - please upgrade to the latest version and try again.

Also the last image you tried to send did not arrive at GitHub.

**Comment by felicitus** [comment]
If you have upgraded to the latest PartKeepr version and you are still receiving the error after login, please switch the authentication provider from WSSE to HTTP Basic. Also please don't use one GitHub issue for multiple problems.

**Comment by leafARC** [comment]
I'm using the 0.76 version and I don't know how to change the
authentication provider.

Another question is about the login, sometimes I can't loggin from a pc in
a Lan network.

Suggestion: find by description

Thanks!

\\\\\\\\\\\\\\\\\\\\\\\\\\\

Alejandro Clerici

**Comment by felicitus** [comment]
The latest version is 0.78 - please update. The authentication provider can be changed during setup.

**Comment by felicitus** [comment]
No feedback given for an extended period of time - closing.

Feel free to re-open with additional information.
