### ISSUE TITLE
Can´t install partkeepr without php-ldap

### ISSUE THREAD

**Issue by michielbrink** [partkeepr/PartKeepr#590]
Hi, 
On this moment, it isn´t possible to install partkeepr without php-ldap.
Is it possible to install it by commenting some lines so I can install it on my webhosting?

thanks,

**Comment by felicitus** [comment]
You need to remove the bundle in the AppKernel, the auth provider in security.yml and probably a few other places. You can simply use a text search to identify most places.

LDAP is a requirement by default as it's a very high effort to release two different PK versions.

**Comment by michielbrink** [comment]
Thanks,
It works until the next error. But that´s issue 526 so I have to wait for the 1.0 release.

**Comment by dugancaswell** [comment]
I second this request: My webhost does not allow LDAP installation on its shared hosting plans, being able to select the authentication provider in setup would be super-duper.

**Comment by szechyjs** [comment]
any progress on making ldap optional?

**Comment by baradhili** [comment]
1.4.0 no need for phpldap now

**Comment by consumr** [comment]
The check for LDAP is still in 1.4.0... I'm trying to get around the check using the instructions here: 
https://wiki.partkeepr.org/wiki/Developers/Removing_LDAP
-So far unsuccessful, but I've only just begun. I'll come back to edit this once I figure it out.

**Comment by christianlupus** [comment]
@consumr this is most probably due to an incompatible PHP version. Please check you are running with PHP 7.1
