### ISSUE TITLE
Forgets change currency to Dollar Sign ($)

### ISSUE THREAD

**Issue by twelve12pm** [partkeepr/PartKeepr#593]
I changed the "Currency Symbol" in User Preferences from Euro to Dollar Sign ($) and unchecked "Currency Symbol after value" -- but the system does not seem to remember this. If I disconnect and then start a new session, the Currency Symbol reverts to Euro. There is no button to "Save" settings.

This occurs with:
PartKeepr-0.79
Debian Linux 8.3 amd64
Apache/2.4.10 (Debian)
PHP 7.0.3-1~dotdeb
MySQL 5.5.47-0+deb8u1

**Comment by felicitus** [comment]
The currency symbol is actually saved as soon as you change the field. I agree that this is counter-intuitive and a save button would be helpful.

I just checked on demo.partkeepr.org and it seems that sometimes the field doesn't detect a change. As a quick workaround you can try to select the existing currency symbol with the mouse, then type a single $. If you open your browser's JS console you should see a request being sent to the server, which indicates that the setting has been saved.

**Comment by felicitus** [comment]
A save button has now been added, can you test if it works for you?

**Comment by datumv** [comment]
This is happening in our production. While we set it to $ and uncheck the "Currecy Symbol After Value", it gets reset to default all the time. I was hoping that this will be fixed in the new release. Would be great to have this taken care in the next release. Thanks.

**Comment by felicitus** [comment]
@datumv can you reproduce it on the demo system?

**Comment by datumv** [comment]
I saw the other thread (#652) on this and it seems like it is fixed. Closing this one.
