### ISSUE TITLE
attachment 0.81 issue

### ISSUE THREAD

**Issue by mctomaszek** [partkeepr/PartKeepr#612]
hi

I have noticed problem with attachment. I can't attach any file and also links  to file disappeared in version 0.81 after database moved from version 0.75. 

regards

**Comment by felicitus** [comment]
Unfortunately, your bug report is very vague. Can you give more details, preferably reproducable on demo.partkeepr.org ?

**Comment by mctomaszek** [comment]
hi

demo has same problems. please try to attach something in demo version. Links to attachment does not exist

regards

**Comment by felicitus** [comment]
I just made a bugfix, can you check on demo.partkeepr.org if it works for you now?

**Comment by mctomaszek** [comment]
hi

so far so good. thank you :)

regards
