### ISSUE TITLE
Still not solved: Call to a member function getType() on null

### ISSUE THREAD

**Issue by adis1987** [partkeepr/PartKeepr#613]
The problem is still present when savin a project. Now the problem appears only when attaching a file and trying to save.

Call to a member function getType() on null

You can test it in demo.

**Comment by felicitus** [comment]
i can confirm the issue.

However please ensure to give enough details next time. The issue does NOT occur when attaching a file the first time. It occurs when at least one file is attached and trying to save the project triggers the problem, even if no subsequent files are attached.

**Comment by felicitus** [comment]
I have added a bugfix, can you test if the issue is gone for you?

**Comment by adis1987** [comment]
What should I do to test it? Edit the file self?

**Comment by felicitus** [comment]
Test it on demo.partkeepr.org if the issue is gone for you

**Comment by adis1987** [comment]
Works grate. Tested many combinations. No error.

**Comment by felicitus** [comment]
Cool, thank you for the feedback! New release should be out soon

**Comment by adis1987** [comment]
Im addicted to partkeepr so, im glad to help and make it a bit better.
