### ISSUE TITLE
webcam attachment

### ISSUE THREAD

**Issue by mctomaszek** [partkeepr/PartKeepr#614]
hi

Probably is configuration problem on my server because in demo webcam attachment is working. Any idea why I'm getting white view square in webcam window instead a live  stream from computer webcam. Should I install extra library or modules on server ?

regards

**Comment by felicitus** [comment]
which browser are you using?

**Comment by mctomaszek** [comment]
hi
I'm using chrome. Demo partkeepr is working okay with my webcam. Looks like my server configuration is wrong. 
regards

**Comment by felicitus** [comment]
Which PartKeepr version are you using?
Any errors in the JS console?

**Comment by mctomaszek** [comment]
hi

previously I had version 1.0.9 and there webcam worked. When I have moved to version 0.81 it stopped....I don't know where is a problem . No errors JS

**Comment by felicitus** [comment]
Chrome seems to have disabled camera support on non-HTTPS sites. Change your PartKeepr installation to HTTPS or try firefox

**Comment by felicitus** [comment]
There needs to be a warning if the webcam isn't working.

**Comment by mctomaszek** [comment]
hi

I have checked with firefox and working okay. Thank you for advice

regards
