### ISSUE TITLE
Error: Call to a member function getName() on null

### ISSUE THREAD

**Issue by adis1987** [partkeepr/PartKeepr#615]
Got a new problem today with v.0.82
When I login to partkeepr and when the component list screen has loaded I get this (Full report):

An error occurred

Details
==================================
Error: Call to a member function getName() on null

Request
==================================
GET [HIDDEN_MY_URL_HERE]/api/parts?_dc=1457953908286

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"Error: Call to a member function getName() on null"}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.11-1ubuntu3.1
auto_start_session: true
maxUploadSize: 33554432
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

**Comment by felicitus** [comment]
Use [app_dev.php (partkeepr wiki)](https://wiki.partkeepr.org/wiki/How_to_Debug#Backend_Debugging) to get a backtrace and post it here.

**Comment by adis1987** [comment]
In the error popup the backtrace is empty. I have attached a log file. The log is from when I enter the login to end where I get the strange error.

[teraterm_log.zip](https://github.com/partkeepr/PartKeepr/files/172775/teraterm_log.zip)

**Comment by adis1987** [comment]
I found the folder that is making this problem. When I try to delete it I get this:

An error occurred

Details
==================================
An exception occurred while executing 'DELETE FROM PartCategory WHERE id = ?' with params [41]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`partkeepr`.`Part`, CONSTRAINT `FK_E93DDFF812469DE2` FOREIGN KEY (`category_id`) REFERENCES `PartCategory` (`id`))

Request
==================================
DELETE /api/part_categories/41?_dc=1457986945732

[object Object]

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"An exception occurred while executing \u0027DELETE FROM PartCategory WHERE id = ?\u0027 with params [41]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`partkeepr`.`Part`, CONSTRAINT `FK_E93DDFF812469DE2` FOREIGN KEY (`category_id`) REFERENCES `PartCategory` (`id`))"}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.11-1ubuntu3.1
auto_start_session: true
maxUploadSize: 33554432
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

**Comment by felicitus** [comment]
Unfortunately there's nothing in the log which says "Call to a member function getName() on null". 

I need either:
- A log entry from app/logs/dev.log which has the line "Call to a member function getName() on null" __-or-__ 
- The backtrace from the error window whilst running PartKeepr using ```app_dev.php``` __-or-__
- Instructions on how to reproduce the issue on https://demo.partkeepr.org

Without that information I can't help, as I don't know where the problem comes from

**Comment by adis1987** [comment]
As soon as I click on one specific category folder I get this error. The backtrace is empty with or without app_dev.php. The log that I attached was with app_dev.php (mod you told me).

The question is; it maby is some problem with some part? I have only three parts in that category. I have installed phpmyadmin. Can I delete them directly from partkeepr.Part table?

**Comment by felicitus** [comment]
If you use app_dev.php then you should receive a backtrace in the error dialog. I don't know if it's a problem with a specific part, without the backtrace it's not possible to answer the question.

**Comment by felicitus** [comment]
Another possibility is that the issue was already fixed, I'll release 0.83 soon, so you can double-check then.

**Comment by adis1987** [comment]
The solution was to manually move the whole db to a new one :(

**Comment by adis1987** [comment]
Now it happend again and I know when it happens!
I have reproduced the problem in https://demo.partkeepr.org/

1. Randomly add parts to the project and save it.
2. Delete all parts from project and add new.
3. When trying to save, the problem ocures.

In some way this has also destroyed my component categories because I get the same error there after this when trying to list a category that has the same component that has been in the project.

**Comment by adis1987** [comment]
Have you looked in to this issue?
The project part is extremly unstable. I was able to reproduce the problem by simply:
1. Select one project (MIDI-CV Converter). Deleting first part in list and clicking on Save. The whole component list is now gone
2. Trying saving any project now results in error.

**Comment by felicitus** [comment]
No, I'm on holiday.
