### ISSUE TITLE
Problem deleting footprint categories

### ISSUE THREAD

**Issue by Addy771** [partkeepr/PartKeepr#621]
Currently, attempting to delete a footprint category which contains entries results in an error message like so:

`An exception occurred while executing 'DELETE FROM FootprintCategory WHERE id = ?' with params [5]: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`frontier_pkeepr`.`Footprint`, CONSTRAINT`FK_7CF3249412469DE2`FOREIGN KEY (`category_id`) REFERENCES`FootprintCategory`(`id`))`

The problem is that the entries must be removed manually before the category can be deleted.

I propose that attempting to delete a category should warn the user that the category is not empty and if possible there should be an option to remove the entries automatically and proceed to delete the category

**Comment by baradhili** [comment]
@Drachenkaetzchen @Addy771 is this now resolved?

**Comment by baradhili** [comment]
No longer occurs in 1.4.0
