### ISSUE TITLE
Error deleting footprint

### ISSUE THREAD

**Issue by Addy771** [partkeepr/PartKeepr#623]
I attempted to delete a footprint that is used by a part, which caused an error. I removed the footprint from the part it was used with and tried to delete it again. This time I got a new error:

The file "a602b288-ed10-11e5-be16-448a5b9fe16a.jpeg" was not found.

I suspect the image associated with the footprint was removed when I first tried to delete the footprint. Now when I try to delete the footprint partkeepr can't find the image and can't finish deleting the footprint

**Comment by felicitus** [comment]
I can confirm the issue, attempting to delete the footprint `HC18/U` on the demo system results in a similar error.
