### ISSUE TITLE
Cron jobs not running correctly

### ISSUE THREAD

**Issue by ruurdadema** [partkeepr/PartKeepr#625]
After login I get the message:

The following cronjobs aren't running:
partkeepr:cron:synctips

How to fix this?

Running Partkeepr version 0.79 on Debian 8.3

**Comment by felicitus** [comment]
Add the cronjobs to your syste as instructed by setup. You can re-run setup at any time if you missed the instructions.

**Comment by ruurdadema** [comment]
Thanks for your response.

I did add the cronjob as mentioned in the guide:
https://wiki.partkeepr.org/wiki/PartKeepr_on_Debian_%22Jessie%22

It seems this guide is slightly different (run cron as user) compared to the setup instructions. Anyway, installed following the setup which solved the problem.

Thank you.
