### ISSUE TITLE
In Projects cannot View part

### ISSUE THREAD

**Issue by adis1987** [partkeepr/PartKeepr#628]
In Porjects when added components, View component is not working on added components. The same in demo.

Using v1.0.0-alpha.1

**Comment by felicitus** [comment]
Steps to reproduce? Reproducible on demo?

**Comment by adis1987** [comment]
1. In menu, click Edit > Projects
2. In project list, select one project or create a new project.
3. In project parts; Add new component or select one that is allready added.
4. Now click on button View Part abow the list.
= The View Part is not working.
![bug](https://cloud.githubusercontent.com/assets/16978248/14013808/e7622bbc-f1ae-11e5-9500-f198bee11225.JPG)
