### ISSUE TITLE
Proper version information for GIT "releases"

### ISSUE THREAD

**Issue by staze** [partkeepr/PartKeepr#632]
There's seemingly no good way to get what version of Partkeepr you're currently running, unless I'm completely blind. 

System Info would make sense, and shows OS, PHP, and Doctrine versions, but doesn't show the actual partkeepr version. =/

**Comment by staze** [comment]
Or, I _AM_ blind, and it just says "GIT development version". So maybe it should show something else there for those of us using git to keep updated?

**Comment by felicitus** [comment]
Are you running PartKeepr from GIT or from a downloaded zip package?

**Comment by staze** [comment]
GIT

**Comment by felicitus** [comment]
If you run from git there will no version information and as such it will display "GIT development version".  You can use `git log` to see what the commit is for your installation.
