### ISSUE TITLE
WSSE server requirements

### ISSUE THREAD

**Issue by 1am** [partkeepr/PartKeepr#633]
Hi,

Are there any special requirements for WSSE authentication? I've first tried this method before switching to Basic HTTP as it was only working on 1 out of 4 tested computers:
- OSX Yosemite, Chrome - working
- OSX Maverick, Chrome+Safari - not working
- Window 7 32bit, Chrome+IE - not working
- Windows 10 64bit, Chrome - not working

Usually it failed with "_Username/password not valid_" response or "_Server returned a response which is not understood_" depending on the tested computer. I don't remember the exact messages but they were not much more verbose than what I've written above.

Referring to [KB00006:Authentication Provider](https://wiki.partkeepr.org/wiki/KB00006:Authentication_Provider) out-of-sync time on sever and client could be an issue but they were fine on both sides.

**Comment by felicitus** [comment]
I don't know why WSSE fails on some systems. I haven't been able to reproduce the problem so far.

**Comment by felicitus** [comment]
I have been able to reproduce the issue. When I run a Windows VM on my dev box and open PartKeepr, it happens as well.

**Comment by brads4** [comment]
The instructions don't mention anything about how to do a WSSE validation... but first thing is a post request to /api/getSalt.  This salt must be integrated into the password in order to get a match.

The reason people are having issues iwth WSSE has nothing to do with code, but simply a lack of a decent api doc that explains the WSSE authentication process as configured by default.

**Comment by felicitus** [comment]
@brads4 Any problem with WSSE was from the user's perspective using the GUI and not the API.

**Comment by brads4** [comment]
Oh, no issues with the gui.  it works perfectly fine.  There is an inconsistency between the generator on the Javascript layer, but it never ever will get triggered unless the user has no salt.. so it's a moot point.  the js layer doesn't handle the empty salt the same way as the framework, but that was not a problem for me like I said, I just noticed it when trying to figure out how this all works :)

**Comment by brads4** [comment]
I  now have a working Java implementation of the client side WSSE authentication completed.  I would be happy to share the algorithm.

**Comment by dghoti** [comment]
I have been able to replicate this issue - and solve it on Mac OSX.
It seems that the time on a MAC tends to drift - in my case the server and client were ~30 seconds out of synch - resetting the automatic time update on the mac fixed the problem.

As long as both server and client are showing the same time, it works. 30+ seconds out and it fails.

**Comment by christianlupus** [comment]
As WSSE is deprecated and a potential solution is present, I close here.
