### ISSUE TITLE
Filters for Distributor and Manufacturer don't return any results

### ISSUE THREAD

**Issue by chrkuhlmann** [partkeepr/PartKeepr#647]
The Filters for distributor and manufacturer do not work

The following can be seen on demo.partkeepr.org:
1) Open a part (in this case 2N7002)
2) Add a manufacturer to the part (enter "Fairschild" sic! with Part Number "2N7002")
3) Click Update to enter the row
4) Click Save to save the part
5) The data has been correctly saved (tested with 2nd browser)
6) Enter "Fairschild" in the Manufacturer field of the filter panel
7) Apply filter

result: no parts are displayed
expected result: At least the modified part should be displayed

The Distributor filter exhibits the same behaviour.

**Comment by felicitus** [comment]
The issue should now be fixed. Please test against the demo system in one hour.

**Comment by chrkuhlmann** [comment]
The issue is fixed. Thanks for the quick response.
