### ISSUE TITLE
In Add Part dialog, "Per Item" checkbox functionality is inverted

### ISSUE THREAD

**Issue by novirium** [partkeepr/PartKeepr#653]
When adding a new part and adding an Initial Stock Level, with the "Per Item" checkbox _unchecked_, the value entered in the "Price" field winds up being shown as the average price when the part is created. When the "Per Item" checkbox is _checked_, the average price shown for the new item is the "Price" field divided by the initial stock level. This appears to be the opposite of the expected behavior.

**Comment by novirium** [comment]
(forgot to add environment):
Ubuntu server 14.04.4
PartKeepr running straight from git, commit [0919df2](https://github.com/partkeepr/PartKeepr/commit/0919df20c5b360e23bd2e7c741c2e3f802af40bc). Browser is Chrome 49.0.2623.112
PHP ver 5.6.20

Also occurred on commit  [28edd48](https://github.com/partkeepr/PartKeepr/commit/28edd4845aaed4e1dc2f54b2530ae2c9c65e4bbc)

**Comment by felicitus** [comment]
The issue should be fixed with the next release
