### ISSUE TITLE
Unable to upload images

### ISSUE THREAD

**Issue by gt6796c** [partkeepr/PartKeepr#666]
I get the below detailed error message when I try to upload png or jpg to Storage Locations or Footprints. (Not to say that it doesn't happen in other circumstances, I just stopped trying.)

Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================

Response Status Code
==================================
200

Response
==================================

    You need JavaScript on to expand/collapse nodes.
{
  "success": true,
  "image": {
    "@context": "/pk/app_dev.php/api/contexts/TempImage",
    "@id": "/pk/app_dev.php/api/temp_images/12",
    "@type": "TempImage",
    "created": "2016-05-13T21:06:32-04:00",
    "replacement": null,
    "originalFilename": "IMG_3197-640x480.jpg",
    "size": 85210,
    "type": "temp",
    "description": null,
    "fullFilename": "188b22e6-1970-11e6-9303-0242b48d1a1a.jpeg",
    "filename": "188b22e6-1970-11e6-9303-0242b48d1a1a",
    "extension": "jpeg",
    "legacyExtension": "jpeg",
    "mimeType": "image/jpeg"
  },
  "response": {
    "@context": "/pk/app_dev.php/api/contexts/TempImage",
    "@id": "/pk/app_dev.php/api/temp_images/12",
    "@type": "TempImage",
    "created": "2016-05-13T21:06:32-04:00",
    "replacement": null,
    "originalFilename": "IMG_3197-640x480.jpg",
    "size": 85210,
    "type": "temp",
    "description": null,
    "fullFilename": "188b22e6-1970-11e6-9303-0242b48d1a1a.jpeg",
    "filename": "188b22e6-1970-11e6-9303-0242b48d1a1a",
    "extension": "jpeg",
    "legacyExtension": "jpeg",
    "mimeType": "image/jpeg"
  }
}  

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.4-7ubuntu2
auto_start_session: true
maxUploadSize: 2097152
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

**Comment by felicitus** [comment]
Please provide all details as per [CONTRIBUTING.md](https://github.com/partkeepr/PartKeepr/blob/master/CONTRIBUTING.md),

**Comment by gt6796c** [comment]
I just tested on Safari and Chrome and everything works fine in those browsers, so the problem seems to only be in Firefox

Browser: Firefox 46
Server: Ubuntu 16.04
SQL: MySQL 14.14

Console: Error message above and 
{sourceClass: "Ext.JSON", sourceMethod: "decode", msg: "You're trying to decode an invalid JSON String: 
    You need JavaScript on to expand/collapse nodes.
{
  "success": true,
  "image": {
    "@context": "/pk/app_dev.php/api/contexts/TempImage",
    "@id": "/pk/app_dev.php/api/temp_images/17",
    "@type": "TempImage",
    "created": "2016-05-14T09:06:55-04:00",
    "replacement": null,
    "originalFilename": "IMG_3197-640x480.PNG",
    "size": 442785,
    "type": "temp",
    "description": null,
    "fullFilename": "bb946fe2-19d4-11e6-bafb-0242b48d1a1a.png",
    "filename": "bb946fe2-19d4-11e6-bafb-0242b48d1a1a",
    "extension": "png",
    "legacyExtension": "png",
    "mimeType": "image/png"
  },
  "response": {
    "@context": "/pk/app_dev.php/api/contexts/TempImage",
    "@id": "/pk/app_dev.php/api/temp_images/17",
    "@type": "TempImage",
    "created": "2016-05-14T09:06:55-04:00",
    "replacement": null,
    "originalFilename": "IMG_3197-640x480.PNG",
    "size": 442785,
    "type": "temp",
    "description": null,
    "fullFilename": "bb946fe2-19d4-11e6-bafb-0242b48d1a1a.png",
    "filename": "bb946fe2-19d4-11e6-bafb-0242b48d1a1a",
    "extension": "png",
    "legacyExtension": "png",
    "mimeType": "image/png"
  }
}

**Comment by felicitus** [comment]
Can you reproduce the issue on the demo system?

**Comment by gt6796c** [comment]
Yes. See below


Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================


Response Status Code
==================================
200

Response
==================================

    You need JavaScript on to expand/collapse nodes.
{
  "success": true,
  "image": {
    "@context": "/api/contexts/TempImage",
    "@id": "/api/temp_images/4",
    "@type": "TempImage",
    "created": "2016-05-14T16:28:11+02:00",
    "replacement": null,
    "originalFilename": "IMG_3201-640x480.png",
    "size": 439826,
    "type": "temp",
    "description": null,
    "fullFilename": "15ef56e0-19e0-11e6-a6a6-000000000000.png",
    "filename": "15ef56e0-19e0-11e6-a6a6-000000000000",
    "extension": "png",
    "legacyExtension": "png",
    "mimeType": "image/png"
  },
  "response": {
    "@context": "/api/contexts/TempImage",
    "@id": "/api/temp_images/4",
    "@type": "TempImage",
    "created": "2016-05-14T16:28:11+02:00",
    "replacement": null,
    "originalFilename": "IMG_3201-640x480.png",
    "size": 439826,
    "type": "temp",
    "description": null,
    "fullFilename": "15ef56e0-19e0-11e6-a6a6-000000000000.png",
    "filename": "15ef56e0-19e0-11e6-a6a6-000000000000",
    "extension": "png",
    "legacyExtension": "png",
    "mimeType": "image/png"
  }
}  



Server Configuration
==================================
doctrine_orm_version: 2.5.1
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.21-1~dotdeb+7.1
auto_start_session: true
maxUploadSize: 2097152
availableImageFormats: JPG,GIF,PNG
autoLoginUsername: admin
autoLoginPassword: admin
motd: <p><b>Welcome to the PartKeepr demo site</b></p>
<p>
Notes:
<ul>
<li>This PartKeepr installation is rebuilt from the GIT sources at every full hour</li>
<li>Rebuild takes about one minute, and you'll receive errors during rebuild</li>
<li>The database is synced from Felicitus' personal database, which might contain german part names or other odd stuff</li>
</ul>
</p>
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

**Comment by felicitus** [comment]
I just tried with Firefox 46.0.1 on Windows, and it works fine here. Is it probably related to the image you're trying to upload? Have you tried a different one?

**Comment by gt6796c** [comment]
Yes,  I've tried multiple PNGs and JPGs. I'm on a Mac. See below for a jpg's error.


Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================


Response Status Code
==================================
200

Response
==================================

    You need JavaScript on to expand/collapse nodes.
{
  "success": true,
  "image": {
    "@context": "/pk/api/contexts/TempImage",
    "@id": "/pk/api/temp_images/24",
    "@type": "TempImage",
    "created": "2016-05-14T10:46:05-04:00",
    "replacement": null,
    "originalFilename": "IMG_3197-640x480.jpg",
    "size": 85210,
    "type": "temp",
    "description": null,
    "fullFilename": "962e8770-19e2-11e6-bf54-0242b48d1a1a.jpeg",
    "filename": "962e8770-19e2-11e6-bf54-0242b48d1a1a",
    "extension": "jpeg",
    "legacyExtension": "jpeg",
    "mimeType": "image/jpeg"
  },
  "response": {
    "@context": "/pk/api/contexts/TempImage",
    "@id": "/pk/api/temp_images/24",
    "@type": "TempImage",
    "created": "2016-05-14T10:46:05-04:00",
    "replacement": null,
    "originalFilename": "IMG_3197-640x480.jpg",
    "size": 85210,
    "type": "temp",
    "description": null,
    "fullFilename": "962e8770-19e2-11e6-bf54-0242b48d1a1a.jpeg",
    "filename": "962e8770-19e2-11e6-bf54-0242b48d1a1a",
    "extension": "jpeg",
    "legacyExtension": "jpeg",
    "mimeType": "image/jpeg"
  }
}  



Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.4-7ubuntu2
auto_start_session: true
maxUploadSize: 2097152
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

**Comment by felicitus** [comment]
Do you have any extensions installed in Firefox?

**Comment by gt6796c** [comment]
That was it. I had a JSON pretty printer extension enabled. I disabled it and the problem went away.

Thanks for the help!

**Comment by felicitus** [comment]
You're welcome :)
