### ISSUE TITLE
Magic matching

### ISSUE THREAD

**Issue by Drachenkaetzchen** [partkeepr/PartKeepr#67]
It has been suggested that we should add some kind of "magic matching". Example:

If a user enters 10.1kOhm into the text field, the database should find also 10.1(kOhm-Char) as well as similar values. 

14:56:14 <    sECuRE> Felicitus: ich hab mir spaßeshalber mal deine partkeepr-installation angeschaut gerade
14:56:25 <    sECuRE> Felicitus: wenn ich da „widerstand“ in die suche haue, krieg ich keine ergebnisse
14:56:34 <    sECuRE> obwohl natürlich einige widerstände im system sind
14:56:54 < dancingfo> So ab heim. Winks
14:56:58 -!- dancingfo [~dancingfo@2001:4d88:100e:ccc0:226:8ff:fe67:b33e] has quit [Quit: Leaving]
14:57:34 < Felicitus> sECuRE: ja, weil die widerstände kein "widerstand" im partnamen tragen
14:57:56 <    sECuRE> Felicitus: ja, das dachte ich mir. aber kann man nicht die kategorie mitreinpacken bei der auswahl, was durchsucht wird
14:57:59 < Felicitus> das ist analog zu der jetzigen partdb
14:57:59 <    sECuRE> ?
14:58:15 <    sECuRE> ja, aber wir wollen das ja verbessern ;)
14:58:49 < Felicitus> ja könnte man - aber da wir eh noch bauteiltypen reinbauen möchten mit parametrisierung, warte ich erstmal ab wie gut die parametersuche funktioniert
14:59:09 -!- MarkusBec [~markusbec@p5DC37329.dip.t-dialin.net] has quit [Ping timeout: 487 seconds]
14:59:30 < Felicitus> dazu muß aber noch überlegt werden ob man den kategorienamen analog zu bauteiltyp setzt oder ob man separat bauteiltypen definiert
14:59:32 <    sECuRE> parametersuche as in separate felder für kategorie, wert, …?
14:59:58 < Felicitus> genau. parametererfassung ist auch schon drin, nur die suche fehlt noch
15:00:10 <    sECuRE> ich find ja freitextsuche besser persönlich
15:00:39 < Felicitus> jau, der bauteilname soll auch später aus den bauteilparametern erzeugt werden können
15:01:11 < Felicitus> dann kann man natürlich wieder freitext suchen
15:01:22 <    sECuRE> hm, ok
15:01:25 <      else> moin
15:01:29 < Felicitus> moin else
15:02:14 < Felicitus> aber grad bei den widerständen macht es durchaus sinn, weil man dann in den genuss von der ähnlichkeitssuche kommt. z.b. suchst du einen widerstand mit 1kOhm, und wir haben aus irgendwelchen gründen keine mehr -
                      dann kann man nach wertigkeit +-10% suchen und findet dann z.b. nen 1.1kOhm widerstand
15:03:16 <    sECuRE> kann man doch auch mit freitext-suche implementieren
15:03:41 < Felicitus> d.h. du gibst 10.1kOhm ein und er parst die 10.1kOhm raus?
15:03:52 <    sECuRE> er macht halt einfach fuzzy matching
15:03:58 <    sECuRE> also zuerst die genauen resultate, danach fuzzy
15:04:20 < Felicitus> naja, find ich jetzt nicht so wirklich prickelnd
15:04:32 < Felicitus> aber ich merks mal vor
15:04:37 < Felicitus> zum nachdenken
15:04:44 <    sECuRE> müsste man halt mal ausprobieren, obs gut funktioniert oder eher nicht
15:05:02 <    sECuRE> aber generell ist automagie besser als viele felder, IMO ;)
15:05:53 < Felicitus> parts.google.com? :)
15:06:16 <    sECuRE> so in die richtung ;)
15:07:05 < Felicitus> da muß aber dann viel magic betrieben werden, fällt mir grad auf
15:07:27 < Felicitus> weil in der DB sollen ja in zukunft "richtige" symbole stehen, z.b. das ohm zeichen
15:07:44 < Felicitus> wenn jetzt ein user "Ohm" eintippt, muss die suche erstmal "Ohm" ins Ohm-zeichen umwandeln
15:07:48 <    sECuRE> ja
15:08:05 <    sECuRE> genauso beim eintragen neuer teile
##

**Comment by baradhili** [comment]
Covered in #54
