### ISSUE TITLE
Log out when trying to view any page

### ISSUE THREAD

**Issue by iankellogg** [partkeepr/PartKeepr#670]
I am running 1.0.0 after updating from 0.1.7
I am able to log into either a migrated account or a new account and view the inventory stock. I can edit/add items to inventory with no issues.
However, If i select any other page, such as projects or project reports the page will log me out and I have to reenter auth information only to be shown the inventory page.

**Comment by iankellogg** [comment]
THis only seems to affect chrome 

Version 50.0.2661.102 m (64-bit)

**Comment by felicitus** [comment]
I just tested it with Version 50.0.2661.94 on Linux and it seems to work fine here.

Can you verify if the same issue happens if you use https://demo.partkeepr.org ? Also, do you receive any JavaScript errors in the JS console?

**Comment by iankellogg** [comment]
Chrome seems to work on 3 of the 5 PCs i've tested now. No errors are present when it fails, and configs should be identical between machines. Will have to do further investigation outside of partkeepr. Thanks.
