### ISSUE TITLE
Part Lookup

### ISSUE THREAD

**Issue by demacus** [partkeepr/PartKeepr#671]
Hi there, since my Partkeepr install (as of 2013) is now somehow broken cause of an Doctrine error I did an update.
I forgot I had a little hack on my install which was basically a part lookup on Farnell website with a simple parser which filled my part editor fields.

I could not get it ported to the actual framework but here is pretty much the base of it, may you can insert it or at least give me a hint on how to declare the needed fields in symfony fw.

``
/**
 * @class PartKeepr.PartEditor

 * <p>The PartEditor provides an editing form for a part. It contains multiple tabs, one for each nested record.</p>
 */
Ext.define('PartKeepr.PartEditor', {
	extend: 'PartKeepr.Editor',
	
	// Assigned model
	model: 'PartKeepr.Part',
	
	// Layout stuff
	border: false,
	layout: 'fit',
	bodyStyle: 'background:#DBDBDB;',
	
	/**
	 * Initializes the editor fields
	 */
	initComponent: function () {
		// Defines the overall height of all fields, used to calculate the anchoring for the description field
		var overallHeight = (this.partMode == "create") ? '-280' : '-235';
		
		this.nameField = Ext.create("Ext.form.field.Text", {
			id:	'nameField',
			name: 'name',
			fieldLabel: i18n("Name"),
			allowBlank: false,
			labelWidth: 150
		});
		
		this.storageLocationComboBox = Ext.create("PartKeepr.StorageLocationComboBox",
			{
				fieldLabel: i18n("Storage Location"),
				name: 'storageLocation',
				id: 'storageLocationId',
				allowBlank: false,
				labelWidth: 150
			});
		
		this.storageLocationComboBox.store.on("load", function () {
			// Re-trigger validation because of asynchronous loading of the storage location field,
			// which would be marked invalid because validation happens immediately, but after loading
			// the storage locations, the field is valid, but not re-validated.
			
			// This workaround is done twice; once after the store is loaded and once when we start editing,
			// because we don't know which event will come first
			this.getForm().isValid();
		}, this);
		
		this.footprintNone = Ext.create("Ext.form.field.Radio", {
				boxLabel: i18n("None"),
				name: 'footprint_mode',
				margin: {
					right: 5
				},
				value: "unset",
				listeners: {
					scope: this,
					change: function (field, newValue) {
						if (newValue === true) {
							this.footprintComboBox.clearValue();
						}
					}
				}
			});
		
		this.footprintSet = Ext.create("Ext.form.field.Radio", {
			name: 'footprint_mode',
			margin: {
				right: 5
			},
			value: "set"
		});
		
		/*
		 * Creates the footprint combo box. We listen for the "change" event, because we need to set the footprint
		 * comboboxes to the right state, depending on the selection. Another way would be to patch the combobox
		 * to support "null" values, however, this is a major change within ExtJS and probably not supported for
		 * updates of ExtJS.
		 */
		this.footprintComboBox = Ext.create("PartKeepr.FootprintComboBox", {
				name: 'footprint',
				flex: 1,
				listeners: {
					scope: this,
					change: function (field, newValue) {
						if (newValue !== 0) {
							this.footprintSet.setValue(true);
						}
					}
				}
		});

		// Defines the basic editor fields
		var basicEditorFields = [
			this.nameField,
			{
				id: 'descField',
				xtype: 'textfield',
				fieldLabel: i18n("Description"),
				name: 'description'
			},{
				layout: 'column',
				bodyStyle: 'background:#DBDBDB',
				border: false,
				items: [{
						xtype: 'numberfield',
						fieldLabel: i18n('Minimum Stock'),
						allowDecimals: false,
						allowBlank: false,
						labelWidth: 150,
						name: 'minStockLevel',
						id: 'minStockLevelField',
						value: 0,
						columnWidth: 0.5,
						minValue: 0
					},{
						xtype: 'PartUnitComboBox',
						fieldLabel: i18n("Part Unit"),
						columnWidth: 0.5,
						margin: "0 0 0 5",
						name: 'partUnit',
						value: PartKeepr.getApplication().getDefaultPartUnit().get("id")
					}]
			},{
				xtype: 'CategoryComboBox',
				fieldLabel: i18n("Category"),
				name: 'category'
			},
			this.storageLocationComboBox,
			{
				xtype: 'fieldcontainer',
				layout: 'hbox',
				fieldLabel: i18n("Footprint"),
				defaults: {
	                hideLabel: true
	            },
				items: [
				        this.footprintNone,
				        this.footprintSet,
				        this.footprintComboBox
				       ]
			},{
				xtype: 'textarea',
				fieldLabel: i18n("Comment"),
				id: 'commentField',
				name: 'comment',
				anchor: '100% ' 
			},
			{
				xtype: 'fieldcontainer',
				layout: 'hbox',
				fieldLabel: i18n("Status"),
				defaults: {
	                hideLabel: true
	            },
	            items: [{
	            	xtype: 'textfield',
	            	fieldLabel: i18n("Status"),
	            	flex: 1,
	            	name: 'status'
	            },{
	            	xtype: 'checkbox',
	            	hideEmptyLabel: false,
	            	fieldLabel: '',
	            	margins: {
	            		left: 5
	            	},
	            	boxLabel: i18n("Needs Review"),
	            	name: 'needsReview'
	            }]
			},{
				xtype: 'textfield',
				fieldLabel: i18n("Condition"),
				name: 'partCondition'
			},{
                xtype: 'fieldcontainer',
                layout: 'hbox',
                items : [{
                    xtype: 'textfield',
                    labelWidth: 150,
                    fieldLabel: i18n("Internal Part Number"),
                    name: 'internalPartNumber',
                    flex: 1
                },{
                    xtype: 'displayfield',
                    margins: {
                        left: 5
                    },
                    fieldLabel: i18n("Internal ID"),
                    name: 'id'
                }]

			},{
                xtype: 'fieldcontainer',
                layout: 'hbox',
                items : [{
                    xtype: 'textfield',
                    labelWidth: 150,
                    columnWidth: 0.5,
                    fieldLabel: i18n("Order Number"),
                    name: 'PartKeepr.PartDistributor.sku',
                    flex: 0,
                    id: 'lookupSku',
                },{
                    xtype: 'button',
                    height: 22,
                    margin: '0 0 0 5',
                    text: i18n("Lookup"),
                    handler: this.onLookupClick,
					icon: 'resources/silkicons/zoom.png'
				},{
					xtype : 'button',
					text: i18n("Parse"),
					height : 22,
					margin : '0 0 0 5',
					scope : this,
					handler: this.onParseClick,
				},/*{
					xtype : 'button',
					text: i18n("Test"),
					height : 22,
					margin : '0 0 0 5',
					scope : this,
					handler: this.lookupFootprints,
				},{
					xtype : 'button',
					text: i18n("ParseFP"),
					height : 22,
					margin : '0 0 0 5',
					scope : this,
					handler: this.parseFootprints,
				},{
					xtype : 'button',
					text: i18n("Category"),
					height : 22,
					margin : '0 0 0 5',
					handler: this.lookupCategorys,
				},{
					xtype : 'button',
					text: i18n("CategoryParse"),
					height : 22,
					margin : '0 0 0 5',
					handler: this.parseCategorys,
				}*/]
			}];
		
	
		// Creates the distributor grid
		this.partDistributorGrid = Ext.create("PartKeepr.PartDistributorGrid", {
			title: i18n("Distributors"),
			iconCls: 'icon-lorry',
			layout: 'fit',
			deferredRender: false
		});
		
		// Creates the manufacturer grid
		this.partManufacturerGrid = Ext.create("PartKeepr.PartManufacturerGrid", {
			title: i18n("Manufacturers"),
			iconCls: 'icon-building',
			layout: 'fit',
			deferredRender: false
		});
		
		// Creates the parameter grid
		this.partParameterGrid = Ext.create("PartKeepr.PartParameterGrid", {
			title: i18n("Parameters"),
			id: 'partParameterGrid',
			iconCls: 'icon-table',
			layout: 'fit',
			deferredRender: false
		});
		
		// Creates the attachment grid
		this.partAttachmentGrid = Ext.create("PartKeepr.PartAttachmentGrid", {
			title: i18n("Attachments"),
			iconCls: 'icon-attach',
			layout: 'fit',
			deferredRender: false
		});
		
		// Adds stock level fields for new items
		if (this.partMode && this.partMode == "create") {
			this.initialStockLevel = Ext.create("Ext.form.field.Number", {
				fieldLabel: i18n("Initial Stock Level"),
				name: "initialStockLevel",
				id: 'initialStock',
				labelWidth: 150,
				columnWidth: 0.5
			});
			
			this.initialStockLevelUser = Ext.create("PartKeepr.UserComboBox", {
				fieldLabel: i18n("Stock User"),
				name: 'initialStockLevelUser',
				columnWidth: 0.5,
				margin: "0 0 0 5"
			});
			
			basicEditorFields.push({
				layout: 'column',
				bodyStyle: 'background:#DBDBDB',
				border: false,
				items: [
				        this.initialStockLevel,
				        this.initialStockLevelUser
				]
			});
			
			this.initialStockLevelPrice = Ext.create("PartKeepr.CurrencyField", {
				fieldLabel: i18n('Price'),
				id: 'priceField',
				labelWidth: 150,
				columnWidth: 0.5,
				name: 'initialStockLevelPrice'
			});
			
			this.initialStockLevelPricePerItem = Ext.create("Ext.form.field.Checkbox", {
				boxLabel: i18n("Per Item"),
				columnWidth: 0.5,
				margin: "0 0 0 5",
				name: 'initialStockLevelPricePerItem',
				id: 'stockLevelPricePerItem'
			});
			
			basicEditorFields.push({
				layout: 'column',
				bodyStyle: 'background:#DBDBDB',
				border: false,
				items: [
				        this.initialStockLevelPrice,
				        this.initialStockLevelPricePerItem
				]
			});
			
			
		}
		
		// Create a tab panel of all fields
		this.items = {
				xtype: 'tabpanel',
				border: false,
				plain: true,
				items: [{
					iconCls: 'icon-brick',
					xtype: 'panel',
					border: false,
					autoScroll: false,
					layout: 'anchor',
					defaults: {
				        anchor: '100%',
				        labelWidth: 150
				    },
					bodyStyle: 'background:#DBDBDB;padding: 10px;',
					title: i18n("Basic Data"),
					items: basicEditorFields
				},
				this.partDistributorGrid,
				this.partManufacturerGrid,
				this.partParameterGrid,
				this.partAttachmentGrid
				]
		};
		
		this.on("startEdit", this.onEditStart, this, { delay: 200 });
		this.on("itemSaved", this._onItemSaved, this);
		
		this.addEvents("partSaved", "titleChange");
		
		this.callParent();
		
		this.on("itemSave", this.onItemSave, this);
		
	},
	onLookupClick: function () {
		var lookupSrc = "http://de.farnell.com/jsp/search/browse.jsp;?N=0&Ntk=gensearch&Ntt="+Ext.getCmp('lookupSku').getValue();
			new Ext.Window({
				title : i18n("Part Lookup"),
				width : 850,
				height: 700,
				maximizable: true,
				constrain: true,
				layout : 'fit',
				items : [{
						xtype : "component",
						flex : 1,
						width: '100%',
						id : 'lookupWindow',
						autoEl : {
							tag : "iframe",
							id: 'lookupSkuSurfedUrl',
							src : lookupSrc,
						}
				}]
			}).show();
    },
	onParseClick: function () {
		var partkeeprUrl = "http://127.0.0.1/PartKeepr/frontend/rest.php";
/*
categoryName: ""
categoryPath: ""
footprint: 0
footprintName: ""
needsReview: false
storageLocation: 0
storageLocationName: ""	
*/	
		var partBody = Ext.get('lookupWindow').dom.contentWindow.document.body;
		var pdContainer = partBody.getElementsBySelector('#pdContainer');
		//console.log(pdContainer);
		var partBasicData = partBody.getElementsBySelector('dd');
		//console.log(partBasicData);
		
		//console.log("Hersteller: "+partBasicData[0].textContent);
		
		Ext.getCmp('lookupSku').setValue(partBasicData[1].textContent);
		this.record.distributors().add('0');
		this.record.distributors().getAt(0).set("distributor_id",'0');
		this.record.distributors().getAt(0).set("distributor_name",'Farnell');
		this.record.distributors().getAt(0).set("orderNumber",partBasicData[1].textContent);
		
		Ext.getCmp('nameField').setValue(partBasicData[2].textContent);
		
		/*
		 * tempfile request
		 * 
		 * POST
		 * http://127.0.0.1/PartKeepr/frontend/rest.php/TempFile
		 * 
		 * ------WebKitFormBoundaryvUfpFxucuNvEIVG4
		 * Content-Disposition: form-data; name="call"
		 * upload
		 * ------WebKitFormBoundaryvUfpFxucuNvEIVG4
		 * Content-Disposition: form-data; name="session"
		 * 23q4o86gvn77509j5vl0khbpb5
		 * ------WebKitFormBoundaryvUfpFxucuNvEIVG4
		 * Content-Disposition: form-data; name="url"
		 * http://www-s.ti.com/sc/psheets/mpbg222b/mpbg222b.pdf
		 * ------WebKitFormBoundaryvUfpFxucuNvEIVG4
		 * Content-Disposition: form-data; name="userfile"; filename=""
		 * Content-Type: application/octet-stream
		 * ------WebKitFormBoundaryvUfpFxucuNvEIVG4--
		 * 
		 * response
		 * {"status":"ok","success":true,"response":{"id":7,"extension":"html","size":4989,"originalFilename":"mpbg222b.pdf"},"timing":1.5049340724945}
		 * 
		 */ 
		var dataSheetLink = partBasicData[3].innerHTML;
		var dsLink = dataSheetLink.substr(dataSheetLink.search("\"")+1,dataSheetLink.search("pdf")+2-dataSheetLink.search("\""))
		console.log(dsLink);
		 
		var imgDiv = partBody.getElementsBySelector('#pdimage')[0].innerHTML;
		var imgLink = "http://de.farnell.com"+imgDiv.substr(imgDiv.search("/"),imgDiv.search("alt=")-7-imgDiv.search("src="));
		console.log(imgLink);
		/*var sessionid = Ext.util.Cookies.get('jsessionid');
		console.log(sessionid);
		var boundary = '----WebKitFormBoundarybGkDcIH9XYvoBZYj';
		var response = Ext.Ajax.request({ 
			url: partkeeprUrl+"/TempFile",
			headers: { 
				"Content-Type": "multipart/form-data; boundary="+boundary
			},
			jsonData: boundary+"\nContent-Disposition: form-data; name=\"call\"\n\nupload\n"+boundary+"\nContent-Disposition: form-data; name=\"session\"\n\nt6ersh83l08thk4ni5jva66sh5\n"+boundary+"\nContent-Disposition: form-data; name=\"url\"\n\n"+imgLink+"\n"+boundary+"\nContent-Disposition: form-data; name=\"userfile\"; filename=\"\"\nContent-Type: application/octet-stream\n\n\n"+boundary,
			method:'POST',
			async: false,
			scope:this 
		});
		console.log(response);
		*/

		 /*
		var atCount = this.record.get("attachmentCount");
		this.record.attachments().add(atCount);
		this.record.attachments().getAt(atCount).set("originalFilename",dsLink);
		this.record.attachments().getAt(atCount).set("description",'Datasheet');
		*/
		// description
		Ext.getCmp('descField').setValue(partBody.getElementsBySelector('.prodAttrSingle')[0].textContent);
		
		// category
		var categoryParsed = partBody.getElementsBySelector('#breadcrumbs')[0].getElementsBySelector('.dropdown>li');
		//console.log(partBody.getElementsBySelector('#breadcrumbs')[0]);
		//console.log(categoryParsed[1].getElementsBySelector('a')[0].innerText);
		//console.log(categoryParsed[2].getElementsBySelector('a')[0].innerText);

		this.record.set("categoryName",categoryParsed[2].getElementsBySelector('a')[0].innerText);
		//console.log(this.CategoryComboBox.picker.getRootNode().findChild("name", categoryParsed[2].getElementsBySelector('a')[0].innerText, true));
		
		// comment
		var partAttrName = partBody.getElementsBySelector('.prodAttrName');
		var partAttrValue = partBody.getElementsBySelector('.prodAttrValue');
		var commentText = "Hersteller: "+partBasicData[0].innerText+"\n";
		for (var i=0; i<partAttrName.length; i++){
			commentText += partAttrName[i].textContent+" "+partAttrValue[i].textContent;
			if (i<partAttrName.length-1){
				commentText += "\n";
			};
		};
		Ext.getCmp('commentField').setValue(commentText);
		
		// stock level
		Ext.getCmp('initialStock').setValue('10');
		Ext.getCmp('minStockLevelField').setValue('2');
		
		// price
		var priceRaw = partBody.getElementsBySelector('.unitprice')[0].textContent;
		var priceSplit = priceRaw.substr( priceRaw.search("[0-9]"), (priceRaw.search(",")+3-priceRaw.search("[0-9]")) );
		Ext.getCmp('priceField').setValue(priceSplit.replace(",","."));
		Ext.getCmp('stockLevelPricePerItem').setValue('true');
		this.record.distributors().getAt(0).set("price",priceSplit.replace(",","."));
		this.record.distributors().getAt(0).set("packagingUnit",'1');
	},
	lookupCategorys: function () {
		var categoryList = "http://de.farnell.com/";
			new Ext.Window({
				title : i18n("Category Lookup"),
				width : 640,
				height: 600,
				maximizable: true,
				constrain: true,
				layout : 'fit',
				items : [{
						xtype : "component",
						flex : 1,
						width: '100%',
						id : 'catlookupWindow',
						autoEl : {
							tag : "iframe",
							src : categoryList,
						}
				}]
			}).show();
	},
	parseCategorys: function () {
		var catBody = Ext.get('catlookupWindow').dom.contentWindow.document.body;
		var catRaw = catBody.getElementsBySelector('.hasSubMenu');
		var catId = 1;
		for ( var i=0; i<catRaw.length; i++) {
			var listRaw = catRaw[i].getElementsBySelector('li');
			var tmpstr = catRaw[i].innerText;
			//console.log( tmpstr.substr(0,tmpstr.length-1) );
			catId ++;
			var pId = catId;
			Ext.Ajax.request({ 
				url: 'http://127.0.0.1/partkeepr/frontend/rest.php/PartCategory',
				method:'POST',
				params:{
					id:catId,
					name:tmpstr.substr(0,tmpstr.length-1),
					text:"",
					description:"",
					parent:1,
					parentId:0,
					leaf:false,	
				},
				async: false,
				scope:this 
			});
			for ( var j=0; j<listRaw.length; j++) {
				tmpstr = listRaw[j].innerText;
				catId ++;
				Ext.Ajax.request({ 
					url: 'http://127.0.0.1/partkeepr/frontend/rest.php/PartCategory',
					method:'POST', 
					params:{
						id:catId,
						name:tmpstr.substr(tmpstr.search("[a-zA-ZäöüÄÖÜ]"), tmpstr.search("[0-9]")-4-tmpstr.search("[a-zA-Z]äöüÄÖÜ") ),
						text:"",
						description:"",
						parent:pId,
						parentId:0,
						leaf:false,	
					},
					async: false,
					scope:this 
				});
				//console.log(tmpstr.substr( tmpstr.search("[a-zA-ZäöüÄÖÜ]"), tmpstr.search("[0-9]")-4-tmpstr.search("[a-zA-Z]äöüÄÖÜ") ));
			};
		}
	},
	
/*	lookupFootprints: function () {
		var mySrc = "http://www.ti.com/sc/docs/psheets/type/type.html";
		new Ext.Window({
				title : i18n("Footprint Lookup"),
				width : 640,
				height: 600,
				maximizable: true,
				constrain: true,
				layout : 'fit',
				items : [{
						xtype : "component",
						flex : 1,
						width: '100%',
						id : 'fplookupWindow',
						autoEl : {
							tag : "iframe",
							src : mySrc,
						}
				}]
			}).show();
	},
/*	parseFootprints: function () {
		var partkeeprUrl = "http://127.0.0.1/PartKeepr/frontend/rest.php";
		var src = "http://www.ti.com";
		var fpTypeLinks = Ext.get('fplookupWindow').dom.contentWindow.document.getElementsByTagName('tbody')[1].getElementsByTagName('a');
		console.log(fpTypeLinks);
		console.log(fpTypeLinks.length);
		//startID
		var fpid = 9;
		for (var i=0; i<fpTypeLinks.length; i++) {
			fpid ++;
			var pfpid = fpid;
			//make category request
			Ext.Ajax.request({ 
				url: partkeeprUrl+"FootprintCategory?",
				method:'POST',
				params:{
					id:0,
					name:"test",
					text:"",
					description:"test",
					parent:1,
					parentId:0,
					leaf:false
				},
				async: false,
				scope:this 
			});
			
			function makeHttpObject() {
				try {return new XMLHttpRequest();}
				catch (error) {}
				try {return new ActiveXObject("Msxml2.XMLHTTP");}
				catch (error) {}
				try {return new ActiveXObject("Microsoft.XMLHTTP");}
				catch (error) {}

				throw new Error("Could not create HTTP request object.");
			}
			
			var request = makeHttpObject();
			console.log(fpTypeLinks[i].href);
			request.open("GET", fpTypeLinks[i].href, false);
			request.send(null);
			request.onreadystatechange = function() {
				if (request.readyState == 4)
					console.log(async);
			};
			
			for (var j=0; j<packages.length; j++) {
				fpid++;
				//set attachments
				
				Ext.Ajax.request({ 
					url: partkeeprUrl+"Footprint?",
					method:'POST',
					params:{
						"id":0,"name":"testfp","text":"","description":"testdesc","image_id":"","category":9,"parentId":0,"leaf":false,"attachments":[{"id":"TMP:6","originalFilename":"Gray-Code-Gen_Edit manually.pdf","footprint_id":0,"mimetype":"","extension":"pdf","description":"","size":"6207"}]
					},
					async: false,
					scope:this 
				});	
			}		
		
		/* 
		 * footprint category request
		 * {"id":0,"name":"test","text":"","description":"test","parent":1,"parentId":0,"leaf":false}
		 * _dc=1382619208704
		 * http://127.0.0.1/PartKeepr/frontend/rest.php/FootprintCategory?_dc=1382619208704
		 * 
		 * footprint footprint request
		 * http://127.0.0.1/PartKeepr/frontend/rest.php/Footprint?_dc=1382619446511
		 * _dc=1382619446511
		 * {"id":0,"name":"testfp","text":"","description":"testdesc","image_id":"","category":9,"parentId":0,"leaf":false,"attachments":[{"id":"TMP:6","originalFilename":"Gray-Code-Gen_Edit manually.pdf","footprint_id":0,"mimetype":"","extension":"pdf","description":"","size":"6207"}]}
		 * 
		 */
		

		
//	},

	/**
	 * Cleans up the record prior saving.
	 */
	onItemSave: function () {
		var removeRecords = [], j;
		
		/**
		 * Iterate through all records and check if a valid distributor
		 * ID is assigned. If not, the record is removed as it is assumed
		 * that the record is invalid and being removed.
		 */
		for (j=0;j<this.record.distributors().getCount();j++) {
			if (this.record.distributors().getAt(j).get("distributor_id") === 0) {
				removeRecords.push(this.record.distributors().getAt(j));
			}
		}
		
		if (removeRecords.length > 0) {
			this.record.distributors().remove(removeRecords);
		}
		
		removeRecords = [];
		
		/**
		 * Iterate through all records and check if a valid parameter
		 * ID is assigned. If not, the record is removed as it is assumed
		 * that the record is invalid and being removed.
		 */

		for (j=0;j<this.record.parameters().getCount();j++) {
			if (this.record.parameters().getAt(j).get("unit_id") === 0) {
				removeRecords.push(this.record.parameters().getAt(j));
			}
		}
		
		if (removeRecords.length > 0) {
			this.record.parameters().remove(removeRecords);
		}
		
		removeRecords = [];
		
		/**
		 * Iterate through all records and check if a valid manufacturer
		 * ID is assigned. If not, the record is removed as it is assumed
		 * that the record is invalid and being removed.
		 */

		for (j=0;j<this.record.manufacturers().getCount();j++) {
			if (this.record.manufacturers().getAt(j).get("manufacturer_id") === 0) {
				removeRecords.push(this.record.manufacturers().getAt(j));
			}
		}
		
		if (removeRecords.length > 0) {
			this.record.manufacturers().remove(removeRecords);
		}
		
		/**
		 * Check if the storage location is valid. If not, try an exact, case-insensitive match for the
		 * storage location name and inject that into the record.
		 */
		if (isNaN(this.record.get("storageLocation"))) {
			var storageLocationRecord = this.storageLocationComboBox.getStore().findRecord(
					"name",
					this.storageLocationComboBox.getValue(),
					0, false, false, true)	;
			
			this.record.set("storageLocation", storageLocationRecord.get("id"));
		}
		
		// Force footprint to be "null" when the checkbox is checked.
		if (this.footprintNone.getValue() === true) {
			this.record.set("footprint", 0);
		}
		
	},
	onEditStart: function () {
		this.bindChildStores();
		this.nameField.focus();
		
		// Re-trigger validation because of asynchronous loading of the storage location field,
		// which would be marked invalid because validation happens immediately, but after loading
		// the storage locations, the field is valid, but not re-validated.
		
		// This workaround is done twice; once after the store is loaded and once when we start editing,
		// because we don't know which event will come first
		this.getForm().isValid();
		
		if (this.record.get("footprint") === 0) {
			this.footprintNone.setValue(true);
		} else {
			this.footprintSet.setValue(true);
		}
	},
	_onItemSaved: function () {
		this.fireEvent("partSaved", this.record);
		
		if (this.keepOpenCheckbox.getValue() !== true && this.createCopyCheckbox.getValue() !== true) {
			this.fireEvent("editorClose", this);
		} else {
			var newItem;
			if (this.partMode == "create") {
				if (this.copyPartDataCheckbox.getValue() === true) {
					data = this.record.getData(true);
					data.id = null;
					newItem = Ext.create("PartKeepr.Part");
					newItem.setDataWithAssociations(data);

					this.editItem(newItem);
				} else {
					newItem = Ext.create("PartKeepr.Part", this.partDefaults);
					this.editItem(newItem);
				}
			} else {
				var data = this.record.getData(true);
				data.id = null;
				newItem = Ext.create("PartKeepr.Part");
				newItem.setDataWithAssociations(data);

				this.editItem(newItem);
			}
			
			
			
			
		}
	},
	bindChildStores: function () {
		this.partDistributorGrid.bindStore(this.record.distributors());
		this.partManufacturerGrid.bindStore(this.record.manufacturers());
		this.partParameterGrid.bindStore(this.record.parameters());
		this.partAttachmentGrid.bindStore(this.record.attachments());
	},
	_setTitle: function (title) {
		var tmpTitle;
		
		if (this.record.phantom) {
			tmpTitle = i18n("Add Part");
		} else {
			tmpTitle = i18n("Edit Part");	
		}
		
		if (title !== "") {
			 tmpTitle = tmpTitle + ": " + title;
		}
		
		this.fireEvent("titleChange", tmpTitle);
	}
	});
``

Thats my PartEditor.js, this worked pretty well for me since 2013...
Best regards

**Comment by felicitus** [comment]
> I  could not get it ported to the actual framework but here is pretty much the base of it, may you can insert it or at least give me a hint on how to declare the needed fields in symfony fw.

That's pretty easy, you create a public or private property in the model file, run `php app/console doctrine:schema:update --force` then [re-generate your environment](https://wiki.partkeepr.org/wiki/Developers/Re-generating_the_environment) and you have both a new database field as well as accessing the newly added property within ExtJS.

**Comment by felicitus** [comment]
No feedback given for an extended period of time, closing. Feel free to re-open if required.
