### ISSUE TITLE
Unable to add Manufacturer to part

### ISSUE THREAD

**Issue by lonlyboy** [partkeepr/PartKeepr#675]
I open a part up to edit it.  I can add the distributors with no issues.  When I  click on Manufacturers, I can search and find the manufacturer I want.  When I hit save, it doesn't save.   If I hit add again, it looks like it creates a blank line and I can add another manufacturer, but when I save all the blank lines  disappear.  I currently can't add a manufacturer to any of my parts.  Any thoughts?

**Comment by amittel** [comment]
I just tried it with the demo.
As far as I can see it, you have to hit the Update Button to save the Manufacture. After that hit save and it's saved.

**Comment by felicitus** [comment]
Yes, the Update Button or enter is currently required. I'll leave this issue open to force saving the manufacturer without needing to hit "Update" or enter.

**Comment by lonlyboy** [comment]
I switched to Chrome and the update button was there.  In Microsoft Edge (Windows 10), the Update button doesn't exist.  That is where the problem lies.  For now, I'll just make sure to use Chrome instead.

**Comment by amittel** [comment]
Strange.
Just tested it with MS Edge. Update button is there.

MS Edge 25.10586.0.0
MS EdgeHTML 13.10586

**Comment by felicitus** [comment]
So may I close the issue or is there a way to reproduce the problem?

**Comment by felicitus** [comment]
No feedback given, closing. Please re-open if you can provide additional information.
