### ISSUE TITLE
Drag & Drop Problem

### ISSUE THREAD

**Issue by lazosweb** [partkeepr/PartKeepr#679]
TypeError: records[i].setCategory is not a function

**Comment by felicitus** [comment]
Please provide all details as per [CONTRIBUTING.md](https://github.com/partkeepr/PartKeepr/blob/master/CONTRIBUTING.md),

**Comment by Leathios** [comment]
I too have the same bug, it is caused when you try to move a category to another one.

I did test it on the demo website with Chrome, Firefox and edge.  Same problem.
main2.js:17389 Uncaught TypeError: records[i].setCategory is not a function

Thanks for this great software, now I know what parts I have and where to look. :)

**Comment by lazosweb** [comment]
Yes, I wrote the first post but they want more details. I do not want to sound rude but go to the DEMO version with Firebug installed and try to move a category you will see the problem.

**Comment by felicitus** [comment]
@lazosweb it works fine for me, so please provide all necessary details. I'm spending my spare time fixing bugs, please don't expect me to guess what is going on. The more details you provide the easier it is for me to fix the bug.

**Comment by lazosweb** [comment]
@felicitus ok!
So the Demo Version I guess is running on the latest version no need for me to write SQL, PHP Version and these stuff.
My Browser Type and Version: **Firefox 47.0.1**
Javascript errors in the console: **TypeError: records[i].setCategory is not a function - main2.js (line 17399, col 17)**
Operating System: Windows 7

This was reported by our production department. It's not isolated to one PC. I tried it on Google Chrome Version 51.0.2704.103 m (64-bit) still same error.

I uploaded images with the error from the 2 browsers.

If you need anything else let me know.

![firefox](https://cloud.githubusercontent.com/assets/19972355/16586386/508074b2-42ce-11e6-81b7-3c55e2bd6eea.JPG)
![chrome](https://cloud.githubusercontent.com/assets/19972355/16586390/5339cbe0-42ce-11e6-98ed-467443c559e1.JPG)

**Comment by felicitus** [comment]
Thank you, I will check later ASAP

**Comment by felicitus** [comment]
To clarify which information was missing: The initial bug report just said "Drag & Drop Problem". I then tested drag and drop of a Part onto a category, which worked just fine.

Important information which was missing:
- The issue occurs when drag'n'drop a category onto another category
- The issue can be reproduced on the demo system

I hope you know that this is not to bug you, and I appreciate every bug report, however, my time is unfortunately limited so I rely on as much information as possible. Thank you :)

**Comment by felicitus** [comment]
The issue should now be solved and can be tested on the demo system in about an hour. If there's any problem left don't hesitate to report it

**Comment by lazosweb** [comment]
@felicitus No offense taken or so ever and I never had any intentions to be rude to you...

Anyway thanks for fixing it and next time if we find something else I will be more detailed. :)
