### ISSUE TITLE
Adding a new field

### ISSUE THREAD

**Issue by yed23931** [partkeepr/PartKeepr#681]
Hello, I'm trying to add a new field to Add Part and Edit Part. I need to do changes in ova version(v0.1.9) of partkeepr. 

![untitled](https://cloud.githubusercontent.com/assets/20219664/16479016/347bfb46-3ea6-11e6-98b9-a840336a2ab2.png)

I added "Part Number" into frontend as you can see from the above attachment but I can not manage the backend. When I try to add or edit a part, "Part Number" doesn't update.

I added src/backend/Partkeepr/part/Part.php `$partNumber;` into variables wrote getter and setter method for partNumber. I modified serialize and deserialize functions accordingly.

Then I changed src/backend/Partkeepr/part/PartManager.php by adding partNumber into
`public function getQueryFields () {
		return array("name", "description", "partNumber", "averagePrice", "status", "needsReview", "createDate", "id", "stockLevel",
					"minStockLevel", "comment", "st.id AS storageLocation_id", "c.categoryPath AS categoryPath",
					"st.name as storageLocationName", "f.id AS footprint_id", "f.name AS footprintName",
					"c.id AS category", "c.name AS categoryName", "pu.id AS partUnit", "pu.name AS partUnitName",
                    "pu.shortName AS partUnitShortName", "pu.is_default AS partUnitDefault", "partCondition"
				);
	}`

I also added `if (array_key_exists("partNumber", $aParameters)) {
			$part->setPartNumber($aParameters["partNumber"]);
		}`

Could you help tell me where am I missing?
Thank you.

**Comment by felicitus** [comment]
You need to add the field to the frontend code as well. I'm afraid that the issue tracker is not a support forum, please use the mailing list for development related questions.
