### ISSUE TITLE
Install issue on Ubuntu Mate 16.04 on Pi 3

### ISSUE THREAD

**Issue by underwoodle** [partkeepr/PartKeepr#684]
I have finally been successful in getting through until nearly the end of the install process.  But near the end when it is 'warming up the cache' I am getting the error message 'Invalid response'.  When I click on the error message button I am getting no better an explanation.  

Not sure what info you need.  Please let me know what you need.

I am running:
Ubuntu Mate 16.04 for Raspberry Pi
PHP 7.0
apcu
apcu_bc

**Comment by felicitus** [comment]
Warming up the cache is a very I/O expensive operation. Check using dstat and iotop what's going on.

Additionally you can use dbench to benchmark  - a few useful hints can be found in my Mail here:

https://groups.google.com/forum/#!msg/partkeepr-users/LxsGzpQ1KrM/t7Bi7vX5CQAJ

**Comment by felicitus** [comment]
No more feedback given, closing. Feel free to re-open with additional information.
