### ISSUE TITLE
Project Reports - Remove parts from stock

### ISSUE THREAD

**Issue by tayfuncetin** [partkeepr/PartKeepr#686]
Hello,

I would like to know if PartKeepr can add 'project name' in comment field on 'stock history' while 'removing parts from stock'. (I mean during batch stock removing.)

By this way, we could track back how many pieces of a stock entry used on which project. 

I think even if Partkeepr doesn't have such a feature, It might be very easy to add few code rows to make it able to do this request. I tried to do it by myself but I couldn't achieve it. Because I have no idea of Partkeepr's code structure. I took a look at it but it seems very complicated.

**Comment by felicitus** [comment]
It seems that there's a bug - it used to work before. Scheduled for 1.0.1

**Comment by felicitus** [comment]
This was an easy one - the bug is fixed, you should be able to test it on the demo system soon. The project name is now written into the comments field for a stock removal.
