### ISSUE TITLE
Setup fails when started from subdir/alias settings

### ISSUE THREAD

**Issue by robertomurta** [partkeepr/PartKeepr#688]
hi, I started the setup from a Alias, but the rewrite fails during checks, however by starting the setup from root dir, it works as expected.

I'm using debian jessie + apache 2.4 + postgresql + php 7.0

the relevant part of my apache configuration is:

<IfModule mod_ssl.c>
        <VirtualHost _default_:443>
                ServerName my.personal.url
                ServerAdmin user.is@github.com

```
            DocumentRoot /var/www/html
   # just used the above to install partkeepr... :)
    #       DocumentRoot /var/www/PartKeepr/web
            Alias /parts /var/www/PartKeepr/web
            <Directory /var/www/PartKeepr/web>
                    AllowOverride All
            </Directory>
```

...

ps. nice work :+1:  :)

**Comment by olewolf** [comment]
I had to make a change in the supplied .htaccess file in order to run PartKeepr from a different directory. First, my Apache config for reference:

```
 Alias /PartKeepr "/usr/local/share/PartKeepr/web"
  <Directory "/usr/local/share/PartKeepr/web">
  Options Indexes MultiViews FollowSymLinks
  AcceptPathInfo On
  AllowOverride All
  Require all granted
 </Directory>
```

And the .htaccess change, which I added right above the RewriteRule ^setup\/$ setup/index.html line:

```
 RewriteBase /PartKeepr
```

This rewritebase should of course be modified according to your Apache config file.

**Comment by christianlupus** [comment]
@robertomurta I assume, you got things sorted out in the meantime, otherwise you would have recontacted. If not, please comment, we will try to help.
