### ISSUE TITLE
Doctrine\Common\Annotations\AnnotationRegistry

### ISSUE THREAD

**Issue by stevey1983** [partkeepr/PartKeepr#695]
Hi, when trying to install i get this error on the "Setup now checks if your server is capable of running PartKeepr." page. when i click on the error i get:

Invalid Response from server

Fatal error: Class 'Doctrine\Common\Annotations\AnnotationRegistry' not found in /public_html/stock/app/autoload.php on line 11

Thanks for your help

**Comment by felicitus** [comment]
Please add all required information as per [CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by felicitus** [comment]
No feedback received, closing. Re-open with additional information if required.
