### ISSUE TITLE
Partkeepr 1.0 search missing matches in Name field occasionally

### ISSUE THREAD

**Issue by backstube** [partkeepr/PartKeepr#696]
This is an example how PK v1.0 behaves performing searches _just in Name field_. There are other issues filed covering search flaws in regard to Description or Comment fields. 

Here's a category view into Zener Diodes Category with an empty search form:

![screen shot 2016-07-30 at 14 32 42](https://cloud.githubusercontent.com/assets/5227989/17270456/2a8ad9fc-5663-11e6-825e-9f57f88cee82.png)

As you can see there are a couple of parts in there. No problem so far. A search query for "Zener" returns exactly the same result, I skip the pic for that.

Now for "Zener 6,2" which is a pretty common task. (Yes, we have added our parts with comma as decimal delimiter instead of points widely used in imperial countries. But anyways, they're strings here so that's irrelevant search-wise.)

![screen shot 2016-07-30 at 14 45 30](https://cloud.githubusercontent.com/assets/5227989/17270507/52429f56-5664-11e6-9d7d-1b88f68447e3.png)

The same with "Zener ZF":

![screen shot 2016-07-30 at 14 46 12](https://cloud.githubusercontent.com/assets/5227989/17270517/73de2892-5664-11e6-9ae7-a1bae7332e04.png)

This is **not** expected behaviour. We want to find parts by narrowing down the set of matches by adding more specific details into search field. Here, any second word entered into search field will falsely zero the set of matches, though several matches do exist.

**Comment by backstube** [comment]
Ok, here's a bunch of use cases that contribute in characterising PK's v1.0 search function compared to v0.1.9 search. They first got posted there #694.

a.) search now does find strings in Description and Comment fields, which is good. However, if a part is needed that happens to be a MOSFET by International Rectifier w/ 29 Amps, I would enter "IRFZ 29A". Result: no match. It's there, but IRFZ is in Name, whereas 29A is in Description field.

b.) there's an "LED, 5x2,5mm, rot". A query for "LED rot" results in zero matches. There also is a part named "LED Mix". A query for those two words does find that part. Why's that? 
This behaviour I also have found in our v1.0 installation and reported that as search being inconsistent.

c.) a search with substring "BC" does match with all parts (mainly Si-Transistors) that have it in either Name or Description or Comment field. But only as long as there comes no other word along in search query like "BC 45V". This is pretty much related to a.) except for the fraction-of-a-word part.

d.) search doesn't find and list all parts which have words in Comment in the boolean OR sense: There are 3 parts: BC547A, BC547B, BC547C. In Comment field, they have alice, bob, claire, respectively. So a query "alice bob claire" OR-ed them in PK v0.1.9, thus spit out all three parts associated to them. In PK v1.0: zero matches.

In my opinion v1.0 search is no better in any conceivable way in comparison to v0.1.9 search back in the day. So if I could chose I'd clearly make it like it was before. I cannot remember any flaws it had then.

**Comment by felicitus** [comment]
I have added OR'ing of all fields. It's now possible to configure the fields searched as well as a full string search or split the string into substrings by space. 

I believe all things you described from a) to d) should be fixed, can you double-check on the demo system?

**Comment by backstube** [comment]
I would if I could, but demo site seems to be broken atm. Page is visibly empty, under the hood there is html stuff, though. A quick peek into the matter w/ WebInspector hasn't brought a terrible error to light, so I dunno what's wrong there.

**Comment by felicitus** [comment]
It should work now, please try again

**Comment by backstube** [comment]
True. Site's up again.

> It's now possible to configure the fields searched as well as a full string search or split the string into substrings by space.

Sounds good. How would I do that? Where's the pref setting to this config located?

**Comment by backstube** [comment]
Ah, under System Prefs. I only took a look unter User Prefs, assumed that this would be a per-user feature. I'll give it a try.

**Comment by felicitus** [comment]
The default config is to use PartKeepr 0.1.9 behavior, I'm not sure about the per-user feature yet, since if the user configures too many fields this could impact database performance and even cause problems since the HTTP query string could become too long without an obvious cause.

**Comment by backstube** [comment]
I haven't had much time to test things on demo site since, hence I'm a bit late on this.

> The default config is to use PartKeepr 0.1.9 behavior, 

Well, I'm not quite sure about this. For what I can def. say is, that (with this setting turned on in Sys Prefs) when entering "BC 45V" to get a set of matches including "BC547A" "BC547B" "BC547C" w/ 45 Volts, this is a use case PK v0.1.9 did as expected. In other words: 0.1.9 would find those transistors, whereas demo right now does not. I'll check this later w/ help of my old 0.1.9 instance, which has to be resurrected first. This is case c.) from above.

> I'm not sure about the per-user feature yet, since if the user configures too many fields this could impact database performance and even cause problems since the HTTP query string could become too long without an obvious cause.

Yes. Agree. That could be expensive. I'm also not fine with the query (the OR-ed fields thing) term. When opted for user selectable search fields in Sys Prefs it isn't useful, it brings up far too many hits. I tend to say the OR part comes a bit too early now. In a few tests I fired off the set of matches grew the more details I entered. This is the opposite of narrowing down, I think. It needs more attention, that's for sure. I am going to contribute here soon.

**Comment by felicitus** [comment]
> Well, I'm not quite sure about this. For what I can def. say is, that (with this setting turned on in Sys Prefs) when entering "BC 45V" to get a set of matches including "BC547A" "BC547B" "BC547C" w/ 45 Volts, this is a use case PK v0.1.9 did as expected. In other words: 0.1.9 would find those transistors, whereas demo right now does not. I'll check this later w/ help of my old 0.1.9 instance, which has to be resurrected first. This is case c.) from above.

When I enter "BC 45V" on the demo I receive a set of matches including "BC547A", "BC547B" and "BC547C2 - tested one minute ago. Maybe it was configured by another user to revert to the old behaviour? The demo site is reset each full hour.

> Yes. Agree. That could be expensive. I'm also not fine with the query (the OR-ed fields thing) term. When opted for user selectable search fields in Sys Prefs it isn't useful, it brings up far too many hits. I tend to say the OR part comes a bit too early now. In a few tests I fired off the set of matches grew the more details I entered. This is the opposite of narrowing down, I think. It needs more attention, that's for sure. I am going to contribute here soon.

Yes, that might be the case. I'll double check against the 0.1.9 behavior, it shouldn't be a big issue to fix.

**Comment by felicitus** [comment]
I have (hopefully) correctly reworked the search behavior to that of 0.1.9 - can you double-check on the demo system if it works for you?

**Comment by felicitus** [comment]
No feedback given, I assume it's fixed. If that's not the case, please re-open.
