### ISSUE TITLE
Showing part information in popup when using barcode reader

### ISSUE THREAD

**Issue by goebel** [partkeepr/PartKeepr#727]
I just tried the partkeepr demo and also tried it with a honeywell MS9520 barcode reader and it really works well. However there is one small feature/improvement I am missing. When I scan a bar code the JS popup appears where I can add the quantity, comment and add or remove the parts from the stock. However, the user does not see the part which he is adding or removing parts from the stock. It would be great if the description, part name or internal reference would appear somewhere in the popup to inform the user which part he is currently modifying. Now the User changes the quantity of a part which is not visible in the screen.
Furthermore, adding the possibility to confirm the add or remove quantity from the stock with a keyboard shortcut would enable working without mouse.

**Comment by felicitus** [comment]
Part details are now displayed when using the combined add/remove stock dialog, which is triggered by the barcode scanner action.

Keyboard functionality is already implemented, positive quantities and enter increase the stock and negative quantities decrease the stock. Example: -11 and enter yields the same result as if you enter 11 and click "Remove". Of course, when you enter -11 and click "Add", stock gets removed ;)

![image](https://cloud.githubusercontent.com/assets/162974/22473222/75f729ca-e7d8-11e6-8640-e33c9809bdee.png)

**Comment by whc2001** [comment]
In case someone still confused by "click \\"Add\\"" while emphasizing keyboard shortcut, hitting Enter while focusing on quantity control is the same as clicking "Add", which enables fully keyboard experience.
