### ISSUE TITLE
Warming up the cache - failed setup

### ISSUE THREAD

**Issue by RichardNeilson** [partkeepr/PartKeepr#729]
Hi,

I have been having trouble installing partkeepr (1.10) I haven't tried using it for quite a while as there was a couple of issues that caused me a problem but now look to be resolved.

I tried to upgrade to 1.10 but after a few problems decided to do a clean install, new file upload and database. I am trying to install it on my outside hosted server (the same as our website runs on)

The setup seems to go ok apart from a yellow warning in prerequisites for PHP settings : 

Symfony2 : 
 a PHP accelerator should be installed
Install and/or enable a PHP accelerator (highly recommended).

PHP APCu cache not found
For best performance install the PHP APCu cache

Unfortunately I have now control over the PHP install on the server.

It then fails at Setup 2/2 when warming up the cache. Is this due to the earlier yellow warning? Is there something I can look at to resolve this?

Many thanks for any help.

Richard

**Comment by felicitus** [comment]
Does it take very long to complete the step "Warming up the cache"? If so, the performance of your server is too low. Warming up the cache generates quite some disk I/O. If you have no control over the server, you're in bad luck - any remendy to the issue would involve adjusting PHP settings, like increasing the `max_execution_time` directive or monitoring disk I/O on the server.

**Comment by RichardNeilson** [comment]
Thanks for the quick response. It takes 40 seconds from starting warm up to showing the error. No, unfortunately I have no control over the server. Has something put more stress on the disk since around version 0.75-0.76. It used to run an older version ok but then maybe something has changed server side?!

**Comment by felicitus** [comment]
It's hard to tell but a well-configured server should take no more than 5-10 seconds to run through the `Warming up the cache` stage. Even on a Raspberry Pi 3 with a slow SD card this takes only  about 50 seconds.

**Comment by RichardNeilson** [comment]
Ok. Would it still pass the setup on the Pi3 at 50 seconds then? 10 seconds longer?!

**Comment by felicitus** [comment]
Yes, because the Raspberry Pi hat a `maximum_execution_time` of 240 seconds. The timeout isn't defined by PartKeepr, it's defined by your PHP configuration.

**Comment by RichardNeilson** [comment]
Ah, of course. Thanks for the help. Guess I'll try to get the hosting company to check it out but I'm not holding my breath!
