### ISSUE TITLE
Mail to info@partkeepr.org for a Android App

### ISSUE THREAD

**Issue by blinzelaffe** [partkeepr/PartKeepr#730]
Hey felicitus,
maybe i'm to impatient, but is the mail-address info@partkeepr.org still maintained? I wrote you some questions about an android app i developed for partkeepr. If you have time and interest, consider to answer me. Maybe this place fits even more for discussions. I'm open minded for your suggestions.

With kind regards
Marcus

**Comment by felicitus** [comment]
Yes, I've seen the mail but haven't gotten time to reply so far. Stay tuned :)
