### ISSUE TITLE
Drag and Drop produces internal error due to excessive memory consumption

### ISSUE THREAD

**Issue by goebel** [partkeepr/PartKeepr#731]
Hi
When I select a couple of parts (+-20) and I want to drag them in another category this works however the application becomes unusable after the action and the OOM killer kills some httpd processes or maraiadb processes because there is not enough memory available. 
My server is a centos 7, 2cpu's and 2GB of memory. 
![dragdrop](https://cloud.githubusercontent.com/assets/440791/18410675/9627b95c-7768-11e6-9b0c-b9d7ffbf5c2c.PNG)

**Comment by goebel** [comment]
This error is reproductible on the demo site of partkeepr.
I took 28 diodes and draged them somewhere else and I also got the same error in the browser

**Comment by felicitus** [comment]
Thanks for the report, it should now be fixed
