### ISSUE TITLE
Parts with price information is not show correct in the summary

### ISSUE THREAD

**Issue by goebel** [partkeepr/PartKeepr#736]
Hi,

I am filling the stock with parts. All the parts I enter in the stock do not have a price higher than 0 euro, so no price. In the summary information all my parts are shown with an average part value of 0euro and there are no parts without a price. Is that the correct behavior ? Does a part with a price of 0 euro enters the category of parts with a price ?

Current Statistics
Different Parts:    309
Total Part Value:   0.00€
Average Part Value: 0.00€
Parts with price:   309
Parts without price:    0
Categories: 22

**Comment by madmax76** [comment]
Different Parts:	64
Total Part Value:	31.00000€
Average Part Value:	0.02500€
Parts with price:	64
Parts without price:	0
Categories:	134

**Comment by goebel** [comment]
Hi,

I think the problem is due to the method getPartCount($withoutPrice = false) in the class StatisticService. When you enter new parts to partkeepr without any price, the averageprice is 0 and not null.  Even the constraint on the column averageprice in the table Parts does not permit null values (mysql schema)

Perhaps it would be an idea to change the where clause to 
WHERE p.averagePrice > 0

`
    /**
     * Returns the part count.
     *
     * @param bool|false $withoutPrice Set to true to retrieve all parts where the average price is null
     *
     * @return mixed
     */
    public function getPartCount($withoutPrice = false)
    {
        $dql = "SELECT COUNT(p.id) FROM PartKeepr\PartBundle\Entity\Part p";
        if ($withoutPrice === true) {
            $dql .= ' WHERE p.averagePrice IS NOT NULL';
        }
        return $this->entityManager->createQuery($dql)->getSingleScalarResult();
    }
`
