### ISSUE TITLE
Setting up default footprint error  PartKeepr 1.1.0

### ISSUE THREAD

**Issue by jgauchia** [partkeepr/PartKeepr#739]
Hi, 
I'm trying to setup the 1.1.0 version of PartKeepr in a clean Debian installation.
I follow all the procedures (I think) to install it but in Setup 1/2 when setting up default footprint it's raise an error.
I'm trying to attach it , but I can't paste all the error message only a small captures 

![partkeepr](https://cloud.githubusercontent.com/assets/1075178/19497697/cf8c5b60-958d-11e6-873f-afb30d152d89.png)
![partkeepr2](https://cloud.githubusercontent.com/assets/1075178/19497696/cf8ac0d4-958d-11e6-9190-350b066247d1.png)
![partkeepr3](https://cloud.githubusercontent.com/assets/1075178/19497698/cf8f93ca-958d-11e6-90c4-453482aadf81.png)

**Comment by felicitus** [comment]
Can you post the `app/log/setup.log` and `app/log/setup_test.log` files, preferably as a pastepin like paste.debian.net ?

**Comment by jgauchia** [comment]
Ok , tomorrow I'll try to post log files

**Comment by jgauchia** [comment]
setup_test.log -> [http://paste.debian.net/883985](http://paste.debian.net/883985/)
setup.log -> [http://paste.debian.net/883986/](http://paste.debian.net/883986/) (cutted)

**Comment by felicitus** [comment]
It seems that you miss the bcmath PHP extension for your system - please install it. Leaving this issue open to have PartKeepr check for the bcmath library.

**Comment by jgauchia** [comment]
ok I'll try
thanks!

**Comment by jgauchia** [comment]
Ok, Works! Thank you!
Only a little warning with ACPu , but doesn't matter.

**Comment by SSpike** [comment]
The step:    
       sudo apt-get install php7.0-bcmath 
 is missing in the  setup documentation "PartKeepr on Debian "Jessie":
       https://wiki.partkeepr.org/wiki/PartKeepr_on_Debian_%22Jessie%22

**Comment by Schurick** [comment]
Had same error-message, because the bcmath-extension is still not mentioned in the setup documentation.

**Comment by siworks** [comment]
bcmath-extension did the job for me to.

**Comment by ramonil** [comment]
Hello People,

I am having below errow message while installing partkeepr on centos 7
i have installed yum install php-bcmath as described above but yet stillthrowing up error
Kindly help me out

Setting up the default footprints...Error

An unexpected error occured during installation. The error message was:
[Syntax Error] line 0, col 69: Error: Expected Literal, got 'ORDER' and happened in /usr/share/pear/Doctrine/ORM/Query/QueryException.php:44

**Comment by christianlupus** [comment]
The main issue was detected and solved. If @ramonil has still the same problem, please open a new issue.
