### ISSUE TITLE
fonts are using http - breaks https support

### ISSUE THREAD

**Issue by Kunsi** [partkeepr/PartKeepr#743]
PartKeepr uses some fonts provided by Google Fonts. However it uses a hard-coded http:// prefix, which results in SSL errors when opening up the PartKeepr Website.

`<link href='http://fonts.googleapis.com/css?family=Ubuntu:400,700italic' rel='stylesheet' type='text/css'>`

Best would be to use https:// or simply //-prefix (the latter will let the browser choose wether to use http or https)

**Comment by Kunsi** [comment]
Seems to only affect the setup procedure, if I see correctly.

**Comment by felicitus** [comment]
I'm reopening this since there should be no need for the google fonts in setup anymore.
