### ISSUE TITLE
New Install:  Unable to log in

### ISSUE THREAD

**Issue by thenetimp** [partkeepr/PartKeepr#755]
Last night I successfully installed partkeepr.  I was able to log with both the primary username I created during setup and a secondary username I created after setup before I went to bed last night.  I woke this morning to log in and I am unable to log in as either.  I have checked all the obvious things (caplock etc...) I am typing in the passwords correctly.  

I'd reset the password but there seems to be no obvious "forgot password" functionality.

Thoughts?

Symfony log contains...

[2016-12-22 13:51:13] ldap_driver.ERROR: 0x51 (Can't contact LDAP server): ldap://127.0.0.1 [] []
[2016-12-22 13:51:13] app.WARNING: Bad credentials. [] []

**Comment by thenetimp** [comment]
Symfony log contains...

[2016-12-22 13:51:13] ldap_driver.ERROR: 0x51 (Can't contact LDAP server): ldap://127.0.0.1 [] []
[2016-12-22 13:51:13] app.WARNING: Bad credentials. [] []

**Comment by thenetimp** [comment]
I cleared the symfony cache and the problem went away.  The cache directory is owned by www-data and I installed the cronjob as www-data.  I suspect that the cronjob somehow borked the permissions on the cache files and prevented normal operations.  I'll keep an eye on it over the rest of the evening and see if it happens again.

**Comment by pingdynasty** [comment]
I have a slightly different problem: after install and setup, I can't log in with the username and password used to create an admin user. In other words I can't log in at all. I've run setup several times and tried both Basic HTTP and WSSE auth.
The error message is the same:
```
[2017-01-16 15:11:35] ldap_driver.ERROR: 0x51 (Can't contact LDAP server): ldap://127.0.0.1 [] []
[2017-01-16 15:11:35] app.WARNING: Bad credentials. [] []
```

**Comment by thenetimp** [comment]
From the install root

rm -rf app/cache/*  

will delete all symfony cache related files.  That's what worked for me.
make sure the cache and log directories are either chmoded 777 or chowned to the webserver username as well.  Symfony gets cranky when it can't right to the cache and log directories

**Comment by pingdynasty** [comment]
thanks @thenetimp - I managed to log in eventually after messing with the cache and updating to latest master.
Oddly enough it was the first username and password that I entered in setup that worked, not the most recent one (several attempts later). But now I'm logged in and happy :smile:

**Comment by christianlupus** [comment]
As this seems solved, I close it.
