### ISSUE TITLE
Web server missconfiguration

### ISSUE THREAD

**Issue by ulashaksu** [partkeepr/PartKeepr#757]
i am on Ubuntu with Apache2/Php7/MariaDB and trying to install partkeepr but having Web server missconfiguration error at the very first step. When i check details it forwards me to https://wiki.partkeepr.org/wiki/KB00005:Web_Server_Configuration
Tried many things without a success. Can anyone help me on this?

**Comment by ulashaksu** [comment]
i have tried everything but still the same mistake. My apache2.conf is as below;

`# Sets the default security model of the Apache2 HTTPD server. It does
# not allow access to the root filesystem outside of /usr/share and /var/www.
# The former is used by web applications packaged in Debian,
# the latter may be used for local directories served by the web server. If
# your system is serving content from a sub-directory in /srv you must allow
# access here, or in any related virtual host.
<Directory />
	Options FollowSymLinks
	AllowOverride All
	Require all denied
</Directory>

<Directory /usr/share>
	AllowOverride All
	Require all granted
</Directory>

<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>

#<Directory /srv/>
#	Options Indexes FollowSymLinks
#	AllowOverride All
#	Require all granted
#</Directory>


  <Directory /var/www/html/stok/web>
  AcceptPathInfo On
  RewriteEngine On
  AllowOverride All
  Require all granted
 </Directory>

<Directory " /var/www/html/stok/web">
   <Files ~ "\.php$"> 
   AcceptPathInfo On 
   </Files> 
</Directory>

# AccessFileName: The name of the file to look for in each directory
# for additional configuration directives.  See also the AllowOverride
# directive.
#
AccessFileName .htaccess

#
# The following lines prevent .htaccess and .htpasswd files from being
# viewed by Web clients.
#
<FilesMatch "^\.ht">
	Require all denied
</FilesMatch>`

**Comment by felicitus** [comment]
Do you have anything configured as per https://wiki.partkeepr.org/wiki/KB00005:Web_Server_Configuration ?

**Comment by nehu92** [comment]
same error, has anyone found a solution, i already configured server as per.

**Comment by christianlupus** [comment]
As this issue is quite old and most probably solved itself, I will close it. In case it is still valid, please write an additional comment.
