### ISSUE TITLE
Unable to Set Currency Type

### ISSUE THREAD

**Issue by dbair** [partkeepr/PartKeepr#758]
Using PartKepr v 1.1.0
I am unable to set the default currency or change the default.  From what I have read, it should be in Edit -> Users -> User settings.  There is no place to set or change the Currency there.

Please advise.

-- David

**Comment by felicitus** [comment]
System->User Preferences->Formatting->Currency Symbol

![image](https://cloud.githubusercontent.com/assets/162974/21485547/2f156c14-cba5-11e6-8f2a-f09b5de5aeaf.png)

**Comment by dbair** [comment]
Thank you!
