### ISSUE TITLE
Getting storage locations, adding parts returns undefined.

### ISSUE THREAD

**Issue by jdtech3** [partkeepr/PartKeepr#775]
I just installed PartKeepr and whenever I try to add a part or access storage locations drop-down menu on the add parts page, it throws a critical error apparently returning undefined:

    Critical Error
    
    Details
    ==================================
    The server returned a response which we were not able to interpret.
    
    Request
    ==================================
    POST https://domain.tld/parts/web/api/parts?_dc=1483807882497
    
    [object Object]
    
    Response Status Code
    ==================================
    0
    
    Response
    ==================================
    undefined

    Server Configuration
    ==================================
    doctrine_orm_version: 2.5.4
    doctrine_dbal_version: 2.5.2
    doctrine_common_version: 2.6.0-DEV
    php_version: 5.6.29-1+deb.sury.org~trusty+1
    auto_start_session: true
    maxUploadSize: 2097152
    availableImageFormats: JPG,GIF,PNG
    max_users: unlimited
    authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
    tip_of_the_day_uri: https://partkeepr.org/tips/%s
    password_change: true

**Comment by felicitus** [comment]
Please post the HTTP request being sent. You can find out how to view HTTP requests here:

[https://wiki.partkeepr.org/wiki/How_to_Debug](https://wiki.partkeepr.org/wiki/How_to_Debug)

Also check your web server logs if there are any errors listed.

**Comment by jdtech3** [comment]
Here is a screenshot of the XHR load log when entering in parts data when I am adding a part: [screenshot 1](http://i.imgur.com/zx1YkTj.png) No errors at this time.

Here's the screenshot when I submit the add part form, with the POST error and version info in background: [screenshot 2](http://i.imgur.com/iLCxi1T.png)

Hopefully they're not too blurry...I'll check the apache logs now.

**Comment by felicitus** [comment]
Well the error in screenshot 2 is because no part measurement unit is set. Usually PartKeepr should create a default part unit named "pieces" and set it as default, but it seems that it didn't work for you for some unknown reason.

You can create a default part unit in "Edit" => "Part Measurement Units"

**Comment by jdtech3** [comment]
Hmm...the error thrown in the screenshot above is different from the one I originally got. Before, it just undefined, now there's an actual response. Here's the full error report btw:

    An error occurred
    
    Details
    ==================================
    Catchable Fatal Error: Argument 1 passed to PartKeepr\PartBundle\Entity\Part::setPartUnit() must be     an instance of PartKeepr\PartBundle\Entity\PartMeasurementUnit, null given, called in /var/www/html/parts/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php on line 556 and defined

    Request
    ==================================
    POST https://jdtechnologies.xyz/parts/web/api/parts?_dc=1483814861725

    [object Object]

    Response Status Code
    ==================================
    500

    Response
    ==================================
    {"@context":"\/parts\/web\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"Catchable Fatal Error: Argument 1 passed to PartKeepr\\PartBundle\\Entity\\Part::setPartUnit() must be an instance of PartKeepr\\PartBundle\\Entity\\PartMeasurementUnit, null given, called in \/var\/www\/html\/parts\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/PropertyAccess\/PropertyAccessor.php on line 556 and defined"}

    Server Configuration
    ==================================
    doctrine_orm_version: 2.5.4
    doctrine_dbal_version: 2.5.2
    doctrine_common_version: 2.6.0-DEV
    php_version: 5.6.29-1+deb.sury.org~trusty+1
    auto_start_session: true
    maxUploadSize: 2097152
    availableImageFormats: JPG,GIF,PNG
    max_users: unlimited
    authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
    tip_of_the_day_uri: https://partkeepr.org/tips/%s
    password_change: true

**Comment by jdtech3** [comment]
Okay, I'll do that and try again.

**Comment by jdtech3** [comment]
There is a measurement unit named pieces with pcs as short form and it's default. The server can't find it, I guess?

**Comment by felicitus** [comment]
For some reason yes. Usually it should be selected when you create a new part.

Can you check if the part measurement unit `Pieces` is available in the Dropdown `Measurement Unit` in the `Add Part` Dialog? If it does, can you check if it works when you select it manually?

**Comment by jdtech3** [comment]
Oh! It works when selecting it manually. And the weirdest thing is, even though the requests before thrown errors, they seem to have actually gone through. Now the parts I used to give you the screenshot appears on the view part page...

**Comment by felicitus** [comment]
That's odd that the default unit is not selected by default. Can you double-check if the default unit is picked when reloading the user interface?

**Comment by jdtech3** [comment]
Now, (still at 1.1) it seems to be fine. The default unit of pieces is automatically picked.
