### ISSUE TITLE
Latest update (from Git) creates error in setup during database connectivity check

### ISSUE THREAD

**Issue by ericmoon** [partkeepr/PartKeepr#779]
I updated to the latest git (using the method outlined in the wiki, which has worked many times before).
During the setup,  I got the following error doing database connectivity check:

The service "partkeepr.octopart_service" has a dependency on a non-existent parameter "partkeepr.octopart.apikey".

I'm running on a postgres database on debian.

**Comment by felicitus** [comment]
To make it work, please add `$container->setParameter('partkeepr.octopart.apikey', '');` to your app/config/parameters.php

**Comment by ericmoon** [comment]
Perfect, thank you, and thanks so much for PartKeepr - top notch software.

Are there any other changes necessary to enable the octopart integration?  I've gotten my api key from them and re-ran setup, but not showing.

**Comment by felicitus** [comment]
No, the button should be visible at all times in the Add/Edit Part Dialog. Is it visible? If not, you might need to clear the browser cache.

**Comment by ericmoon** [comment]
That was it.  Thought I did it before, but oh well.. thanks again.
