### ISSUE TITLE
Warming up the Cache - failed setup on Synology DS715

### ISSUE THREAD

**Issue by Peet59** [partkeepr/PartKeepr#786]
Hi,

I have been having trouble installing PartKeepr (v1.1.0) on a Synology NAS DS715. I have used PartKeepr never before. The setup seems to go ok. No yellow warning. It then fails at Setup 2/2 when “warming up the cache” after ~60 seconds with Invalid Respons of Server. Show Error is 504 gateway timeout. I have read the issue #729 that maybe the performance of my server is too low? I played with php-setting _max_execution_time_ but with no results. Some of my php-setting who I can change are: 

max_execution_time 240
max_file_uploads 20
max_input_nesting_level 64
max_input_time 60
max_input_vars 1000
post_max_size 32M
upload_max_filesize 32M

Is someone running PartKeepr on a Synology NAS? 
Is there something I can look at to resolve the “Warming up the Cache” error?

Many thanks for any help.

Peet

**Comment by felicitus** [comment]
If you receive error 504 then your system is most likely too slow. You might want to increase `max_execution_time` and/or `max_input_time` even further, but I doubt PartKeepr is fun on such a slow system.
