### ISSUE TITLE
new version of partkeepr(demo)......issue of status(needs review)

### ISSUE THREAD

**Issue by mctomaszek** [partkeepr/PartKeepr#788]
once you will mark "needs review" later system does not allow you to change status again

**Comment by felicitus** [comment]
I believe this is now fixed, can you test?

**Comment by mctomaszek** [comment]
demo still has the same issue

**Comment by felicitus** [comment]
Please try in about one hour, the demo system is updated on every full hour.

**Comment by mctomaszek** [comment]
ok. Thank U. Could you let me know please when new version will be ready to download?

**Comment by felicitus** [comment]
Version 1.2 is scheduled for Feb 1st 2017
