### ISSUE TITLE
keyMap.on is not a function error

### ISSUE THREAD

**Issue by lazosweb** [partkeepr/PartKeepr#789]
I updated Partkeepr to the latest version using git. But since the update this is how the first page is loading and the error message in the image below. I cleared my browser cache. I tried this on both firefox and chrome still same problem. I cleared Partkeepr cache still same problem. I even deleted my old directory and re-run the setup in a new directory with the same parameters and database and I still have the same problem. Any ideas?

![capture](https://cloud.githubusercontent.com/assets/19972355/22023004/0ef90e5c-dccd-11e6-9414-5e064f2f4e7b.JPG)

**Comment by lazosweb** [comment]
I installed again the version 1.1.0 from the ZIP file instead of the git one and now everything is back to normal. You can close the issue if you like.

**Comment by felicitus** [comment]
This should now be fixed.

**Comment by lazosweb** [comment]
Thank you.
