### ISSUE TITLE
Login issue immediately after successful installation

### ISSUE THREAD

**Issue by raghuveer-s** [partkeepr/PartKeepr#790]
Hello,

I installed PartKeepr successfully by following all the instructions and I hit the "Submit" button to take me to the login page and I got this screen. I couldn't enter the login credentials and the login box is on the top left.

I'm using Chrome Version 55.0.2883.87 m, Windows 7 host. The server is a VM Ubuntu 12.04, running on PHP 7.0, MySQL (mysql version 14.14 and mysqld version 5.5) and nginx version 1.1.19.

Chrome console showed this as an error:
Uncaught TypeError: keyMap.on is not a function
    at g.assignEnterKey (main2.js:10397)
    at F.fire (extjs.js:22)
    at g.doFireEvent (extjs.js:22)
    at g.doFireEvent (extjs.js:22)
    at g.a.doFireEvent (extjs.js:22)
    at g.fireEventArgs (extjs.js:22)
    at g.fireEvent (extjs.js:22)
    at g.finishRender (extjs.js:22)
    at g.render (extjs.js:22)
    at g.doAutoRender (extjs.js:22)

Any help is appreciated, thank you.

![screenshot](https://cloud.githubusercontent.com/assets/2290960/22060753/211b547a-dd98-11e6-98b1-f6f1819783c5.jpg)

**Comment by felicitus** [comment]
It seems that you installed PartKeepr from GIT (the information is missing from your bug report) - if so, please update your installation and re-run setup. The issue was fixed yesterday

**Comment by raghuveer-s** [comment]
It worked, thank you!
