### ISSUE TITLE
Demo_Themes

### ISSUE THREAD

**Issue by mctomaszek** [partkeepr/PartKeepr#791]
This option is making system very unstable at the moment. After few changes of themes.... system is crashing

**Comment by felicitus** [comment]
Can you elaborate what you mean with "system is crashing"?

**Comment by mctomaszek** [comment]
demo does not work any more

**Comment by felicitus** [comment]
I can't reproduce that

**Comment by felicitus** [comment]
Please provide all details as per [CONTRIBUTING.md](https://github.com/partkeepr/PartKeepr/blob/master/CONTRIBUTING.md),

**Comment by mctomaszek** [comment]
can you open https://demo.partkeepr.org/ ?

**Comment by mctomaszek** [comment]
without problem?

**Comment by felicitus** [comment]
yes I can

**Comment by felicitus** [comment]
__Please__ provide information as noted in __[CONTRIBUTING.md](https://github.com/partkeepr/PartKeepr/blob/master/CONTRIBUTING.md)__ !

**Comment by mctomaszek** [comment]
after few times of themes changes https://demo.partkeepr.org/ does not work. 
![partkeepr_12](https://cloud.githubusercontent.com/assets/13379408/22125855/4270eafe-de8d-11e6-87b8-d2f9c371542c.png)

**Comment by felicitus** [comment]
Again, _PLEASE_ provide _ALL_ information as per __[CONTRIBUTING.md](https://github.com/partkeepr/PartKeepr/blob/master/CONTRIBUTING.md)__ including your __BROWSER__ and your __BROWSER VERSION__!

**Comment by mctomaszek** [comment]
sorry for It Felicitus... don't take me wrong. I will try explain you .

browser: firefox, IE, chrome same problem. 

After changing themes I have tried reload (refresh) demo site.  Page of demo does not want to load again

**Comment by JohnEffland** [comment]
Using chrome pointing at https://demo.partkeepr.org/, the debugger claims this css fails to load:

GET https://demo.partkeepr.org/js/packages/extjs6/build/packages/ux/classic/aria/resources/ux-all.css

**Comment by felicitus** [comment]
I could reproduce the problem using a Windows VM - there's a race condition which caused the ExtJS layout manager to fail when the stylesheet was replaced. Please try again, the issue should now be fixed.
