### ISSUE TITLE
search option is giving error

### ISSUE THREAD

**Issue by mctomaszek** [partkeepr/PartKeepr#798]
hi

when i have tried  to find the parts on demo I get error 

An error occurred

Details
==================================
Unknown operator 

Request
==================================
GET https://demo.partkeepr.org/api/parts?_dc=1485415214003

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"Unknown operator "}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.29-1~dotdeb+7.1
auto_start_session: true
maxUploadSize: 12582912
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
autoLoginUsername: admin
autoLoginPassword: admin
motd: <p><b>Welcome to the PartKeepr demo site</b></p>
<p>
Notes:
<ul>
<li>This PartKeepr installation is rebuilt from the GIT sources at every full hour</li>
<li>Rebuild takes about one minute, and you'll receive errors during rebuild</li>
<li>The database is synced from Felicitus' personal database, which might contain german part names or other odd stuff</li>
</ul>
</p>
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

**Comment by mctomaszek** [comment]
how to reproduce:

1. go to fulltext search (system preference)
2. mark option :store location-name
3. save

**Comment by mctomaszek** [comment]
I have noticed also that  fulltext search option (some of the field for example "id ") in version 1.1.0 creating similar issues

**Comment by mctomaszek** [comment]
hello Felicitus 
Could you check if you can reproduce this fault as well please on demo version?

regards

**Comment by JohnEffland** [comment]
I just confirmed it appears on demo version.  For example, with "-A071" entered into the search box, the error described above occurs.  Chrome's debugger shows the query string to the server has the correct quotes around the search string: "%-A071%".

**Comment by mctomaszek** [comment]
if l mark something  in system preferences --fulltext search in "search fields"  ( does mater what) ...it will give later one search box error.  You can not use search box in demo version  till system will be reload at full hour. I have noticed same problem with version 1.1.0.  During simulation this issue in version 1.1.0 I have marked some options in system preferences---fulltext search  and I got error

{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"Unknown operator "}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.15-1+deb.sury.org~xenial+1
auto_start_session: true
maxUploadSize: 15728640
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true


later I have tried unmark all options but search box in partkeepr does not work any more. Probably I have to do re-setup again :( 

![part](https://cloud.githubusercontent.com/assets/13379408/22366041/8567e548-e472-11e6-9b47-a50face760ef.png)

**Comment by mctomaszek** [comment]
I did re-setup.......but search box still is giving error and my system is useless . I don't know how to sort out problem. :(. Please help....

**Comment by felicitus** [comment]
You can try to delete all user preferences in the database table UserPreferences. The issue will be fixed with the next release

**Comment by felicitus** [comment]
Sorry, I meant the table `SystemPreference`.

**Comment by felicitus** [comment]
The issue should now be fixed - can you double check?

**Comment by mctomaszek** [comment]
hi

fulltext search via "id" still is giving error at demo version : 

 An error occurred

Details
==================================
[Syntax Error] line 0, col 83: Error: Expected =, <, <=, <>, >, >=, !=, got 'id'

Request
==================================
GET https://demo.partkeepr.org/api/parts?_dc=1486970423136

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"[Syntax Error] line 0, col 83: Error: Expected =, \u003C, \u003C=, \u003C\u003E, \u003E, \u003E=, !=, got \u0027id\u0027"}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.14-2
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
autoLoginUsername: admin
autoLoginPassword: admin
motd: <p><b>Welcome to the PartKeepr demo site</b></p>
<p>
Notes:
<ul>
<li>This PartKeepr installation is rebuilt from the GIT sources at every full hour</li>
<li>Rebuild takes about one minute, and you'll receive errors during rebuild</li>
<li>The database is synced from Felicitus' personal database, which might contain german part names or other odd stuff</li>
</ul>
</p>
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

**Comment by christianlupus** [comment]
The search itself is working except for the id field.

Regarding the ID fiels see #924 and #992.
