### ISSUE TITLE
Problem connecting to existing PartKeepr database - unknown database type enum requested

### ISSUE THREAD

**Issue by Gasman2014** [partkeepr/PartKeepr#807]
I have a working Partkeepr 1.1.0 installation. I have now managed to upgrade to 1.2 and have confirmed basic functionality incl Octopart integration - the reason for the upgrade.

I have followed the instructions for copying my `data/` directory and `parameters.php` file over from the 1.1 to the 1.2 install. I have then run setup again. If I then select the MySql database of parts from my 1.1 install, it connects but then I get the following error whilst 'setting up database schema' 

![screen shot 2017-02-02 at 11 36 24](https://cloud.githubusercontent.com/assets/8401593/22548204/4844e0ce-e93d-11e6-9b3c-5fcbebf4a063.png)

Apparently this is a recognised error as discussed here https://wildlyinaccurate.com/doctrine-2-resolving-unknown-database-type-enum-requested/
with a suggested solution.

I do not have the skills to implement this in your code myself so would appreciate any advice!

**Comment by felicitus** [comment]
PartKeepr doesn't use `ENUM`, so this error is very strange. Do you probably have other software installed in the same database?

For further analysis, I'd need a database dump which contains the database structure only. You can create one either by using `mysqldump -d <databasename> -u <yourusername> -p` or use `phpMyAdmin` to export all tables without the data.

**Comment by Gasman2014** [comment]
It was some Pma_#### tables from phpMyadmin that were causing the problem. Now just need to figure out how to get rid of them.

John

**Comment by Gasman2014** [comment]
Errant 'PMA' tables had been created in the database from phpMyAdmin. When removed, database imported without issue and now working fine.
