### ISSUE TITLE
lost attachments with upgrade

### ISSUE THREAD

**Issue by lookme2** [partkeepr/PartKeepr#808]
I just up graded from 1.1 to 1.2.  All the attached links are broken.  So no thumbnail and no data sheets.  I use the URL field and copy from Digi-Key.  

It still shows the paper clip and under attachments they are still listed but do not work.

Frankie

**Comment by felicitus** [comment]
Please provide all details as per [CONTRIBUTING.md](https://github.com/partkeepr/PartKeepr/blob/master/CONTRIBUTING.md), especially if and how to reproduce on the demo system.

**Comment by felicitus** [comment]
Can you right-click and select "Open i new tab" on the broken attachment thumbnail? Also, do you receive errors in your app/logs/partkeepr.log ?

**Comment by lookme2** [comment]
Sorry I have not gotten back to you.  

If I right-click and Open in a new tab I get 404 File not found.

I have attached the partkeepr log file below

[partkeepr.log.zip](https://github.com/partkeepr/PartKeepr/files/755137/partkeepr.log.zip)

**Comment by felicitus** [comment]
@Gasman2014 Please provide all details as per [CONTRIBUTING.md](https://github.com/partkeepr/PartKeepr/blob/master/CONTRIBUTING.md), in your case, from which to which version you migrated

**Comment by felicitus** [comment]
Also, please report if you re-ran setup after upgrading. Setup should copy the old files to the new location, which is configured by the parameter `partkeepr.filesystem.data_directory` in the parameters.php file. The mappings for all subdirectories can be viewed in `app/config/config_filesystem.yml`

**Comment by Gasman2014** [comment]
I did a clean git install and overwrote the previous version as I ran into some permission problems but it was a 1.3 version from around July/August. I ran setup and it imported the database with no problems except this.

The `app/config/config_filesystem.yml` file is empty. Perhaps I can restore the links if I can reconstruct this file?

 Obviously can't reproduce this on demo system.

**Comment by Gasman2014** [comment]
Sorry - made a mistake app/config/config_filesystem.yml is NOT empty.

**Comment by felicitus** [comment]
So can you check if the files of the type which isn't working are in the directory configured in `app/config/config_filesystem.yml`?

**Comment by Gasman2014** [comment]
I had an older version of PartKeepr (which I moved aside to PK_old) and have. The diff between the old and new is unhelpful:
```

39c39
< $container->setParameter('partkeepr.cronjob.check', true);
---
> $container->setParameter('partkeepr.cronjob.check', false);
52d51
< $container->setParameter('partkeepr.patreon.statusuri', 'https://www.partkeepr.org/patreon.json');

```

**Comment by felicitus** [comment]
when you copied PartKeepr, did you copy the data/ folder within PartKeepr to the new location prior running setup?

**Comment by Gasman2014** [comment]
No, should I have? That wasn't in the instructions as far as I can see...
https://wiki.partkeepr.org/wiki/Running_PartKeepr_from_GIT

**Comment by felicitus** [comment]
Yes, you should have. The GIT instructions assume that you run PartKeepr within the same directory when you upgrade. In your case, you upgraded from 1.3 to GIT. It's logical, PartKeepr stores all attachments in data/, so if you move your old installation, PartKeepr (unfortunately) can't magically guess where the old attachments are stored.

**Comment by Gasman2014** [comment]
Thanks for the tip - I just restored /data from a backup and it is now fine. Phew! Sorry for the hassle and thanks again for the help.
BW

**Comment by felicitus** [comment]
You're welcome, I'm glad it works now :) I think it must be somehow documented that attachments aren't stored in the database

**Comment by Gasman2014** [comment]
Thank you - I hadn't realised that the documents were outside of the database and that the data directory needed to be preserved between updates. 

BW

John Pateman
