### ISSUE TITLE
cronjob stopped to work

### ISSUE THREAD

**Issue by mctomaszek** [partkeepr/PartKeepr#809]
Im getting error like that.....

after run cron job

/usr/bin/php /var/www/html/partkeepr-1.2.0/app/console partkeepr:cron:synctips 

 [Symfony\Component\Debug\Exception\ContextErrorException]  
  Warning: Invalid argument supplied for foreach()           
                                                             

partkeepr:cron:synctips [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by felicitus** [comment]
The tips database is currently not available. Additionally you're running the wrong cronjob - you should run
 
```php app/console partkeepr:cron:run```

**Comment by mctomaszek** [comment]
I'm running also 
/usr/bin/php /var/www/html/partkeepr-1.2.0/app/console partkeepr:cron:run

but I'm still getting error about synctips

**Comment by mctomaszek** [comment]
it just happen tonight before everything was okay

**Comment by felicitus** [comment]
You can ignore it for now, it's a server-side problem. Will try to fix ASAP

**Comment by felicitus** [comment]
The issue should now be fixed

**Comment by G-Pereira** [comment]
It isn't fixed. Any ideas? How can I help?
