### ISSUE TITLE
https of wiki is broken

### ISSUE THREAD

**Issue by prolineserver** [partkeepr/PartKeepr#810]
The encrypted version of the wiki is not acessible, and redirects to a Wordpress "PartKeepr Developer Blog" breaking links, for example from https://partkeepr.org/support/

**Comment by FinalHopee** [comment]
The link you provided worked for me, but as you said Wiki page did bring Wordpress page.
[https://wiki.partkeepr.org/](https://wiki.partkeepr.org/)

**Comment by felicitus** [comment]
Human error, please try again now ;)
