### ISSUE TITLE
Footprint attachement fails 

### ISSUE THREAD

**Issue by f1rmb** [partkeepr/PartKeepr#815]
Hi,

# System Information

* PartKeepr Version: fresh github sources.
* Reproducible on the demo system: YES

[PartKeepr_footprint_issue.txt](https://github.com/partkeepr/PartKeepr/files/769131/PartKeepr_footprint_issue.txt)

# How to reproduce

After uploading a document to a footprint, clicking on "Save Footprint" pops up an error window (see attachment). This happens for newly created footprints and already created ones.

Cheers.
---
Daniel

**Comment by mindsolve** [comment]
@f1rmb If I understood your description correctly, this seems to be fixed since the commit 12aa3b638c5502d42a6480ff81be3d68aee42f98.
At least this is not happening anymore in the demo.

**Comment by f1rmb** [comment]
Yes, it's working as intended since then.

Cheers.
---
73 de Daniel, F1RMB


Le 11 juil. 2017 22:23, "Felix E." <notifications@github.com> a écrit :

@f1rmb <https://github.com/f1rmb> If I understood your description
correctly, this seems to be fixed since the commit 12aa3b6
<https://github.com/partkeepr/PartKeepr/commit/12aa3b638c5502d42a6480ff81be3d68aee42f98>
.
At least this is not happening anymore in the demo.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/partkeepr/PartKeepr/issues/815#issuecomment-314560599>,
or mute the thread
