### ISSUE TITLE
Octopart is not configured

### ISSUE THREAD

**Issue by andriotiskon** [partkeepr/PartKeepr#816]
I had Partkeepr on Ubuntu for some time. I am very satisfied and i upgrade it to v 1.2.0 the day before yesterday.
I want to use the Octopart integration so i created an account at Octopart to get the API key for my application. I put my key to the /app/config/parameters.php.dist like below
              $container->setParameter('partkeepr.octopart.apikey', 'xxxxxxxx');
and then i run the setup process without any errors and everything else seems to work
I get a message that "Octopart is not configured" when i click at the Octopart button at the add new part tab.

Do i have to configure something else for this to work?

**Comment by felicitus** [comment]
`/app/config/parameters.php.dist` is the wrong file. You need to place your key in `/app/config/parameters.php`.

**Comment by andriotiskon** [comment]
Thanks you very much!
