### ISSUE TITLE
Not able to copy&paste errors messages during setup

### ISSUE THREAD

**Issue by yschroeder** [partkeepr/PartKeepr#819]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version: 1.2.0
* Reproducible on the demo system: Yes.
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): No.

# How to reproduce

* When getting an error message during setup, the text in the pop-up box is not selectable making it hard to debug problems (read: google error messages).

**Comment by yschroeder** [comment]
Maybe even more important: You cannot copy&paste the cronjob configuration at the end of the installation.

**Comment by progman32** [comment]
This now also includes the commands to create the DB, making the "show commands to create the database" rather useless.
