### ISSUE TITLE
PartKeeper upgrade fails with MySQL 5.7

### ISSUE THREAD

**Issue by yschroeder** [partkeepr/PartKeepr#823]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version: 0.1.9 to 1.2.0
* Reproducible on the demo system: No.
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): None.

# How to reproduce

Updating the database during setup (`ALTER TABLE ...`) fails with MySQL 5.7 as it changes some default behaviour.
This can be fixed by changing MySQL 5.7 configuration as described here:
https://mattstauffer.co/blog/how-to-disable-mysql-strict-mode-on-laravel-forge-ubuntu

However, I think that PartKeeper should work with the default settings of MySQL 5.7.

**Comment by baradhili** [comment]
Needs checking that upgrades still have problems.. this is an old bug

**Comment by christianlupus** [comment]
This might be related to #842
