### ISSUE TITLE
Meta-Parts not working correctly in Project Reports

### ISSUE THREAD

**Issue by rattlelv** [partkeepr/PartKeepr#824]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version: 1.2.0
* Reproducible on the demo system: Yes
* [JavaScript errors]: "grid.parentRecord is undefined" @ main2.js:22180:13

Please attach files, for example, screenshots to describe your issue. If you can, create a screenshot ob View->System Information.

# How to reproduce

In the demo system:
1) Go to Project Reports, select a project containing a meta-part: "ASM-2 PSU". Select quantity: 1
2) Create Report. In the project report list, select meta-part ("test", last line). Expand meta-part
3) Select a part with sufficient stock ("2N7000", total items in stock: 89), tick "Use", click "apply parts"
4) Meta-part is changed into 2N7000 with quantity "89", which is the total stock of part and not the required quantity (1)
5) click "Remove parts from stock"
6) select part "2N7000" in Part Manager, in Part Details click "Stock History". Most recent record shows "-89" but it should have been -1

So far, no JS errors.
Now, repeat steps 1-3. The JS error "TypeError: grid.parentRecord is undefined" pops up as soon as "use" checkbox is selected, and Apply Part button remains disabled until F5 refresh of browser

**Comment by felicitus** [comment]
I have most likely fixed the issue, can you double-check on the demo system in an hour to verify that the issue is gone? I wasn't able to reproduce it there.

**Comment by felicitus** [comment]
One minor drawback: The already assigned number of parts isn't displayed anymore (5 / 10 for example). However, I feel that this is better than having wrong calculations and being unable to perform meta part assignments.

The upstream bug is here: https://www.sencha.com/forum/showthread.php?342847-Large-Grid-w-Buffered-Renderer-grid-getView()-refresh()-bug

Unfortunately we can't afford an ExtJS support license, so we've to hope that they'll fix it…

**Comment by rattlelv** [comment]
Just tried to run a project report with a meta-part, and it is now 
possible to "Apply Parts", that bit seems to work now. However, when 
pressing the "Remove parts from stock" button, I get a Server 500 error 
on "massRemoveStock". Part removal works for projects without 
meta-parts. I don't know if this is a new bug or directly connected with 
the original. My guess is that this simply was not tested because noone 
could get past the Apply Parts button.

**Comment by mpdanny** [comment]
We were getting the Server 500 error on "massRemoveStock" too, but found that in the Form Data, "projects" is set to null if you load a saved report, whereas if you create a new report using the "Create Report" button, it works fine.
