### ISSUE TITLE
memory_limit can't be parsed in php7.1 if it contains a k, m or g

### ISSUE THREAD

**Issue by Gotos** [partkeepr/PartKeepr#825]
# System Information

* PartKeepr Version: Tested on commit 17bcd332.

# How to reproduce

Using PHP 7.1 set memory_limit to 128M or 1G or similar in php.ini. Start the setup. Setup gets stuck at "Testing for correct PHP settings" - even if "success" is set to true like in the screenshot.

![partkeepr](https://cloud.githubusercontent.com/assets/991937/23166232/1c168f04-f840-11e6-9ffe-04ff631b383c.png)

**Comment by baradhili** [comment]
Need to test that this occurs in 1.4.0

**Comment by christianlupus** [comment]
This should have been closed by [this commit](https://github.com/partkeepr/PartKeepr/commit/81809e68b275d23e79026cb07d7772eeb8c79386) already.
