### ISSUE TITLE
Internal Id not shown after add

### ISSUE THREAD

**Issue by GavinAndrews** [partkeepr/PartKeepr#828]
When I add a new part I would like to see the internal Id since I write that on the part as I put it in the box.  Please show the InternalId either as you add it or shortly afterwards.

Thanks

**Comment by felicitus** [comment]
The Internal ID cannot be shown when adding a part, as it is unknown until you click "save" and the part has actually been inserted into the database. 

Maybe the detail panel could be opened after a successful save operation?

**Comment by baradhili** [comment]
wont' fix
