### ISSUE TITLE
host name mismatch on certificate when trying to access https://partkeepr.org/tips.json

### ISSUE THREAD

**Issue by gyansantokhi** [partkeepr/PartKeepr#837]
# System Information

* PartKeepr Version: 1.2.0
* Reproducible on the demo system: No.
* JavaScript errors: none 

After solving my troubles with the partkeepr run cronjob, I still get a partkeepr:cron:synctips related error when logging in.

![screen shot 2017-03-20 at 09 46 06](https://cloud.githubusercontent.com/assets/11832986/24093015/1a75a924-0d52-11e7-8b88-20661490ac9d.png)

Running the job manually gives the following error:

![screen shot 2017-03-20 at 09 44 59](https://cloud.githubusercontent.com/assets/11832986/24092983/edd06422-0d51-11e7-9c53-010c046473e8.png)

Digging around the source code it seems this error is generated when trying to access [https://partkeepr.org/tips.json] or [https://partkeepr.org/tips/]. Accessing these links in safari leads to a notification of host name mismatch on the certificate. Seeing that it says demo.partkeepr.org it makes sense why it isn't reproducible on the demo system.

![screen shot 2017-03-20 at 09 42 09](https://cloud.githubusercontent.com/assets/11832986/24092952/c6734656-0d51-11e7-870e-3f7fbcceecca.png)

Can anyone confirm the problem lies in the certificate?

**Comment by felicitus** [comment]
Thanks for the info, the certificate is now fixed.
