### ISSUE TITLE
Partkeepr base URI

### ISSUE THREAD

**Issue by turdusmerula** [partkeepr/PartKeepr#839]
Is partkeepr relocatable in a sub URI?
I would like to run it in my server at `http://<domain>/partkeepr` but the setup fails to pass checks.

Here is my virtualhost for apache, I have redmine running at `http://<domain>/redmine` and would like to put partkeepr beside it:
```
<VirtualHost *:443>

        DocumentRoot /var/www
        <Directory /var/www/redmine>
                RailsBaseURI /redmine
                PassengerResolveSymlinksInDocumentRoot on
        </Directory>


        AcceptPathInfo on
        php_value date.timezone France/Paris

        Alias /partkeepr/setup "/var/www/partkeepr/setup"
        <Directory "/var/www/partkeepr/setup/">
            Options Indexes FollowSymLinks
            AllowOverride All
            Order allow,deny
            Allow from all
        </Directory>

        Alias /partkeepr "/var/www/partkeepr/web"
        <Directory "/var/www/partkeepr/web/">
            Options Indexes FollowSymLinks
            AllowOverride All
            Order allow,deny
            Allow from all
        </Directory>



        SSLEngine on
        SSLCertificateFile /etc/apache2/server.crt
        SSLCertificateKeyFile /etc/apache2/server.key
</VirtualHost>

```

Do you have an idea how to do this?

Thank you :)

**Comment by felicitus** [comment]
I never setup partkeepr with an alias but the setup directory needs to be below /web. Is alias recursive? If yes your shouldn't need the setup alias section. 

Am 30. März 2017 16:56:39 MESZ schrieb Sebastien Besombes <notifications@github.com>:
>Is partkeepr relocatable in a sub URI?
>I would like to run it in my server at `http://<domain>/partkeepr` but
>the setup fails to pass checks.
>
>Here is my virtualhost for apache, I have redmine running at
>`http://<domain>/redmine` and would like to put partkeepr beside it:
>```
><VirtualHost *:443>
>
>        DocumentRoot /var/www
>        <Directory /var/www/redmine>
>                RailsBaseURI /redmine
>                PassengerResolveSymlinksInDocumentRoot on
>        </Directory>
>
>
>        AcceptPathInfo on
>        php_value date.timezone France/Paris
>
>        Alias /partkeepr/setup "/var/www/partkeepr/setup"
>        <Directory "/var/www/partkeepr/setup/">
>            Options Indexes FollowSymLinks
>            AllowOverride All
>            Order allow,deny
>            Allow from all
>        </Directory>
>
>        Alias /partkeepr "/var/www/partkeepr/web"
>        <Directory "/var/www/partkeepr/web/">
>            Options Indexes FollowSymLinks
>            AllowOverride All
>            Order allow,deny
>            Allow from all
>        </Directory>
>
>
>
>        SSLEngine on
>        SSLCertificateFile /etc/apache2/server.crt
>        SSLCertificateKeyFile /etc/apache2/server.key
></VirtualHost>
>
>```
>
>Do you have an idea how to do this?
>
>Thank you :)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/partkeepr/PartKeepr/issues/839

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by turdusmerula** [comment]
I abandoned this solution, I don't quite understand why i does not work
