### ISSUE TITLE
php-7.0 timezone setting 

### ISSUE THREAD

**Issue by prolineserver** [partkeepr/PartKeepr#844]
# System Information

* PartKeepr Version: 1.2
* Reproducible on the demo system: unknown.
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): no
* PHP 7.0.15-0ubuntu0.16.04.4 

# How to reproduce
* During installation, partkeepr checks several system requirements, among others the timezone setting in the php.ini-file (line 428ff in app/SymfonyRequirements.php). However, php-7.0 by default doesn't use the setting anymore:
Snippet from /usr/share/doc/php7.0-common/README.Debian.gz:
[...]
Timezone data from system timezone database
----------------------------------------------------------------------

  Debian PHP has been patched to use the system wide timezone database
  from the tzdata package, making sure any updates there are
  automatically used by PHP as well.

**Comment by felicitus** [comment]
I'm aware of that debian does indeed patch it to use the timezone database. As Symfony does this check and not PartKeepr, there's not much I can do about it. You should be able to configure date.timezone in the php.ini file anyways to satisfy the requirements.

**Comment by baradhili** [comment]
Closing this as a non-issue
