### ISSUE TITLE
Not able to login with the same credentials from a different machine

### ISSUE THREAD

**Issue by classbproject** [partkeepr/PartKeepr#854]
I have installed PartKeepr on an EC2 instance. I can access the installation from the computer that I used for the installation. However, when I try to login from a different computer using the same credentials, I get a `Username or password is invalid' message. If you'd like I can create another user for you, confirm that I can login and then share that with you and you can try logging in. 

* PartKeepr Version: 1.2.0
* Reproducible on the demo system: Don't know
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): None

[UPDATE]
I tried logging from the machine that I could login from and now I see this: 

```
Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET http://52.35.141.160/api/part_categories/getExtJSRootNode?_dc=1495266681448

Response Status Code
==================================
401

Response
==================================


Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.15-0ubuntu0.16.04.4
auto_start_session: true
maxUploadSize: 536870912
isOctoPartAvailable: false
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.WSSEAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

```

**Comment by felicitus** [comment]
Try HTTP Basic Auth instead of WSSE.

**Comment by classbproject** [comment]
Yep that works. Thanks.
