### ISSUE TITLE
Partkeepr-installation with PHP-7.1.4

### ISSUE THREAD

**Issue by Schurick** [partkeepr/PartKeepr#856]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version: 1.2.0
* Reproducible on the demo system: No.
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): -

Hi, I try to install Partkeepr on XAMPP (Win7, 64bit) with **PHP 7.14**. 

Following error message occur:

![image](https://cloud.githubusercontent.com/assets/6098876/26393240/83952994-4069-11e7-9bc2-792ced88cddf.png)

Please help.

**Comment by felicitus** [comment]
Can you give me the value of the `realpath_cache_size` found on your [phpinfo.php](https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page) page?

**Comment by Schurick** [comment]
Local and Master value are both 4096K, respectively.

**Comment by felicitus** [comment]
You could try to set a value of `4194304` instead of `4096K` - maybe that works? I currently don't have PHP 7.14 to test with

**Comment by Schurick** [comment]
Have changed the value, error-list is smaller now:

![image](https://cloud.githubusercontent.com/assets/6098876/26400478/540ea1ba-4081-11e7-882f-5f2f8b40d52d.png)

**Comment by felicitus** [comment]
You most likely need to adjust the `memory_limit` value as well. Seems that PHP 7.1 has changed some behavior. Sorry for the inconvenience

**Comment by felicitus** [comment]
Oh, what you also could try: Set the `error_reporting` in your php.ini file to `E_ALL ^ E_NOTICE`

**Comment by Schurick** [comment]
Ok, I changed the memory_limit from 128M to 134217728. Now the setup continues, with warnings: 
![image](https://cloud.githubusercontent.com/assets/6098876/26401032/232b29bc-4084-11e7-8e4d-0f10dd51fdae.png)
Isn't opcache the PHP accelerator? Or do I have to install APCu to get more performance?

What does the error_reporting-change do?

**Comment by felicitus** [comment]
No, `opcache` caches PHP statements and `APCu` caches data. I don't know if `APCu` exists for XAMPP.

The `error_reporting` changes the way PHP reports errors, in your case, it supresses PHP notices such as the non-well-formed integer value. The value I've given you makes sure that PHP reports everything except notices.

**Comment by Schurick** [comment]
Setup was successfull. There is [APCu](http://pecl.php.net/package/APCu/5.1.8/windows) for XAMPP, intalled it too, works great. Thanks a lot.

**Comment by Schurick** [comment]
But loading a csv-file into the importer does not work anymore:

![image](https://cloud.githubusercontent.com/assets/6098876/26407092/6df2581a-409a-11e7-8ea7-45400721dcd1.png)

**Comment by felicitus** [comment]
Looks like a filesystem issue, similar to https://github.com/partkeepr/PartKeepr/issues/853

**Comment by felicitus** [comment]
Please be aware that running PartKeepr on Windows is not supported, as I do not have any knowledge of using XAMPP and the quirks of the windows filesystem

**Comment by Schurick** [comment]
I changed the permission of the partkeepr-folder to "everyone", but have still this error. What else can I do?

**Comment by felicitus** [comment]
I don't know

**Comment by felicitus** [comment]
The root cause is that the unlink() PHP function receives a "Resource temporarily unavailable" error from your operating system. I can't tell why this is happening.

**Comment by felicitus** [comment]
unlink() does delete a file. I hope this helps somehow.

**Comment by Schurick** [comment]
Can I change the temp-location?

**Comment by Schurick** [comment]
I did not find the reason, but commenting out the unlink()-function helped in my case.

I think it´s a PHP-issue, cause it worked with PHP-5.6.
