### ISSUE TITLE
Default column presets for grids

### ISSUE THREAD

**Issue by Drachenkaetzchen** [partkeepr/PartKeepr#863]
Right now, column presets revert to their defaults configured in the code. It would be good if the desired column preset would be stored in the user preferences.

**Comment by kjetilpp** [comment]
Any update to this`?

**Comment by Drachenkaetzchen** [comment]
No, it's done when it's done

**Comment by baradhili** [comment]
duplicate of #1100  closing this one as 1100 has more details

**Comment by Satnet** [comment]
> No, it's done when it's done

5 years later and I'm waiting patiently. :)
