### ISSUE TITLE
PostgreSQL config isn't applied when re-running setup 

### ISSUE THREAD

**Issue by felicitus** [partkeepr/PartKeepr#867]

**Comment by diodenschein** [comment]
Is it a bad Idea to copy them from config.php to app/config/parameters.php by hand?

**Comment by felicitus** [comment]
What is the config.php? PartKeepr doesn't use such a file

**Comment by diodenschein** [comment]
There is such a file in my Partkeepr base directory with correct database settings. 
It seems it was in your repro 12 days ago too. 
I think I screwed up somewhere updating while running it from git. 
I'll try again later.

**Comment by felicitus** [comment]
Maybe the config.php file is from an old installation. PartKeepr since 0.89 uses Symfony2 and as such there's no config.php file anymore. That file has nothing to do with this issue, if you encounter any issue please open a new issue, thanks :)
