### ISSUE TITLE
New install fails on Warming up Cache after 120 seconds

### ISSUE THREAD

**Issue by hlantz** [partkeepr/PartKeepr#870]
# System Information

* VM running Ubuntu 16.04.2 LTS with PHP Version 7.0.15-0ubuntu0.16.04.4, Apache2, MySQL.  (Brand new VM with nothing else apart from the Partkeepr system requirements installed.)
* PartKeepr Version: 1.2.0
* Reproducible on the demo system: N/A
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): none

# How to reproduce
* When installing Partkeepr, my system stops on "Warming up cache" which fails with "Invalid Response from Server" after exactly 2 minutes each time.  (PHP Max execution time and Apache timeout are both set to 300 seconds, confirmed by phpinfo.)
![cache-error](https://user-images.githubusercontent.com/4787672/26870335-f0b420be-4b6f-11e7-8af5-79901b86f164.png)

* In Chrome Developer Tools under the Network tab, when I double click warmupCache, it takes me to a Symfony warning page as attached.  Perhaps this can help track down the underlying issue here?  (I won't pretend to know what any of this means, I just know it's usually better to include as much info as possible...)
![symfony-error](https://user-images.githubusercontent.com/4787672/26870336-f0b4cf6e-4b6f-11e7-95b5-deab5991b463.png)

* There are no entries in the Apache error log, only a 200 OK message in access.log after the 2 minutes have passed.  (When I double-click the cacheWarmup page directly, I get a 500 error back, still in the access.log,)

* I get this issue regardless of whether I attempt installation from our office network or from a host within the same network as the target host; so this should not be the same as the proxy issue reported in #811.

* Any suggestions on where to look next?

**Comment by felicitus** [comment]
Does your server have access to the internet? Right now, the installer requires internet connectivity, so that might be the problem.

**Comment by felicitus** [comment]
On the other hand, warming up the cache should not require connectivity. You could have a look in `app/logs/` below your PartKeepr installation if there is anything informational there.

I think setup should provide a way to view those logs directly.

**Comment by hlantz** [comment]
Allowing the server access to the Internet fixed the issue on the first try - thanks!
Will the application require Internet access once installed and running?

I pulled some 1000 lines of log app/logs/setup.log from another failed attempt before allowing Internet access - most of them was simply "XXX is deprecated in Symfony 2.8 and will be removed entirely in 3.0", so that's probably something that should be looked into for later versions (let me know if you want me to attach the log files for reference).

But with this - issue solved; thanks for fast response!

**Comment by felicitus** [comment]
It depends - if you want to use OctoPart, you need to allow access to the internet. There's a cronjob which syncronizes the tips, but you can turn it off ( https://github.com/partkeepr/PartKeepr/blob/master/app/config/parameters.php.dist#L245 ) - re-run setup after you did the change

**Comment by hlantz** [comment]
Thanks - I won't be needing Octopart integration, and I don't technically need the tips either.  Thanks for fast feedback!
