### ISSUE TITLE
Nginx + php-fpm times out during cache warmup upgrade to 1.2.0

### ISSUE THREAD

**Issue by kbembedded** [partkeepr/PartKeepr#873]
I have a FreeBSD + Nginx setup for Partkeepr (originally used apache24 before migration from a waayy earlier partkeepr version, I think 0.19?)  Anyway, ran in to some resistance during the setup due to timeouts.  It is a fairly slow system, however with nginx there is another timeout that needs to be modified other than the php timeout.

In the information here: https://wiki.partkeepr.org/wiki/KB00005:Web_Server_Configuration
I suggest adding a line like:
fastcgi_read_timeout 120;  #or greater, depending.  Default is 60 I believe.

No matter what you set the php timeout to, nginx as a frontend will timeout first if the php setting is a larger time.  This also affects Linux systems as well, FYI.

# System Information
FreeBSD 11.0-RELEASE-p9

* PartKeepr Version: 1.2.0 install
* Reproducible on the demo system: Probably not

**Comment by christianlupus** [comment]
I'll change it in the potential new wiki pages.

**Comment by christianlupus** [comment]
The temporary version is visible [here](https://github.com/christianlupus/Test-PK-Pages/wiki/KB00005_Web_Server_Configuration). @kbembedded are you ok with the modifications?

**Comment by kbembedded** [comment]
I'm glad to see this project is moving forward again.

The potential wiki change looks good to me!

**Comment by christianlupus** [comment]
Thanks, I'll keep it then like that.
