### ISSUE TITLE
Update button drawn incorrectly in Edit Part dialog

### ISSUE THREAD

**Issue by twelve12pm** [partkeepr/PartKeepr#875]
System Information:
* PartKeepr Version: PartKeepr-1.2.0
* Debian GNU/Linux 8.8 "Jessie"
* Apache 2.4.10
* PHP 7.0.20-1~dotdeb+8.1
* Doctrine DBAL 2.5.2
* Doctrine ORM 2.5.4
* Firefox 53.0.3 build 20170518000419 on Mac OS X
* Reproducible on the demo system: Maybe; this is an intermittent bug

Problem: The "Update" button is drawn incorrectly in the Edit Part dialog. It is partly obscured by the header row of the table. The "Update" button should be drawn below the field, not above. This is an intermittent bug but it usually occurs when editing a part and manually adding distributor information, usually when adding the 2nd distributor. See the screenshot:

![editpartdialogbug](https://user-images.githubusercontent.com/13225038/27546983-67121a12-5a62-11e7-961b-30ac111c78a9.png)

**Comment by christianlupus** [comment]
I cannot reproduce it in the current demo version. Most probably it was solved in the meantime.
