### ISSUE TITLE
Feature Request:Show full "path" of "Storage Location" in "Parts List"

### ISSUE THREAD

**Issue by hdt551** [partkeepr/PartKeepr#877]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

* PartKeepr Version: v1.2.0
* Reproducible on the demo system: Yes.

in "Storage Locations" I created a tree:
"cabinet-a"/"drawer-1"
then a storage location:
"box-001"

In "Part Manager" I added a part:
"10k resistor"
And selected the above storage location.

This works perfectly, except that in the "Parts List"
the "Storage Location" only shows "box-001"

Using a final location of just "box-001" and not named:
"cabinet-a_drawer-1_box-001" would of course mean "box-001" could be moved to 
"cabinet-a"/"drawer-2" (assuming that had already been created) very easily without having re-create the entire structure.

It would be very helpful if the entire "path" to "box-001"
were visible and of course in any reports as well.

**Comment by twelve12pm** [comment]
I agree. Without "full path" you cannot tell which box-001 contains your part.

**Comment by felicitus** [comment]
I agree as well. Now with the introduction of re-usable column renderers, this could be relatively easily implemented.

**Comment by hdt551** [comment]
Until this feature is added, I wrote a sql query which can be run on the MySQL host and returns most of the information I find useful.  Of importance to me is to order things like capacitors by their size so it is easy find one close I may already have on hand.
----------------------------------------------------------------
select Part.name as 'part_name',
 Part.description as 'part_desc',
 Part.comment,
 StorageLocationCategory.categoryPath as 'container_location',
 StorageLocation.name as 'container_id',
 PartCategory.categoryPath,
 Footprint.name as 'footprint',
 PartParameter.description as 'part_param_desc',
  PartParameter.stringValue,
 PartParameter.name as 'parameter_name',
 PartParameter.value as 'parameter_value',
  SiPrefix.symbol as 'prefix',
 Unit.symbol as 'unit'
  
 from Part
 
 left join PartParameter
 on Part.id = PartParameter.part_id
 
 left join Unit
 on PartParameter.unit_id= Unit.id
 
 left join SiPrefix
 on PartParameter.siPrefix_id=SiPrefix.id
 
 left Join StorageLocation
  on Part.storageLocation_id=StorageLocation.id
  
 left join StorageLocationCategory
 on  StorageLocation.category_id=StorageLocationCategory.id
 
 left join Footprint
 on Part.footprint_id=Footprint.id 
 
 left join PartCategory
 on Part.category_id=PartCategory.id

 order by PartCategory.categoryPath, PartParameter.normalizedValue,PartParameter.name,Part.name

**Comment by hdt551** [comment]
With the addition of column customization in release 1.3, adding a column showing:
storageLocation.category.categoryPath
covers this feature request.
