### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by thebaron23** [partkeepr/PartKeepr#880]
Hello,
After setting up PartKeepr & storage locations, I tried adding a part. While selecting "storage location" and sitting at the "add a part" menu, I get the following popup every few seconds:

Rrequest: GET "MYURL"/api/system_notices?_dc=1499435373077
Response: Undefined

Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET MYURL/api/system_notices?_dc=1499435373077

Response Status Code
==================================
0

Response
==================================
undefined

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.30
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: false
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

This error keeps popping up one after the other non stop.

Thanks for your support!

**Comment by felicitus** [comment]
Please have a look at your webserver logs and your browser's JS console, see http://wiki.partkeepr.org/wiki/How_to_Debug#Frontend_Debugging

**Comment by felicitus** [comment]
No feedback given for an extended period of time, closing the issue.

Feel free to re-open if you have additional information.

**Comment by zhanglongqi** [comment]
Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET https://www.xngy.co/api/system_notices?_dc=1532918565808

Response Status Code
==================================
0

Response
==================================


Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.30-0ubuntu0.16.04.1
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.WSSEAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]
defaultGridPresets: [{"grid":"PartKeepr.BaseGrid","configuration":"[{\"dataIndex\":\"internalPartNumber\",\"text\":\"partNumber\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"stockLevel\",\"text\":\"Qty\",\"hidden\":false,\"width\":50,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"name\",\"text\":\"Name\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]}]"},{"grid":"PartKeepr.ProjectPartGrid","configuration":"[{\"dataIndex\":\"part.internalPartNumber\",\"text\":\"\\u00a0part_num\",\"hidden\":false,\"width\":100,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"quantity\",\"text\":\"qty\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"overage\",\"text\":\"overage\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"overageType\",\"text\":\"overage type\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"part.name\",\"text\":\"man._part._number\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"remarks\",\"text\":\"remarks\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]}]"},{"grid":"PartKeepr.Components.Project.ProjectReportResultGrid","configuration":"[{\"dataIndex\":\"part.internalPartNumber\",\"text\":\"part_number\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"quantity\",\"text\":\"Qty\",\"hidden\":false,\"width\":100,\"tooltip\":\"\",\"renderers\":[{\"rtype\":\"projectReportQuantity\",\"rendererConfig\":{\"quantityField\":\"quantity\"}}]},{\"dataIndex\":\"\",\"text\":\"Part Name\",\"hidden\":false,\"flex\":2,\"tooltip\":\"\",\"renderers\":[{\"rtype\":\"projectReportMetaPart\",\"rendererConfig\":null}]},{\"dataIndex\":\"part.description\",\"text\":\"Part Description\",\"hidden\":false,\"flex\":2,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"remarks\",\"text\":\"Remarks\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[{\"rtype\":\"projectReportRemarks\",\"rendererConfig\":null}]},{\"dataIndex\":\"part.storageLocation.name\",\"text\":\"Storage Location\",\"hidden\":false,\"width\":100,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"part.stockLevel\",\"text\":\"Available\",\"hidden\":false,\"width\":75,\"tooltip\":\"\",\"renderers\":[{\"rtype\":\"projectReportMetaPartAvailability\",\"rendererConfig\":null}]},{\"dataIndex\":\"missing\",\"text\":\"Order Amount\",\"hidden\":false,\"width\":100,\"tooltip\":\"\",\"renderers\":[{\"rtype\":\"projectReportQuantity\",\"rendererConfig\":{\"quantityField\":\"missing\"}}]}]"}]

**Comment by zhanglongqi** [comment]
Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET https://MYDOMAIN/api/system_notices?_dc=1532918565808

Response Status Code
==================================
0

Response
==================================


Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.30-0ubuntu0.16.04.1
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.WSSEAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]
defaultGridPresets: [{"grid":"PartKeepr.BaseGrid","configuration":"[{\"dataIndex\":\"internalPartNumber\",\"text\":\"partNumber\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"stockLevel\",\"text\":\"Qty\",\"hidden\":false,\"width\":50,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"name\",\"text\":\"Name\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]}]"},{"grid":"PartKeepr.ProjectPartGrid","configuration":"[{\"dataIndex\":\"part.internalPartNumber\",\"text\":\"\\u00a0part_num\",\"hidden\":false,\"width\":100,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"quantity\",\"text\":\"qty\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"overage\",\"text\":\"overage\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"overageType\",\"text\":\"overage type\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"part.name\",\"text\":\"man._part._number\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"remarks\",\"text\":\"remarks\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]}]"},{"grid":"PartKeepr.Components.Project.ProjectReportResultGrid","configuration":"[{\"dataIndex\":\"part.internalPartNumber\",\"text\":\"part_number\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"quantity\",\"text\":\"Qty\",\"hidden\":false,\"width\":100,\"tooltip\":\"\",\"renderers\":[{\"rtype\":\"projectReportQuantity\",\"rendererConfig\":{\"quantityField\":\"quantity\"}}]},{\"dataIndex\":\"\",\"text\":\"Part Name\",\"hidden\":false,\"flex\":2,\"tooltip\":\"\",\"renderers\":[{\"rtype\":\"projectReportMetaPart\",\"rendererConfig\":null}]},{\"dataIndex\":\"part.description\",\"text\":\"Part Description\",\"hidden\":false,\"flex\":2,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"remarks\",\"text\":\"Remarks\",\"hidden\":false,\"flex\":1,\"tooltip\":\"\",\"renderers\":[{\"rtype\":\"projectReportRemarks\",\"rendererConfig\":null}]},{\"dataIndex\":\"part.storageLocation.name\",\"text\":\"Storage Location\",\"hidden\":false,\"width\":100,\"tooltip\":\"\",\"renderers\":[]},{\"dataIndex\":\"part.stockLevel\",\"text\":\"Available\",\"hidden\":false,\"width\":75,\"tooltip\":\"\",\"renderers\":[{\"rtype\":\"projectReportMetaPartAvailability\",\"rendererConfig\":null}]},{\"dataIndex\":\"missing\",\"text\":\"Order Amount\",\"hidden\":false,\"width\":100,\"tooltip\":\"\",\"renderers\":[{\"rtype\":\"projectReportQuantity\",\"rendererConfig\":{\"quantityField\":\"missing\"}}]}]"}]
