### ISSUE TITLE
Internal Part Number Ribbon in Project Report

### ISSUE THREAD

**Issue by redjiveV2** [partkeepr/PartKeepr#882]
Hi there,

just wanted to ask a question to the functions of the "Project Report" window. After you chose one of the project options, the project itself opens up at the lower half of the screen.
Is it possible to change one of the ribbons to "Internal Part Number"? 

Thanks for your help!
BR
redjiveV2

**Comment by christianlupus** [comment]
As far as I understand, you want to have the internal part number visible in the big grid.

Hover with the mouse over one of the column headers, click on the small triangle and click on **Colums**->**Customize**.
Right to the cancel button is button to add a column. Click it. On the right select a field and *part*->*internalPartNumber*. Give the column a title like *internal ID*. Click on **Apply** and you should have your column at hand.
