### ISSUE TITLE
Internal Server Error on File Upload - Red Hat Linux Installation

### ISSUE THREAD

**Issue by KevinH35** [partkeepr/PartKeepr#885]
The following error is generated when attempting to import a BOM file into a project:

Dunglas\\ApiBundle\\Exception\\InvalidArgumentException(code: 0): No resource associated to \"\". at /data/www/partkeepr-1.2.0/vendor/dunglas/api-bundle/Api/IriConverter.php:84)"} []

Partkeepr version 1.2.0

System:  Red Hat Linux

Reproducible on Demo - No; File import works on Demo and source data is visible.

Observed Behavior - In Project window, after selecting a file to import into the project, no data from the file is imported into Partkeepr (button executes import but no visible indicator it did anything).  No data appears in Source tab.  Chrome browser debugger shows in an internal server error (error 500). 

Attempted Resolutions:   X-XSS-Protection (Mode-Block) removed; Increased timeout intervals on server

**Comment by KevinH35** [comment]
The application is also generating a fault when attempting to use the filters.  In the Google Chrome debug mode, PHP indicates it can't load the filter plug-in.  It appears the install is missing files and/or file locations, but I am unsure what specific files may be missing or where to find them.

**Comment by felicitus** [comment]
Please double-check on the demo system, there were a few improvements made recently to display verbose errors

**Comment by felicitus** [comment]
Is the problem solved?

**Comment by KevinH35** [comment]
I think the issue is resolved.  Our IT person made some changes to the installation and everything appears to be working correctly.  Thanks for the follow-up
