### ISSUE TITLE
Cronjob could not open input files because cronjobs folder is missing

### ISSUE THREAD

**Issue by yschroeder** [partkeepr/PartKeepr#886]
# System Information

* PartKeepr Version: 1.2.0
* Reproducible on the demo system: No.

# Bug Details
My Partkeepr installation cannot find the cronjob php files. `sudo crontab -e` has the following line:

```
0 0,6,12,18 * * * /usr/bin/php /var/www/PartKeepr/app/console partkeepr:cron:run
```

The job tells me, that different files in `/var/www/PartKeepr/cronjobs` are missing. I've checked and the whole `cronjobs` folder does not exist.

The files are:
* `CreateStatisticSnapshot.php`
* `CheckForUpdates.php`
* `UpdatePartCacheData.php`
* `UpdateTipsOfTheDay.php`

I am not sure since when this problem exists, as due to a misconfiguration cron only recently started to send mails.

What is the problem here? Should the installation have a `cronjobs` folder?

**Comment by felicitus** [comment]
There's no `cronjob` folder. Where exactly does it tell you that `/var/www/PartKeepr/cronjobs` is missing?

**Comment by felicitus** [comment]
Actually there used to be a `cronjob` folder in earlier versions - maybe you still got an old crontab entry in place?

**Comment by yschroeder** [comment]
The output of the running cronjob says:
```
Could not open input file: /var/www/PartKeepr/cronjobs/UpdatePartCacheData.php
```
With different variations of files (see above).

What would be the correct cronjobs line? I guess after the update to 1.2.0 it was not changed to the new cronjob?

**Comment by felicitus** [comment]
```
Could not open input file: /var/www/PartKeepr/cronjobs/UpdatePartCacheData.php
```

That is an old cronjob file. This error is emitted from your cron configuration. The correct line is

```
0 0,6,12,18 * * * /usr/bin/php /var/www/PartKeepr/app/console partkeepr:cron:run
```

as you have written in your initial bug report. Please find the old lines in your cronjob configuration and remove them.

**Comment by yschroeder** [comment]
I found the old cronjobs in `/etc/cron.d`.

The jobs have been a leftover from and old PartKeepr version. Thanks for the help!

**Comment by felicitus** [comment]
You're welcome, I'm glad you found the old configuration ;)
