### ISSUE TITLE
Cron job not running correctly

### ISSUE THREAD

**Issue by dersch81** [partkeepr/PartKeepr#893]
# System Information

* PartKeepr Version: 1.2.0 & 1.3.0

I having an issue with the cron job. Seems there is something broken in the XmlUtils.php

/usr/bin/php /var/www/partkeepr/app/console partkeepr:cron:run
PHP Fatal error:  Class 'DOMDocument' not found in /var/www/partkeepr/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php on line 52

**Comment by felicitus** [comment]
You seem to be missing the PHP XML extension on your CLI version of PHP, since I assume that you have installed PartKeepr successfully. You can check using:

`php -m`

The extensions `dom` and `xml` should be listed there.

**Comment by dersch81** [comment]
Thanks for your quick reply. You where right both extensions were missing. 

So i've installed them sucessfully. Then i got the message of missing APCache module. I fixed it. 
Then i got the message of missing php-ldap. I've installed it. 

Then i got this:

/usr/bin/php /var/www/partkeepr/app/console partkeepr:cron:run


  [Doctrine\DBAL\Exception\DriverException]
  An exception occured in driver: could not find driver



  [Doctrine\DBAL\Driver\PDOException]
  could not find driver



  [PDOException]
  could not find driver


partkeepr:cron:run [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>


It was the missing php-mysql module. 

Now it works fine! Thanks a lot for directing me to the php issue ;)

**Comment by felicitus** [comment]
You're welcome :) May I close the issue?

**Comment by dersch81** [comment]
Only thing open is that i still get the message of the webview "The following cronjobs aren't running" partkeepr:cron:synctips

**Comment by felicitus** [comment]
Can your server connect to the internet? Maybe it has trouble retrieving the tips information.

**Comment by dersch81** [comment]
Sure, it is my webserver with couple of webpages.

**Comment by felicitus** [comment]
Can you check if you can retrieve the tips.json file from your server:

`wget https://partkeepr.org/tips.json`

Another random idea: Maybe you have two PartKeepr installations and the cronjob is updating the wrong one?

Additionally, you can check the `app/logs/partkeepr.log` file while running cronjobs manually. Maybe there is some information present.

If the cronjob runs correctly, the table `CronLogger` receives an entry with the cron name and the last run date. You could check if the entry for the tips cron gets updated.

**Comment by dersch81** [comment]
That's strange. 

i can retrieve the json file via wget. I only have one PartKeepr running and one mysql table.

The cronjob runs via cli without any error and no new entry within the .log file appears (there are just 2 errors from 2 hrs ago) 

The table CronLogger has 2 entries:
2017-09-05 10:28:28
partkeepr:cron:versioncheck

2017-09-05 10:28:28
partkeepr:cron:create-statistic-snapshot

I don't get any idea where the cause could be.

**Comment by felicitus** [comment]
Can you try running `php app/console partkeepr:cron:synctips` ?

**Comment by dersch81** [comment]
Ah some hint:

php /var/www/partkeepr/app/console partkeepr:cron:synctips


  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
  The parameter "partkeepr.tip_of_the_day_list" must be defined.


partkeepr:cron:synctips [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by felicitus** [comment]
I think I found and fixed the issue. Will create a new release later today or tomorrow.

**Comment by dersch81** [comment]
Great that I could help locating some small bug :D 

Thanks a lot for your quick and very nice help! :+1:

**Comment by MichaelDodd** [comment]
I have a similar problem, I think, with 1.3 and a Mac/MAMP installation. I also get warnings of cron jobs not running and when trying to run partkeepr:cron:synctips get the same tip_of_the_day_list must be defined. Looking at the Partkeepr installation directory I probably installed on the 24th October, some time after Felicitus reply on the 5th September, having migrated from a centos install that was running on a server that was costing me a fortune to run 24/7. So, my question: would the fix for this be present in the 1.3 release that I would have downloaded in October?, or should I wait for the next release?

**Comment by christianlupus** [comment]
I assume this is no longer an issue with version 1.4. Thus closing.
