### ISSUE TITLE
search text issue when "id" option is marked

### ISSUE THREAD

**Issue by mctomaszek** [partkeepr/PartKeepr#894]
This issue is appearing on both version 1.2 and 1.3. Very easy to reproduce just you have to mark searching by "id"  (menu full text search) and you will get  error during search

An error occurred

Details
==================================
[Syntax Error] line 0, col 83: Error: Expected =, <, <=, <>, >, >=, !=, got 'id'

Request
==================================
GET https://demo.partkeepr.org/api/parts?_dc=1504712028423

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"[Syntax Error] line 0, col 83: Error: Expected =, \u003C, \u003C=, \u003C\u003E, \u003E, \u003E=, !=, got \u0027id\u0027"}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.19-1
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
autoLoginUsername: admin
autoLoginPassword: admin
motd: <p><b>Welcome to the PartKeepr demo site</b></p>
<p>
Notes:
<ul>
<li>This PartKeepr installation is rebuilt from the GIT sources at every full hour</li>
<li>Rebuild takes about one minute, and you'll receive errors during rebuild</li>
<li>The database is synced from Felicitus' personal database, which might contain german part names or other odd stuff</li>
</ul>
</p>
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]

**Comment by christianlupus** [comment]
See #1027 #992 #798
