### ISSUE TITLE
Project report auto-fill

### ISSUE THREAD

**Issue by RiccardoRics** [partkeepr/PartKeepr#896]
# System Information
* PartKeepr Version: unknow, from hosting plan
* Reproducible on the demo system: No.
* [JavaScript errors] none in console

# How to reproduce
When i do a Project report and click on "Auto-fill Distributors", i get the pop-up showing the action, but then no distributor is set per component.
Also, if i click inside the distributor cell of a component of the project, i don't get any value to choice from.
For each component i used Octopart autofilling for distributor and prices, but perhaps i miss a step.

**Comment by felicitus** [comment]
Hi, the PartKeepr version on the servers have been upgraded. Can you check if it works for you now?

**Comment by RiccardoRics** [comment]
Hi, still not working. Same behaviour.

**Comment by felicitus** [comment]
Please check if the relevant distributors have the "Use this distributor for price calculations in project reports" flag enabled in Edit->Distributors. If they are, there should be a small money bag icon to the right of them.

Also you can check if pricing calculations are used for the parts if you click the "Distributors" tab - there should be an icon as well.

**Comment by RiccardoRics** [comment]
Yup! Thanks for the tips, now is working!
