### ISSUE TITLE
Frontend web server authentication 

### ISSUE THREAD

**Issue by anyonebutme** [partkeepr/PartKeepr#897]
I have partkeepr v1.3.0 setup with HTTPBasic authentication with apache2 running as the frontend web server. If I enable authentication in apache, partkeepr doesn't accept username/password. I tried enabling auto login with username/password thinking that might solve it but that doesn't work either (auto login works fine if I disable the authentication in apache).

I would like the frontend web server to take care of authentication instead of partkeepr. But partkeepr doesn't seem to allow for that.

# System Information
* PartKeepr Version: v1.3.0
* Web Server: Apache2
* System: Ubuntu

**Comment by felicitus** [comment]
When you select HTTPBasic authentication, you don't have to configure your authentication in Apache. PartKeepr handles that for you. Right now, you cannot have other external authentication methods.
