### ISSUE TITLE
Adding a manufacturer column in Parts list fails and causes further corruption

### ISSUE THREAD

**Issue by njrs92** [partkeepr/PartKeepr#898]
When adding a manufacturer column in a custom view in the parts list it fails to display any manufacturer. It then causes display issues when opening a part to edit, as it does not exit cleanly then when opening another part it shows up partially in the corner. Only a refresh fixes the issue.

System: Ubuntu 16.04 and demo site
PartKeepr: 1.3.0
Reproducible on the demo system: Yes
Tested on Chrome and Firefox

![image](https://user-images.githubusercontent.com/28581852/30246087-0701a040-9633-11e7-874e-893798887487.png)

![image](https://user-images.githubusercontent.com/28581852/30246128-7b783fbe-9634-11e7-9cee-ef494b61776c.png)

![image](https://user-images.githubusercontent.com/28581852/30246143-cd6b3fb0-9634-11e7-9334-8da2e4969a50.png)

![image](https://user-images.githubusercontent.com/28581852/30246146-e15546c4-9634-11e7-836f-d012832b4dd4.png)

**Comment by eriwst** [comment]
Same behavior here.

**Comment by ikcalB** [comment]
Same problem here. 

Does someone have a workaround?

**Comment by baradhili** [comment]
linked to #1100
