### ISSUE TITLE
Project report doesn't fill in Distributor Order Number

### ISSUE THREAD

**Issue by spacekookie** [partkeepr/PartKeepr#900]
Creating a project report (and clicking autofill) doesn't also fill in the Distriutor Order Number (only the prices)

# System Information

* PartKeepr Version: 1.2
* Reproducible on the demo system: Not Tested (it's late).

**Comment by christianlupus** [comment]
Can you please try to verify on demo page? I cannot reproduce. If you can, please provide exact steps.
