### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by avenirlabs** [partkeepr/PartKeepr#907]
Hi 

I've installed partkeepr to the folder,

chat.avenirlabs.com, you can safely rewrite all the existing contents of this folder.

I've already tried installing it in this folder, but it gives me following errors upon install:

Timezone CST6CDT must be supported by your installation of PHP

Current install is at the following URL:
http://chat.avenirlabs.com/partkeepr/web/setup/

Can you please check how to resolve this issue

**Comment by felicitus** [comment]
Enter a valid timezone which is supported by PHP:

http://php.net/manual/en/timezones.php

**Comment by christianlupus** [comment]
This is solved. Closing.
