### ISSUE TITLE
Out of Memory - Hosting server

### ISSUE THREAD

**Issue by RiccardoRics** [partkeepr/PartKeepr#908]
Hi there, trying to see some projects i've saved, but i can't due to an error message related to memory issues.

**# System Information**

* PartKeepr Version: (Can't detect)
* Reproducible on the demo system: Not tried, too many variables to insert.
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): 

**# How to reproduce**

1) Access to Partkeepr
2) Click on Edit menu
3) Click on Projects
4) I get the following error response:

An error occurred

Details
==================================
Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2621423 bytes)

Request
==================================
GET https://xxx.hosting.partkeepr.com/api/projects?_dc=1506369672752

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2621423 bytes)"}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.30-0+deb8u1
auto_start_session: true
maxUploadSize: 10485760
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]

**Comment by felicitus** [comment]
I just increased the memory limit, can you try again?

**Comment by RiccardoRics** [comment]
Thanks, just got this back, for both "Projects" and "Projects report" tabs:

Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET https://rics.hosting.partkeepr.com/api/projects?_dc=1506402471649

Response Status Code
==================================
0

Response
==================================
undefined

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.30-0+deb8u1
auto_start_session: true
maxUploadSize: 10485760
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]

**Comment by felicitus** [comment]
The maximum execution time was increased as well, can you check if it works now?

**Comment by RiccardoRics** [comment]
Yep, now is working, although the response time are really slow.

**Comment by RiccardoRics** [comment]
Here it is again, sorry:

Critical Error -> 21:37 GMT+1 (If you want to identify some logs from the server)

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET https://xxx.hosting.partkeepr.com/api/projects?_dc=1506454515639

Response Status Code
==================================
0

Response
==================================
undefined

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.30-0+deb8u1
auto_start_session: true
maxUploadSize: 10485760
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]

**Comment by felicitus** [comment]
I'm sorry for the delay, but the servers are upgraded to PHP7 now. Can you try again to see if the error is now gone? If not, do I have permission to analyze your database to see what's going on?

**Comment by RiccardoRics** [comment]
No problem at all, now seems it is going better.
Thanks!
