### ISSUE TITLE
Project Report Doesn't Display Associated Project Remarks

### ISSUE THREAD

**Issue by KHuffman35** [partkeepr/PartKeepr#909]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information
Linux Mint Version 18.1; PHP version 7.0.22; MySQL Ver 14.14

* PartKeepr Version:   1.3.0
* Reproducible on the demo system: Yes/No. - Yes
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): 

Please attach files, for example, screenshots to describe your issue. If you can, create a screenshot ob View->System Information.

# How to reproduce:  
![screenshot-2017-10-2 partkeepr](https://user-images.githubusercontent.com/23065237/31105544-fdeedb30-a7b2-11e7-93ab-474a36e61094.png)
![screenshot-2017-10-2 partkeepr 1](https://user-images.githubusercontent.com/23065237/31105543-fdecb4a4-a7b2-11e7-883a-7fa53c3442c6.png)
Create a project with information in the remarks section (I use this to store reference designators). Save the project. Run a project report on that project; the remarks are not displayed.

Fill in any steps to reproduce the issue. A good description of an issue would be:

* When I click the button "Add Part" in the "Parts List", then I expect the "Add Part" window to be opened. Instead, I receive an error on the JavaScript console.

A bad description would be:
* Adding parts do not work

**Comment by KHuffman35** [comment]
It also appears the issue applied to Production Remarks and Projects columns in the Project Report generator.  Production remarks entered in the corresponding fields on parts records are not displayed in the Parts Report; Parts Report Project column is also empty.

**Comment by christianlupus** [comment]
@KHuffman35 Can you verify this is still an issue on the current demo page?

**Comment by KHuffman35** [comment]
This issue is resolved.  Honestly it was probably user error.  Once I worked through all of the import issues, I documented the results and posted them on Partkeepr's Google groups.  The directions appear to work as others have successfully used them.  Thank you for following up on this.

Are you managing new bug reports?  I've spent several weeks attempting to install Partkeepr on a Raspberry Pi3.   Appears there's issues with newer versions of PHP, Symfony, and MariaDB?

**Comment by baradhili** [comment]
@KHuffman35  from other tickets.. try using mysql instead of mariadb, seems mariadb version might be confusing the installer..

I'll close this ticket, and if you do a search for install and mariadb here you should find the relevant tickets..

Christian and myself are trying to get the issues into order so that they can be sensibly worked on..

**Comment by KHuffman35** [comment]
Thanks for the information and your work on moving PartKeepr issues forward. 
I'm using mariadb (following Debian Stretch instructions).  The install runs, but I get a database schema out of date error after running setup.  I've attempted to run the force command on the database but get a Symfony warning (does not appear the force executes).
I tried doing the install with both PHP7.3 and 7.1 (same schema error). The only info in PartKeepr log is:
1.4.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 179 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /app/logs/ignore.json\" (from \"http://localhost/setup/\") at /var/www/partkeepr-1.4.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:179, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/partkeepr-1.4.0/app/cache/prod/appProdProjectContainerUrlMatcher.php:3087)"} []

Thoughts and suggestions are appreciated.

**Comment by christianlupus** [comment]
The message *database schema is out of date* at each start of PartKeepr is a clear indication for a version conflict of the used (but in the meantime outdated) Symphony2 framework of PartKeepr and the MariaDB version you have installed (probably 10.2 or later). See #1065 and the duplicates.

On which device/distribution are you running? If you are running on a real machine (no raspberry pi nor on virtualization), may I suggest to use docker? This allows very fine grained selection of the used parts in your setup and encapsulates things nicely.
If you have more questions there, please open a new ticket (so we do not hijack this one).

**Comment by KHuffman35** [comment]
My goal is to run on Pi.  I'll follow your advice and downgrade the MariaDB (or switch to a standard computer).  Thanks for the quick responses.  Your efforts with Partkeepr are greatly appreciated
