### ISSUE TITLE
Right click and click/drag selecting is disabled

### ISSUE THREAD

**Issue by schneidersoft** [partkeepr/PartKeepr#911]
It should be possible to select (highlight) the contents of data fields like manufacturer part number etc. If A user has used partkeepr to find a capacitor he/she will want to copy the part number footprint etc into say KiCad. Without copy/paste this means manual error prone typing.

As a bare minimum the text contents of message and error dialogs should be highlight-able. That way users can google the errors they get.

**Comment by felicitus** [comment]
Can you clarify which fields you mean (screenshot is sufficient)?

**Comment by schneidersoft** [comment]
![2017-10-05-150021](https://user-images.githubusercontent.com/7611333/31234391-55499d5c-a9de-11e7-9fc6-d5614bcb017b.png)

In general any time user data is displayed it would help to have it selectable. For highly interactive user interface items like tables this might not work well. Because those items are drag&drop capable. But for things like the part details it should be possible.

**Comment by felicitus** [comment]
Yes, I agree - the table should be somehow selectable

**Comment by schneidersoft** [comment]
Merge with #841
