### ISSUE TITLE
Unable to load the projects list

### ISSUE THREAD

**Issue by RiccardoRics** [partkeepr/PartKeepr#919]
**#Comment**
Hi there, here i'm again.
I'm trying to open the "Edit project" tab, i get the page loaded but then, on projects list loading, i get a "Critical error" message.

**#System Information**

Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET https://xxx.hosting.partkeepr.com/api/projects?_dc=1509083177670

Response Status Code
==================================
500

Response
==================================

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.30-0+deb8u1
auto_start_session: true
maxUploadSize: 10485760
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]

**#JS console warnings**
unreachable code after return statement[Ulteriori informazioni]  extjs.js:22:366125
unreachable code after return statement[Ulteriori informazioni]  main2.js:5582:12
unreachable code after return statement[Ulteriori informazioni]  main2.js:31089:91
unreachable code after return statement[Ulteriori informazioni]  main2.js:31349:91
unreachable code after return statement[Ulteriori informazioni]  main2.js:5582:12

**# How to reproduce**
1) Access Partkeepr.
2) Click on Edit -> Projects
3) Wait for the projects list to be loaded and then see the "Critical error" alert.

**Comment by felicitus** [comment]
Do I have permission to have a look in your database?

**Comment by RiccardoRics** [comment]
Yes, of course you can.

**Comment by felicitus** [comment]
I was finally able to track this down - in short, a combination of an odd configuration error on the hosting servers and a too low timeout. I was able to speed things up, I hope this works until I can re-factor project loading to be faster.

Can you try in about 2 hours if it works for you?

**Comment by RiccardoRics** [comment]
Still bad reply...


Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET https://rics.hosting.partkeepr.com/api/reports?_dc=1509813348070

Response Status Code
==================================
0

Response
==================================
undefined

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.19-1
auto_start_session: true
maxUploadSize: 10485760
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]
defaultGridPresets: []

**Comment by felicitus** [comment]
In two hours, not now ;)

**Comment by RiccardoRics** [comment]
Sorry, got the opposite like you had to get test feedback before 19:30!
Was focused in SMD solderings :)

**Comment by felicitus** [comment]
I just double checked, loading is still slow but it works on my side. Can you see if it works for you now?

**Comment by RiccardoRics** [comment]
Project list seems to work now.
But then, trying to use the "Project Reports" tool, i got again the critical error message after i set "Qty" 1 to a project and clicked on "Create report".

Here it is (please tell me if I need to open a new issue):

Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET https://xxx.hosting.partkeepr.com/api/grid_presets?_dc=1509911192364

Response Status Code
==================================
0

Response
==================================
undefined

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.19-1
auto_start_session: true
maxUploadSize: 10485760
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]
defaultGridPresets: []

**Comment by felicitus** [comment]
Does it take very long as well, or does it give you the error very short?

**Comment by RiccardoRics** [comment]
Got quite imemdiate the error message, but then i got the parts list too.
Now i tried again on top of the previous asking for another project report: it was slow but at the end i got the parts list without any critical error message.

**Comment by felicitus** [comment]
I will double check this tomorrow. I wasn't satisfied with the project report performance as well, so there might be something still wrong on the hosting systems

**Comment by RiccardoRics** [comment]
Okies, thanks. Let's keep us updated.
I'll try again some features, if something different or new will happen, I'll report of course.

**Comment by felicitus** [comment]
Thank you as well for bringing this to my attention :)

**Comment by felicitus** [comment]
I just realized that the production hosting servers had xdebug turned on, which resulted in very slow responses. I disabled xdebug and the parts list loads now 3 times faster than before, so probably the project reports should now be faster as well. Can you double-check if it works now? (hopefully)

**Comment by felicitus** [comment]
Btw don't worry about the message "cron jobs are not running" - that should go away later today

**Comment by RiccardoRics** [comment]
I've tested it and that's what i got:

- First page load around 3 secs
- Projects tabs needed around 8 secs to load
- Project reports list needed around 8 secs to load more 2 secs for the previous projects reports list
- A 36 parts report needed 13 seconds
- A 44 parts report needed 15 seconds

My download connetion is 20Mbps with 14ms ping.

BTW no more critical error messages. And yep, got about that cron message. ;)

**Comment by felicitus** [comment]
Yes, the numbers you gave are very similar to what I could measure here. Unfortunately further improvements are only possible once I can migrate PartKeepr to use a later version of the Symfony2 framework, but that will possibly take a while :(

**Comment by RiccardoRics** [comment]
Well, that would be a welcomed improvement, but not necessarely urgent ;)

**Comment by RiccardoRics** [comment]
Hi Felicia, got again the same error with memory report:

An error occurred

Details
==================================
Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 10489856 bytes)

Request
==================================
GET https://xxxx.hosting.partkeepr.com/api/projects?_dc=1521198525876

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 10489856 bytes)"}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.27-0+deb9u1
auto_start_session: true
maxUploadSize: 10485760
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]
defaultGridPresets: []

**Comment by Drachenkaetzchen** [comment]
for some reason the memory_limit had reverted to 128MB (probably an upgrade of the server), I have increased it again, it should work now

**Comment by RiccardoRics** [comment]
Thanks, and yes, now it's back to work flawlessy.
