### ISSUE TITLE
Can´t access the column-editor

### ISSUE THREAD

**Issue by Schurick** [partkeepr/PartKeepr#920]
# System Information
PartKeepr Version: 1.3.0
Reproducible on the demo system: No.

**I upgraded to** 
![image](https://user-images.githubusercontent.com/6098876/32380309-144f1e9c-c0b0-11e7-8029-1189206577a3.png)
**...and ran successfully through the setup, but don´t see the new column-editor:**
![image](https://user-images.githubusercontent.com/6098876/32380411-48f18e1e-c0b0-11e7-8527-c8ae8fdad952.png)

**Comment by felicitus** [comment]
Make sure to delete your browser's cache. You can also try another browser to ensure it's not cached somehow.

**Comment by Schurick** [comment]
**Here my system-config:**
![image](https://user-images.githubusercontent.com/6098876/32380670-ec73c00c-c0b0-11e7-97f8-0759327d347f.png)

**Comment by Schurick** [comment]
Wow, you are fast :) 

...yes, failure-source was the browser´s cache, thanks a lot.
