### ISSUE TITLE
How do you delete a saved report?

### ISSUE THREAD

**Issue by tracklogic** [partkeepr/PartKeepr#923]
Hi

Once I've saved a report, how do I delete it? I can't see an option for it anywhere

Thanks in advance

Matt

**Comment by felicitus** [comment]
There currently isn't one, we're working on it.

**Comment by tracklogic** [comment]
Thanks - i guess for now i can just do some SQL magic and dump the entries from table?

**Comment by christianlupus** [comment]
It is possible to remove a report by now. Closing.
