### ISSUE TITLE
Unable to apply changes in the FrontEnd

### ISSUE THREAD

**Issue by BorjaLeon15** [partkeepr/PartKeepr#925]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

Hello,

I´m trying to edit the FrontEnd, for example in the Auth.
To do that I edit the LoginDialog.js in web/bundles/partkeeprfrontend/js/Components/Auth
Like this:

this.loginField = Ext.ComponentMgr.create({
            xtype: 'textfield',
            value: "",
            fieldLabel: "**Usuario**",
            anchor: '100%'
        });

I save changes and the FrontEnd is still with the default settings.
I know maybe I have to restart with Phing or something like that, but I cant find information about how to do it.

Any solutions?

**Comment by felicitus** [comment]
See http://wiki.partkeepr.org/wiki/Developers/Getting_Started

**Comment by BorjaLeon15** [comment]
Wops, I guess I was in the incorrect files. Thank you very much and very good work btw.

**Comment by felicitus** [comment]
Thanks :) If you have further questions, you can also ask in our IRC channel :)

**Comment by BorjaLeon15** [comment]
Sorry for reopening the topic,
Now I can edit the frontend well and I see the changes in the app_dev.
The problem is that the changes in the prod dont appear.
 I have used the command phing regenerate-environment and the result is this:

 Buildfile: /XXX/XXXX/XXX/XXXX/build.xml
 [property] Loading /XX/XX/XX/XX/build.properties

PartKeepr > regenerate-environment:


BUILD FINISHED

Total time: 1.0348 second

**Comment by christianlupus** [comment]
@BorjaLeon15 Is this issue still valid or did you get it sorted out otherwise?

**Comment by baradhili** [comment]
closed issue resolved
