### ISSUE TITLE
Long wait time for response

### ISSUE THREAD

**Issue by Schurick** [partkeepr/PartKeepr#926]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version: 1.3.0
* Reproducible on the demo system: No.
![image](https://user-images.githubusercontent.com/6098876/32949392-ea3aed0e-cba2-11e7-8c8f-0a4cc2fc28d4.png)

Since I upgraded to 1.3.0 I must always wait for over 1 minute for the login-window:

![image](https://user-images.githubusercontent.com/6098876/32949458-31589b8c-cba3-11e7-890b-a91b7dee282c.png)

partkeepr.log:

![image](https://user-images.githubusercontent.com/6098876/32949477-42a0ab00-cba3-11e7-9f56-6de804e09324.png)

It seems that it comes from the ldap-functionality. How can I disable it?

Here my config of the ldap-parameters:

![image](https://user-images.githubusercontent.com/6098876/32950032-2ac6c21a-cba5-11e7-9ae0-20c07edfdc5d.png)

**Comment by Schurick** [comment]
I commented out following rows:

AppKernel.php:
![image](https://user-images.githubusercontent.com/6098876/33026338-83a7dc08-ce10-11e7-97e2-575cc1b03a38.png)


app/config/security.yml
![image](https://user-images.githubusercontent.com/6098876/33025901-785fe3a0-ce0f-11e7-9865-0966352bb623.png)

app/config/config.yml
![image](https://user-images.githubusercontent.com/6098876/33026027-cf903378-ce0f-11e7-8309-514b895b459b.png)

app/config/config_setup_test.yml
![image](https://user-images.githubusercontent.com/6098876/33025963-9eb649e0-ce0f-11e7-8af2-493f77d7ff1d.png)


Get following error-message then during installation:
![image](https://user-images.githubusercontent.com/6098876/33026133-0cda61cc-ce10-11e7-990e-4fd82630687b.png)

**Comment by Schurick** [comment]
Had to delete "fr3d_ldapbundle" in following row in app/config/security.yml:
![image](https://user-images.githubusercontent.com/6098876/33027560-bb8239f4-ce13-11e7-9659-67a8b3788aed.png)

Now I can go through the setup without errors and there is no ldap-message in the log-file anymore, but the response-time is still over one minute :/

**Comment by Schurick** [comment]
By the way: The setup-window opens very quick, so it is not a server-issue. Same problem in Chrome and IE.

**Comment by felicitus** [comment]
Hard to tell what the issue is. I doubt it is related to LDAP since when there's no LDAP server, a connection refused on pot 389 will occur. 

Can you see if there is anything in app/logs/partkeepr.log? Do you have a firewall enabled?

**Comment by Schurick** [comment]
- I exclude LDAP too, cause it is disabled now and the long response time still exists. 
- Firewall is inactive.
- SELinux is in permissive-mode
- partkeepr.log is empty.
- I reinstalled version 1.3.0 -> still the same issue
- I installed version 1.2.0 parallel -> no problem, response comes very fast

**Comment by felicitus** [comment]
I assume that your server somehow cannot retrieve `https://www.partkeepr.org/patreon.json` and times out at some point. As a workaround, you could retrieve `https://www.partkeepr.org/patreon.json` manually and place it somewhere on that server (for exampe, within the PartKeepr web directory), and then point to the URL by specifying the new one in your parameters.php:

```
$container->setParameter('partkeepr.patreon.statusuri', 'http://localhost/PartKeepr/patreon.json');
```

**Comment by Schurick** [comment]
Worked!!! ...thanks a lot.

Seems that it could not retrieve petreon.json because I´m behind a proxy.

**Comment by hwriesni** [comment]
/* $aParameters["patreonStatus"] = $this->get("partkeepr_systemservice")->getPatreonStatus(); */

Comment this line in the src/PartKeepr/FrontendBundle/Controller/IndexController.php file....
B.R.
Hr.Bert
