### ISSUE TITLE
Project Report Page is not loading

### ISSUE THREAD

**Issue by kinnans** [partkeepr/PartKeepr#929]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version:
* Reproducible on the demo system: Yes/No.
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): 

Please attach files, for example, screenshots to describe your issue. If you can, create a screenshot ob View->System Information.

# How to reproduce

Fill in any steps to reproduce the issue. A good description of an issue would be:

* When I click the button "Add Part" in the "Parts List", then I expect the "Add Part" window to be opened. Instead, I receive an error on the JavaScript console.

A bad description would be:
* Adding parts do not work

**Comment by felicitus** [comment]
Please add an actual bug report. Your bug report only contains the template, which is not filled out. Closing; please open a new issue with an actual bug report.
