### ISSUE TITLE
Project Report Page is not loading 

### ISSUE THREAD

**Issue by kinnans** [partkeepr/PartKeepr#930]
Showing Critical Error Meaasge.
![project report page error messageerror](https://user-images.githubusercontent.com/33956204/33208810-11e94d50-d139-11e7-8ed0-c5427c237403.png)
 When login this message is showing
![partkeepr login](https://user-images.githubusercontent.com/33956204/33208828-21e27db2-d139-11e7-849f-e0c6aa020e92.png)

PFA

**Comment by felicitus** [comment]
Probably your timeout is set too low, please increase the PHP configuration `max_execution_time` to a higher value

**Comment by kinnans** [comment]
how to increase that same

**Comment by felicitus** [comment]
In your php.ini file

**Comment by kinnans** [comment]
our part keepr version is 1.2 and syatem information is this
![infod](https://user-images.githubusercontent.com/33956204/33208970-d568e3da-d139-11e7-9add-f4e9a58ce79b.png)

**Comment by kinnans** [comment]
hi felicitus,
I am only a user and don't no so much about the system/server configuration. Can you tell things in simply.Is there any issues or bug in PartkeeprV1.3. Can we upgrade to that version for these kind of bug. have you see the login message picture. it having message of cron jobs not running.

**Comment by felicitus** [comment]
Well unfortunately my time does not permit to help with server configuration issues. You'd need to consult your server administrator to perform these configurations for you.

You can try to upgrade, there were some performance improvements in 1.3 but I can't guarantee that it will work.

**Comment by kinnans** [comment]
is there anything we need to change in our system information

**Comment by felicitus** [comment]
As mentioned previously, you need to increase `max_execution_time` in your `php.ini` file. The location of the file depends on your distribution, so you should ask supporters of your specific distribution on how to change that value.

**Comment by kinnans** [comment]
up to which value we should have to increase

**Comment by felicitus** [comment]
For a start, I'd recommend to double the value.

**Comment by kinnans** [comment]
ok.For that cron job issue what is the solution

**Comment by felicitus** [comment]
Have you configured the cronjob? If so, how does the crontab line look?

**Comment by kinnans** [comment]
@Drachenkaetzchen 
We have changed the partkeepr version to V1.3. and Changed the execution time from 300 to 6000. But it facing the same critical error message.

**Comment by kinnans** [comment]
@Drachenkaetzchen @abrock @dunglas @henrikh @matthijskooijman 
Can you suggest any solution for solving this.

**Comment by X3msnake** [comment]
Did you restart the server after changing the php.ini?

What are you using for server?

**Comment by Drachenkaetzchen** [comment]
I believe this issue is related to #914 which is solved. Version 1.4.0 is due today, please check after upgrade if the issue persists and re-open the issue if necessary.
