### ISSUE TITLE
Number of Partkeepr files on the server

### ISSUE THREAD

**Issue by mitjakukovec** [partkeepr/PartKeepr#932]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version: 1.3.0
* Reproducible on the demo system: NA

# How to reproduce

When I extracted the partkeepr archive file *partkeepr-1.3.0.zip* to the server, I did count for 42.502 files in the extracted folder. It was a little surprise to me that after I was finished with a setup procedure, the number of files increased to the astonishing 133.000+.

I have to comply with some of the restrictions assigned by my web hosting provider, and one of them is number of nodes (number of all files and directories) that are allowed on the server. With this substantial increase of files just for partkeepr setup (there are no parts in the database yet), I am using almost half of the nodes allowed.

Why there is so many files after the setup procedure? Are there files that are just left overs from the setup I could delete? Are there any temporary files that could be deleted without any damage?

Thank you

**Comment by mitjakukovec** [comment]
I was able to figure out, these file number increase comes from the application cache folder (*./partkeepr-1.3.0/app/cache*).

Am I correct to assume that whatever there is in the *./partkeepr-1.3.0/app/cache/setup* and *./partkeepr-1.3.0/app/cache/setup_test* folders is safe to delete?

Thank you

**Comment by felicitus** [comment]
Yes, you can remove the setup and setup_test caches. However, they will be re-created when you re-run setup. 

This is related to #928

**Comment by Drachenkaetzchen** [comment]
During testing if and how PartKeepr can be migrated to Symfony3, I also realized that the amount of files in the cache directories is now significantly smaller than with Symfony2.

Examples:

Directory | Num Files SF2 | Num Files SF3
------------ | ------------- | -------------
app/cache/dev | 68778 | 7323
app/cache/prod | 29737 | 2545

I do not have numbers for the `setup` and `setup_test` directories, but they should be similar to the `app/cache/dev` directory. Overall, I expect a 90% decrease in required files, which also helps with small filesystems where the inode count is limited.

**Comment by christianlupus** [comment]
@mitjakukovec I think, your question was answered by Drachenkaetzchen, right? I will therefore close the issue here.
