### ISSUE TITLE
showing webserver configuration error

### ISSUE THREAD

**Issue by Athulpsidharthan** [partkeepr/PartKeepr#933]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version:
* Reproducible on the demo system: Yes/No.
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): 

Please attach files, for example, screenshots to describe your issue. If you can, create a screenshot ob View->System Information.

# How to reproduce

Fill in any steps to reproduce the issue. A good description of an issue would be:

* When I click the button "Add Part" in the "Parts List", then I expect the "Add Part" window to be opened. Instead, I receive an error on the JavaScript console.

A bad description would be:
* Adding parts do not work

**Comment by Athulpsidharthan** [comment]
while running setup, testing web-server rewrite capability, it shows webserver configuration issue. The reference llink is not found useful

**Comment by christianlupus** [comment]
@Athulpsidharthan Please be much more specific. What have you done? What error message is reported?
Additionally please use the latest commit/release. Is the problem still reproducible?

**Comment by baradhili** [comment]
Closing, user setup error
