### ISSUE TITLE
Partkeepr Ubuntu 17. Install issues

### ISSUE THREAD

**Issue by Imgg55** [partkeepr/PartKeepr#935]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version: Latest and greatest 
* Reproducible on the demo system: Yes/No.
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): I can't seem to find any of the proper steps for the new Ubuntu. None of the old guides seem to get me through even the first check phase

Please attach files, for example, screenshots to describe your issue. If you can, create a screenshot ob View->System Information.

# How to reproduce

Fill in any steps to reproduce the issue. A good description of an issue would be:

All the different walkthrough guides just not giving proper commands to download with version

**Comment by felicitus** [comment]
I'm sorry but I have to close that issue. Please read https://musescore.org/de/developers-handbook/how-write-good-bug-report-step-step-instructions

**Comment by Imgg55** [comment]
I figured it would get closed but I just have no luck with getting this running. I literally rebuilt a laptop just for this program to use at work with no luck at all getting it to start. Is it easier to down grade my OS for this or can you point me in the right direction?



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
