### ISSUE TITLE
Can't insert parts with parameters with unit (OctoPart)

### ISSUE THREAD

**Issue by Dragonyme** [partkeepr/PartKeepr#937]
Hi, when I try to insert part with OctoPart and it contains part parameters with units (like capacitance : 100 **u**F) I've a "Critical error : The server returned a response which we were not able to interpret."

# System Information

* PartKeepr Version: GIT
* Reproducible on the demo system: Yes.

# How to reproduce

* Juste add this part : C3225X5R0J107M250AC with OctoPart then clic save. Tadaaaaahhh

# Full report : 
Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
POST https://demo.partkeepr.org/api/parts?_dc=1513966027905

[object Object]

Response Status Code
==================================
0

Response
==================================
undefined

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.19-1
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
autoLoginUsername: admin
autoLoginPassword: admin
motd: <p><b>Welcome to the PartKeepr demo site</b></p>
<p>
Notes:
<ul>
<li>This PartKeepr installation is rebuilt from the GIT sources at every full hour</li>
<li>Rebuild takes about one minute, and you'll receive errors during rebuild</li>
<li>The database is synced from Felicitus' personal database, which might contain german part names or other odd stuff</li>
</ul>
</p>
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]
defaultGridPresets: []

**Comment by christianlupus** [comment]
In the meantime this seems to be solved. I tried it on the demo page and it works (except that the Digikey distributor must not be duplicated, but that another issue).
