### ISSUE TITLE
An Exception was thrown while handling: Internal Server Error

### ISSUE THREAD

**Issue by mattalt** [partkeepr/PartKeepr#939]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

On version 1.3.0 I´m getting the following error after installing the app on XAMPP

An Exception was thrown while handling: Internal Server Error

**Comment by Drachenkaetzchen** [comment]
Please provide all details as per [CONTRIBUTING.md](https://github.com/partkeepr/PartKeepr/blob/master/CONTRIBUTING.md), especially if and how to reproduce on the demo system.

**Comment by mattalt** [comment]
I´ve installed everything, and when I entered 127.0.0.1/partkeepr-1.3.0/web I get the error

I´m using XAMPP Control Panel 3.2.2 PHP 5.6.32

**Comment by Drachenkaetzchen** [comment]
Log file contents?

**Comment by Drachenkaetzchen** [comment]
Have you ran setup?

**Comment by mattalt** [comment]
where can i find it?

**Comment by mattalt** [comment]
Yes, I´ve run setup and everything was ok

**Comment by Drachenkaetzchen** [comment]
It's described in the CONTRIBUTING.md file, see above

**Comment by mattalt** [comment]
now I tried to re run setup and I´m getting Invalid response  from the server
