### ISSUE TITLE
[installer] non-standard database port does not update

### ISSUE THREAD

**Issue by ikcalB** [partkeepr/PartKeepr#942]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version: v1.3.0
* Reproducible on the demo system: No. (no access to installer)

# How to reproduce

* While running the installer: when changing the port of the database connection (first enable the checkbox, then change the value - either by up/down or manual input) the port value does not actually update  
(confirmed by logs of other DB instances running at the default ports.)

**Comment by christianlupus** [comment]
@ikcalB Is this still an open issue? I think it was fixed. Can you verify with the latest release?

**Comment by ikcalB** [comment]
@christianlupus have no time to test ATM - as my patch is merged, I can only assume this issue is resolved (it sure did resolve it for me, back than)

If further testing is desired, pls contact me directly.

**Comment by christianlupus** [comment]
Thank you
