### ISSUE TITLE
Exception: Not Found after upgrade from 0.1.9 to 1.3

### ISSUE THREAD

**Issue by es-ka** [partkeepr/PartKeepr#949]
# System Information

* PartKeepr Version: 1.3
* Reproducible on the demo system: No.
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): No.
* PHP 5.6.33 / MySQL 5.5.59 / Apache 2.4.10 on Debian 8 Jessie
* Apache error logs: no entries concerning partkeepr
* app/logs/partkeepr.log: a lot of errors like this:

[2018-02-12 00:47:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /js/compiled/extjs.js" (from "https://myhost/partkeepr/web/")" at /srv/www/intranet/htdocs/partkeepr/app/cache/prod/classes.php line 2107 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /js/compiled/extjs.js\" (from \"https://myhost/partkeepr/web/\") at /srv/www/intranet/htdocs/partkeepr/app/cache/prod/classes.php:2107, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /srv/www/intranet/htdocs/partkeepr/app/cache/prod/appProdProjectContainerUrlMatcher.php:3037)"} []

# How to reproduce

* Upgrade from 0.1.9 to 1.3 without errors.
* https://myhost/partkeepr/web/ shows only a blank page
* some of the css/js files are missing ("An Exception was thrown while handling: Not Found"):

"/partkeepr/web/css/ec39aa1.css"
"/partkeepr/web/images/245ec67.ico"
"/partkeepr/web/js/compiled/extjs.js"
"/partkeepr/web/js/compiled/main.js"
"/partkeepr/web/js/compiled/models.js"
"/partkeepr/web/js/compiled/main2.js"

I guess something went silently wrong during upgrade...

**Comment by Drachenkaetzchen** [comment]
First of all, sorry for the late reply.

I'm not sure what the cause of your problem is, but can you try to see if you have a file called `/srv/www/intranet/htdocs/partkeepr/js/compiled/extjs.js` on your system?

If not, probably the resource compilation went wrong. In that case, you could try to run the following command '''as your webserver user''':

```
cd /srv/www/intranet/htdocs/partkeepr
php app/console assetic:dump  --env=prod
```

The output should now tell you which files are created, in my case, I have the file listed:

```
$ php app/console assetic:dump  --env=prod
Dumping all prod assets.
Debug mode is off.

19:43:03 [file+] /home/felicitus/public_html/PartKeepr-clean/app/../web/css/ec39aa1.css
19:43:03 [file+] /home/felicitus/public_html/PartKeepr-clean/app/../web/images/245ec67.ico
19:43:03 [file+] /home/felicitus/public_html/PartKeepr-clean/app/../web/js/compiled/extjs.js
19:43:03 [file+] /home/felicitus/public_html/PartKeepr-clean/app/../web/js/compiled/extjs.js
19:43:03 [file+] /home/felicitus/public_html/PartKeepr-clean/app/../web/js/compiled/main.js
19:43:03 [file+] /home/felicitus/public_html/PartKeepr-clean/app/../web/js/compiled/models.js
19:43:03 [file+] /home/felicitus/public_html/PartKeepr-clean/app/../web/js/compiled/main2.js
19:43:03 [file+] /home/felicitus/public_html/PartKeepr-clean/app/../web/css/b4ab7d1.css
19:43:03 [file+] /home/felicitus/public_html/PartKeepr-clean/app/../web/js/compiled/mobile_extjs.js
19:43:03 [file+] /home/felicitus/public_html/PartKeepr-clean/app/../web/js/compiled/mobile_extjs.js
19:43:03 [file+] /home/felicitus/public_html/PartKeepr-clean/app/../web/js/compiled/mobile_main.js
19:43:03 [file+] /home/felicitus/public_html/PartKeepr-clean/app/../web/js/compiled/mobile_models.js
19:43:03 [file+] /home/felicitus/public_html/PartKeepr-clean/app/../web/js/compiled/mobile_app.js
```

**Comment by es-ka** [comment]
There is no file `/srv/www/intranet/htdocs/partkeepr/js/compiled/extjs.js`, not even a directory `js`.
I found a dir `/web/js/` but it doesn't contain a dir `compiled`:
```
$ ls -l web/js/
drwxr-sr-x 3 vuser3 www-data 4096 Nov 14 23:06 packages
```

Output of `php app/console assetic:dump  --env=prod` is:

```
Dumping all prod assets.
Debug mode is off.

20:24:18 [file+] /srv/www/intranet/htdocs/partkeepr/app/../web/css/ec39aa1.css
                                                                                 
  [RuntimeException]                                                             
  The source file "/srv/www/intranet/htdocs/partkeepr/app/../  
  web/bundles/partkeeprfrontend/css/PartKeepr.css" does not exist.
```
```
$ ls -l web/bundles/
drwxr-sr-x 2 vuser3 www-data 4096 Jan  9 00:14 doctrinereflection
```

**Comment by Drachenkaetzchen** [comment]
That's very odd, but I have a suspicion: Can you tell me from which URL you've called the PartKeepr setup? Maybe you've used the one from 0.1.9 by accident. The correct URL would be, in your case, `https://myhost/partkeepr/web/setup/`, should look like this and should ask for an authentication key.

![image](https://user-images.githubusercontent.com/162974/39399891-7df598b6-4b26-11e8-9e38-e20b3e24a788.png)

**Comment by Drachenkaetzchen** [comment]
Hmm hard to tell what's wrong on your side. Never had a case like this, and without error messages it makes the whole thing much more strange...

You could try to see if there's anything in your app/logs/setup.log and app/logs/setup_test.log

**Comment by es-ka** [comment]
Well the logs are really big, but I don't see any errors, only debug messages:
[setup.log](https://werkraum.freiraumzittau.de/temp/setup.log)
[setup_test.log](https://werkraum.freiraumzittau.de/temp/setup_test.log)

**Comment by Drachenkaetzchen** [comment]
A few more hints:

If you run `php app/console assets:install --env=prod` it should install things into `web/bundles`. After that, you should be able to run the `assetic:dump` command again. 

Also often distributions mess up the apache configuration, so that PHP errors don't end up in the usual places. You can verify this by creating a `test.php` file with some invalid PHP:

´´´
<?php
doerror();
```

If everything is configured correctly, PHP should now log an error in the apache.

**Comment by es-ka** [comment]
`[OK] All assets were successfully installed.`
`assetic:dump` works now and login to Partkeepr was successful :-)

Thank you very much!

**Comment by Drachenkaetzchen** [comment]
Perfect :) The root cause is still puzzling me, but at least it works now!

**Comment by es-ka** [comment]
Upgrading step by step might be the better way instead of jumping from 0.1.9 to 1.3 ...

**Comment by Drachenkaetzchen** [comment]
Hmm maybe there were some leftover files from 0.1.9 which caused the issue?

You could just unzip 1.3 into a new directory, copy the old files from the data/ directory and point setup to the old database.

**Comment by es-ka** [comment]
I will give that a try tomorrow.
