### ISSUE TITLE
Not able to start partkeepr 1.3.0

### ISSUE THREAD

**Issue by QuakeString** [partkeepr/PartKeepr#950]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version:1.3.0
* Reproducible on the demo system: Yes/No. yes
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): 
screenshot attached.
http://pasteall.org/pic/index.php?id=127968
http://pasteall.org/pic/index.php?id=127971
http://pasteall.org/pic/index.php?id=127972
http://pasteall.org/pic/index.php?id=127973

**Comment by progman32** [comment]
That rings a bell... in my case, a hard refresh fixed it. Maybe try that?

**Comment by QuakeString** [comment]
sorry, "hard refresh" mean ?

**Comment by progman32** [comment]
Ah, sorry. It means clearing the browser cache. The specifics depend on your browser. https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/

**Comment by Drachenkaetzchen** [comment]
No feedback given for an extended period of time, closing the issue.

Feel free to re-open if you have additional information.
