### ISSUE TITLE
Missing files/folders when using nginx

### ISSUE THREAD

**Issue by Windoofs** [partkeepr/PartKeepr#956]
Hi and thank you for developing and maintaining PartKeepr!
The installation and creating a nice sorted inventory was easy and only with one problem:
After every login I get an Critical Error: 
```
Critical Error

Details

The server returned a response which we were not able to interpret.
Request

GET https://parts.mydomain.de/api/manufacturers?_dc=1520777315128
Response Status Code

0
Response

Server Configuration

doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.33-0+deb8u1
auto_start_session: true
maxUploadSize: 104857600000
isOctoPartAvailable: false
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true`
```
I cant detamin one part of the software that is not working, but the error is quite annoying.
Mayby someone can share his nginx conf for testing.
The nginx log says that files/folders are missing.
[nginx.log](https://github.com/partkeepr/PartKeepr/files/1800551/nginx.log)
[nginx.conf.txt](https://github.com/partkeepr/PartKeepr/files/1800552/nginx.conf.txt)
[fastcgi.conf.txt](https://github.com/partkeepr/PartKeepr/files/1800553/fastcgi.conf.txt)

**Comment by Drachenkaetzchen** [comment]
See http://wiki.partkeepr.org/wiki/KB00005:Web_Server_Configuration
