### ISSUE TITLE
Install PartKeepr in RHEL

### ISSUE THREAD

**Issue by ahernanr** [partkeepr/PartKeepr#957]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version: Any version
* Reproducible on the demo system: No.
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): 

Hello, I want to know if I can install PartKeepr in RHEL. The exactly release where I want to install this software is: 
Red Hat Enterprise Linux Server release 6.9 (Santiago)

Thanks in advance. 

Regards,
Antonio.

**Comment by Drachenkaetzchen** [comment]
I don't see a rason why it wouldnt work.
