### ISSUE TITLE
ERRORS(2) /PartKeepr.PartBundle.Entity.Part/

### ISSUE THREAD

**Issue by nehu92** [partkeepr/PartKeepr#958]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)
 i have download the .zip and installed in my Centos 7 server.
* PartKeepr Version: 1.3.0

the instalation was easy and no problems occurs, but when i try to import a CSV file, two errors show up.

"/PartKeepr.PartBundle.Entity.Part/name            The Field is required, but is not configured"
"/PartKeepr.PartBundle.Entity.Part/category       The Field is required, but is not configured"

and this dont allow to check any item in the "Mapping" list

![screenshot from 2018-03-21 12-07-49](https://user-images.githubusercontent.com/11857536/37718471-8285ff4e-2d01-11e8-84ee-64ea60128de0.png)

**Comment by Drachenkaetzchen** [comment]
You can't check the checkboxes. You have to configure each item. Also please try to reproduce on the demo system.

**Comment by nehu92** [comment]
ok, i get that. but why the errors? anyone know how to solved that. i have tu create the entity by hand?

**Comment by Drachenkaetzchen** [comment]
because you need to configure name and storage location, either fixed or create a mapping from the import file.

**Comment by nehu92** [comment]
thanks it was just me that my brain isnt working as it should

**Comment by Drachenkaetzchen** [comment]
I'm glad it worked out :) Yes the import is very generic and confusing at first, but I haven't had time to create a proper documentation yet :(

**Comment by nehu92** [comment]
but once you put hand to work and you touch everything it becames very intuitive. Great Work!
