### ISSUE TITLE
Partskeeper doesn't work with reverse proxy into subdirectory

### ISSUE THREAD

**Issue by thenetimp** [partkeepr/PartKeepr#961]
We want to host parts keeper at /partskeepr of our website so we can keep all other similar applications under one SSL certificate.  (wiki, bug tracker etc).  To do this I have multiple docker containers one for each application, they get aliased to their perspective directories via nginx reverse proxy.  I have successfully used this docker container https://hub.docker.com/r/mhubig/partkeepr/ to install partskeepr and run the setup script without the reverse proxy but when if I point the reverse proxy to the container and try to run setup and get a No Route Found for "POST //setup.php/setup/webserverTest" .  Is there anyway to correct this so that I can use this the way I want. 

You can pull our docker structure from here.
https://github.com/TokyoHackerspace/website_docker

 Also, please turn on select and copy on errors, so I can copy and paste errors to you instead of having to type them out manually.

**Comment by thenetimp** [comment]
According to the 3rd party docker image that I provided a link (https://hub.docker.com/r/mhubig/partkeepr/~/dockerfile/)  the version is 1.3.0 which looks to be the latest release.

Using Chrome on MacOS I can not select text from any of the modal dialog boxes.

<img width="1280" alt="image1" src="https://user-images.githubusercontent.com/438087/39084221-a6aea33a-45ac-11e8-8a27-22c767a187d4.png">

<img width="1280" alt="image2" src="https://user-images.githubusercontent.com/438087/39084222-a92877bc-45ac-11e8-9009-67e0456d6c8a.png">

<img width="1280" alt="image3" src="https://user-images.githubusercontent.com/438087/39084225-b95ae520-45ac-11e8-99d5-da07359da720.png">

 know it's PartsKeepr, but I did not create the first link that I provided, that was a 3rd party who created the docker image, therefore you're correcting the wrong person on how to spell the name ;-)

**Comment by Drachenkaetzchen** [comment]
Oh nevermind, I wasn't fully awake yet. Yes, there's a `setup.php` file but it should not be called directly.

The usual way to setup PartKeepr is to call the web/setup/ directory (where I recommend that web/ is the webserver root), which then should not call `web/setup.php/setup/webserverTest` but rather `web/setup/webserverTest`. 

Unfortunately, my knowledge regarding nginx is somewhere between very limited to non-existent :( In the apache2 world, all you have to do is to enable `mod_rewrite` and the provided `.htaccess` file does the translation from e.g. `setup/webserverTest` to `setup.php/setup/webserverTest`.

In the wiki, there's a contributed nginx config which should to the same as the `.htaccess` file: https://wiki.partkeepr.org/wiki/KB00005:Web_Server_Configuration#nginx - the relevant config entry is most likely:

```
location /setup {
        try_files $uri $uri/ /setup.php?$query_string;
    }
```

What makes me suspicious is that the path gets translated to `//setup.php/setup/webserverTest` - could it be that nginx doesn't actually use setup.php in that case, but rather let `app.php` handle it? Do you have a way to check the nginx logs?

**Comment by Drachenkaetzchen** [comment]
Okay, I have to say sorry again - in fact, `setup.php` is actually called. Haven't much touched the setup script for years now - I should really double check instead of citing from memory ^^ So I guess the only problem you have to fix is that not `//setup.php/setup/webserverTest` is called, but `/setup.php/setup/webserverTest`.

**Comment by thenetimp** [comment]
I've tried to look through the symfony code, the only place I find any mention of setup.php is in some javascript file and changing that doesn't seem to help.   I've been at this for 6hrs.  If someone wants to use my git repo and try to figure out what the problem is and how I can fix it that'd be appreciative, but I am done putting anymore time into it myself.

**Comment by Drachenkaetzchen** [comment]
Have you tried to change the nginx directive from
```
location /setup {
        try_files $uri $uri/ /setup.php?$query_string;
    }
```

to 

```
location /setup {
        try_files $uri $uri/ setup.php?$query_string;
    }
```

It's just a shot in the dark, as I have no idea of nginx. I'm sorry that I couldn't assist in identifying the issue :(

**Comment by thenetimp** [comment]
nginx is only the reverse proxy server, the actual web server running partkeepr is apache.  My nginx is pretty much nil as well.  You can see what nginx is doing here.

https://github.com/TokyoHackerspace/website_docker/blob/master/ths-rproxy/nginx.conf

**Comment by Drachenkaetzchen** [comment]
Oh I see. Is the current state available on a public URL? I could have a look if you like.

**Comment by thenetimp** [comment]
It is not, but you could build run the docker containers locally with the
2nd url I gave you in the original post.  Then access the code inside the
container running the partkeepr container.  The read me has the only 2
commands you would need to run to get it working locally

**Comment by Drachenkaetzchen** [comment]
I couldn't get docker to run properly. However, just to double-check, I have tested if the issue could be related to the port, but it works fine running on a port.

However, doing a quick google for "nginx proxy double slash" quite many results come up, especially this one: http://nginx.2469901.n2.nabble.com/proxy-pass-generates-double-slash-td7598349.html

I'd say your nginx location directive is just wrong. Instead of `location /parts {` it should be `location /parts/ {`.

**Comment by thenetimp** [comment]
ding ding ding ding ding ... we have a winner...

I didn't even think to search for nginx double slash.  That fixes the problem.

**Comment by Drachenkaetzchen** [comment]
Well, it only occurred to me like 5 minutes prior my last comment ;)

The only thing which "concerns" me a bit is that the docker container uses PartKeepr 1.3, which is quite old - I recommend to run PartKeepr from GIT whenever possible, mainly because the GIT version has so many bugfixes and creating a new release is quite a bit of effort. However, I believe there will be a version 1.4 soon.

**Comment by thenetimp** [comment]
I am basically trying to build something that anyone at the hackerspace can maintain with little to no effort if something should happen to me.  Looking at the GIT it doesn't look like there are any tags other than releases, so even if I went from GIT I wouldn't pull from master I would only pull from a known working tag.  I would worry that if something changed in the install/build process and I wasn't around to fix it we'd be without until I had time to resolve it.  I'll stay at 1.3.0 for now and wait for an update.  Thanks for letting me know about the bug fixes in master though.

**Comment by thenetimp** [comment]
*sigh* . Just when I thought all was good.  For some reason the app.request.baseUrl in the twig template is returning (unknown) to the template which breaks the javascript on the main page.

**Comment by thenetimp** [comment]
This is from the developer console

GET http://tokyohackerspace.local:8900/js/packages/extjs6/build/classic/theme-classic/resources/theme-classic-all.css net::ERR_ABORTED
(index):15 GET http://tokyohackerspace.local:8900/js/packages/extjs6/build/packages/ux/classic/classic/resources/ux-all.css net::ERR_ABORTED
(index):18 GET http://tokyohackerspace.local:8900/css/ec39aa1.css net::ERR_ABORTED
(index):30 GET http://tokyohackerspace.local:8900/js/compiled/extjs.js net::ERR_ABORTED
(index):32 GET http://tokyohackerspace.local:8900/js/compiled/main.js net::ERR_ABORTED
(index):39 GET http://tokyohackerspace.local:8900/js/compiled/models.js net::ERR_ABORTED
(index):41 GET http://tokyohackerspace.local:8900/js/compiled/main2.js net::ERR_ABORTED

**Comment by Drachenkaetzchen** [comment]
Can you post the output of the Apache Environment when you create a phpinfo.php file within web/?

The file's content should be:

```
<?php
phpinfo();
```

**Comment by Drachenkaetzchen** [comment]
I also found a similar question with nginx reverse proxies: 

https://serverfault.com/questions/804298/nginx-reverse-proxy-without-base-url

**Comment by thenetimp** [comment]
I suspect nginx isn't passing something along, but I don't know what.

<img width="869" alt="image4" src="https://user-images.githubusercontent.com/438087/39088741-70bb17a4-45f2-11e8-9f78-55ed2a523659.png">

**Comment by Drachenkaetzchen** [comment]
Well yes, the reason is simple. A baseUri of "" is fine because from the container perspective, PartKeepr is running on the root. From the browser's perspective, PartKeepr is running below /parts.

That's the reason why a `proxy_redirect` directive is needed, which translates from "" to /parts. When using Apache as a reverse proxy, also a ProxyPassReverse directive is needed.

From how I understand the nginx doc regarding `proxy_redirect`, this should do the trick unless I made a typo somewhere:
```
proxy_redirect http://tokyo-hackerspace.local:8900/parts/ http://docker-partskeepr/;
```

**Comment by Drachenkaetzchen** [comment]
I also researched a bit further, there seems to be no simple solution. A probably crude but very simple idea would be to move the container's docroot so that the `web/` directory is found at `http://docker-partskeepr/parts/` or create a symlink.

Another thing I found is that Symfony2 has support for the `X-ORIGINAL-URL` header - you could try to set it in the nginx reverse config. This sounds the most promising solution so far to me.

**Comment by thenetimp** [comment]
*sigh* . Yeah reading up on the asset tag in twig and the javascripts and stylesheets tags lead me to the "there is no simple solution for that".  I will download the source for the container in the morning (er afternoon) and modify based on your suggestion above.

**Comment by Drachenkaetzchen** [comment]
I just checked if `X-ORIGINAL-URL` works, but unfortunately it doesn't :(

**Comment by Drachenkaetzchen** [comment]
Well, I just came to the conclusion that it should be absolutely possible to run PartKeepr behind a scenario like yours. As Symfony2 doesn't natively support it, or I haven't found out how, I will implement a configuration directive in PartKeepr's config to allow that.

That gives me an excuse to push out a new release, would you mind waiting till tomorrow evening (your time)? I think all you would need to do in the docker script is to change the version number of the zip file.

**Comment by thenetimp** [comment]
Sure that's fine, i won't wake up until this evening my time so no worries.
Thanks.

**Comment by Drachenkaetzchen** [comment]
Quick update: I'm still in the process to implement the new base url feature, but I'm currently stuck in symfony2 dependency hell ;) Could take a while, probably a few days…

**Comment by Drachenkaetzchen** [comment]
I now have tested the new features regarding reverse proxying and at least on my setup it works. Haven't gotten around earlier, and I don't know if I can find some time to prepare a new release prior the weekend, but I hope so.

**Comment by thenetimp** [comment]
cool.  I am busy with my day job atm, so I won't be revisiting the hackerspace website until this weekend anyway.

**Comment by Drachenkaetzchen** [comment]
PartKeepr 1.4.0 is now released, feel free to try :)

**Comment by thenetimp** [comment]
Sweet, thanks!  I'll give it a try this week and let you know how it goes.

**Comment by thenetimp** [comment]
Just trying this out today.  I've installed the system, and added the necessary lines in parameters.php and in config_custom.yml .  I downloaded phing.phar and run it against system.  Then tried to load the system.  I still get a blank page.  If I go into the file

`FrontendBundle/Resources/views/index.html.twig`

and add /parts/ in front of all the asset_urls it loads, but then trying to authenticate I get issues with the call to get the salt. 

```
Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
POST http://www.tokyohackerspace.local:8101/parts/api/users/getSalt

Response Status Code
==================================
0

Response
==================================


Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.1.17
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.WSSEAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]
defaultGridPresets: []
```

**Comment by Drachenkaetzchen** [comment]
Looks like you didnt clear the production cache using phing, but the dev cache. Also can you post the changes to the config files?

**Comment by Drachenkaetzchen** [comment]
Btw the WSSE auth method could also cause problems, can you use HTTP Basic please? WSSE will be faded out soon

**Comment by Drachenkaetzchen** [comment]
It would also be interesting to see what the generated HTML of the index page looks like, can you post it?

**Comment by christianlupus** [comment]
@thenetimp We are closing the open issues at the moment. What is the latest status? Did you get it working by now somehow?

**Comment by thenetimp** [comment]
I didn't get it working.  I abandoned what I was trying to do with it as it was too time-consuming to get it to work.  I'm probably not going to revisit it.

**Comment by christianlupus** [comment]
Just out of curiosity: Did you try to use Apache (for testing purposes) once as a reverse proxy?

**Comment by thenetimp** [comment]
That was two years ago, I barely remember what happened last week.  I couldn't say if I did or didn't.

**Comment by christianlupus** [comment]
As there is a solution with an apache reverse proxy, I will close this issue now. If nginx pops up once later, I hope we will find this thread again. I will try to link in the wiki.
