### ISSUE TITLE
Issue with System

### ISSUE THREAD

**Issue by ghost** [partkeepr/PartKeepr#962]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version: 1.4.0
* Reproducible on the demo system: No.

Hello, when I try any action in PartKeepr, including adding parts or a new category, I get the following:

An error occurred

Details
==================================
Compile Error: require(): Failed opening required '/var/www/html/partkeepr/app/cache/prod/doctrine/orm/Proxies/__CG__PartKeeprPartBundleEntityPartCategory.php' (include_path='.:/usr/share/php')

Request
==================================
POST http://192.168.0.19/partkeepr/web/api/part_categories?_dc=1525540242969

[object Object]

Response Status Code
==================================
500

Response
==================================
{"@context":"\/partkeepr\/web\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"Compile Error: require(): Failed opening required \u0027\/var\/www\/html\/partkeepr\/app\/cache\/prod\/doctrine\/orm\/Proxies\/__CG__PartKeeprPartBundleEntityPartCategory.php\u0027 (include_path=\u0027.:\/usr\/share\/php\u0027)"}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.27-0+deb9u1
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: false
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]
defaultGridPresets: []

**Comment by Drachenkaetzchen** [comment]
Have you re-ran setup for the upgrade? Is there enough disk space available? Does the file exist?

**Comment by jackdickson5390** [comment]
File doesn't exist, there's plenty of disk space. I haven't yet re-ran setup. One thing I did have to do was to disable the warm up cache by commenting it, as found on a Github issue.

**Comment by Drachenkaetzchen** [comment]
> One thing I did have to do was to disable the warm up cache by commenting it, as found on a Github issue.

Well, that's the root cause. If the cache isn't warmed up, then of course the files required for operation won't be there.

**Comment by jackdickson5390** [comment]
Right. The cache warm up was timing out, and the PHP max_execution_time was 120. Shall I add this line back and increase the time further?

**Comment by Drachenkaetzchen** [comment]
Does your setup use a proxy? If no, increasing the timeout might help.

**Comment by jackdickson5390** [comment]
No proxy is used. I'll try increasing the timeout, thanks.
