### ISSUE TITLE
null 'mimetype' while Setting up the default footprints

### ISSUE THREAD

**Issue by CodeLenny** [partkeepr/PartKeepr#963]
# System Information

* PartKeepr Version: 1.4.0
* Database: MariaDB 10.2.14
* PHP: 7
* (Running inside Docker)
* Reproducible on the demo system: Yes/**No**.
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): N/A

# How to reproduce

During setup (1/2), stage "Setting up the default footprints" fails with "Footprint creation error", and produces the following error message:

> An exception occurred while executing 'INSERT INTO FootprintImage (type, filename, originalname, mimetype, size, extension, description, created, footprint_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["footprint", "cb9af118-5550-11e8-8e34-a7bd2bc9ff26", "CBGA-32.png", null, 23365, "png", null, "2018-05-11 15:23:33", 37]:
> 
> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'mimetype' cannot be null

**Comment by Drachenkaetzchen** [comment]
This is because of a bug in the upstream doctrine library we use, see https://github.com/doctrine/doctrine2/issues/6565

Right now, the only recommendation I have is to use an older MariaDB Version. Upgrading to a more recent doctrine version is complicated, as many changes in PartKeepr would need to be done (dependency hell).

**Comment by CodeLenny** [comment]
Thanks for the information!  I've tried:

- mariadb:10.2.6
- mariadb:10.1
- mysql:5.7
- mysql:5.5

All failed with the same error.  (And mysql:8.0.11 didn't like the authentication method.)

Do you have a known working version?  Otherwise, do you know of any other fixes?  Thanks!

**Comment by Drachenkaetzchen** [comment]
Okay that's very odd. I can confirm that PartKeepr runs up to at lesat mysql 5.6.30, so maybe the bug looks similar to the upstream bug, but is actually a different thing? I'll have a look what possible other causes the issue could have

**Comment by Drachenkaetzchen** [comment]
Okay, it seems that mime type detection does not work on your system. We actually use the Symfony2 implementation, which usually handles most cases. As you run docker, maybe there are some things missing, like the mime type database?

**Comment by CodeLenny** [comment]
Thank you, you nailed it on the head!  I was missing `php7-fileinfo`.

I got past "Setup (1/2)", but "Setup (2/2)" failed when "Setting up the admin user":

> "Notice: iconv(): Wrong charset, conversion from \`ASCII' to \`UTF-8/IGNORE' is not allowed

And that error went away after I installed `php7-mbstring` (and `php7-iconv`?)

Thanks, everything is working now!
