### ISSUE TITLE
I have Partkeepr on a Linux guest machine.  Each time I open Partkeepr, I have to reset the IP address.  How do I keep from having to re-enter each time I open?

### ISSUE THREAD

**Issue by Lostdude** [partkeepr/PartKeepr#967]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version:
* Reproducible on the demo system: Yes/No.
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): 

Please attach files, for example, screenshots to describe your issue. If you can, create a screenshot ob View->System Information.

# How to reproduce

Fill in any steps to reproduce the issue. A good description of an issue would be:

* When I click the button "Add Part" in the "Parts List", then I expect the "Add Part" window to be opened. Instead, I receive an error on the JavaScript console.

A bad description would be:
* Adding parts do not work

**Comment by Drachenkaetzchen** [comment]
Once again: Filling in the subject (or title) is NOT enough! Fill out the template provided for you with all the details requested in the template (marked as red area).

![image](https://user-images.githubusercontent.com/162974/41488905-4b9a9964-70ee-11e8-9d88-51b6e483b268.png)
