### ISSUE TITLE
Removing LDAP did not work

### ISSUE THREAD

**Issue by EkNaLiVE** [partkeepr/PartKeepr#973]
Hello!

I tried following the instructions here:
https://wiki.partkeepr.org/wiki/Developers/Removing_LDAP

But unfortunately, it still checks for LDAP during setup.

![Stuck at step 2](https://i.imgur.com/AroDgZD.png)

**Comment by Drachenkaetzchen** [comment]
Remove the check in the setup file. Sorry, you have to figure it out yourself.

Please note that the GitHub issue tracker is reserved for bug reports and feature requests. It is not a support forum - for community support, please refer to https://partkeepr.com/support/
