### ISSUE TITLE
login fail after installation

### ISSUE THREAD

**Issue by zhanglongqi** [partkeepr/PartKeepr#978]
There is an error message after I clicked the Login button 
PartKeepr version: master branch of git
Env version: ubuntu 16.04 x86-64, PHP 7.0
I have sent my confidential to sales@partkeepr.com
![screenshot from 2018-07-07 20-11-19](https://user-images.githubusercontent.com/956693/42410817-101ade1c-8223-11e8-8637-5db86c02a65e.png)

**Comment by zhanglongqi** [comment]
It suddenly works after 20 mins. Very strange. I can log in now.

**Comment by zhanglongqi** [comment]
I finally found the bug. I can only login after pressing ENTER key on the keyboard instead of clicking the CONNECT button

**Comment by Drachenkaetzchen** [comment]
Please do not send your confidential information without prior notice to the sales email. Also note that sales is not for free support!

Issue is fixed now.
