### ISSUE TITLE
storage location

### ISSUE THREAD

**Issue by mctomaszek** [partkeepr/PartKeepr#981]
Is it a chance to create option which it will be create clone of the parts with only different storage location. I need extra record of the same parts with another location on the same database.  I would like to avoid situation to create from scratch names,description, distributors etc.  of the same parts only for different location. (-time consuming)

**Comment by Drachenkaetzchen** [comment]
It is there already - you can duplicate a part - it's in the same toolbar as "Add Part".

**Comment by mctomaszek** [comment]
thank you :)...
