### ISSUE TITLE
Cron dont work

### ISSUE THREAD

**Issue by kjetilpp** [partkeepr/PartKeepr#983]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version: ZIP-140
* Reproducible on the demo system: Unknown.

Sysinfo: https://drive.google.com/open?id=1ReM2CrtN1e5lBRCGBiC8mG48a54eEUTR

# How to reproduce
Have problem with cron not running. So tested run synctips.

Go to terminal, type:
`[lager@duracell ~]$ /usr/local/bin/php /home/lager/public_html/app/console partkeepr:cron:synctips
`
Then i got this output:
```
[Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0

partkeepr:cron:synctips [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>
[lager@duracell ~]$
```
Php.ini:
```
[lager@duracell ~]$ cat public_html/php.ini
; cPanel-generated php ini directives, do not edit
allow_url_fopen = ON
allow_url_include = ON
display_errors = Off
max_execution_time = 90
max_input_time = 60
max_input_vars = 1000
memory_limit = 288M
post_max_size = 8M
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php70"
upload_max_filesize = 256M
zlib.output_compression = Off
[lager@duracell ~]$
```

What can be wrong?

**Comment by Drachenkaetzchen** [comment]
It says it right there:

```
  Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0
``` 

Enable allow_url_fopen in your php.ini.

**Comment by Drachenkaetzchen** [comment]
Please note that the GitHub issue tracker is reserved for bug reports and feature requests. It is not a support forum - for community support, please refer to https://partkeepr.com/support/
