### ISSUE TITLE
lacking bcmath module check during setup

### ISSUE THREAD

**Issue by t-szczyrba** [partkeepr/PartKeepr#988]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information
ubuntu 18.04 armhf, php-7.1 and modules from ppa:ondrej/php

* PartKeepr Version:
1.4.0
* Reproducible on the demo system: Yes/No.
No
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): 

# How to reproduce

Run partkeepr/web/setup with php-7.1 and without bcmath module
During attachement upload there will be info about lacking symbol Moontoast\Math\bcadd from bcmath module.

**Comment by Drannor-Dosalith** [comment]
I've experience the same behavior on php-7.0.

**Comment by Drannor-Dosalith** [comment]
I've corrected the issue in my installation and summited the correction #993. It should be fix soon, if my fix is done correctly.

**Comment by Drachenkaetzchen** [comment]
I have merged the pull request which should now fix the issue.
