### ISSUE TITLE
Touchscreen notebook (device) mouseclick problem - FIREFOX only - SOLVED 😃

### ISSUE THREAD

**Issue by worm6666** [partkeepr/PartKeepr#994]
This is for all instances of windows (perhaps) running on touchscreen devices - in my case notebook Lenovo YOGA with touchscreen - and FIREFOX browser.

Mouse click is not detected properly - only touchscreen click works well...

Tested also on another touchscreen notebook - same result - reproduceable.

Tested all touch about:config options - one after another - and:

### **dom.w3c_touch_events.enabled = 0**

works like expected - now You can work also with the mouse on PartKeepr.

IE, Edge, Tor - no problem... (for Tor it is because it is FF clone and has the variable set to 0 😃)

Happy partkeeping ! 😈

**Comment by worm6666** [comment]
closed by self 😄😄😄😄😄😄...

**Comment by worm6666** [comment]
reopened for more people for better search results... (?) 😈

**Comment by btittelbach** [comment]
Ahh. so THAT is the reason partkeepr never works in Firefox. Never would have guessed that it could be because the monitor i'm NOT using partkeeper on is a touchscreen.

Issue also effects Firefox 61.0.1 on Linux.

dom.w3c_touch_events.enabled = 0 is NOT a valid fix, since it disables touch events for all webpages, not just for partkeepr.

**Comment by worm6666** [comment]
hmmm... I think it should explain somebody from FF development team - for what it is the variable - because the touch display works still also after changing the variable to 0 (disabled).

I can use the mouse and also the touch display with fingers...

**Comment by christianlupus** [comment]
@worm6666 As far as I understand, there is a workaround but that is not nice as it affects the whole browser, right? Did you check with the latest version of Firefox+PartKeepr?

**Comment by baradhili** [comment]
@christianlupus am running a yoga2 pro, tested trackpad and touchscreen work fine with current firefox, suggest we close

**Comment by christianlupus** [comment]
OK, if anyone stumbles on it, we can link/reopen.
