### ISSUE TITLE
Decimal in Quantity

### ISSUE THREAD

**Issue by aleenf1** [partkeepr/PartKeepr#995]
Can the Partkeepr input the quantity in decimal places and also display the balance quantity in decimal?

**Comment by twelve12pm** [comment]
AFAIK no.

This has been discussed before; for example it would be useful for keeping track of continuous items like wire, cable, 3D printer filament, etc. If this is what you want to do, my suggestion is to decide on a granularity that you're interested in, e.g., you're not interested in any length less than a meter, and then input discrete quantities in terms of meters.

**Comment by christianlupus** [comment]
As this is finally answered, I close the issue.
