### ISSUE TITLE
Argument error when adding distributor to part.

### ISSUE THREAD

**Issue by ThJohannsen** [partkeepr/PartKeepr#996]
# System Information

* PartKeepr Version: 1.4.0
* Reproducible on the demo system: No. :-(
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): 

Please attach files, for example, screenshots to describe your issue. If you can, create a screenshot ob View->System Information.

![selection_206](https://user-images.githubusercontent.com/40489883/44955684-b85ab280-aeb7-11e8-8b80-7fb70c361346.png)

# How to reproduce

- Created a part successfully.
- Created a distributor successfully.

Then
- editing the part, 
- switching to distributor tab, 
- clicking "Add",
- clicking on the "drop down" (down-faced arrow)
- selecting a distributor
- entering order no, price, currency
- clicking update

(so far everything works as expected. The distributor is now in the grid view.
![selection_208](https://user-images.githubusercontent.com/40489883/44955704-0ff91e00-aeb8-11e8-837c-33f57b141f4f.png)

- pressing "Save" I would expect the distributor to be "attached" to the part and the dialogue to close.

Instead I get an error window:
![selection_209](https://user-images.githubusercontent.com/40489883/44955707-17b8c280-aeb8-11e8-9145-610bd5e2bd9c.png)

Three tabs; "Full report" says:

-------------------------------------------------------------------------------------------------
An error occurred

Details
==================================
Type error: Argument 1 passed to Proxies\__CG__\PartKeepr\PartBundle\Entity\PartManufacturer::setManufacturer() must be an instance of PartKeepr\ManufacturerBundle\Entity\Manufacturer, null given, called in /var/www/partkeepr-1.4.0/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php on line 591

Request
==================================
PUT /api/parts/1?_dc=1535889000821

[object Object]

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"Type error: Argument 1 passed to Proxies\\__CG__\\PartKeepr\\PartBundle\\Entity\\PartManufacturer::setManufacturer() must be an instance of PartKeepr\\ManufacturerBundle\\Entity\\Manufacturer, null given, called in \/var\/www\/partkeepr-1.4.0\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/PropertyAccess\/PropertyAccessor.php on line 591"}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.30-0+deb9u1
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: false
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]
defaultGridPresets: []

-------------------------------------------------------------------------------------------------
After closing the windows, "Save" is greyed out, only "Cancel" and "OctoPart" are clickable.

**Comment by ThJohannsen** [comment]
FYI: Error is fixed in latest GIT version on which the "demo system" is based;
 GIT development version Commit 8a6380e46efc81fd52c650995ad4ab62b7cbcedf Short Commit 8a6380e4

**Comment by christianlupus** [comment]
@ThJohannsen Can you verify that it is no longer an issue?

**Comment by christianlupus** [comment]
I close this as it seems to be solved in `master` and no other information was provided.
